### ISSUE TITLE
Single instance process

### ISSUE THREAD

**Issue by oblitum** [bulletmark/libinput-gestures#1]
First, MANY thanks for this, I was looking for something to resemble OS X like touchpad gestures for a long time for Gnome that was simple like this. The only thing I'd like to have now was a 3/4 finger pinch instead of the 2 finger one.

I'd like to report that while doing my configurations I've logged-in and out to make them effective and in this process it looked like I was running several instances of the application, which resulted in a single gesture producing many events. It's the kind of program for which a single instance should be running at any time.

After a reboot it got back to normal behavior for now.

**Comment by bulletmark** [comment]
@oblitum you're right that there should only be 1 instance running at any one time (per user) so I have added commit 1e9e39d6f1ed15be7fe61d2dfdb577db471b175c for this.

**Comment by oblitum** [comment]
Thanks, from what I've tested it looks fixed.

**Comment by bulletmark** [comment]
Actually there is no need to log out to reload your config (or to upgrade the software). I have updated the README to make this clear with commit 7300a6ba721a47b43986e8ea5104a0b75871792e.

**Comment by oblitum** [comment]
Thanks, good to know.

**Comment by oblitum** [comment]
@bulletmark What's "mark restart"? Never seen this command before. Ah, you did a typo, I gues you mean `make restart`.

**Comment by bulletmark** [comment]
Yes, I noticed that the second after I pushed. I fixed it with commit e954e2f2a86cff6bd6130c6896b3fa9b7122bbd0.

**Comment by oblitum** [comment]
OK.

**Comment by bulletmark** [comment]
Note that libinput-debug-events does not seem able to report different finger counts on gesture events so I can't do anything about that. I actually have coded to be able to specify optional finger count gestures in a private branch if it ever becomes possible.

**Comment by oblitum** [comment]
@bulletmark OK, that's sad. Thanks for reporting, maybe that's not a big change in libinput-debug-events sources to starting providing that, I'll try to check that later.
