### ISSUE TITLE
All ok but gestures not working

### ISSUE THREAD

**Issue by AndresTonello** [bulletmark/libinput-gestures#100]
Hi!

I'm running Ubuntu 16.04 on a new laptop which has a multitouch trackpad (which supports just three fingers) (Banghó Zero Pro).

I've followed all steps and I finally got it errors-free, but gestures are just not working. I'm just able to move cursor with one finger and right-click with three fingers tap. All I want is scroll working properly. :s

I'm using the custom configs and setting "device /dev/input/event12" now, but I've tried with "device ImPS/2 Generic Wheel Mouse" and "device all". No one worked.

Paste of `libinput-list-devices` output (just the trackpad device):

```
Device:           ImPS/2 Generic Wheel Mouse
Kernel:           /dev/input/event12
Group:            7
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat*adaptive
```

I just noticed it says "Nat.scrolling: disabled", what does that mean?

Output of `libinput-gestures -e`

```
libinput-gestures: session ubuntu+x11 on Linux-4.4.0-87-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.2.3

libinput-gestures: using ~/.config/libinput-gestures.conf with 6 gestures
libinput-gestures: device /dev/input/event12: ImPS/2 Generic Wheel Mouse
```

However, I've also tried looking `libinput-debug-events` output and it just log pointer movements, no gestures or scrolling.

Thanks a lot for reading! :) (I'm sorry about my english, I'm from Argentina!)

**Comment by bulletmark** [comment]
Please paste the entire output of `libinput-list-devices`. The device you list looks like a mouse, not a trackpad. You say you have configured `device /dev/input/event12` so you must have read that paragraph in `libinput-gestures.conf` about how to do this - but did you not notice the words that you can not specify a raw device like you have? That device number can (and very often does) change between reboots so you must use `/dev/input/by-path/*` symlink.

As per the trouble-shooting section, if you don't see GESTURE events and only see POINTER events then there is little we can do about this. However, given my words above I am not confident you are using the correct device. I don't know Ubuntu or it's current versions but is your system up to date? That kernel 4.4 and libinput 1.2.3 seem awfully darn old to me. New laptops require recent versions of kernel and libinput to best ensure Linux support.

**Comment by bulletmark** [comment]
I just noticed you said you tried `device all` and you did not get gestures so that probably means your touchpad is not being recognised by your kernel. Try a later kernel, ideally with a later libinput.

**Comment by AndresTonello** [comment]
Oh :(

Okay, I'll see what I can do. Maybe I can give a try to Ubuntu 17.04 and see what happens. I'll be back soon :P 

Thank you!
