### ISSUE TITLE
List of _internal commands

### ISSUE THREAD

**Issue by samr28** [bulletmark/libinput-gestures#103]
Where would I find a list of these _internal ws_xx commands? I've looked around online but can't seem to find one. I might be looking for the wrong thing though. I'm specifically trying to mimic the mac three finger swipe up for mission control.

**Comment by bulletmark** [comment]
There is only one `_internal` command and it only takes two arguments `ws_up` or `ws_down`, and three options, `--wrap`, `--col`, and `--row`. I.e. all possible options are already described with examples in the default `libinput-gestures.conf` file.

Mission control is the same as the GNOME overview isn't it? Thus the default configuration should give you  want already? You didn't paste `libinput-gestures -e` like the TROUBLESHOOTING sections says to if you raise a bug so I have no idea of your environment etc.

**Comment by samr28** [comment]
Yeah. I guess I just thought that there might be a few more options with the _internal but the GNOME overview might be what I'm looking for. Thanks for the help!
