### ISSUE TITLE
Libinput custom configuration error

### ISSUE THREAD

**Issue by Leonard142** [bulletmark/libinput-gestures#105]
I'm using Lenovo Yoga 510 and I found the gesture events in my touchpad, but the gesture is still not working. I edited the configuration note in /.config (ex. gesture swipe-left	xdotool key super+Right), then I started libinput-gestures-setup via terminal, it always says error at line 1 in that configuration text : Configuration command "﻿gesture" is not supported.
Must be "gesture" or "device".
I'm using elementary OS Loki currently.
Help please... Thanks!

**Comment by bulletmark** [comment]
Please follow the instructions given in the TROUBLESHOOTING section. In particular, follow step 7, i.e. paste the output of `libinput-gestures -e` and `libinput-gestures -l` here.

**Comment by Leonard142** [comment]
`leonard@leonard:~$ libinput-gestures -e
libinput-gestures: session pantheon+x11 on Linux-4.8.0-52-generic-x86_64-with-elementary-0.4.1-loki, python 3.5.2, libinput 1.6.3

Error at line 1 in file /home/leonard/.config/libinput-gestures.conf:
>> ﻿gesture swipe left	xdotool key super+Right <<
Configuration command "﻿gesture" is not supported.
Must be "gesture" or "device".
`

`leonard@leonard:~$ libinput-gestures -l
Error at line 1 in file /home/leonard/.config/libinput-gestures.conf:
>> ﻿gesture swipe left	xdotool key super+Right <<
Configuration command "﻿gesture" is not supported.
Must be "gesture" or "device".
`

**Comment by bulletmark** [comment]
@Leonard142, when pasting text from terminal please use code tags. I edited your post above to add them.

**Comment by bulletmark** [comment]
Are you using the latest unmodified version of `libinput-gestures` from this repository? How did you install it? You may have an odd unprintable character in your config file. Please copy the default config file and re-edit your changes in.

**Comment by Leonard142** [comment]
@bulletmark so sorry I'm a newbie here.
I install it via terminal and just following the instruction from github.com.
Edit in what line exactly? Because I just found it like an instruction (the default file), and when I opened my /.config folder I found its copy was just an empty text document, so I just filled it with that gesture commands.

**Comment by bulletmark** [comment]
This utility and it's installation procedure never creates any file in your `~/.config/` so if there is/was a file there then you must have manually edited or put it there. It sounds like it has non-printable characters in that file. Please do the following:

~~~~
rm ~/.config/libinput-gestures.conf
~~~~

Then redo the installation instructions in the README here.

That will restart with the default configuration which includes that same gesture configuration as you quote above. If that works and you still want to create custom configuration then follow the instructions here.

**Comment by Leonard142** [comment]
default setting works, but it can only swipe up and down (only 2 gestures). You said I have to follow the instruction to create custom configuration, but I don't see the link to the instruction above... Thanks a lot for the help by the way!

**Comment by bulletmark** [comment]
The main README here says at the very top of the CONFIGURATION section: "Otherwise, if you want to create your own custom gestures etc, keep reading .."

Seriously, please read the documentation.

**Comment by Leonard142** [comment]
Well, thank you!
