### ISSUE TITLE
Two Finger Swiping

### ISSUE THREAD

**Issue by majonathany** [bulletmark/libinput-gestures#106]
Hi,

I was wondering if there's any way to support two finger swiping. I noticed in the raw output there were no logs for a swipe gesture when only two fingers are used on my MacBook Pro (pointer axis is logged, but swipes are logged for 3 or 4 fingers). I would like to use two finger gestures.

Is there any way to change this? Do I have to do something to the python file to allow it to recognize two finger swipes?

Thanks!

**Comment by bulletmark** [comment]
This utility is just a simple program which maps what libinput interprets as gestures to configured commands. Run `libinput-debug-events` on the command line to see what libinput interprets as a GESTURE which for swipes is always 3 or more fingers. If you can work out a way to configure libinput to return GESTURE events for 2 finger swipes then this utility will work for those as well. AFAIK, it is not possible to configure libinput to do that.

Beyond that, you or somebody could write a similar program which just read the low level POINTER_MOTION events and interpreted it's own gestures from the raw pointer movements. Two finger swipe is usually used for scrolling etc so you have to deal with clashing with that in many apps.

**Comment by kaerfredoc** [comment]
Possibly supportable when this is addressed in libinput...

  https://bugs.freedesktop.org/show_bug.cgi?id=99165
