### ISSUE TITLE
Disabling native GNOME gestures

### ISSUE THREAD

**Issue by marcosfede** [bulletmark/libinput-gestures#107]
Thanks for this wonderful piece of work.
I want to configure 4 finger swipe up and down but its interfering with the GNOME default gesture which changes workspaces, so both actions are triggering at the same time. Is there any way to disable the default GNOME gesture so I can configure what 4 finger swipes do using your program?
Thanks!

**Comment by bulletmark** [comment]
I don't think there is a way to disable that default 4 finger swipe sorry. That is a GNOME issue.

**Comment by marcosfede** [comment]
Ok, thanks anyway! Closing this.
