### ISSUE TITLE
Alt+Tab like gesture application change

### ISSUE THREAD

**Issue by marcosfede** [bulletmark/libinput-gestures#108]
Hello, Is there a way to configure an Alt-Tab like application switcher gesture with libinput-gestures? I've tried using `xdotool key alt+Tab`  and `xdotool key shift+alt+Tab` but they do not work (on Gnome Wayland). 
Perhaps there is a way to get the same behaviour with a command similar to 
```dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();' ``` ?
Regards

**Comment by bulletmark** [comment]
No, this utility only actions a single command at the of what libinput reports as a gesture so I can't see how it could do what you want.

**Comment by vn-ki** [comment]
A similar method would be to do the following.

Save the following script to a file in your home dir, say ".switchWidows.sh". 
`#!/bin/sh

xdotool keydown alt
xdotool key Tab
sleep 0.1
xdotool keyup alt`

Make it executable.("chmod +x .switchWindows.sh")

Add the following line to libinput-gestures config
`gesture: swipe right 3  /home/<user>/.switchWindows.sh`

**Comment by ViktorZhurbin** [comment]
> A similar method would be to do the following.
> 
> Save the following script to a file in your home dir, say ".switchWidows.sh".
> _#!/bin/sh_
> 
> _xdotool keydown alt_
> _xdotool key Tab_
> _sleep 0.1_
> _xdotool keyup alt_
> 
> Make it executable.("chmod +x .switchWindows.sh")
> 
> Add the following line to libinput-gestures config
> `gesture: swipe right 3 /home/<user>/.switchWindows.sh`

This actually works, thank you!
Note for copy-pastors like myself: pay attention to the file name `.switchWidows.sh` VS `.switchWindows.sh` :)

**Comment by wuilsons** [comment]
> A similar method would be to do the following.
> 
> Save the following script to a file in your home dir, say ".switchWidows.sh".
> _#!/bin/sh_
> 
> _xdotool keydown alt_
> _xdotool key Tab_
> _sleep 0.1_
> _xdotool keyup alt_
> 
> Make it executable.("chmod +x .switchWindows.sh")
> 
> Add the following line to libinput-gestures config
> `gesture: swipe right 3 /home/<user>/.switchWindows.sh`

hey, im new in this and i dont know how to do this. can u help me?

**Comment by MarcelRentier** [comment]
I'm not sure, if that's the case everywhere, but for me (debian, gnome3, a few plugins)  super+tab does the same as alt+tab; It also makes the code much more convenient:

```
#!/bin/sh

gesture swipe right 3 xdotool key super+Tab
```
For newbies @wuilsons :
1) Open editor. Copy paste above code into editor. Safe file as ".switchWindows.sh" in a folder you can remember, lets say /home/Documents

2) Open Terminal. Use [dir and] cd commands to navigate to the remembered folder, e.g.
`cd Documents/
`
Type
`chmod +x .switchWindows.sh`
to make the file executable.

3) Open Filemanager, navigate to home/.config
Do notice, that "." means, the file/folder is hidden, you might need to look into your filemanager-settings, if it's not shown.
In that folder, open libinput-gestures.conf (a standard text editor is enough).
Add the following line to the end of the document
`gesture swipe right 3 /home/<user>/.spuerTab.sh`
Be sure to replace \<user\> by your actual username.
Safe file.

4) restart computer (or atleast log out/in again). Finished :)

**Comment by mykhailohoy** [comment]
> A similar method would be to do the following.
> 
> Save the following script to a file in your home dir, say ".switchWindows.sh".
> 
> ```
> #!/bin/sh
> 
> xdotool keydown alt
> xdotool key Tab
> sleep 0.1
> xdotool keyup alt
> ```
> 
> Make it executable.("chmod +x .switchWindows.sh")
> 
> Add the following line to libinput-gestures config
> `gesture: swipe right 3 /home/<user>/.switchWindows.sh`

Actually it only switches between two last opened windows and so does pressing alt+tab, than releasing, then pressing again. I tried adding "--delay" to keyup, though it didn't work for me: next gesture isn't working until the previous one hasn't ended. I wonder if there is another way.

**Comment by JohnnyNovaes** [comment]
> > A similar method would be to do the following.
> > Save the following script to a file in your home dir, say ".switchWindows.sh".
> > ```
> > #!/bin/sh
> > 
> > xdotool keydown alt
> > xdotool key Tab
> > sleep 0.1
> > xdotool keyup alt
> > ```
> > 
> > 
> > Make it executable.("chmod +x .switchWindows.sh")
> > Add the following line to libinput-gestures config
> > `gesture: swipe right 3 /home/<user>/.switchWindows.sh`
> 
> Actually it only switches between two last opened windows and so does pressing alt+tab, than releasing, then pressing again. I tried adding "--delay" to keyup, though it didn't work for me: next gesture isn't working until the previous one hasn't ended. I wonder if there is another way.

In the code, change the sleep value (0.1) to higher, like 2 or 4 seconds. This way you will be able to change, like windows.
