### ISSUE TITLE
Possible to remap 3 finger tap?

### ISSUE THREAD

**Issue by samr28** [bulletmark/libinput-gestures#109]
I want to map a three finger tap to open my clipboard history. Could this feature be added to libinput-gestures or would it need to be implemented lower in libinput itself?

Also thanks for creating this piece of software, it has helped me immensely! :+1:

**Comment by bulletmark** [comment]
All this utility does is map what libinput reports as gestures to commands you configure in a file. Run `libinput-debug-events` to see what gestures are. Taps are not gestures so, no, this utility can not do what you want.
