### ISSUE TITLE
gtk-launch: no such application libinput-gestures

### ISSUE THREAD

**Issue by oblitum** [bulletmark/libinput-gestures#11]
Got this error on `make restart`:

```
❯❯❯ make restart                                                                                                               master ✱
libinput-debug-events stopped.
removed '/home/francisco/.local/bin/libinput-gestures'
'libinput-gestures' -> '/home/francisco/.local/bin/libinput-gestures'
libinput-gestures.desktop -> /home/francisco/.local/share/applications/libinput-gestures.desktop
/home/francisco/.local/share/applications/libinput-gestures.desktop -> /home/francisco/.config/autostart/libinput-gestures.desktop
gtk-launch: no such application libinput-gestures
```

**Comment by oblitum** [comment]
It may not be your fault, but this `gtk-launch` simple doesn't work here, even passing full path...

**Comment by bulletmark** [comment]
Please confirm which version you are running?

**Comment by oblitum** [comment]
```
❯❯❯ gtk-launch --version                                                                                                       master ✱
3.20.3
```

And I've just pulled the libinput-gesture master and applied a minor patch to use `~/.local/bin` instead of `~/bin`.

**Comment by bulletmark** [comment]
That explains that odd line in your log above then.

**Comment by bulletmark** [comment]
And probably explains your bug also. Why would anybody want to hide their ~/bin under ~/.local?

Please remove your changes and try the stock install in ~/bin then close the bug if necessary.

**Comment by oblitum** [comment]
@bulletmark I guess this is common usage in some circle, I've seen this around in several places. In any case, it's what's in my PATH, not `~/bin`, it doesn't exist.

**Comment by oblitum** [comment]
https://www.freedesktop.org/software/systemd/man/file-hierarchy.html

**Comment by bulletmark** [comment]
I had accidently hard coded `~/bin` in the install script in one place. You probably just changed the BINDIR variable and that would have caused this bug. Fixed with commit 0636fa363b3690aeaf55248d64b8994f0da14b14.

**Comment by oblitum** [comment]
@bulletmark thanks!

**Comment by bulletmark** [comment]
@oblitum given that freedesktop link you provided I really should cater for `~/.local/bin` so new commit 11e824c4c0cbf3c4bf4eae4015bafffa6f916a61 enhances the installer script for look for that dir first, and then `~/bin`.

Thanks for your input. You can get rid of your personal patch now!

**Comment by oblitum** [comment]
Ah, thank you!
