### ISSUE TITLE
Gesture does not apply to window under cursor

### ISSUE THREAD

**Issue by swapsCAPS** [bulletmark/libinput-gestures#110]
This might be an issue concerning libinput or the DE. (Currently running Ubuntu Gnome 17.04)

I use a three finger swipe left/right in the browser to go backwards and forwards.
However, when a terminal is the 'active' window it will apply the gesture's command to that window.
Is it possible to apply the gesture to the window under cursor? Same as two finger scrolling works.

**Comment by bulletmark** [comment]
No sorry, this is a simple utility which just actions commands globally. If you are keen it would be possible to write a wrapper script/program which could be called by `libinput-gestures` and would selectively action commands as you ask.

**Comment by swapsCAPS** [comment]
I just found a workaround while googling for 'ubuntu gnome get current window under cursor'
Setting focus mode to 'mouse' in the Tweak Tool does the trick.
Thanks for the nudge in the right direction :+1:

**Comment by nlambert** [comment]
Googled my way here. Thanks for the help.

Here are a few breadcrumbs for others searching...

`gesture swipe down 4 gesture_close`

```
#!/bin/bash
# gesture_close
xdotool getmouselocation --shell | grep WINDOW | awk -F= '{print "windowactivate " $2}' | xdotool - & xdotool key alt+F4
```

**Comment by bulletmark** [comment]
@nlambert Just a minor shell coding suggestion that rather than `grep` + `awk` you are better to just use `sed`:

    xdotool getmouselocation --shell | sed -n 's/WINDOW=/windowactivate /p' | xdotool - & xdotool key alt+F4

Also, think about the point of a single comment `# gesture_close`? The user already knows that much! You should instead describe what the script does.

**Comment by nlambert** [comment]
Much better with sed :-)

The comment was only for the purpose of the post
