### ISSUE TITLE
Swipe still propagates three finger click after action

### ISSUE THREAD

**Issue by obermillerk** [bulletmark/libinput-gestures#111]
Hi, I'm using Antergos with KDE plasma desktop.  I just found this little library and it's exactly what I wanted.  I set it up to use three finger right/left swipe to change workspaces, however I've noticed that if my cursor lands over a link in my web browser after performing a desktop switch with a swipe, the three finger tap action is propagated to the OS, which in my case is a  middle click and opens a new tab for whatever link I'm over.

I noticed from one of the open issues that this library is really just skimming CLI output, so maybe it's not particularly possible to fix this issue, but I'd greatly appreciate you looking into it.

Great work on this!

**Comment by bulletmark** [comment]
Initially, I thought this shouldn't be possible but I ran `libinput debug-events --verbose` from the command line and see that taps etc are propagated even while libinput recognizes a gesture sequence so what you say makes sense. No matter how much I try I can't reproduce it in GNOME though so perhaps GNOME is inhibiting these events during workspace switching but KDE is not? I am surprised however that no other KDE user has reported this as an issue.

Either way, as you say this simple utility is just reading libinput debug events and actioning commands based on reported gestures so it is not possible to address this, without making it a heck of a lot more complicated. We are all waiting for the DE's to implement better gesture controls.

**Comment by obermillerk** [comment]
Thanks for looking into it, it's a rather specific case and doesn't create
much of a problem anyway so I'll deal with it.
