### ISSUE TITLE
3 finger swipe accidently pastes clipboard contents to any focused cursor.

### ISSUE THREAD

**Issue by soulawaker** [bulletmark/libinput-gestures#112]
my ~/.config/libintput-gestures.conf contains below commands

```bash
gesture swipe left      3       _internal ws_up

gesture swipe right     3       _internal ws_down
```
These commands paste clipboard contents to any focused cursor inadvertently.
I've copied "**this is a pasted sentence**" text before testing "libinput-gestures -d" below. 
Then I test them.

```bash
$ libinput-gestures -d
libinput-gestures: session pantheon+x11 on Linux-4.10.0-35-generic-x86_64-with-elementary-0.4.1-loki, python 3.5.2, libinput 1.6.3

libinput-gestures: using ~/.config/libinput-gestures.conf with 4 gestures
libinput-gestures: device /dev/input/event6: ETPS/2 Elantech Touchpad
libinput-gestures: SWIPE right 3 [528.21, -48.38]
   _internal ws_down
**this is a pasted sentence**libinput-gestures: SWIPE left 3 [-445.3599999999999, -25.419999999999998]
   _internal ws_up
**this is a pasted sentence**libinput-gestures: SWIPE left 3 [-396.97, -21.73]
   _internal ws_up
**this is a pasted sentence**libinput-gestures: SWIPE right 3 [562.6600000000001, -116.86]
   _internal ws_down
libinput-gestures: SWIPE right 3 [579.88, -70.54]
   _internal ws_down
**this is a pasted sentence**libinput-gestures: SWIPE left 3 [-445.78, 11.89]
   _internal ws_up
**this is a pasted sentence**libinput-gestures: SWIPE right 3 [604.91, -118.51]
   _internal ws_down
**this is a pasted sentence**libinput-gestures: SWIPE left 3 [-570.44, 9.839999999999998]
   _internal ws_up
**this is a pasted sentence**
```
How can I prevent pasting?

**Comment by soulawaker** [comment]
These happen 3 finger swipe only. 4 finger swipe no problem.

**Comment by bulletmark** [comment]
You show only 2 configured commands but the debug output says there are 4. As the TROUBLESHOOTING section says, please paste the output of `libinput-gestures -l` to show your actual configuration.

The `_internal_` command merely invokes `wmctrl` to send commands (via XWayland) to your DE to switch between workspaces. I know this works for GNOME and KDE but please run it manually to prove it works for your DE. Use `wmctrl -d` to list and then and `wmctrl -s N` to switch.

**Comment by soulawaker** [comment]
Ok, my settings.

```bash
$ libinput-gestures -l                                                                   
Gestures configured in ~/.config/libinput-gestures.conf:
swipe right      3 _internal ws_up
swipe left       3 _internal ws_down
swipe left       4 xdotool key alt+Left
swipe right      4 xdotool key alt+Right
```

Confirmed `wmctrl` works.

**Comment by bulletmark** [comment]
Works? You mean using `wmctrl` you can list desktops and then select one to move to?

To be clear, apart from the erroneous paste, does a 3 finger swipe actually switch the workspace?

All this utility does is execute the command you configure, just as you would have typed them yourself so I can't see how it can be pasting anything.

**Comment by soulawaker** [comment]
Yeah, it actually switch the workspace just with pasting clipboard contents.

But after changing commands below, it does not appear.

```bash
swipe up     4 _internal ws_up
swipe down       4 _internal ws_down
swipe left       4 xdotool key alt+Left
swipe right      4 xdotool key alt+Right
```

It's weired.

Anyway, thanks to your works and kindly reply.

I would try to inspect more by myself.

**Comment by soulawaker** [comment]
I met an error message. 

```bash
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.6.3/touchpad_jumping_cursor.html for details
```

It looks like a kernel bugs.

**Comment by bulletmark** [comment]
I've long seen that harmless kernel/libinput touch jump message and it has been reported by many others so I don't think it is related to your pasting issue.

**Comment by soulawaker** [comment]
Ok, I see. I decided to use only 4 finger swipe. Therefore, close this issue to prevent a useless question from annoying the developer's mental health. Thank you for your works!

**Comment by iamrickyspanish** [comment]
same here. Using unity, Ubuntu 17.04
libinput-gestures -l says:

> Gestures configured in /etc/libinput-gestures.conf:
> swipe down         xdotool key super+w

Same Kernel Bug.
No idea why to close the issue. I mean it persists....
realy no way around this? (4 finger swipe not an option)

this tool was my last hope to get gestures working :-D

**Comment by maroc81** [comment]
This is likely a result of synaptics driver interpreting 3 fingers as a middle click and nothing libinput-gestures can do about it.  You can disable 3 finger middle click with the command:

`synclient TapButton3=0`

That worked for me.

**Comment by soulawaker** [comment]
Oh, I'll try later! Thank you for noticing!

2018-01-10 2:18 GMT+09:00 maroc81 <notifications@github.com>:

**Comment by soulawaker** [comment]
@maroc81 I confirmed. You are right! Thanks!

**Comment by TheSalarKhan** [comment]
I am using ubuntu 18.04. Turns out that it was a gnome-tweaks setting that needs to be changed. so just open 'gnome-tweaks' then goto 'Keyboard and Mouse' and disable 'Middle click Paste'

**Comment by bulletmark** [comment]
@TheSalarKhan, 3 finger middle click paste is a fundamental operation most of us use everyday. You'd have to be crazy to turn off such essential functionality.

**Comment by TheSalarKhan** [comment]
@bulletmark I don't use it... I turned it off for me.... It should still work for you buddy!  :stuck_out_tongue: 

I'm more than happy if you have no issues with it turned on and 3 finger scroll working fine. :smile:

**Comment by aamnah** [comment]
> This is likely a result of synaptics driver interpreting 3 fingers as a middle click and nothing libinput-gestures can do about it. You can disable 3 finger middle click with the command:
> 
> `synclient TapButton3=0`
> 
> That worked for me.

In case this command doesn't work, you can also do it with Gnome Tweaks. _Tweaks > Keyboard & Mouse > disable 'Middle Click Paste'_

**Comment by ElectroBuddha** [comment]
Just quick addition, after executing `synclient TapButton3=0` and disabling 'Middle Click Paste' I also had to restart all my applications to make them stop pasting three-finger swipe.
