### ISSUE TITLE
Another "Could not determine touchpad device."

### ISSUE THREAD

**Issue by leledumbo** [bulletmark/libinput-gestures#113]
This is on GPD Pocket. libinput-list-devices output:
[libinput-devices.txt](https://github.com/bulletmark/libinput-gestures/files/1346709/libinput-devices.txt)
Tried forcing the device in config using Goodix Capacitive TouchScreen, but running `libinput-gestures-setup -d` followed by touches here and there gives no output. I'm already in input group and have logged out-in + reboot as well.

**Comment by bulletmark** [comment]
Please note step 7 of the TROUBLESHOOTING guide asks you to paste the output of `libinput-gestures -e` when raising an issue.

**Comment by bulletmark** [comment]
That device appears to be a touchscreen, not a touchpad. Run `libinput-debug-events` directly yourself to see if you get touchpad events. If not, then there is little this utility can do about it sorry.

**Comment by leledumbo** [comment]
Right, only TOUCH_* events are generated. It's unfortunate because google chrome has built-in gestures that work with it (i.e. pinch to zoom, swipe to back/forward).
