### ISSUE TITLE
Installation issue with evilWM

### ISSUE THREAD

**Issue by kalimeroo** [bulletmark/libinput-gestures#114]
Hello,

When I try to run libinput-gestures-setup start, I get the following error : "Don't know how to invoke libinput-gestures.desktop"
libinput-gestures -d and libinput debug-events show that the touchpad events are issued and received by the programs.

It is due to the fact that I do not use a desktop environement but only a simple windows manager (evilwm). Do you think there might be a work around ?

Best Regards

**Comment by bulletmark** [comment]
Please note step 7 of the TROUBLESHOOTING section and thus please include the output of `libinput-gestures -e` here.

I have no experience with evilWM sorry. If you look at `libinput-gestures-setup` you will see code that starts the app for GNOME, KDE, I3, etc. 

So you are saying it works ok, you just don't know how to autostart it? Perhaps you can just add a `/usr/bin/libinput-gestures &` before you start `evilwm` in your `~/.xinitrc`?

**Comment by bulletmark** [comment]
OP never got back to me so closing.

**Comment by recurved** [comment]
Hello,
  I been having an issue running this under LXDE on the Raspberry Pi.
 I can actually get it working if I manually click the libinput-gestures.desktop file, but the command `libinput-gestures-setup start` only outputs the error "Don't know how to invoke libinput-gestures.desktop".
 Every attempt to autostart fails. libinput-gestures -l output pasted below. Any thoughts?

Thanks for your time,
  Rowan

```
rowan@brandywine:~ $ libinput-gestures -l
libinput-gestures: session lightdm-xsession+x11 on Linux-4.19.97-v7l+-armv7l-with-debian-10.3, python 3.7.3, libinput 1.12.6
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
swipe right        xdotool key alt+Right
swipe left         xdotool key alt+Left
libinput-gestures: device /dev/input/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.2-event-mouse(event2): Logitech Rechargeable Touchpad T650
```

**Comment by bulletmark** [comment]
@recurved you really should have opened a new issue. Can you please checkout and try [branch launchers](https://github.com/bulletmark/libinput-gestures/tree/launchers)?

**Comment by recurved** [comment]
Sorry about that.I can delete my message and start a new issue if you'd like. I'm still learning git etiquette.

**Comment by bulletmark** [comment]
Please try that new branch:
```
git clone https://github.com/bulletmark/libinput-gestures.git
git checkout launchers
sudo make install
```
Then see if it now works. If it doesn't then install the `dex` package and try again (as per new paragraph in README).

**Comment by recurved** [comment]
Installed dex and using the Launchers branch. Running `libinput-gestures-setup start` manually now works, but I am still unable to get it to autostart. Even creating an entry inthe  lxsession autostart file fails. But again, manually running `libinput-gestures`, `libinput-gestures-setup start`,  or clicking the libinput-gestures.desktop file all seem to work fine.

**Comment by recurved** [comment]
Just had a breakthrough! When running `libinput-gestures -l` I noticed the message "Could not determine touchpad device." So, after searching and finding this [post](https://github.com/bulletmark/libinput-gestures/issues/156) I added the line `device all` to the config file. After a reboot, autostart works fine now.

Thanks for you time, assistance, and patience,
Rowan/Recurve(d|r)

**Comment by bulletmark** [comment]
Hang on @recurved you are going backwards. Setting `device all` is a desperation measure that imposes a performance overhead on your machine. You already provided your `libinput-gestures -l` output in your first post here and that established that libinput-gestures was finding your touchpad device perfectly fine. What have you changed to break that? Please remove your custom configuration file and provide the output of `libinput-gestures -l` again here.

**Comment by recurved** [comment]
Everything was still working, just the autostart continued to fail. Initially, I enabled `device all` with the intent of changing it to my specific touchpad once I got it working. I didn't notice any lag or sluggishness so I left it.
Here is my `libinput-gestures -l` output with the default configuration:
```
~ $ libinput-gestures -l
libinput-gestures: session lightdm-xsession+x11 on Linux-4.19.97-v7l+-armv7l-with-debian-10.3, python 3.7.3, libinput 1.12.6
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.2-event-mouse(event2): Logitech Rechargeable Touchpad T650
```

**Comment by bulletmark** [comment]
You don't need to "change it to your specific touchpad". As you can see above using the default configuration libinput-gestures finds your touchpad automatically. as it normally does for 99% of users. Don't use `device all`. Just add your desired gestures configuration from here and confirm it still works, before you try getting it to autostart. Take a step at a time.

**Comment by recurved** [comment]
Ok. Removed `device all` and custom config. Was getting inconsistent results from running `libinput-gestures -l`: sometimes it would see the touchpad and sometime it wouldn't.
So, on a hunch, I went directly to the terminal immediately after reboot and ran `libinput-gestures -l` twice. Between the two commands I did a left 3-finger swipe on the touchpad. This is result:
```
rowan@brandywine:~ $ libinput-gestures -l
libinput-gestures: session lightdm-xsession+x11 on Linux-4.19.97-v7l+-armv7l-with-debian-10.3, python 3.7.3, libinput 1.12.6
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
Could not determine touchpad device.
rowan@brandywine:~ $ libinput-gestures -l
libinput-gestures: session lightdm-xsession+x11 on Linux-4.19.97-v7l+-armv7l-with-debian-10.3, python 3.7.3, libinput 1.12.6
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.2-event-mouse(event2): Logitech Rechargeable Touchpad T650
rowan@brandywine:~ $ libinput-gestures-setup status
libinput-gestures is installed.
libinput-gestures is set to autostart.
libinput-gestures is not running.
libinput-gestures is using default configuration.
```

**Comment by bulletmark** [comment]
To be clear, so you are saying that after a reboot then it does not detect your touchpad but you then do a 3-finger swipe and from then on it is detected? Please `libinput-gestures-setup autostop` then reboot and repeat that test.

**Comment by recurved** [comment]
Exactly. Here is the output:
```
rowan@brandywine:~ $ libinput-gestures -l
libinput-gestures: session lightdm-xsession+x11 on Linux-4.19.97-v7l+-armv7l-with-debian-10.3, python 3.7.3, libinput 1.12.6
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
Could not determine touchpad device.
rowan@brandywine:~ $ libinput list-devices
Device:           Logitech M705
Kernel:           /dev/input/event0
Group:            1
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

Device:           Logitech K520
Kernel:           /dev/input/event1
Group:            2
Seat:             seat0, default
Capabilities:     keyboard pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    disabled
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

rowan@brandywine:~ $ libinput-gestures -l
libinput-gestures: session lightdm-xsession+x11 on Linux-4.19.97-v7l+-armv7l-with-debian-10.3, python 3.7.3, libinput 1.12.6
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.2-event-mouse(event2): Logitech Rechargeable Touchpad T650
rowan@brandywine:~ $ libinput list-devices
Device:           Logitech M705
Kernel:           /dev/input/event0
Group:            1
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

Device:           Logitech K520
Kernel:           /dev/input/event1
Group:            2
Seat:             seat0, default
Capabilities:     keyboard pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    disabled
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Logitech Rechargeable Touchpad T650
Kernel:           /dev/input/event2
Group:            3
Seat:             seat0, default
Size:             123x103mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

**Comment by bulletmark** [comment]
Well that is odd. The device definitely does not appear until after you use it(!). I have not seen that ever reported before and I guess that requires you will have to use `device all` after all. Sorry to send you on a goose-chase.

**Comment by recurved** [comment]
No worries. I've never had any issues like this before; I've been using libinput-gestures on my Lenovo Yoga with no problems for about a year, I think, and it has been almost plug and play. I may eventually end up moving to Ubuntu 20.04 on this Raspberry Pi 4 setup. Hopefully that will be less finicky.

Cheers,
 Recurve(d|r)
