### ISSUE TITLE
Document support for chaining of xdotool commands

### ISSUE THREAD

**Issue by kaerfredoc** [bulletmark/libinput-gestures#115]
There appears to be some capacity for chaining xdotool commands. I was hoping for some official direction/doc that explains the correct syntax. For example minimizing the currently active window works as follows:

`gesture swipe down 3 xdotool getactivewindow windowminimize`

However I was unable to find a combination that will minimize the window that's under the mouse. Using xdotool on the console, this can be done by executing the following:

`xdotool windowminimize $(xdotool getmouselocation | sed 's/.*window://')`

All of the following attempts to accomplish this using libinput-gestures (along with other variations) fail with the following error:
active "X Error of failed request:  BadWindow (invalid Window parameter)"

`gesture swipe down 3 xdotool windowminimize $(xdotool getmouselocation | sed 's/.*window://')`
`gesture swipe down 3 xdotool windowminimize xdotool getmouselocation | sed 's/.*window://'`
`gesture swipe down 3 xdotool getmouselocation $(sed 's/.*window://') windowminimize`

**Comment by bulletmark** [comment]
For efficiency and because most don't need it, `libinput-gestures` does not run the configured command under a shell so command substitutions and expansions etc will not be parsed. However, just add your commands in an executable personal script, e.g. `~/bin/libinput-gestures.sh`. Run that by hand until you get it working then configure that script name as your command in `libinput-gestures`.

**Comment by kaerfredoc** [comment]
Sounds good. Thanks for the reply. For the record i added an executable script on my local path named `libinput-gestures-min-window.sh` with the following contents:

`#!/bin/bash`
`xdotool windowminimize $(xdotool getmouselocation | sed 's/.*window://')`

And added this to the libinput gestures config:
`gesture swipe down 3 'libinput-gestures-min-window.sh'`

**Comment by bulletmark** [comment]
I will add a comment about this in the main README.
