### ISSUE TITLE
not working on wayland session of Ubuntu 17.10

### ISSUE THREAD

**Issue by keighrim** [bulletmark/libinput-gestures#116]
I'm having trouble with gestures not working on wayland session of the new Ubuntu )I upgraded Ubuntu 17.04 to 17.10). 
Gestures works just find on xorg session as it did before upgrading, but not on wayland. However, when I run `libinput-gestures -d` to monitor the input, it seems to be able to catch all inputs. 
Attaching my xinput and gesture monitoring. If you need any other logs, let me know. 

```bash
$ 10:24:00>> xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ xwayland-pointer:13                     	id=6	[slave  pointer  (2)]
⎜   ↳ xwayland-relative-pointer:13            	id=7	[slave  pointer  (2)]
⎜   ↳ xwayland-touch:13                       	id=9	[slave  pointer  (2)]
⎜   ↳ xwayland-stylus:13                      	id=10	[slave  pointer  (2)]
⎜   ↳ xwayland-eraser:13                      	id=11	[slave  pointer  (2)]
⎜   ↳ xwayland-cursor:13                      	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ xwayland-keyboard:13                    	id=8	[slave  keyboard (3)]
```

```bash
$ 10:25:39>> libinput-gestures -d
libinput-gestures: session gnome+wayland on Linux-4.10.0-37-generic-x86_64-with-debian-stretch-sid, python 3.6.1, libinput 1.8.2
libinput-gestures: using ~/.config/libinput-gestures.conf with 8 gestures
libinput-gestures: device /dev/input/event6: SynPS/2 Synaptics TouchPad
libinput-gestures: SWIPE up 3 [128.5, -878.32]
   xdotool key super+Tab
libinput-gestures: SWIPE up 3 [-78.74, -647.0899999999999]
   xdotool key super+Tab
libinput-gestures: SWIPE right 4 [424.15, -139.94]
   xdotool key super+j
libinput-gestures: SWIPE left 4 [-518.49, -57.97]
   xdotool key super+k
```

I tried uninstall and re-install (with the latest commit), but didn't help.

**Comment by keighrim** [comment]
I found, after a reboot, gestures are working in wayland session as well. Sorry for the fake alarm! Closing the issue.

**Comment by bulletmark** [comment]
Those `xdotool` gestures you have configured should not work on Wayland. Please read the Wayland section of the main README. In the environment in which you say this is working, please capture the output of `libinput-gestures -el` and paste it here.

**Comment by keighrim** [comment]
Yup, I read the wayland section and figured out what's going on. So they were not really working, they only work in some apps (browser) only as you mentioned in the `README`.  I should have read the documentation carefully first. Sorry and thanks!
