### ISSUE TITLE
Ubuntu 17.10 - Strange behavior for some gestures

### ISSUE THREAD

**Issue by DougBeney** [bulletmark/libinput-gestures#117]
I greatly appreciate your work! This project has been a major help in switching from Mac OS X to Linux without losing the features I love. 

Yesterday, I switched from 16.04 to 17.10, with the same configuration, and am experiencing some odd behavior. Just want to note that I have always been using Gnome, even on 16.04.

So, three-finger right/left swiping works fine. So does three-finger up/down swiping.

However, 4-finger left/right/up/down swiping does not work and 3-finger pinch is producing strange behavior. 

Here are the lines in my configuration that aren't functioning properly:

```
# SNAP WINDOWS WITH 4 FINGER SWIPE LEFT/RIGHT/FULL SCREEN/REGULAR
gesture swipe left 4	xdotool key Super+Left
gesture swipe right 4	xdotool key Super+Right
gesture swipe up    4	xdotool key Super+Up
gesture swipe down  4	xdotool key Super+Down
```

```
# GNOME SHELL open/close overview (works for GNOME on Wayland and Xorg)
gesture pinch in 3 dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'
gesture pinch out 3 dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'
```

The three-finger pinch gestures are mapped to open the gnome overview (Where it shows all of my open application windows). What happens is that the gnome overview pops up as expected, but then immediately closes.

**Comment by bulletmark** [comment]
Please note step 7 of the TROUBLESHOOTING section, i.e. please paste the output of `libinput-gestures -e` here.

**Comment by DougBeney** [comment]
My bad.

```
libinput-gestures: session ubuntu+wayland on Linux-4.13.0-16-generic-x86_64-with-Ubuntu-17.10-artful, python 3.6.3, libinput 1.8.2
libinput-gestures: using ~/.config/libinput-gestures.conf with 10 gestures
libinput-gestures: device /dev/input/event8: bcm5974
```

**Comment by bulletmark** [comment]
You are using 17.10 Ubuntu on Wayland which I have no experience with but does the last paragraph of WAYLAND AND OTHER NOTES section apply to you? Possibly Ubuntu has also a default gesture for 3 pinch to already open the overview so you are doing it twice?

**Comment by bulletmark** [comment]
No response from OP so closing.

**Comment by zshimanchik** [comment]
ubuntu 17.10 already has gesture for 3 finger in/out pinch - it opens main overview.
So if you configured libinput-gesture to toggle main overview: firstly native ubuntu gesture will open main overview and then libinput-gesture toogle it back (close it).

**Comment by bulletmark** [comment]
Note my comment https://github.com/bulletmark/libinput-gestures/issues/117#issuecomment-340308912. The OP never got back to me. Are you guys definitely sure that Ubuntu 17.10 has configured 3 finger gesture? If so then I will add a note to the README.

**Comment by zshimanchik** [comment]
Yes ubuntu 17.10 has 3 finger in\out ping gesture. I disabled libinput-gesture for this gesture. But ubuntu 17.10 gesture is not convenient because it only opens main overview, but not toggle it back.

**Comment by zshimanchik** [comment]
I have just found it and put it here. 
There is an option in ubuntu 17.10 to start DE using X11 instead of wayland. This is solution for behavior described above and also xdotool (which is used by libinput-gestures) will work with all applications.
