### ISSUE TITLE
libinput error in Gnome 3.20

### ISSUE THREAD

**Issue by ZJaume** [bulletmark/libinput-gestures#12]
Gestures doesn't work for me on Arch with Gnome 3.20. I have ran libinput-gestures with make start and I get this error when I try a gesture.
`libinput error: libinput bug: Event for missing capability CAP_GESTURE on device "SynPS/2 Synaptics TouchPad"`

**Comment by bulletmark** [comment]
That appears to be a bug in libinput: https://bugs.freedesktop.org/show_bug.cgi?id=95314.

Note there that a patch has already been committed https://lists.freedesktop.org/archives/wayland-devel/2016-May/028849.html.

**Comment by ZJaume** [comment]
Thanks!

**Comment by bulletmark** [comment]
@ZJaume I see that fix was included in libinput 1.3.1 which was released today. The Arch packages usually update within a few days.

**Comment by ZJaume** [comment]
Now I have updated to the 1.3.1 version and still not working. When I execute "./libinput-gestures -v" and then try any gesture I don't get any output and nothing happens. I don't understand, my touchpad is multitouch and I have tried xdotool commands and they work.

**Comment by bulletmark** [comment]
I am running up-to-date Arch x64 (i.e. with libinput 1.3.1) and it works fine for me. I suggest you search around the forums and bug trackers for comments about libinput and your model notebook/touchpad.

To take libinput-gestures out of the equation, ensure you are a member of the input group then disable `libinput-gestures` (with `make stop`) and type:

    libinput-list-devices

Note which `/dev/input/eventX` device your touchpad is. Then type:

    libinput-debug-events --device /dev/input/eventX

And then confirm that it is reporting SWIPE and PINCH gestures.

**Comment by ZJaume** [comment]
Ok, the output I got was this (doing swipe down and up):
`event10	DEVICE_ADDED     SynPS/2 Synaptics TouchPad        seat0 default group1 cap:p	size 63.94/32.08mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on`
`event10	POINTER_AXIS      +2.59s	vert -0.08* horiz 0.00`
`event10	POINTER_AXIS      +2.62s	vert -0.42* horiz 0.00`
`event10	POINTER_AXIS      +2.64s	vert -1.24* horiz 0.00`
`event10	POINTER_AXIS      +2.67s	vert -2.16* horiz 0.00`
`event10	POINTER_AXIS      +2.69s	vert -3.20* horiz 0.00`
`event10	POINTER_AXIS      +2.71s	vert -4.32* horiz 0.00`
`event10	POINTER_AXIS      +2.74s	vert -4.28* horiz 0.00`

**Comment by bulletmark** [comment]
I get the same messages when I swipe with 2 fingers but that is irrelevant here because the point of this application is to process 3(+) finger swipes, or 2(+) finger pinches which are called gestures by libinput. See https://wayland.freedesktop.org/libinput/doc/latest/gestures.html for explanation.

What does it report when you swipe with 3 fingers?

Do a `make stop` and run `./libinput-gestures -d` in a terminal. Then try 3 fingers swipe left/right/up/down and 2 or 3 finger pinch in/out and see if it reports correctly.

**Comment by ZJaume** [comment]
When I run `./libinput-gestures -d` and swipe(3+ fingers) or pinch(2 fingers) I don't get any output, and the output with `libinput-debug-events --device /dev/input/event10` swipping woth 3 or more fingers was that.

**Comment by bulletmark** [comment]
OK, `libinput-gestures` should report GESTURE_SWIPE_* and GESTURE_PINCH_* events if your touchpad was being recognized correctly so clearly this bug is external to this application. As I said above, I suggest you trawl the web for similar issues with your model notebook/touchpad.
