### ISSUE TITLE
Libinpu-gestures stopped working

### ISSUE THREAD

**Issue by notaduck** [bulletmark/libinput-gestures#123]
Libinput-gestures suddenly stopped working out of no where.

```
[daniel@road_warrior ~]$ libinput-gestures -l

  File "/usr/bin/libinput-gestures", line 70
    print(str(e), file=sys.stderr)
                      ^
SyntaxError: invalid syntax
```
I can't do anything.... even `libinput-gestures --version` doesn't work

**Comment by notaduck** [comment]
There was an error with symblinking between the different python versions.

**Comment by bulletmark** [comment]
Yes, I was about to point out that:
~~~~
% python2 ./libinput-gestures
  File "./libinput-gestures", line 70
    print(str(e), file=sys.stderr)
                      ^
SyntaxError: invalid syntax
~~~~

So I was guessing you somehow got your python3 pointing to python2.

**Comment by notaduck** [comment]
Something like that year :D
