### ISSUE TITLE
GNOME show all applications shortcut?

### ISSUE THREAD

**Issue by C2N14** [bulletmark/libinput-gestures#129]
Does anybody know how to assign a shortcut to switch to the "Show all applications" menu in GNOME similar to `gesture swipe up dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'` without any keyboard shortcuts?

For some reason xdotool does not work correctly all the time on my computer on Ubuntu 17.10 and I was wondering if there was any way I could trigger this menu without it because I am tired of troubleshooting it.

**Comment by bulletmark** [comment]
A general "forum query" like this is not a bug or enhancement request for libinput-gestures. Nor will it attract much of an audience. You statement "For some reason xdotool does not work" is probably answered in the Wayland notes of the main README here.

**Comment by C2N14** [comment]
Whoa that was fast, anyway I found it. Here it is: `dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.show(); if (! Main.overview.viewSelector._showAppsButton.checked) {Main.overview.viewSelector._showAppsButton.checked = true;} else {Main.overview.hide();};'`

And about xdotool not working, it probably is because I'm using Wayland, but honestly I've tried all I could think off and I still found it way too unreliable so I think I'm just going to pass on it.

**Comment by bulletmark** [comment]
`xdotool` is not unreliable. Read the note I referred to. `xdotool` won't work for all Wayland native apps (e.g. gnome-terminal, files) but will work for XWayland apps (e.g. chome, firefox).
