### ISSUE TITLE
Could not determine touchpad device.

### ISSUE THREAD

**Issue by marlanbar** [bulletmark/libinput-gestures#13]
In Ubuntu 16.04, XPS13 (9350)

Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)

xps13:~/libinput-gestures$ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ DLL0704:01 06CB:76AE Touchpad           	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD                    	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=13	[slave  keyboard (3)]

**Comment by bulletmark** [comment]
Note the second step the installation instructions. Have you done that?

**Comment by marlanbar** [comment]
Ups, you're right. Thank you
