### ISSUE TITLE
Support multiple touchpads

### ISSUE THREAD

**Issue by domsle** [bulletmark/libinput-gestures#131]
Hey
Long user here. Recently I got myself an exteranal touchpad (Logitech T650) additionally to one that is already build-in to my laptop. 
Problem is, I need to restart libinput-gestures service for it to work after plugging in(at home). 
Then, when I want to use build in touchpad, I need to restart it again(when I'm out). 
It this something that can be fixed?

**Comment by bulletmark** [comment]
This is already supported if you add a `device all` to your configuration file. I just added some more notes to accentuate this feature with commit d39fb024e59d719f5e26db2e45a65ccddeea3203.

Please come back here and comment if this works for you.

**Comment by bulletmark** [comment]
Closing as no response from OP.
