### ISSUE TITLE
Ability to control playback volume with gestures

### ISSUE THREAD

**Issue by nevack** [bulletmark/libinput-gestures#133]
In Windows 10 there's an ability to change volume with 3 fingers up/down
For example if I swipe 5mm volume changes by 5% (approximately), 10mm - 10% and so on.

With libinput-gestures and pulseaudio on Arch:
`gesture swipe up	pactl set-sink-volume 0 +10%`

So if I want to change volume by 30% I need to swipe 3 times, not 1.

**Comment by bulletmark** [comment]
Not a bad suggestion so I will think about it.

**Comment by JJK96** [comment]
Probably related:

I would like to repeat a command if I swipe longer so that I can switch multiple tabs with one (longer) swipe. I think an implementation of this would also save the problem of @nevack because then a longer swipe would increase the volume with 10% 3 times.

**Comment by nevack** [comment]
> I would like to repeat a command if I swipe longer

This! 👍

**Comment by bulletmark** [comment]
Please try the experimental _scaling_ branch I just added. Refer to new section in README there.

**Comment by nevack** [comment]
I will try.
Will it trigger command only when gesture is ended (removed my fingers from touchpad)?
Or will it execute on the go?

**Comment by bulletmark** [comment]
Gestures are only executed and the end. I am reluctant to change this because it is so fundamental to the design. I just hacked up something crude to change volume on the fly and found it doesn't work as well anyhow. Does windows action the volume change at the end of the gesture, or on the fly?

**Comment by nevack** [comment]
On the fly. I'll upload video later to show how exactly this works.

**Comment by nevack** [comment]
Quality is shit (i have poor upload speed), but enough to explain.
https://vk.com/video?z=video118781407_456239075

**Comment by bulletmark** [comment]
That video shows how I expected it to work. When doing a volume swipe the user really needs a popup OSD volume slider but that, and on the fly commands in general, are difficult to implement in the current framework design of libinput-gestures. To implement that, I would probably implement a new major version with an incompatible configuration file syntax.

I'll leave this issue open in case I ever get around to that.

**Comment by Superdanby** [comment]
Awesome!

**Comment by AlekseiBugaiov** [comment]
Very useful feature!

**Comment by stefanocirici** [comment]
The key to control volume are 

- `xdotool key XF86AudioRaiseVolume`
- `xdotool key XF86AudioLowerVolume`

Checking the log witn `libinput-gestures -d` the command is sent but nothing happen (obviously running the command in terminal the volume is changed).

**Comment by bulletmark** [comment]
@stefanocirici I configure those commands as gestures and they work for me. Clearly they will only work with an Xorg desktop so perhaps you are using Wayland?

**Comment by stefanocirici** [comment]
@bulletmark Yes. I though 18.04 was using x11 as default. Now I can see that they works.

**Comment by KaelWD** [comment]
> I would like to repeat a command if I swipe longer

Looks like [fusuma](https://github.com/iberianpig/fusuma) supports this.

**Comment by joholl** [comment]
Exactly. Unfortunately, this is a show stopper for me. Using fusuma now and it works just as expected.

**Comment by bulletmark** [comment]
Closing, Fusuma is an alternative if you want this.
