### ISSUE TITLE
Autostart (/usr/bin/libinput-gestures script) freezes Gnome 3.26

### ISSUE THREAD

**Issue by tbutcaru** [bulletmark/libinput-gestures#134]
Hello,

Yesterday I've installed `libinput-gestures` and configured it to autostart. 
Today when I've started my machine, after logging in and opening some apps I've noticed that I could not action anything inside all application (click, move, close, etc).

I'm using Gnome DE (v3.26) with X. 
All `libinput-gestures` were working fine, Gnome overview/workspaces/apps were working, but I could not use any open app.

I've removed the `libinput-gestures.desktop`, restarted the machine and everything came back to normal.
Then I've added it again, but I've changed the exec command to be `libinput-gestures-setup start` instead of `/usr/bin/libinput-gestures`, restarted the machine and no issues at all!

So, somehow `/usr/bin/libinput-gestures` script is causing application freeze on my machine.

Other info:
- Manjaro distribution
- Gnome 3.26 (X)
- Intel HD Graphics
- Linux kernel 4.14
- User defined config file.

If you need any other info, please tell!

Thanks!

**Comment by bulletmark** [comment]
Please remove `libinput-gestures` completely and if you do enough restarts etc then you will/may see this problem again and you will realise that libinput-gestures has nothing to do with it.

What extensions are you running? I also some see very occasional odd stability issue with GNOME 3.26 (on Arch) but that is mainly on my PC where I do not run `libinput-gestures`.

I will have to leave this bug open for a while and then close it after we see that nobody else has jumped to the conclusion you have.

**Comment by tbutcaru** [comment]
I added again the original `libinput-gestures.desktop` file, deactivated `Workspaces to Dock` extension (that's what I've also installed yesterday on my system), restarted & no issue.
Reactivated the extensions, restarted & no issue.

Today when I had the issue, it persisted through several restarts, so it didn't happened just once.
Another think I noticed is that my replacement of the Exec command does not make it through restart. I've opened the `.desktop` file right now (after several restarts) and every time my custom command was replaced with `/usr/bin/libinput-gestures`... So the script really works.

Also, I did not made any updates today. Maybe it was a random freeze caused by Gnome or a conflict between `libinput-gestures` and some extensions.

Extensions I'm using:
- Alternate tab
- Clipboard indicator
- Dash to dock
- Manjaro linux updates indicator
- Media player indicator
- Openweather
- Places status indicator
- Pomodoro
- Removable drive menu
- Topicons plus
- User themes
- Workspaces to dock

These being said, I don't think the issue is caused by `/usr/bin/libinput-gestures` script (since my custom exec does not survive during restart and this is used), so I think you can close the issue or leave it open for few days..

Thank you!

**Comment by bulletmark** [comment]
We agree this is unlikely to be related to `libinput-gestures` so closing this bug.
