### ISSUE TITLE
xdotool super+[letter] not working

### ISSUE THREAD

**Issue by Smeaven** [bulletmark/libinput-gestures#138]
Generally libinput-gestures runs perfectly on my eOS. I don't no why, but I can't map super+[letter] shortcut e.g. super+A, super+H or super+S to a touch swipe gestures.

Other key shortcuts such as super+Up/Down/Left/Right or super+ctrl+Left/Right are mapped correctly.
If I am in a terminal on a new/empty line and do the touch gestures which I mapped to e.g. super+H, for each it adds an H to my terminal line.

My touchpad supports touch gestures up to three fingers, also pinch in & out. If I run the debug mode, also everything works as expected. Tests in raw mode also ok.

```
libinput-gestures -e
libinput-gestures: session pantheon+x11 on Linux-4.13.0-37-generic-x86_64-with-debian-stretch-sid, python 3.6.4, libinput 1.6.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 6 gestures
libinput-gestures: device /dev/input/event11: ATML3000:00 03EB:8D02 Touchpad

libinput-gestures -d
libinput-gestures: session pantheon+x11 on Linux-4.13.0-37-generic-x86_64-with-debian-stretch-sid, python 3.6.4, libinput 1.6.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 6 gestures
libinput-gestures: device /dev/input/event10: ATML3000:00 03EB:8D02 Touchpad
libinput-gestures: SWIPE up 3 [0.0, -147.38]
   xdotool key super+Up
libinput-gestures: SWIPE right 3 [525.9300000000001, -40.400000000000006]
   xdotool key super+ctrl+Right
libinput-gestures: SWIPE left 3 [-751.0699999999998, -18.180000000000007]
   xdotool key super+ctrl+Left
libinput-gestures: SWIPE down 3 [-33.330000000000005, 932.75]
   xdotool key super+H
libinput-gestures: PINCH in 2 [-8.5, -7.680000000000001]
   xdotool key super+A
libinput-gestures: PINCH out 2 [31.0, 1.4200000000000021]
   xdotool key super+Down
^CTraceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 497, in <module>
    for line in cmd.stdout:
KeyboardInterrupt

libinput-gestures -l
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key super+Up
swipe down       3 xdotool key super+H
swipe left       3 xdotool key super+ctrl+Left
swipe right      3 xdotool key super+ctrl+Right
pinch in           xdotool key super+A
pinch out          xdotool key super+Down
```

**Comment by rsjudka** [comment]
> If I am in a terminal on a new/empty line and do the touch gestures which I mapped to e.g. super+H, for each it adds an H to my terminal line.

+1 for this issue, also on eOS.

To further elaborate on this issue, it requires performing the gesture twice. The first time inserts the character used in the mapped shortcut (in any text field not just terminal) and the second time actually performs the action.

**Comment by Smeaven** [comment]
To clarify the thing with the terminal, that just occurs for the troubled key mappings. 
But I can't confirm, that doing the gesture twice, finally performs the action. On my eOS (Loki) it adds the character for every gesture.

**Comment by bulletmark** [comment]
As per the TROUBLESHOOTING section, please paste the output of step 4 there and also paste the output of `libinput-gestures -l` (step 7).

**Comment by bulletmark** [comment]
@rsjudka, you please also paste the output of your `libinput-gestures -e` (like @Smeaven  has done in opening comment).

**Comment by bulletmark** [comment]
No response from either person here so closing.

**Comment by SaitDev** [comment]
@bulletmark im having same problem, here is the output in my machine
```
swipe left       4 xdotool key super+Left
swipe right      4 xdotool key super+Right
swipe down       3 xdotool key super+Down
swipe left       3 bash /data/apps/previous-tab-if-chrome.sh
swipe right      3 bash /data/apps/next-tab-if-chrome.sh
pinch clockwise    xdotool key super+Up
pinch anticlockwise   xdotool key super+h
libinput-gestures: device /dev/input/event6: ETPS/2 Elantech Touchpad
```

**Comment by SaitDev** [comment]
there is still args -e?
```
libinput-gestures -e
usage: libinput-gestures [-h] [-c CONFFILE] [-v] [-d] [-r] [-l]
                         [--device DEVICE]
libinput-gestures: error: unrecognized arguments: -e
```
print h: in my terminal, a new char "H" added, like when i type "h" key without super. i'll try reproduce this for more details. for now its working

**Comment by bulletmark** [comment]
@SaitDev the comment that I referred you to does not mention `-e`. There is no longer that option. Please follow all the steps of the TROUBLESHOOTING section. You say "H" is output but for what gesture is that happening?

**Comment by SaitDev** [comment]
ah, about that i already answered https://github.com/bulletmark/libinput-gestures/issues/138#issuecomment-437258407

**Comment by bulletmark** [comment]
@SaitDev you have NOT provided the full output of `libinput-gestures -l`, nor done ANY of the troubleshooting steps, nor answered my question WHICH gesture causes the h to be output.

**Comment by SaitDev** [comment]
figured it out the problem, unlike arrow keys (Up, Down...) i shouldnt use capitals for letter keys. so super+h instead of super+H. thank you for response

**Comment by SaitDev** [comment]
you are right, i tried it directly with gestures config instead of xdotool alone first
