### ISSUE TITLE
How to map 3 or 4 finger horizontal swipe to ctrl+alt+(left|right arrow key)

### ISSUE THREAD

**Issue by luzpaz** [bulletmark/libinput-gestures#139]
I can't find a clear resource that shows how to do this. My objective is to simulate the Mac OS X 3 finger screen/desktop swipe

Running:
```
Kernel: 4.15.13-1-MANJARO x86_64 bits: 64 
Compiler: gcc v: 7.3.1 
Desktop: Xfce 4.12.4 (Gtk 2.24.31) 
Distro: Manjaro Linux 17.1.7 Hakoila 
libinput 1.10.3
```

**Comment by bulletmark** [comment]
Please note step 7 of the TROUBLESHOOTING instructions. Please paste the output of `libinput-gestures -e` here, and also of `libinput-gestures -l` to show what config you are using.

I haven't used a Mac for many years and have never used Xfce. Please state exactly what you want to do. E.g. What does ctrl+alt+left/right do? etc.

**Comment by luzpaz** [comment]
Sorry, I didn't see that TROUBLESHOOTING section. 
`libinput-gestures -e` returns  
```
libinput-gestures: session xfce+x11 on Linux-4.15.13-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.6.4, libinput 1.10.3
libinput-gestures: using /etc/libinput-gestures.conf with 6 gestures
libinput-gestures: device /dev/input/event8: DLL0704:01 06CB:76AE Touchpad
```

`libinput-gestures -l` returns  
```
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
```
XFCE is a linux window manager. I'm on a laptop so I want to have multiple workspaces(desktops) that I can toggle back and forth between. For example, I have a dev environment on one and a web browser for misc. things on another. I separate them so I can work efficiently. Right now when I press `ctrl+alt+right arrow` then the screen changes to the next workspace. You can see that in the screencast, though I start the screencast showing how I manually use the mouse to get to the next workspace..only a few moments later do i use the key-combo. 

![switch-workspaces](https://user-images.githubusercontent.com/4140247/38156215-e13def1c-346b-11e8-8af2-c03fe3413a29.gif)
 
What I would love to do is map the 3 finger horizontal gesture to the key-combo so i can 3 finger swipe to get to the next workspace instead of using the key-combo...make sense?

**Comment by bulletmark** [comment]
Ok, so you simply want to add 2 gestures like:

    gesture swipe left    xdotool key ctrl+alt+Left
    gesture swipe right   xdotool key ctrl+alt+Right

But surely you have tried this so what doesn't work?

**Comment by luzpaz** [comment]
That actually worked! Thank you. 
My question though is how do I differentiate the 3 finger and 4 finger swipes from each other?

**Comment by bulletmark** [comment]
Those 2 lines are commented out examples from the default `libinput-gestures.conf`.

To make them 3 finger only:

    gesture swipe left    3 xdotool key ctrl+alt+Left
    gesture swipe right   3 xdotool key ctrl+alt+Right

**Comment by luzpaz** [comment]
So 4 fingers is:
```
gesture swipe left    4 xdotool key ctrl+alt+Left
gesture swipe right   4 xdotool key ctrl+alt+Right
```
Nice!
If you want I can add a little extra line in the .conf file directing other peoples attention to this little known fact?

**Comment by bulletmark** [comment]
It's documented at the top of the default `libinput.conf` file.

**Comment by slarsar** [comment]
> So 4 fingers is:
> 
> ```
> gesture swipe left    4 xdotool key ctrl+alt+Left
> gesture swipe right   4 xdotool key ctrl+alt+Right
> ```
> 
> Nice!
> If you want I can add a little extra line in the .conf file directing other peoples attention to this little known fact?

Thank you, I added '-' before finger number and it was not work , real confused me .thank you
