### ISSUE TITLE
Finger Count

### ISSUE THREAD

**Issue by Aterocana** [bulletmark/libinput-gestures#14]
First of all congrats for this excellent tool, which I find very useful.
This isn't a real issue, just a question about using gestures specifying the finger_count option.
How can I specify it? For example `gesture: pinch out	xdotool key super+s` is the command to open the overview activity on Gnome with the gesture pinch out. How can I specify the same gesture for just 4 fingers (instead of 3 and 4 like it is now)?
Moreover, leaving the default config file, I often have the overview opened when I try to tap with 3 fingers (for example to open a page in a new tab on chromium).
Thank you for your efforts.

**Comment by bulletmark** [comment]
Read the comments at the top of the config file http://github.com/bulletmark/libinput-gestures/blob/master/libinput-gestures.conf. You just insert the finger count, i.e. 3 or 4, between the gesture and the command. So for your example:

    gesture: pinch out 4 xdotool key super+s

It's a bit of a kludge I agree but I added the finger count option later and wanted to preserve the existing syntax. If the first field in the configured command is a single character number then the software strips it out as a finger count.
