### ISSUE TITLE
Overview in Plasma

### ISSUE THREAD

**Issue by michaldybczak** [bulletmark/libinput-gestures#142]
In Plasma overview is launched by default with ctrl+f9, I also set additional key to meta+x for convenience.

I wanted to set a gesture for it so I thought, 3 finger swipes up/down are already reserved for virtual desktop switch for me (swipe up/down	3 _internal ws_down/up), I set 4 gesture swipe:

gesture swipe down  4 xdotool key ctrl+f9

I reloaded configuration and I don't see any results. What am I doing wrong?
Or maybe it's better to use pinch for it?

P.S. By the way, with time libinput-gestures became more and more awesome and not only because of new possibilities but also by gestures detection. Maybe it was libinput updates? At the beginning detection was clunky and success rate was about 20-30%, now it's 100% most of the time - smooth, without any mismatches! This is SUPER AWESOME, like native super multi gestures touchpad! So THANK YOU AGAIN FOR THIS INCREDIBLE SOFTWARE!

P.S.2 I recommend to correct Plasma overview in Kwin Desktop Effects settings from default "natural" setting (and ugly, chaotic view) to "regular grid" (more like a gnome style)

**Comment by bulletmark** [comment]
As per troubleshooting section step 7, please paste the output of `libinput-gestures -e` here. Also paste `libinput-gestures -l` output to see what other gestures you have configured.

Have you tried the obvious? I.e what happens when you run `xdotool key ctrl+f9` directly on the command line?

**Comment by michaldybczak** [comment]
Thanks, I tried `xdotool key ctrl+f9 `and got `ignore` output so I corrected it to `xdotool key ctrl+F9` it worked! So I rewrote the gesture to:

#Open/close overview in Plasma:
gesture: swipe down	4 xdotool key ctrl+F9

It works! Thank you very much :D

That is maybe not necessary but here is my` libinput-gestures -e` output:
```
libinput-gestures: session KDE+x11 on Linux-4.16.2-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.6.4, libinput 1.10.4
libinput-gestures: using ~/.config/libinput-gestures.conf with 7 gestures
libinput-gestures: device /dev/input/event7: SynPS/2 Synaptics TouchPad
```

**Comment by mllg** [comment]
In case somebody else lands here via google (like me), for KDE/wayland you can use `qdbus` to get the window overview:

```
gesture pinch in qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Expose
gesture pinch out qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Expose
```
