### ISSUE TITLE
Swipes are creating notices or pastes in Plasma desktop

### ISSUE THREAD

**Issue by michaldybczak** [bulletmark/libinput-gestures#146]
I tested intensely libinput-gestures last week and I came across few issues. One of it is really weird. I'm using Manjaro KDE, updated 64bit system.

If gesture is made on desktop directly (which is not covered behind windows) it always put notices. Initially I believed it is triggering paste action, because the note is always filled with what is in clipboard. Also when using it with window where there is box with text to write, gesture is also pasting clipboard entry. However, pressing ctrl+v is giving different output on desktop (a dialog to name new document) so I am confused.

I installed Neon in VirtualBox to test if this issue is reproducible and it is. I installed libinput-gestures on Neon, configured all swipe gestures to ctrl+F9 and did few gestures with all minimized windows and I also got notices on desktop with pasted clipboard so that's a general bug.

I need to find out if that's libinput-gesture fault (so you can look into it and possibly fix) or is it libinput or plasma itself? If it turns out to be not libinput-gesture fault, I file a bug to proper place but I have to start somewhere.

My understanding is: libinput-gestures uses some libinput API to translate libinput gestures into xdotool. If so, why a gesture that is a success and is producing desirable result is also creating an additional, not intended result?

This also happens when libinput fails to recognize the gesture so initially I thought it happens only in those situations, but then I started seeing on successful gestures.

Can you look into it? Using gestures in Plasma becomes tiring because I get dozens of yellow notices that I have to delete afterwards.

I just want to improve libinput-gestures in Plasma and for that we need to find the root of the issue and fix it or file a bug report so it would be fixed.
Thanks

**Comment by bulletmark** [comment]
As per the troubleshooting section step 7, please paste the output here of `libinput-gestures -el`.

**Comment by michaldybczak** [comment]
```
[michaldybczak@alienware-PC ~]$ libinput-gestures -el
libinput-gestures: session KDE+x11 on Linux-4.16.2-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.6.4, libinput 1.10.4
libinput-gestures: using ~/.config/libinput-gestures.conf with 6 gestures
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down         xdotool key ctrl+F9
swipe up           xdotool key ctrl+F9
swipe left         xdotool key ctrl+F8
swipe right        xdotool key ctrl+F8
pinch in           xdotool key ctrl+minus
pinch out          xdotool key ctrl+plus
```

**Comment by bulletmark** [comment]
What is `ctrl+F8` expected to do?

What happens when you execute `xdotool key ctrl+F9` in a terminal window. So long as your terminal app is not interpreting those keys then whatever problem you see should reoccur, and thus nothing to do with `libinput-gestures`.

**Comment by michaldybczak** [comment]
ctrl+F8 does desktop grid (probably must be enabled in desktop effects, I assume it is enabled by default but I'm not sure):

![screenshot_20180426_235012](https://user-images.githubusercontent.com/10132958/39333861-c16da596-49ac-11e8-8083-5bc9c53b3438.jpg)

xdotool key ctrl+F9 does overview:

![screenshot_20180426_235210](https://user-images.githubusercontent.com/10132958/39333885-e5b87688-49ac-11e8-95f0-ef5903ff9b02.jpg)

As I said, issue is reproducible on other DE with the same DE. I understand that you didn't code anything more so it shouldn't add anything that is not there but somehow execution does something extra and probably this extra is added outside libinut-gestures but libinut-gestures contributes to it somehow or is triggering something that creates that effect. I guess it would be easier if you would be using Plasma yourself and be a KDE developer... but you're not so I predict you may have no idea where to look at, but since I don't know what you don't know or know, it doesn't hurt to ask, maybe you will get some idea. Or maybe you will be talking with some Plasma user or developer and you mention this and then the other person may have idea where to look. Who knows? I'm fishing now ;)

Also, there has to be a way to observer what is happening on the computer in real time (something like wireshark but for desktop processes) to see what is happening. Or maybe there isn't?. Hmmm...

**Comment by bulletmark** [comment]
You didn't answer my question. What happens when you execute these xdotool commands manually yourself in a terminal?

**Comment by michaldybczak** [comment]
I already did: they trigger those effects as intended. The real swipe is different, because it may be done on a pure desktop without windows on it (all minimized) and only then this issue appears. You cannot do terminal commands without terminal.
My point is, despite your package working, probably executing it on plasmashell triggers unwanted effect. This could be as well a plasmashell bug. However, I started with you, because this usually goes like this: not my issue, it's the other one, the other one will say, I don't know anything about it, if the other project triggers it on mine, it's the other one issue. And so on, ball is passed on.

The thing is, this may not be directly libinput-gestures issue, but it may be triggering something in this DE and to some limited extent the package is responsible. It's hard to tell if that is something you can tweak to avoid that collision with Plasma, or maybe this is something that Plasma should not do and can be fixed on their side. Either way we must gather as much info as possible to file a bug in proper place and in a proper manner to avoid the "not my thing" game. Maybe it's unavoidable and plasma needs some function and they won't fix it or maybe this is a real bug that can be fixed.

I'm not an IT person and no developer so for me it's hard to debugg such things. If you have no ideas where to look for, I may try to file a plasmashell bug and link it to this thread and let's hope someone will be interested in checking it on their side.

EDIT. I have an idea: maybe I rewrite this gesture from xdotool to this wmctrl and see if this happens as well? Maybe this is a xdotool thing and can be avoided? Also the plus would be if it worked in wayland. However, this wmctrl or is confusing and I cannot comprehend logic behind it so I don't know how to trigger a key shortcut with it but from what I read it should be possible. This paste-notice effect was present when I had configured swipes for workspaces so if overview and grid view are not possible to set with it, I can try out those gesture swipe up	_internal ws_up.

**Comment by bulletmark** [comment]
"You already did"? I reread your post above and still don't see where you answered my question. Anyhow, just think a little bit more out of the box. Do the following command in a terminal then minimise the window etc, move your mouse and click on the desktop, and see if the problem happens.

    sleep 10; xdotool key ctrl+F9

The default up+down swipe configuration in the default `libinput-gestures.conf` should already work in KDE to change workspaces. It uses an `_internal` command which ultimately calls wmctrl to select the new workspace. You can even configure KDE virtual desktops in a NxM grid and swipe up/down/left/right to move around them. See the examples and comments in the default `libinput-gestures.conf` for how to do this.

**Comment by michaldybczak** [comment]
The command invokes proper effect but no issue with the notice paste. So it's not xdotool then.

Here is the video I made now to show you how it happens when using gesture:

https://youtu.be/wQh90p8fFcY

As you can see, notice shows up in place where cursor is.

**Comment by michaldybczak** [comment]
**OK, I think I am on to something!**

When I went to Plasma's settings->pad I see that there is an option "emulation of mouse click" and it has 3 sub-options for 1, 2 and 3 fingers.
I turned the whole option off and... Gestures stopped working! The issue is, when the option is on, all three sub-options are grayed out so I can't disable this 3 finger emulation. Maybe it has something to do with libinput not matching completely synaptic pad?

**Comment by bulletmark** [comment]
I see that if you do a "paste" on the KDE desktop then it will create a note with the contents of the clipboard. Paste is middle click which libinput generates on a touchpad when 3 fingers are tapped (see https://wayland.freedesktop.org/libinput/doc/latest/touchpads.html and https://wayland.freedesktop.org/libinput/doc/latest/clickpad_softbuttons.html).

So I suggest those notes are being created when you triple tap, not when you do a clean gesture. Perhaps your touchpad/libinput is not discerning them accurately but either way it is not an issue for this utility.

**Comment by michaldybczak** [comment]
Somehow when I disabled this mouse click emulation my gestures weren't disabled like the last time. Strange. Either way, the issue is no more and you know what to say if someone else will complain about it ;).

**Comment by michaldybczak** [comment]
Eh... I had to enable this emulation again, because without it I can't do normal confirmation taps :(

So yeah, it looks like a driver issue because 3 finger swipe is automatically recognized as this 3 finger emulation tap. I never used it so I didn't know that it even existed but yes, 3 fingers tap does puts notes with pasted content and most of the 3 finger swipes have this double effect: swipe plus tap, hence the issue.

If I could only disable the 3 finger emulation, but the option is grayed out :(. Hmm... What to do? Find conf that is responsible for it and edit it manually? Because Plasma has "such great" documentation... Or maybe that's a driver thing? This looks like a issue above my skills to solve. The easiest way to workaround would be to assign 4 gesture swipes.

Anyway, thanks for help. Talking to someone stirs productivity and because of that we know more.

**Comment by michaldybczak** [comment]
I added this to KDE bugtracker. We'll see if it brings any result or will be closed or ignored...:

https://bugs.kde.org/show_bug.cgi?id=393755

**Comment by DaanDL** [comment]
@michaldybczak I had the same issue, thanks for investigating this!

**Comment by michaldybczak** [comment]
I can confirm that 3 swipes are still creating notices on Plasma desktop.
I'm trying to reopen my bug report. Maybe it will need to open another one. We'll see. Anyway, the GUI that was grayed out is now gone, and we still have no way to disable this atrocious behavior. Who on earth could think that 3 finger swipe is a good idea to paste notices???

**Comment by cfeck** [comment]
If your input driver still sends a middle-click with a 3-finger swipe, then you need to disable the Paste mouse action in Plasma, or reassign it to a different button.

**Comment by michaldybczak** [comment]
I searched through my mouse and pad settings, there is no option for paste mouse action or anything similar. So I have no idea where to find it.

**Comment by cfeck** [comment]
Right-click desktop > Configure Desktop > Mouse Actions

**Comment by michaldybczak** [comment]
Wow, this works. I get no longer yellow notices on desktop during 3 finger swipe. Thanks!
This was so easy, and yet I haven't figured it out, although I use Plasma for 5 years ;P.
