### ISSUE TITLE
3 finger and 4 finger functionality

### ISSUE THREAD

**Issue by Shmink** [bulletmark/libinput-gestures#149]
I'd like to have both 3 finger gestures (for workspaces) and 4 finger gestures (for browsers). 3 fingers I've been able to set up but 4 fingers is the issue. For example, I'd like to do the following:
`gesture swipe left  4 _internal xdotool key contol+Tab`.

But of course this results in an error with `xdotool` with the following output:
`usage: _internal [-h] [-w] [--row ROW] [--col COL] {ws_up,ws_down}
_internal: error: argument action: invalid choice: 'xdotool' (choose from 'ws_up', 'ws_down')
`

Is `ws_up` and `ws_down` the only options when it comes to the `n _internal` command? Is my command even correct? or if so is there another way to get what I'd like?

**Comment by bulletmark** [comment]
Please follow the instructions in the TROUBLESHOOTING section, in particular the last step.

**Comment by bulletmark** [comment]
`_internal` is a special command built internally into `libinput-gestures` to switch workspaces/desktops universally on all desktops and works both for both Xorg and Wayland clients (`xdotool` can never work for Wayland clients).

So your configured command `_internal xdotool` is completely off track. See the examples in the default `libinput-gestures.conf` file. In short, play around with `xdotool` on the command line to create the exact command which does what you want and when it works then configure it as:

    gesture swipe left 4 xdotool <whatever_works>

**Comment by bulletmark** [comment]
Note also your spelling mistake `contol` in your example config. That is an example mistake you find and remove when you practice it on the command line first.
