### ISSUE TITLE
question: is 3-finger swipe window dragging supported?

### ISSUE THREAD

**Issue by gallowstree** [bulletmark/libinput-gestures#152]
This is the main reason I want to install libinput-gestures, but not sure it will work, as most of the docs mention navigating workspaces as the main use case.

**Comment by bulletmark** [comment]
No, that is not what libinput calls a gesture. Read https://wayland.freedesktop.org/libinput/doc/latest/touchpads.html and linked pages for more info. Most DE's provide a easy way to drag windows anyhow. E.g. GNOME provides super + 2 finger drag or just double tap and hold in the title bar if you just want to use your touchpad fingers only.

**Comment by anbroid** [comment]
> This is the main reason I want to install libinput-gestures, but not sure it will work, as most of the docs mention navigating workspaces as the main use case.

@gallowstree This got forked recently, works great for 3-finger drag:
https://github.com/daveriedstra/libinput-gestures/tree/three-finger-drag

Using it successfully with an Arkscan TP01 / Jelly Comb USB touchpad.

**Comment by specious** [comment]
It's not just about dragging windows, it's also for selecting text with a three finger swiping motion. I use it constantly.

That's why I'm currently using the above mentioned fork.

**Comment by specious** [comment]
There seems to be some confusion as to which software layer needs to implement this functionality. Please take a look at this [discussion](https://gitlab.freedesktop.org/libinput/libinput/-/issues/298) about adding three finger drag support to libinput itself.
