### ISSUE TITLE
E: Unable to locate package libinput-tools

### ISSUE THREAD

**Issue by utkarsh447** [bulletmark/libinput-gestures#155]
Followed Documentation and tried,
sudo apt-get install libinput-tools

Got error:
E: Unable to locate package libinput-tools

Using ubuntu 16.04 LTS
Please have a look at this issue.

**Comment by bulletmark** [comment]
Firstly, please note the troubleshooting instructions (and the new issue template) require you to paste the output of `libinput-gestures -l` when you raise a new bug. Please add that here.

Secondly, please note the installation instruction you are referring to is a short one-line which says "Debian and Ubuntu users also need to install `libinput-tools` **if that package exists in your release**". So I don't understand your confusion?

I'll add a "may" in front of "also need to install" but heck we are splitting hairs here.

**Comment by bulletmark** [comment]
Closing as no response from OP.
