### ISSUE TITLE
"could not determine touchpad device" when run libinput-gestures

### ISSUE THREAD

**Issue by enlighten5** [bulletmark/libinput-gestures#156]
```
Run libinput-gestures -l on the command line and paste the output here.  
libinput-gestures: session ubuntu+x11 on Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.6.3

Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         4 xdotool key ctrl+alt+Up
swipe down       4 xdotool key ctrl+alt+Down
swipe left       4 xdotool key ctrl+alt+Left
swipe right      4 xdotool key ctrl+alt+Right
swipe up         3 xdotool key shift+super+w
swipe down       3 xdotool key super+d
swipe left       3 xdotool key alt+Left
swipe right      3 xdotool key alt+Right
pinch out          xdotool key ctrl+super+Up
pinch in           xdotool key ctrl+super+Down
Could not determine touchpad device.


```

**Describe the issue**
I'm using a apple magic trackpad 2 and got that issue. I followed the instructions in README and the device info is showed when i run libinput-list-devices
Thank you very much!

**Comment by bulletmark** [comment]
Did you do the steps in the TROUBLESHOOTING section? Note particularly step 2 and step 8.

**Comment by enlighten5** [comment]
Yes I followed the steps and reboot after add myself in input group. the libinput-gestures -l is in the above. Here is the libinput-gestures -d, libinput-gestures -r and libinput-list-devices:
libinput-gestures -d
libinput-gestures: session ubuntu+x11 on Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.6.3

Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         4 xdotool key ctrl+alt+Up
swipe down       4 xdotool key ctrl+alt+Down
swipe left       4 xdotool key ctrl+alt+Left
swipe right      4 xdotool key ctrl+alt+Right
swipe up         3 xdotool key shift+super+w
swipe down       3 xdotool key super+d
swipe left       3 xdotool key alt+Left
swipe right      3 xdotool key alt+Right
pinch out          xdotool key ctrl+super+Up
pinch in           xdotool key ctrl+super+Down
Could not determine touchpad device.

libinput-gestures -r
libinput-gestures: session ubuntu+x11 on Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.6.3
Could not determine touchpad device.

libinput-list-device:
Device:           Apple Inc. Magic Trackpad 2
Kernel:           /dev/input/event3
Group:            5
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

**Comment by bulletmark** [comment]
Is that the full output of `libinput-list-devices`? You only have 1 device listed.

**Comment by enlighten5** [comment]
Thank you for your reply!
the whole list is like this:
Device:           Power Button
Kernel:           /dev/input/event2
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event6
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event1
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Sleep Button
Kernel:           /dev/input/event0
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Apple Inc. Magic Trackpad 2
Kernel:           /dev/input/event3
Group:            5
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

Device:           HID 046a:0011
Kernel:           /dev/input/event4
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           DELL Laser Mouse
Kernel:           /dev/input/event5
Group:            7
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

Device:           Dell WMI hotkeys
Kernel:           /dev/input/event7
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

**Comment by bulletmark** [comment]
Well libinput is not recognizing your touchpad explicitly. Did you try with an explicit device name? E.g. set

    device Apple Inc. Magic Trackpad 2

in your `~/.config/libinput-gestures.conf` file and see if that works.

I don't know Ubuntu but your kernel and libinput versions seem quite old. You are much more likely to have success with later versions, e.g. my standard Arch system has kernel 4.16.13 and 1.11 compared to your 4.13.0 and 1.6.3. Perhaps upgrade your Ubuntu release?

**Comment by enlighten5** [comment]
Thank you so much. libinput recognizes my device now. but it semms like the gestures is not working. the only thing I can do is move cursor with one finger and click. 
here is my /usr/share/X11/xorg.conf.d/40-libinput-conf file:
Section "InputClass"
        Identifier "libinput touchpad catchall"  
        MatchIsTouchpad "on"   
        MatchDevicePath "/dev/input/event*"  
        Driver "libinput"Option   
        "Tapping" "True"  
EndSection

**Comment by enlighten5** [comment]
part of libinput-gestures -r is like this: i tried with multiple-touches and they look all the same
libinput-gestures: session ubuntu+x11 on Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.6.3

libinput-gestures: device /dev/input/event3: Apple Inc. Magic Trackpad 2
-event3   DEVICE_ADDED     Apple Inc. Magic Trackpad 2       seat0 default group1  cap:p left scroll-nat scroll-button
event3   POINTER_MOTION    +1.01s	  0.00/  0.30
event3   POINTER_MOTION    +1.02s	  0.00/  2.65
event3   POINTER_MOTION    +1.03s	  0.00/  5.00
event3   POINTER_MOTION    +1.04s	  0.00/  4.00
event3   POINTER_MOTION    +1.05s	  0.00/  4.00
event3   POINTER_MOTION    +1.07s	  0.00/  3.00
event3   POINTER_MOTION    +1.08s	  0.00/  2.00
event3   POINTER_MOTION    +1.09s	  0.00/  2.00
event3   POINTER_MOTION    +1.10s	  0.00/  4.00
event3   POINTER_MOTION    +1.11s	  0.00/  3.00
event3   POINTER_MOTION    +1.12s	  0.00/  2.00
event3   POINTER_MOTION    +1.19s	 -0.96/ -2.89
event3   POINTER_MOTION    +1.20s	  0.00/ -1.93
event3   POINTER_MOTION    +1.21s	 -1.00/ -7.02
event3   POINTER_MOTION    +1.22s	 -3.28/ -9.85
event3   POINTER_MOTION    +1.23s	 -4.83/ -9.66

**Comment by bulletmark** [comment]
Adding that device command to `libinput-gestures.conf` won't change anything with respect to libinput. That just tells `libinput-gestures` what device to monitor. It is likely (at least with the old versions you are using) that no gestures are being reported by that touchpad. Run `libinput-debug-events` and look for raw GESTURE events as you move your fingers. If you don't see any, then there is nothing this utility can do. As I said, consider updating to a later Ubuntu release.

**Comment by enlighten5** [comment]
I run libinput-debug-event and got the result similar like the result of libinput-gestures -r I just posted. It seems like it can only recognize single-finger movement and click. 
I'll also try to update my kernel and libinput

**Comment by bulletmark** [comment]
Closing this because not a problem with `libinput-gestures`. Please return and comment if you update your versions.
