### ISSUE TITLE
libinput 1.11.1-1 not playing nice

### ISSUE THREAD

**Issue by rjl6789** [bulletmark/libinput-gestures#158]
Hi,
I think this is more of an fyi as opposed to an issue with libinput-gestures but the recent update to libinput 1.11.1-1 (arch) has broken libinput-gestures for me. libinput-gestures was failing to find my device (I've been succesfully using libinput-gestures previous to the 1.11.1-1 update). calling libinput list-devices caused a segmentation fault, hence assuming the issue is with libinput.  Downgrading to libinput to 1.11.0-1 restores gestures.
Regards
Rob

**Comment by bulletmark** [comment]
See https://gitlab.freedesktop.org/libinput/libinput/issues/50.

I will leave this bug open until that `libinput` issue is fixed for others to read.

**Comment by michaldybczak** [comment]
Yeah, I also noticed that libinput-gestures won't start after libinput update. Maybe I'll downgrade it till the fix arrives. Or maybe I'll just wait. Fix was merged 15 hours ago. Now it's just a matter of how quickly it will be available on Arch/Manjaro. Will they wait for more commits to post a new version or maybe that goes right away to repo as a new version? Hmmm...

Anyway, thanks @bulletmark for letting us know what is going on.

**Comment by bulletmark** [comment]
Also raised [a bug on Arch](https://bugs.archlinux.org/task/59082) hoping to get the fix ported asap. Please vote for the bug there.

**Comment by HallWoodZhang** [comment]
This is the bug of the libinput, not the libinput-gesture. When the script run the "libinput list-devices", then a segment fault exception would be raised.

**Comment by HallWoodZhang** [comment]
Now, if you are using archlinux, you can.
`Enable the testing repository on /etc/pacman.conf:

[testing]
Include = /etc/pacman.d/mirrorlist
Install libinput xz package:
# pacman -Sy libinput

and then run libinput list-device
if no error is reported, restart the libinput-gesture
`

[https://archlinux.pkgs.org/rolling/archlinux-testing-x86_64/libinput-1.11.1-2-x86_64.pkg.tar.xz.html](url)

**Comment by michaldybczak** [comment]
Thanks! If it's in Arch testing we should get it in few days (Manjaro unstable). Will look for it.

**Comment by bulletmark** [comment]
Package `libinput 1.11.1-2` with this fix was updated in the standard Arch packages today.
