### ISSUE TITLE
Elantech Touchpad Support

### ISSUE THREAD

**Issue by malimM** [bulletmark/libinput-gestures#16]
Thank you for this, it's one feature I miss from Windows 10. I keep on getting this error when setting up, after executing: `./libinput-gestures -d`

libinput error: libinput bug: Event for missing capability CAP_GESTURE on device "ETPS/2 Elantech Touchpad"

What am I to do here? I'm on Manjaro with KDE.

**Comment by bulletmark** [comment]
Appears to be same issue as https://github.com/bulletmark/libinput-gestures/issues/12.
