### ISSUE TITLE
libinput-gestures stops working after some time

### ISSUE THREAD

**Issue by leewdch** [bulletmark/libinput-gestures#160]
I noticed this happens after a period of inactivity (last time I checked uptime it happened after 1 hour from boot) AND after waking the system up from sleep mode

This is the content of my config file in `~/.config`
```
gesture swipe left   3 xdotool key alt+Right
gesture swipe right  3 xdotool key alt+Left
gesture swipe left   4 bspc desktop -f next
gesture swipe right  4 bspc desktop -f prev
```
At first I tried using the /etc/ config file but it gets reset after sometime for some reason so I started using this local config file hoping for a solution but gestures keeps resetting. It's not only missing gestures but general responsiveness that affects me, in fact general scrolling in web pages is delayed by 1 second. I tried restarting libinput-gestures but the config file is ignored and it looks like it is only using the general config in /etc/

When I try to use 4 fingers to switch workspace it fires the alt+Right or alt+Left instead. I don't know if it is using the default /etc/ config file or it's just something wrong with my local config

**Comment by bulletmark** [comment]
Please note the instructions if you raise a bug you MUST paste include the output of `libinput-gestures -l`.

**Comment by leewdch** [comment]
I noticed that two finger scrolling stops working as well sometime so I'm starting to think that  this might not be a libinput-gestures issue..

This is the output of the command
```
$ libinput-gestures -l
libinput-gestures: session unknown+unknown on Linux-4.17.3-1-ARCH-x86_64-with-arch, python 3.6.5, libinput 1.11.1
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       3 xdotool key alt+Right
swipe right      3 xdotool key alt+Left
swipe left       4 bspc desktop -f next
swipe right      4 bspc desktop -f prev
swipe up           _internal ws_up
libinput-gestures: device /dev/input/event13: SynPS/2 Synaptics TouchPad
```
This is my X11 configuration for my touchpad
```
$ cat /etc/X11/xorg.conf.d/30-touchpad.conf 
Section "InputClass"
    Identifier "devname"
    Driver "libinput"

    Option "Tapping" "true"
    Option "ClickMethod" "buttonareas"
    Option "TappingButtonMap" "lrm"
    Option "TappingDrag" "false"
    Option "NaturalScrolling" "true"
EndSection
```

**Comment by bulletmark** [comment]
It is not an issue with libinput-gestures, it is an issue likely with your hardware, bios, libinput and/or Linux kernel. Others have reported this, e.g see issue #68, and an occasional post on the Arch forums and reddit. I just wanted your `libinput-gestures -l` output to see how unique your environment is but it looks pretty stock Arch, apart from running bspwm which should be irrelevant. Perhaps ensure your bios is up to date but other than that I can not suggest anything more. What notebook/machine is this running on?
