### ISSUE TITLE
Could not determine touchpad device.

### ISSUE THREAD

**Issue by imlyox** [bulletmark/libinput-gestures#162]
Hi I had the Xiaomi Mi notebook air 13 2017 and when I try to restart the libinput gesture on the console this is the error:

libinput-gestures-setup restart

(gtk-launch:4376): Gtk-WARNING **: Theme parsing error: gtk.css:4691:30: Junk at end of value

(gtk-launch:4376): Gtk-WARNING **: Theme parsing error: gtk.css:4706:30: Junk at end of value

(gtk-launch:4376): Gtk-WARNING **: Theme parsing error: gtk.css:4715:19: Junk at end of value
libinput-gestures started.
david@Lyox-ElementaryOS:~$ Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Can not see any devices, did you add yourself to the input group and log out/in?
Could not determine touchpad device.

**Comment by bulletmark** [comment]
It's telling you your mistake in the second last sentence. Please follow the trouble shooting section. Note step 2 and step 7 particularly.

**Comment by bulletmark** [comment]
No response from OP so closing ..
