### ISSUE TITLE
3 or 4 Fingers Tap

### ISSUE THREAD

**Issue by baharalidurrani** [bulletmark/libinput-gestures#164]
Hi,
Great Work! It helped me a lot. Just one question by the way.
How can I add an action for 3 or 4 fingers TAP not swipe.
Example tap 3 fingers to go back in browser.

durrani@ideapad:~$ libinput-gestures -l
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.5, libinput 1.10.4
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 _internal ws_up
swipe down       3 _internal ws_down
swipe left       3 xdotool key alt+Tab
swipe right      3 xdotool key alt+shift+Tab
swipe right      4 xdotool key alt+Right
swipe left       4 xdotool key alt+Left
swipe down       4 xdotool key ctrl+super+d
swipe up         4 xdotool key ctrl+super+d
swipe right_up   3 xdotool key control+Tab
swipe left_up    3 xdotool key control+shift+Tab
swipe left_down  3 xdotool key control+w
swipe right_down 3 xdotool key control+shift+t
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/event13: Elan Touchpad

**Comment by bulletmark** [comment]
No, you can not configure anything for taps using this tool. This tool is quite simple and merely catches what [libinput calls gestures](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html) which is presently only 3+ finger swipes and 2+ finger pinches, and maps them to your configured command strings. I guess you could write another program to catch other events but there is no plan to expand this tool beyond libinput gestures.

**Comment by bulletmark** [comment]
BTW, I use 3 finger swipe right/left to go back/forward in browser, and also use swipes to move between tabs, and to close and re-open tabs as described at https://github.com/bulletmark/libinput-gestures#extended-gestures. I have never had much feedback about this but I use it personally and it works very well.

**Comment by baharalidurrani** [comment]
Thank you very much for explaining it to me.
I didn't know that taps are supported by libinput.
