### ISSUE TITLE
Configurable swipe distance

### ISSUE THREAD

**Issue by tadly** [bulletmark/libinput-gestures#165]
I'd be nice to be able to set some form of "distance" you have to swipe for the configured action to trigger.  
In my specific case, doing a 3 finger tap/click (to paste my clipboard) often times resolves in a 3 finger swipe, change my active workspace instead.  

Just to be clear, it is (in my case) enough to...
 1. place 3 fingers on the touchpad
 2. have them move up/down by about 0.1 - 0.2 cm
 3. release fingers

...to be considered a swipe instead of a tap.

```
$ libinput-gestures -l
libinput-gestures: session i3+x11 on Linux-4.17.8-1-ARCH-x86_64-with-arch, python 3.6.6, libinput 1.11.2
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up           i3-msg workspace prev
swipe down         i3-msg workspace next
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
libinput-gestures: device /dev/input/event17: DLL0665:01 06CB:76AD Touchpad
```

**Comment by bulletmark** [comment]
I used to have a threshold distance for swipes but removed it after some complaints. I just added it back with commit 6195e39243e1f079e9f99036d8aac272e9fefcc4 in test branch `threshold` but have set the default to 0 dots. You can set some other value with the `swipe_threshold` command in your `~/.config/libinput-gestures.conf`. See the comments at the bottom of the default file. Please try this branch out and if it does what you want I will add it to the master branch and next release.

Note that this program does not decide on what is a swipe, and what is a tap. This is all done with libinput so if you configure that option that will only stop `libinput-gestures` actioning your command below that threshold, it won't magically reinterpret that small movement as a tap.

**Comment by tadly** [comment]
Wow that was quick and it does indeed work wonders!
From the little testing I also can't make out any issues :)

**Comment by bulletmark** [comment]
What dot value did you set it to?

**Comment by tadly** [comment]
Currently 300 but might fine-tune it a bit

**Comment by bulletmark** [comment]
OK. I  will add this back into master with the value 0 to give same functionality as now by default. I used to have it internally hard-coded to 70 but as I said some thought that was too high so it seems it really is a personal/hardware thing and good to have configurable.

**Comment by tadly** [comment]
Certainly agree and thanks a lot :)

**Comment by bulletmark** [comment]
And there is a new release in the AUR for you :)

**Comment by mdmayfield** [comment]
This is fantastic! Thank you @bulletmark for adding this to master. (I was testing in a private fork with 300 dots as well, since no threshold was much too sensitive on my XPS 15.)
