### ISSUE TITLE
Libinput-gestures 2.36 totally removes /usr/share/doc when doing uninstall

### ISSUE THREAD

**Issue by semplar2007** [bulletmark/libinput-gestures#168]
And deletes lots of other stuff. Please, re-check it, it's kinda serious issue.

**Comment by bulletmark** [comment]
Please I have tried to make it very clear in the instructions, if you raise a bug **please paste the output of `libinput-gestures -l`**.

Also, you've given no hint of what you are actually doing? Are you running `make uninstall` from a git clone dir? Can you not paste some output of what the errors actually are?

Why use 2.36 when you could have easily at least used the current 2.38?

**Comment by bulletmark** [comment]
No response so assume user error.
