### ISSUE TITLE
libinput-gestures not dealing with dynamic script

### ISSUE THREAD

**Issue by Brett99** [bulletmark/libinput-gestures#169]
```
libinput-gestures: session unknown+unknown on Linux-4.14.65-1-lts-x86_64-with-arch, python 3.7.0, libinput 1.11.3
Gestures configured in ~/.config/libinput-gestures.conf:
pinch clockwise notify-send test
libinput-gestures: device /dev/input/event6: SynPS/2 Synaptics TouchPad
```

For some reason, `libinput-gestures` can't handle my script changing. It seems to be "storing" what the script does on the first run, and using this for all subsequent gestures. 

How can I make it so that it runs the script every time?

**Comment by bulletmark** [comment]
I'm sorry but your script probably has a bug. Paste it here if you don't mind.

**Comment by Brett99** [comment]
I think I found out what was happening. I had changed the config file, but couldn't reload it because `pkill libinput-gestures` wasn't working.

**Comment by Brett99** [comment]
I'm still struggling to make it so that a pinch gesture while the screenlocker is activated doesn't make it relock once it's unlocked.

**Comment by bulletmark** [comment]
"wasn't working" is not very explanatory. You mean you ran `libinput-gestures-setup restart` and got an error message?
