### ISSUE TITLE
Make .desktop Icon invocation more generic

### ISSUE THREAD

**Issue by Edenhofer** [bulletmark/libinput-gestures#17]
To allow the icon to be 'themable' simply use the icon name (without suffix) as argument to `Icon` and place your logo in `/usr/share/icons/hicolor/`*`resolution`*`/`*`whatever`*`/`.

Refer to c48357f for more information.

**Comment by bulletmark** [comment]
Fixed by commit 1e1b28162a37aa9791b3ff5b3dc41e07439d29fc
