### ISSUE TITLE
Config information for overview

### ISSUE THREAD

**Issue by crouthamela** [bulletmark/libinput-gestures#170]
In the default config it says:
```
# GNOME SHELL open/close overview (works for GNOME on Xorg only)
gesture pinch in        xdotool key super+s
gesture pinch out       xdotool key super+s
```

I just wanted to let you know that you can get the same experience in KDE with:

```
# PLASMA SHELL open/close overview (works for GNOME on Xorg only)
gesture pinch in	xdotool key ctrl+F9
gesture pinch out	xdotool key ctrl+F9
```

**Comment by bulletmark** [comment]
Why have you left the comment `(works for GNOME on Xorg only)`?

**Comment by crouthamela** [comment]
Right, I just forgot to edit that second piece of the comment. My bad.

**Comment by bulletmark** [comment]
Added this example as commit e62f4450925e0fd66e8aaabe784413cd3c7a105c.
