### ISSUE TITLE
[Feature Request] Disable/enable touchpad by touchpad itself only.

### ISSUE THREAD

**Issue by soulawaker** [bulletmark/libinput-gestures#174]
When laptop touchpad does not support palm detection fully, we need to turn off/on manually. I imagine some features. When a libinput-gesture recognizes a specific gesture which indicates disabling touchpad, disables detecting all gesture but only one which enables the touchpad again. When it detects the gesture, enables to detect all gestures. Is it possible?

**Comment by bulletmark** [comment]
Of course that is already possible if you write a script which takes an argument to switch in/out a pair of alternate `libinput-gestures.conf` files (and also can do the manual disable/enable palm detection?). Then configure a gesture to run that script + argument[s].

**Comment by soulawaker** [comment]
I'm impressed! I confirmed it's possible, too. I couldn't imagine the gestures still is enabled while touchpad is off. Wow! It's really possible. Thanks you!
