### ISSUE TITLE
Hide 'Gestures' app icon

### ISSUE THREAD

**Issue by dmig** [bulletmark/libinput-gestures#175]
```
libinput-gestures: session ubuntu+x11 on Linux-4.18.12-041812-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.6, libinput 1.10.4
Gestures configured in ~/.config/libinput-gestures.conf:
libinput-gestures: device /dev/input/event11: DELL0804:00 06CB:7E7E Touchpad
```

'Libinput gestures' icon only used for autostarting daemon. So please add `NoDisplay=true` to .desktop file.

**Comment by bulletmark** [comment]
There are probably users who don't start `libinput-gestures` automatically and so start it manually via their desktop/dock etc.
