### ISSUE TITLE
LIBINPUT-GESTURES don't work after system suspend

### ISSUE THREAD

**Issue by IjonFryderyk** [bulletmark/libinput-gestures#177]
Hi, LIBINPUT-GESTURES don't work after resuming from suspend. Is there any way to manually turn it on? I tried to restart it from command line but it didn't work. I need to reboot the system to make gestures work again. I have the same problem with Fusuma.

**Comment by bulletmark** [comment]
This is not an issue with this utility. E.g. see issues #68, #160, #167.
