### ISSUE TITLE
Could not determine touchpad device.

### ISSUE THREAD

**Issue by damodaranudas** [bulletmark/libinput-gestures#182]
```
libinput-gestures -l
```
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.5, libinput 1.10.4, hash ?
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
Could not determine touchpad device.
```
libinput list-devices
```
Device:           Power Button
Kernel:           /dev/input/event3
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Asus Wireless Radio Control
Kernel:           /dev/input/event8
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event6
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event5
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event0
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Lid Switch
Kernel:           /dev/input/event1
Group:            5
Seat:             seat0, default
Capabilities:     switch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Sleep Button
Kernel:           /dev/input/event2
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA ATI HDMI HDMI/DP,pcm=3
Kernel:           /dev/input/event11
Group:            7
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HD-Audio Generic Mic
Kernel:           /dev/input/event12
Group:            7
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HD-Audio Generic Headphone
Kernel:           /dev/input/event13
Group:            7
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           USB2.0 VGA UVC WebCam: USB2.0 V
Kernel:           /dev/input/event10
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Asus WMI hotkeys
Kernel:           /dev/input/event9
Group:            9
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event4
Group:            10
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           PS/2 Logitech Wheel Mouse
Kernel:           /dev/input/event7
Group:            11
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

**Describe the issue**
Laptop ASUS X555Q is known to have an issue with touchpad, I tried to install focaltech driver but it's not available anymore:
[https://askubuntu.com/questions/609892/touchpad-not-recognized-on-asus-n550jk-tp500l-focaltech
](https://askubuntu.com/questions/609892/touchpad-not-recognized-on-asus-n550jk-tp500l-focaltech
)when followed these steps I got:
```
The user named '~hanipouspilot' has no PPA named 'ubuntu/focaltech-dkms'. It shoulden't be necessary with kernels
```
Then I tried to install such driver
[https://github.com/hanipouspilot/focaltech-dkms](https://github.com/hanipouspilot/focaltech-dkms)
```
sudo dkms add ./focaltech-dkms

Creating symlink /var/lib/dkms/focaltech/1.5/source ->
                 /usr/src/focaltech-1.5

DKMS: add completed.
haribol@haribol:~$ sudo dkms install -m focaltech -v 1.5

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.15.0-36-generic -C /lib/modules/4.15.0-36-generic/build M=/var/lib/dkms/focaltech/1.5/build/src psmouse.ko....(bad exit status: 2)
ERROR (dkms apport): binary package for focaltech: 1.5 not found
Error! Bad return status for module build on kernel: 4.15.0-36-generic (x86_64)
Consult /var/lib/dkms/focaltech/1.5/build/make.log for more information.
```
I researched everywhere without more solutions now I have no clue how to detect the touchpad as a touchpad, not a PS/2 mouse.

**Comment by bulletmark** [comment]
If your touchpad is not being detected by your kernel/libinput then why are you raising a bug here?

Run `libinput debug-events` on the command line then do some touchpad swipes and pinches. If you do not see any GESTURE events reported then clearly they are not being reported for your hardware and thus there is little we can do about it here.

**Comment by ravishan110** [comment]
i tried `libinput debug-events`, and i can see the gesture events here, but still when i try `libinput-gestures -l`, it gives me `could not  determine touchpad device`

```
$ libinput-gestures -l

libinput-gestures: session pantheon+x11 on Linux-4.15.0-46-generic-x86_64-with-elementary-5.0-juno, python 3.6.7, libinput 1.10.4

/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce

Gestures configured in ~/.config/libinput-gestures.conf:

swipe up         3 xdotool key super+Up

swipe down       3 xdotool key super+Down

swipe left       4 xdotool key super+Right

swipe right      4 xdotool key super+Left

swipe left       3 xdotool key alt+Right

swipe right      3 xdotool key alt+Left

Could not determine touchpad device.
```

Anyone has an idea whats going on??

My laptop is Lenovo Ideapad 130

**Comment by bulletmark** [comment]
@ravishan110 please paste the full output here of `libinput list-devices`.
