### ISSUE TITLE
Use wmctrl with bash interpolation 

### ISSUE THREAD

**Issue by stonedMoose** [bulletmark/libinput-gestures#184]
Hi,

I try to bind three fingers swipe to switch between workspaces. 

I use dynamic desktop on gnome and a little extension to cycle through workspaces.

The goal for me is to be able to prevent switching to the empty workspace created by gnome ie. (given N the number of desktops):

- When I swipe **right**, if I'm on desktop N-2 I want to switch to the desktop 0 else to the next desktop.
- When I swipe **left**,  if I am on desktop 0 I want to switch to the desktop N-2 else to the previous one 

I found the good expression to do that using `wmctrl`, these are the commands I put  in `~/.config/libinput- gestures.conf`. These commands work in a terminal, but somehow they don't work through libinput gestures binding. Hope you can help me understand why :smile: 

**~/.config/libinput-gestures.conf**
```
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.6, libinput 1.10.4, hash ?
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       3 wmctrl -s $(((`xdotool get_desktop` - 2 + `xdotool get_num_desktops`)%(`xdotool get_num_desktops` - 1)))
swipe right      3 wmctrl -s $(((`xdotool get_desktop` + `xdotool get_num_desktops`)%(`xdotool get_num_desktops` - 1)))
swipe up         3 xdotool key super
swipe down       3 xdotool key super
swipe left       4 xdotool key alt+Left
swipe right      4 xdotool key alt+Right
libinput-gestures: device /dev/input/event11: SYNA2393:00 06CB:7A13 Touchpad
```

**Comment by bulletmark** [comment]
Your problem is explained in the second last paragraph of the configuration section of the main README.
