### ISSUE TITLE
Gestures not detected with external keyboard-touchpad combo (Logitech K400+)

### ISSUE THREAD

**Issue by AdX9170** [bulletmark/libinput-gestures#185]
```
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.6, libinput 1.10.4, hash ?
Gestures configured in ~/.config/libinput-gestures.conf:
device /dev/input/event6
libinput-gestures: device /dev/input/event6: Logitech K400 Plus
```

Gestures not working on external keyboard-touchpad combo.

I set up the library correctly as per instructions but it doesn't seem to be working with a Logitech K400 Plus keyboard-touchpad combo device. I do not see any logs while running it in debug mode.

Note: I cannot test the installation with my laptop's internal touchpad as it is not working.

**Comment by bulletmark** [comment]
No response from OP, closing.
