### ISSUE TITLE
Gestures recognized correctly but no commands executed

### ISSUE THREAD

**Issue by noir-Z** [bulletmark/libinput-gestures#186]
So -d and -r show that my swipes are recognized correctly, however none of the commands get actually executed. I did verify that wmctrl and xdotool work correctly through console. 
Here's -d
```
libinput-gestures: session KDE+x11 on Linux-4.19.1-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.1, libinput 1.12.3
/usr/bin/libinput-gestures: hash c01dd357d0887df342b87c226302309e
Gestures configured in ~/.config/libinput-gestures.conf:
libinput-gestures: device /dev/input/event10: SynPS/2 Synaptics TouchPad
libinput-gestures: SWIPE up 3 [1143.1299999999999, -1169.37]
libinput-gestures: SWIPE down 3 [-1003.4499999999999, 1082.3]
libinput-gestures: SWIPE left 3 [-1708.37, 61.32]
libinput-gestures: SWIPE right 3 [1297.3300000000002, -93.14000000000001]
```
I'm using the vanilla conf now, but i tried replacing the commands with xdotool set_desktop and the wmctrl equivalent. They both work when run from console.

**Comment by bulletmark** [comment]
As the instructions say everywhere, when raising an issue **please paste the output** of `libinput-gestures -l` here. It doesn't look like you have any gestures oonfigured?

**Comment by noir-Z** [comment]
-l shows exactly the same as the first four lines of -d, that's why i skipped posting it, sorry!
I was under the impression that without configuring anything /etc/libinput-gestures.conf gestures should work? Do i have to copy that to ~/.config/libinput-gestures.conf?
```[demian@rincewind ~]$ libinput-gestures -l
libinput-gestures: session KDE+x11 on Linux-4.19.1-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.1, libinput 1.12.3
/usr/bin/libinput-gestures: hash c01dd357d0887df342b87c226302309e
Gestures configured in ~/.config/libinput-gestures.conf:
libinput-gestures: device /dev/input/event10: SynPS/2 Synaptics TouchPad
```

**Comment by noir-Z** [comment]
Okay, i'm sorry for wasting your time, just figured out thanks to your hint "it doesn't look like you have any gestures configured". For some reason it tried to use an empty config file in ~/.config/ - i do not remember setting this up yesterday.
