### ISSUE TITLE
Multi-statement commands are not executed

### ISSUE THREAD

**Issue by arslancharyev31** [bulletmark/libinput-gestures#187]
Good day.
Single statement commands work perfectly. However, when I try to combine multiple commands into 1 statement (via `;`, `||` or `&&`) `libinput-gestures` does not seem to execute such statements. What could be the issue?

```
libinput-gestures: session KDE+x11 on Linux-4.19.2-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.1, libinput 1.12.3
/usr/bin/libinput-gestures: hash c01dd357d0887df342b87c226302309e
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down       3 xdotool getactivewindow windowminimize
pinch out        2 notify-send hello; notify-send world
libinput-gestures: device /dev/input/event11: SYNA7DB5:01 06CB:7DB7 Touchpad
```

**Comment by bulletmark** [comment]
The reason for this, and the solution, are described in the second last paragraph of the configuration section.
