### ISSUE TITLE
Environment variable is not read

### ISSUE THREAD

**Issue by arslancharyev31** [bulletmark/libinput-gestures#188]
Good day.
For some reason, I cannot get an envoronment variable from the script that is executed by `libinput-gestures`, even though I can get it if I execute the script from terminal. For example let's say I have environment variable `STACK_PATH=/home/arslan/.config/my_config/stack.txt`. If I `notify-send $STACK_PATH` in terminal or in a script that I execute from the terminal, I would receive notification with expected text. However if the same script is executed by `libinput-gestures`, then it fails to do so. Same with other commands that access this environment variable. What could be the reason for such behaviour?

```
libinput-gestures: session KDE+x11 on Linux-4.19.2-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.1, libinput 1.12.3
/usr/bin/libinput-gestures: hash c01dd357d0887df342b87c226302309e
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down       3 /home/arslan/bin/minimize_with_stack.sh
swipe up         3 /home/arslan/bin/restore_with_stack.sh
swipe down       4 xdotool search  windowminimize %@
swipe up         4 xdotool search  windowactivate %@
pinch out        2 xdotool key ctrl+plus
pinch in         2 xdotool key ctrl+minus
libinput-gestures: device /dev/input/event11: SYNA7DB5:01 06CB:7DB7 Touchpad
```

**Comment by bulletmark** [comment]
This has nothing to do with libinput-gestures and is a question about Linux. You have not stated the most important question which is where are you setting that environment variable? For GNOME I add to `~/.profile` but for KDE it [appears to be here](https://userbase.kde.org/Session_Environment_Variables).

Or put all related env vars in a file (e.g. `~/.stack.env`) and source that file in your script[s], and from `~/.bashrc` for your terminal. E.g. I do that for my BORG env vars for my backup script, and for my borg command line use.

**Comment by bulletmark** [comment]
No response from OP so closing ....
