### ISSUE TITLE
Gestures without xdotool/wmctrl

### ISSUE THREAD

**Issue by amivaleo** [bulletmark/libinput-gestures#191]
Hi!

I use GNOME Shell 3.28.3, Wayland session.
I'd like to configure a few swipe gestures so that they maximize/minimize windows or show the app-grid, etc.

I know how to do that using xdotool or wmctrl, but since these aren't supported under wayland, I'd like to ask you if you know how to avoid using them.

For example, I found this in the libinput-gestures.conf file:
`gesture swipe right 4 dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'`
(I changed the action to swipe right)

Is there some similar command for window maximizing/unmaximizing? Something like:
`gesture swipe up 3 dbus-send --session --type=method_call --dest=org.gnome.Shell [MAXIMIZE_WINDOW_TOGGLE]`

Where can I find a complete list for these commands...?

Thank you!

**Comment by bulletmark** [comment]
Sorry but I do not know much about GNOME Shell programming. I remember running [this script](https://gist.github.com/bulletmark/0b278a1ce321b960ad3fccb2d4634b55) to extract the shell source code where I found that toggle function. Have a look around there to see if you can find and use a window function to do what you want.
