### ISSUE TITLE
Works fine, but an observation

### ISSUE THREAD

**Issue by wd5gnr** [bulletmark/libinput-gestures#192]
All working but a few observations:

1) The build process isn't compatible with checkinstall -- not sure if there are options to checkinstall that would have made it work. Not a big deal.

2) With an Apple Magic Trackpad and BT headphones, gestures processed by libinput-gestures causes audible artifacts in the headphones. It is only during the duration of the gesture. Normal mouse operations do not bother the audio. Does not affect other audio streams.

This did not happen with touchegg when it used to work ;-)

**Comment by wd5gnr** [comment]
Looking at a very old bug report on the BT stack, this fixed it:

hciconfig hci0 lm ACCEPT,MASTER
hciconfig hci0 lp HOLD,SNIFF,PARK

Not sure what that means.

**Comment by bulletmark** [comment]
1. Please note the **bold output** in the opening paragraph of the trouble-shooting section.

2. I don't use debian or make a package for debian so checkinstall not really relevant sorry.

3. This program can not affect your audio. It is a very simple utility to invoke your configured commands just as if you have run them manually.

**Comment by wd5gnr** [comment]
Heh.
