### ISSUE TITLE
libinput gestures getting discarded on Elantech touchpad Ubuntu(18.10)

### ISSUE THREAD

**Issue by tanaymehta28** [bulletmark/libinput-gestures#193]
```
libinput-gestures: session ubuntu+x11 on Linux-4.18.0-13-generic-x86_64-with-Ubuntu-18.10-cosmic, python 3.6.7, libinput 1.12.1
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key super+Down
swipe left       3 xdotool key super+Right
swipe right      3 xdotool key super+Left
libinput-gestures: device /dev/input/event5: ETPS/2 Elantech Touchpad

```

**Describe the issue**
I have set custom gestures as you can see. I have restarted both the System and libinput-gestures but of to no help. 
When I try one of these above custom gestures, I get the below output:
```
libinput error: event5  - ETPS/2 Elantech Touchpad: kernel bug: Touch jump detected and discarded.
```

**Comment by bulletmark** [comment]
That kernel bug warning is harmless and very common. I see it reported on my notebook constantly and many others have reported it also but it appears to be completely benign. Do your xdotool commands work at the command line? Have you tried all the steps in the trouble shooting section?

**Comment by tanaymehta28** [comment]
> That kernel bug warning is harmless and very common. I see it reported on my notebook constantly and many others have reported it also but it appears to be completely benign. Do your xdotool commands work at the command line? Have you tried all the steps in the trouble shooting section?

Hey there! Sorry for late reply!
The real Problem is that these xdotools assigned actions don't work at all, let alone giving that bug.
I have tried all the troubleshooting steps written back there, but of to no success.
It would be really helpful, if you were to tell me the steps on reinstalling libinput-gestures and xdotools as the only possibility I can see; is a troubled-up installation.
Thanks!

**Comment by tanaymehta28** [comment]
I guess, I have solved the problem!
In Ubuntu 18.10; if you press the key combo: "super + right" simultaneously, it doesn't change to the next application; rather it takes the running app (which you are into) and makes it shift to right side of the screen. Same goes when you try to use "super + left" or "super + down".
These keys combos only shift the application window to either left or down or right, etc.
But when I manually try to do this in this order: "super + 'a split second' + right/left/down"; the multitasking works.

So I guess; you have to add some sort of a timer so that it can work as expected.
Note: For all this time; I was thinking, "why in the world, my App windows are shifting rather than multitasking?".
I Hope you can solve that!

Thanks!

**Comment by bulletmark** [comment]
Super + left/right are standard GNOME keyboard shortcuts to "tile" a window. What are you trying to do?

**Comment by tanaymehta28** [comment]
I was trying to multitask by using super + left/right; as if you press super + left (with a bit of delay after super, you can actually go into the other app window). I guess I have to try a different command combo for that.
Do have any possible solution?
Any ways thanks for helping out, I am fairly new to Linux and will close this issue after your reply!
Sorry for the inconvenience!

**Comment by bulletmark** [comment]
It is unclear what you mean by "multitask"? Do you mean to Alt+Tab, or Alt+`, or something else? Either way, this bug is not an issue with `libinput-gestures`.
