### ISSUE TITLE
"libinput-gestures-setup restart" executed by systemd as user (not as root) has no effect.

### ISSUE THREAD

**Issue by ZZZXXX0110** [bulletmark/libinput-gestures#194]
Libinput gestures stops working after suspend on my Surface Pro 6. When it stops after suspend it can be made to work again with the command "libinput-gestures-setup restart". However, attempts to automate this process with systemd does not seem to work.

What I have tried:
- Put "sudo -u zx libinput-gestures-setup" in a script in /lib/systemd/system-sleep.
- Create a new service that excutes a scrip containing "sudo -u zx libinput-gestures-setup" or "libinput-gestures-setup" as user (not as root), and setup a static configuration file to run the service after resuming from suspend.

Non of the above seem to be able to restart libinput-gestures after suspend, even though each script/service are verified to be executed.

libinput-gestures -l output (although I don't think this is related to the specific OS/hardware combination):
libinput-gestures: session KDE+x11 on Linux-4.18.20-surface-linux-surface-x86_64-with-Ubuntu-18.10-cosmic, python 3.6.7, libinput 1.12.1
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down       3 xdotool key ctrl+F12
swipe up         3 xdotool key ctrl+F9
swipe right      3 xdotool key alt+Tab
swipe left       3 xdotool key alt+shift+Tab
swipe right      4 xdotool key alt+ctrl+Right
swipe left       4 xdotool key alt+ctrl+Left
swipe up         4 xdotool key ctrl+F8
swipe down       4 xdotool key ctrl+F8
libinput-gestures: device /dev/input/event5: Microsoft Surface Type Cover Touchpad

**Comment by bulletmark** [comment]
There have been a few issues raised about this same issue previously. E.g. see #68, #163, #167, #177. It seems that the underlying `libinput debug-events` does not automatically resume after a suspend for some users/touchpads (works for me and many others though). Somebody posted a work-around [here](https://github.com/bulletmark/libinput-gestures/issues/163#issuecomment-428340925). Please let me know if that works for you.

**Comment by ZZZXXX0110** [comment]
Wow this actually worked!!! Thank you!

I use KDE instead of Gnome though, so I modified the line 
dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" |
to 
dbus-monitor --session "type='signal',interface='org.freedesktop.ScreenSaver'" |
for it to work properly.

**Comment by guttermonk** [comment]
I'm experiencing the same issue reported in this thread. Gestures work fine after booting, but stop working after I hibernate. 

Running `libinput-gestures` again gives me:
`libinput-gestures is already running for guttermonk, terminating ..
`
Here's the output of `libinput-gestures -l`:
```
libinput-gestures: session Hyprland+wayland on Linux-6.6.46-x86_64-with-glibc2.39, python 3.11.9, libinput 1.25.0
Hash: d41d8cd98f00b204e9800998ecf8427e
Gestures configured in /nix/store/dkfan6xflv34n3jyrq0afxmc1pd9b8bp-hm_libinputgestures.conf:
swipe up         3 hyprctl dispatch fullscreen 1
swipe down       3 hyprctl dispatch fullscreen 1
swipe up         4 hyprctl dispatch fullscreen 0
swipe down       4 hyprctl dispatch fullscreen 0
swipe left_up    2 hyprctl dispatch workspace 1
swipe left_down  2 hyprctl dispatch workspace 2
swipe right_up   2 hyprctl dispatch workspace 3
swipe right_down 2 hyprctl dispatch workspace 4
pinch clockwise    hyprctl dispatch splitratio 0.1
pinch anticlockwise   hyprctl -- dispatch splitratio -0.1
pinch in         4 hyprctl dispatch killactive
pinch out        4 hyprctl dispatch exec kitty
hold on         4 xdotool key control+t
libinput-gestures: device /dev/input/by-path/pci-0000:00:14.0-usbv2-0:5:1.2-event-mouse(event2): bcm5974
```
Looks like some have written scripts as a work around for Gnome and KDE. Not sure how I would do that for NixOS.
