### ISSUE TITLE
Page Up and Page down keys

### ISSUE THREAD

**Issue by svliantiss** [bulletmark/libinput-gestures#196]
I cannot map the Page Up and or Page Down keys,
Could someone provide a the correct command to map them and I want to request that a list of all working keys will be added to the readme or wiki.
I have tried:
Page Up
Page Down
Page up
Page down
page up
page down
Page_Up
Page_Down
Page_up
Page_down
page_up
page_down
PgUp
PgDown
Pgup
Pgdown
pgup
pgdown

**Comment by armc** [comment]
I would point you to two resources.  I don't know what distro you are using so you may find this link helpful.  Note, you need to use X11 to use xdotool and not Wayland as your window manager.

Try this command in terminal:
`xev`

Press keys to see what is returned for the key.  Note that the "Event Tester" window needs to have focus when doing key presses and you will see feedback in the terminal window.

On my system, Page Up is "Prior" and Page Down is "Next"

(Source:  [https://github.com/koldkaching/semicomplete/issues/78#issuecomment-457454857](url)

Also you may find the following information helpful... 
https://www.mankier.com/1/xdotool#Synopsis
https://askubuntu.com/a/93789

Hope this helps.  
Arick

**Comment by svliantiss** [comment]
Prior and Next are the right names for page up and page down.
I would still think it would be a good idea to make a list of every key.

**Comment by bulletmark** [comment]
@svliantissm and others, this is a bug tracker for `libinput-gestures`.  General Linux questions should be addressed to a discussion forum, reddit, slashdot, stackexchange, etc, not here. If a bug is raised here then please following the trouble-shooting guide and provide the mandatory information asked for.

**Comment by senzyo** [comment]
Well, On my system: 
- `Home` is `KP_Home`
- `End` is `KP_End`
- `Page Up` is `KP_Page_Up` and `KP_Prior`
- `Page Down` is `KP_Page_Down` and `KP_Next`
