### ISSUE TITLE
Events recognized, but not working

### ISSUE THREAD

**Issue by mareklowy** [bulletmark/libinput-gestures#198]
Hey,
I am running libinput-gestures on Fedora 29 with GNOME 3.x.x and I have encountered problems with recognizing events. I am currently using the default config file for gestures in which I have changed the gesture to switch workspace to swipe down 3. However, when I restart using `libinput-gestures-setup restart`, I get following error:
```
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event16 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
```
I think there are some gestures that work because I can scroll using two fingers, switch workspaces using swipe down/up with 4 fingers and right click with two finger tap. I tried running `libinput-gestures -d`, but I get the same error. When I ran it under root I got the following result:
```
libinput-gestures: session unknown+unknown on Linux-4.20.6-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine, python 3.7.2, libinput 1.12.6
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in /etc/libinput-gestures.conf:
swipe up         3 _internal ws_up
swipe down       3 _internal ws_down
swipe left       2 xdotool key alt+Right
swipe right      2 xdotool key alt+Left
pinch in         2 xdotool key super+s
pinch out        2 xdotool key super+s
libinput-gestures: device /dev/input/event5: SynPS/2 Synaptics TouchPad
```
When I leave the command running and try some gestures I am only able to see following gestures:
```
libinput-gestures: SWIPE up 3 [-5.480000000000002, -888.8000000000003]
   _internal ws_up
libinput-gestures: PINCH out 2 [4.73, 0.18000000000000002]
   xdotool key super+s
libinput-gestures: PINCH in 2 [-6.290000000000001, 23.450000000000003]
   xdotool key super+s
```
I am not sure whether it is a libinput-gestures problem, or if some other gesture software is interfering, since I have the swipe down with 4 fingers gesture running, which I am sure is not in the config file. I have tried adding myself into the input group, but it did not work.
Thank you guys for help.

**Comment by bulletmark** [comment]
I edited your comment about to fix various formatting problems and make it clearer to read.

1. Did you follow the installation instructions. The permission errors hint that you failed to follow the very first instruction, i.e. add yourself to the `input` group and log out/in or reboot.

2. Never run `libinput-gestures` as root. That output is meaningless. Run `linput-gestures -l` as your normal user and paste the diag output here. But fix 1 above first.

Please read the entire README first. Note the Wayland section which tells you that 4 finger workspace change is implemented natively by GNOME on Wayland (nothing to do with `libinput-gestures` so that is why you are seeing that. Also, 2 finger taps are not gestures.

**Comment by mareklowy** [comment]
I have added myself into input group at the beginning. I ran `libinput-gestures -l` with following output: 
`libinput-gestures: session gnome+wayland on Linux-4.20.6-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine, python 3.7.2, libinput 1.12.6
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 _internal ws_up
swipe down       3 _internal ws_down
swipe left       2 xdotool key alt+Right
swipe right      2 xdotool key alt+Left
pinch in         2 xdotool key super+s
pinch out        2 xdotool key super+s
libinput-gestures: device /dev/input/event5: SynPS/2 Synaptics TouchPad`
The output look okay, however the gestures are still not working.

**Comment by mareklowy** [comment]
Okay, I have read the README and I suspect that the problem is in wayland. I heaven't read that part before. I am running GNOME above 3.22 so that is probably the reason why xdotool doesn't work for me.

**Comment by bulletmark** [comment]
Again I edited your post above to fix the formatting. When you paste code or terminal output please put it in a code block.

So it seems you fixed your fundamental problem that you did not add yourself to the `input` group. You say "the gestures are still not working" but surely the 3 finger swipe up and down are now working? Also the swipe left and right will work in apps like chrome and firefox browsers etc? Perhaps you misread that section on Wayland. `xdotool` commands will still work in Wayland for non-Wayland native apps like those browsers and many other apps. Please be clear in what you say. The 2 pinch commands are for gnome-shell so they will not work with `xdtotool` for Wayland but 3 finger pinch is natively implemented in GNOME on Wayland for that function anyhow (as the README says) so you don't really need it. And it you really want 2 fingers for that function, then the `libinput-gestures.conf` file shows you an example for how to configure 2 finger pinch for the GNOME overview which works on both Xorg and Wayland so you can easily do it anyhow. So all those gestures you list can easily made to work with the exception that  swipe left/right will not work in native Wayland apps like Nautilus etc.

**Comment by abhinavps** [comment]
I am facing a similar issue on installation even after adding myself as the input group. On running the command `libinput-gestures-setup start`I get
`abhinav@hp:~/libinput-gestures$ libinput-gestures-setup start
libinput-gestures started.
abhinav@hp:~/libinput-gestures$ Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Failed to open /dev/input/event16 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Can not see any devices, did you add yourself to the input group and log out/in?
Could not determine touchpad device.`

**Comment by bulletmark** [comment]
@abhinavps I also edited your comment to fix up the formatting.

Please follow the installation, and then troubleshooting guide. Step 1 is to provide your `libinput-gestures -l` output. Did you log out/in (or easier to just reboot) after adding yourself to the `input` group?

**Comment by abhinavps** [comment]
The output of `libinput-gestures -l` is
`abhinav@hp:~$ libinput-gestures -l
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.7, libinput 1.10.4
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Failed to open /dev/input/event16 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Can not see any devices, did you add yourself to the input group and log out/in?
Could not determine touchpad device.`

**Comment by bulletmark** [comment]
I had to fix your formatting again. Please guys, learn how to paste code/command text in github!

What about my questions to you above?

**Comment by abhinavps** [comment]
Yes, i added myself to the input group and log out/in. I even tried rebooting the system, but it gives the same error.

**Comment by bulletmark** [comment]
@abhinavps, please paste the output here of `id` and `ls -l /dev/input`

**Comment by abhinavps** [comment]
```
abhinav@hp:~$ id
uid=1000(abhinav) gid=1000(abhinav) groups=1000(abhinav),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lpadmin),126(sambashare),999(bumblebee)
abhinav@hp:~$ ls -l /dev/input
total 0
drwxr-xr-x 2 root root      60 Feb 17 10:46 by-id
drwxr-xr-x 2 root root     120 Feb 17 10:46 by-path
crw-rw---- 1 root input 13, 64 Feb 17 10:46 event0
crw-rw---- 1 root input 13, 65 Feb 17 10:46 event1
crw-rw---- 1 root input 13, 74 Feb 17 10:46 event10
crw-rw---- 1 root input 13, 75 Feb 17 10:46 event11
crw-rw---- 1 root input 13, 76 Feb 17 10:46 event12
crw-rw---- 1 root input 13, 77 Feb 17 10:46 event13
crw-rw---- 1 root input 13, 78 Feb 17 10:46 event14
crw-rw---- 1 root input 13, 79 Feb 17 10:46 event15
crw-rw---- 1 root input 13, 80 Feb 17 10:46 event16
crw-rw---- 1 root input 13, 66 Feb 17 10:46 event2
crw-rw---- 1 root input 13, 67 Feb 17 10:46 event3
crw-rw---- 1 root input 13, 68 Feb 17 10:46 event4
crw-rw---- 1 root input 13, 69 Feb 17 10:46 event5
crw-rw---- 1 root input 13, 70 Feb 17 10:46 event6
crw-rw---- 1 root input 13, 71 Feb 17 10:46 event7
crw-rw---- 1 root input 13, 72 Feb 17 10:46 event8
crw-rw---- 1 root input 13, 73 Feb 17 10:46 event9
crw-rw---- 1 root input 13, 63 Feb 17 10:46 mice
crw-rw---- 1 root input 13, 32 Feb 17 10:46 mouse0```

**Comment by bulletmark** [comment]
@abhinavps do you not see you are not a member of the `input` group? That is your problem.

**Comment by bulletmark** [comment]
Follow the 1st line in the installation instructions, i.e. `sudo gpasswd -a $USER input`.

**Comment by abhinavps** [comment]
After the reboot it started working
```
abhinav@hp:~$ libinput-gestures -l
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.7, libinput 1.10.4
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/event6: SynPS/2 Synaptics TouchPad
```
Thanks for the help

**Comment by bulletmark** [comment]
It "started working" because you only just now did as the first step says.
