### ISSUE TITLE
Hey, I've created a native alternative to this software

### ISSUE THREAD

**Issue by Coffee2CodeNL** [bulletmark/libinput-gestures#199]
Hey there :grin: 

I've written an alternative to this software that implements libinput natively, instead of having to rely on unstable tools like `libinput debug-events`

I have also referenced your project in my repository!

I hope this has piqued your interest!

[Link to my repo](https://github.com/Coffee2CodeNL/gebaar-libinput)

**Comment by bulletmark** [comment]
As I said on issue #18 which I closed yesterday, we see after 3.5 years that relying on `libinput debug-events` has actually proven to be very stable. Also, `libinput-gestures` runs quite efficiently so I have never seen any reason to implement any or all of it in C.

**Comment by sijad** [comment]
I've tried gebaar, it feels faster and more accurate to me.
