### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by rickysarraf** [bulletmark/libinput-gestures#2]
I wanted to drop you a thank you note. There is no other channel to talk, so I'm using the issue tracker.

Thank you for creating this. I have a Lenovo Yoga 2 13, and this just works perfect. It will be some time before I can move to Wayland based solution, so until then, this is really going to come handy.

And, on my box, the 4 finger swipe works perfect.

**Comment by bulletmark** [comment]
Thanks. If you run the following command:
```
stdbuf -oL -- libinput-debug-events | grep GESTURE
```
do you see individual 3 and 4 finger gestures? I never see anything other than 3 finger gestures reported.

**Comment by rickysarraf** [comment]
On Thu, 2015-12-03 at 23:48 -0800, Mark Blakeney wrote:
> Thanks. If you run the following command:
> stdbuf -oL -- libinput-debug-events | grep GESTURE
> do you see individual 3 and 4 finger gestures? I never see anything
> other than 3 finger gestures reported.

For me, both 3 and 4 fingers emulate the same events. 

```
event15	GESTURE_SWIPE_UPDATE	+187.17s	3
-2.55/76.71 (-3.18/95.89 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+187.19s	3
-2.47/79.25 (-3.09/99.06 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+187.21s	3
-3.40/76.20 (-4.25/95.25 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+187.23s	3
-1.62/61.47 (-2.03/76.84 unaccelerated)
event15	GESTURE_SWIPE_END	+187.25s	3
event15	GESTURE_SWIPE_BEGIN	+188.18s	4
event15	GESTURE_SWIPE_UPDATE	+188.18s	4  0.00/-
1.19 ( 0.00/-2.30 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.20s	4 -0.04/-
2.75 (-0.19/-12.86 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.22s	4 -1.03/-
11.49 (-2.70/-30.24 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.24s	4 -2.26/-
20.22 (-5.21/-46.67 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.26s	4 -1.85/-
32.10 (-3.47/-60.33 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.28s	4 -1.92/-
44.54 (-3.09/-71.76 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.30s	4 -3.09/-
61.79 (-4.25/-84.77 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.33s	4 -0.69/-
77.98 (-0.87/-97.47 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.35s	4  5.40/-
83.82 ( 6.75/-104.78 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.37s	4 10.73/-
87.12 (13.41/-108.90 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.39s	4 13.43/-
84.58 (16.79/-105.73 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.41s	4 17.91/-
80.77 (22.39/-100.97 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+188.43s	4 21.46/-
77.47 (26.83/-96.84 unaccelerated)
event15	GESTURE_SWIPE_END	+188.45s	4
event15	GESTURE_SWIPE_BEGIN	+189.31s	4
event15	GESTURE_SWIPE_UPDATE	+189.31s	4
-4.62/14.53 (-7.53/23.65 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.33s	4
-3.10/17.73 (-7.04/40.32 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.35s	4
-3.35/37.56 (-5.50/61.60 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.37s	4
-6.31/54.99 (-9.07/79.06 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.39s	4
-10.05/66.15 (-13.22/87.00 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.41s	4
-9.93/71.69 (-12.45/89.85 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.43s	4
-7.26/72.39 (-9.07/90.49 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.46s	4
-5.48/73.41 (-6.85/91.76 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.48s	4
-4.25/74.17 (-5.31/92.71 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.50s	4
-3.71/68.07 (-4.63/85.09 unaccelerated)
event15	GESTURE_SWIPE_UPDATE	+189.52s	4
-3.93/56.99 (-5.02/72.71 unaccelerated)
event15	GESTURE_SWIPE_END	+189.53s	4
```


And for pinch:

```
event15	GESTURE_PINCH_BEGIN	+222.55s	2
event15	GESTURE_PINCH_UPDATE	+222.55s	2  4.94/
7.11 (12.35/17.78 unaccelerated)  0.89 @  2.07
event15	GESTURE_PINCH_UPDATE	+222.57s	2  3.82/
9.43 ( 9.26/22.86 unaccelerated)  0.79 @  1.56
event15	GESTURE_PINCH_UPDATE	+222.58s	2  4.46/
5.76 (10.81/13.97 unaccelerated)  0.71 @  1.46
event15	GESTURE_PINCH_UPDATE	+222.60s	2  1.85/
3.05 ( 4.63/ 7.62 unaccelerated)  0.65 @  0.84
event15	GESTURE_PINCH_UPDATE	+222.62s	2  6.79/
3.05 (16.98/ 7.62 unaccelerated)  0.60 @  1.32
event15	GESTURE_PINCH_UPDATE	+222.63s	2  4.17/
3.05 (10.42/ 7.62 unaccelerated)  0.57 @  0.14
event15	GESTURE_PINCH_UPDATE	+222.65s	2  0.15/-
1.52 ( 0.39/-3.81 unaccelerated)  0.56 @  0.79
event15	GESTURE_PINCH_UPDATE	+222.66s	2  0.14/
0.45 ( 0.39/ 1.27 unaccelerated)  0.56 @  0.13
event15	GESTURE_PINCH_UPDATE	+222.68s	2  0.14/
2.38 ( 0.39/ 6.35 unaccelerated)  0.55 @  0.82
event15	GESTURE_PINCH_UPDATE	+222.70s	2  3.24/
0.00 ( 8.11/ 0.00 unaccelerated)  0.54 @ -0.86
event15	GESTURE_PINCH_UPDATE	+222.72s	2  0.14/
0.00 ( 0.39/ 0.00 unaccelerated)  0.54 @ -0.04
event15	GESTURE_PINCH_UPDATE	+222.73s	2  0.07/
0.22 ( 0.39/ 1.27 unaccelerated)  0.54 @  0.13
event15	GESTURE_PINCH_END	+222.75s	2
```


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by bulletmark** [comment]
Hmm, so it seems some touchpads are reported with different finger counts with libinput. I actually have coded this utility to be able to configure different finger count gestures so I will push that branch to master soon.

**Comment by bulletmark** [comment]
There you go. I pushed 3b6e6edf455f3227bb4dfbf753d0a15318d8d972 to add finger count configuration which you can try. I haven't tried this explicitly myself of course but it should work.

**Comment by rickysarraf** [comment]
On Fri, 2015-12-04 at 00:32 -0800, Mark Blakeney wrote:
> There you go. I pushed 3b6e6ed to add finger count configuration
> which you can try. I haven't tried this explicitly myself of course
> but it should work.

This is just awesome. Thank you.

I remapped 4 finger swipe to changing workspaces and 3 finger swipe to
show desktop (super+s)

And pinch event to ctrl+plus and ctrl+minus.

Works pretty good. The pinch calculations may need some fine tuning but
overall, they work.


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."


# Configuration file for libinput-gestures
# Lines starting with '#' and blank lines are ignored.
# At present only gesture lines are configured in this file.
#
# Each gesture: line has 3 [or 4] arguments:
#
# action motion [finger_count] command
#
# where action and motion is either:
#     swipe up
#     swipe down
#     swipe left
#     swipe right
#     pinch in
#     pinch out
#
# command is the remainder of the line and is any valid shell command +
# arguments.
#
# finger_count is optional (and is typically 3 or 4). If specified then
# the command is executed when exactly that number of fingers is used in
# the gesture. If not specified then the command is executed when that
# gesture is executed with any number of fingers. Gesture lines
# specified with finger_count have priority over the same gesture
# specified without any finger_count.
#
# Typically command will be xdotool, or wmctrl. See "man xdotool" for
# the many things you can action with that tool.

# GNOME SHELL move to next workspace
gesture: swipe up	4 xdotool key super+Page_Down

# GNOME SHELL move to prev workspace
gesture: swipe down	4 xdotool key super+Page_Up

gesture: swipe up	3 xdotool key super
gesture: swipe down	3 xdotool key super


# GNOME/Browser go back
gesture: swipe right	xdotool key alt+Left

# GNOME/Browser go forward
gesture: swipe left	xdotool key alt+Right

# GNOME SHELL open overview
gesture: pinch in	xdotool key ctrl+minus
gesture: pinch out	xdotool key ctrl+plus

**Comment by superscript18** [comment]
I've got to add to this!  It's so nice to have a demo of how to recognize these gestures from a script.  I wasn't aware of how to use `libinput-debug-events` from userspace, thanks!
