### ISSUE TITLE
Gentoo Ebuild

### ISSUE THREAD

**Issue by fin-ger** [bulletmark/libinput-gestures#20]
I wrote a simple gentoo ebuild that installs from the current git master.

```
EAPI=5

inherit git-2

DESCRIPTION="Actions gestures on your touchpad using libinput"
HOMEPAGE="https://github.com/bulletmark/libinput-gestures"
SRC_URI=""
EGIT_REPO_URI="https://github.com/bulletmark/libinput-gestures.git"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~x86 ~amd64"
RDEPEND="
    >=dev-lang/python-3
    >=dev-libs/libinput-1
    x11-misc/xdotool
"
DEPEND="${RDEPEND}"
```

To use this copy the ebuild to `/usr/local/portage/x11-plugins/libinput-gestures/`, cd into the folder and do `ebuild libinput-gestures-9999.ebuild manifest` and install with `emerge libinput-gestures`. You need a [local overlay](https://wiki.gentoo.org/wiki/Overlay/Local_overlay) configured for this to work.

I don't know how to share this. Maybe put it into the repo and reference the installation guide in the readme?

[libinput-gestures-9999.ebuild](https://github.com/bulletmark/libinput-gestures/files/464540/libinput-gestures-9999.ebuild.txt)

**Comment by bulletmark** [comment]
I am unfamiliar with Gentoo but an ebuild file seems exactly analogous to a PKGBUILD file for Arch Linux. E.g. just like I maintain at https://aur.archlinux.org/packages/libinput-gestures/. That is a public git repository also so I don't want to maintain that PKGBUILD file in parallel here in the source repo and that's the first place where people, and Arch AUR installer programs, go to find and download 3rd party packages. I guess it is the same with [Gentoo packaging](https://packages.gentoo.org/) so I suggest you submit it there?

**Comment by AndreMiras** [comment]
@fin-ger, this is very nice, why don't you post a "ebuild request" on bugs.gentoo.org and post the link here?
I would definitely vote for your bug.
