### ISSUE TITLE
Official RPi 7inch display

### ISSUE THREAD

**Issue by Hhenni** [bulletmark/libinput-gestures#201]
Run libinput-gestures -l on the command line and paste the output here.

libinput-gestures: session unknown+unknown on Linux-4.19.25-v7+-armv7l-with-debian-9.4, python 
3.5.3, libinput 1.6.3

/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in ~/.config/libinput-gestures.conf:
Could not determine touchpad device.

libinput-gestures-devices

Device:           FT5406 memory based driver
Kernel:           /dev/input/event0
Group:            1
Seat:             seat0, default
Capabilities:     touch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

**Describe the issue**

Hi,

thanks for the great work but my official RPi 7 inch touchpad wont work. If i try to start the program with "libinput-gestures-setup start" it says "Dont know how to invoke libinput-gestures.desktop". I have tried all the truobleshooting but unfortunately it is not working.

Thank you in advance and best regards

Henrik

**Comment by bulletmark** [comment]
That's a touchscreen isn't it? Not a touchpad. See the first sentence of https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#touchscreen-gestures. `libinput` does not process gestures for a touchscreen and thus `libinput-gestures` is not relevant.
