### ISSUE TITLE
 disable scroll by 3 and 4 fingers on synaptics touchpad

### ISSUE THREAD

**Issue by js-d-coder** [bulletmark/libinput-gestures#205]
```
libinput-gestures: session KDE+x11 on Linux-5.0.5-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.3, libinput 1.13.0

/usr/bin/libinput-gestures: hash 4cc3250c5befc6926c04b3e499114677

Gestures configured in ~/.config/libinput-gestures.conf:

swipe up         4 xdotool key super+Page_Up
swipe down       4 xdotool key super+Page_Down
swipe right      4 xdotool key ctrl+alt+Left
swipe left       4 xdotool key ctrl+alt+Right
swipe right_up   4 xdotool key XF86AudioPlay
swipe left       3 xdotool key alt+Right
swipe right      3 xdotool key alt+Left
swipe right_up   3 xdotool key ctrl+Tab
swipe left_down  3 xdotool key ctrl+shift+Tab
pinch anticlockwise 2 xdotool key XF86AudioLowerVolume
pinch clockwise  2 xdotool key XF86AudioRaiseVolume
libinput-gestures: device /dev/input/event8: SynPS/2 Synaptics TouchPad

```

I am fine with scrolling with 2 fingers. I have already disbaled edge scrolling by 1 finger.
I want to disable click and scrolling by 3 and 4 fingers on my synaptics touchpad.

Currently, what happens is I swipe down to minimize a window (according to my config) the application gets scrolled down little before minimizing. This is not what I want. Thus I want to disable scrolling by 3 and 4 while keeping other gestures.

Thanks

**Comment by bulletmark** [comment]
Follow the trouble shooting guide and do step 5 to just see the raw libinput events with `libinput-gestures` functionality disabled. You should see either POINTER movements **or** GESTURE events, not both combined which is what I think you are saying is happening. Please run that and then perhaps reconsider your description above.

Note that `libinput-gestures` only looks at and invokes actions on GESTURE events. POINTER events are ignored by `libinput-gestures`, i.e. all normal mouse movement, scroll, clicks, etc are handled by your desktop and/or your application.

**Comment by js-d-coder** [comment]
@bulletmark Hi, thanks for replying. I followed step 5 under troubleshooting and see that all of my gestures are detected:

```shell
$ libinput-gestures-setup stop
 libinput-gestures -d
libinput-debug-events stopped.
libinput-gestures stopped.
libinput-gestures: session KDE+x11 on Linux-5.0.5-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.3, libinput 1.13.0
/usr/bin/libinput-gestures: hash 4cc3250c5befc6926c04b3e499114677
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         4 xdotool key super+Page_Up
swipe down       4 xdotool key super+Page_Down
swipe right      4 xdotool key ctrl+alt+Left
swipe left       4 xdotool key ctrl+alt+Right
swipe right_up   4 xdotool key XF86AudioPlay
swipe left       3 xdotool key alt+Right
swipe right      3 xdotool key alt+Left
swipe right_up   3 xdotool key ctrl+Tab
swipe left_down  3 xdotool key ctrl+shift+Tab
pinch anticlockwise 2 xdotool key XF86AudioLowerVolume
pinch clockwise  2 xdotool key XF86AudioRaiseVolume
libinput-gestures: device /dev/input/event8: SynPS/2 Synaptics TouchPad
libinput-gestures: SWIPE right 3 [1075.52, 24.879999999999995]
   xdotool key alt+Left
libinput-gestures: SWIPE left 3 [-1061.2, 144.01]
   xdotool key alt+Right
libinput-gestures: SWIPE down 4 [184.32999999999998, 596.77]
   xdotool key super+Page_Down
libinput-gestures: SWIPE up 4 [60.849999999999994, -476.58]
   xdotool key super+Page_Up
libinput-gestures: SWIPE right_up 4 [926.99, -398.88]
   xdotool key XF86AudioPlay
libinput-gestures: PINCH in 2 [-0.2400000000000001, 6.34]
libinput-gestures: PINCH in 2 [-0.49, 11.389999999999999]
libinput-gestures: PINCH out 2 [4.84, 11.1]
libinput-gestures: PINCH in 2 [-3.79, -13.71]
libinput-gestures: PINCH clockwise 2 [3.2, 56.35]
   xdotool key XF86AudioRaiseVolume
libinput-gestures: PINCH clockwise 2 [1.91, 66.56]
   xdotool key XF86AudioRaiseVolume
libinput-gestures: PINCH anticlockwise 2 [-0.1100000000000001, -53.45]
   xdotool key XF86AudioLowerVolume
libinput-gestures: PINCH anticlockwise 2 [-1.0699999999999998, -58.41999999999999]
   xdotool key XF86AudioLowerVolume
^CTraceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 554, in <module>
    for line in cmd.stdout:
KeyboardInterrupt
```

This is the output I get when I did one gesture of 'swipe down' by 4 fingers:

```
$ libinput-gestures-setup stop
 libinput-gestures -r
libinput-gestures: session KDE+x11 on Linux-5.0.5-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.3, libinput 1.13.0
/usr/bin/libinput-gestures: hash 4cc3250c5befc6926c04b3e499114677
libinput-gestures: device /dev/input/event8: SynPS/2 Synaptics TouchPad
-event8   DEVICE_ADDED     SynPS/2 Synaptics TouchPad        seat0 default group1  cap:pg  size 99x49mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on
event8   GESTURE_SWIPE_BEGIN  +1.01s    4
event8   GESTURE_SWIPE_UPDATE  +1.01s   4 -3.40/43.36 (-14.32/182.35 unaccelerated)
event8   GESTURE_SWIPE_UPDATE  +1.03s   4 -0.51/52.77 (-1.79/183.38 unaccelerated)
event8   GESTURE_SWIPE_UPDATE  +1.06s   4 -0.56/48.57 (-1.79/154.37 unaccelerated)
event8   GESTURE_SWIPE_END  +1.10s  4
c^CTraceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 554, in <module>
    for line in cmd.stdout:
KeyboardInterrupt
```

Strangely, I don't see `POINTER_` in output when I scroll down using 4 fingers even though the terminal got scrolled.  
With above command ( `-r` option) on separate test, I get both `GESTURE_` and `POINTER_`.

**Comment by bulletmark** [comment]
I don't use KDE. What does super+Page_Down do? Is that a default/standard keyboard shortcut?

If you completely disable `libinput-gestures`, and then do a 4 finger swipe down, then does the terminal scroll?

**Comment by js-d-coder** [comment]
In KDE, Super+Page_Down minimizes focused window. After, disabling `libinput-gestures`, terminal does scroll....

**Comment by bulletmark** [comment]
So your problem is that 4 finger swipes are scrolling your terminal so you need to find out how to fix or disable that bug/issue in your system/environment/config etc. Obviously, you can not use `libinput-gestures` with gestures that are already being intercepted.

Closing because, as you agree, this is nothing to do with `libinout-gestures`.

**Comment by js-d-coder** [comment]
@bulletmark that is what I think now (don't know if it is correct). Thanks for co-operating.

**Comment by js-d-coder** [comment]
@bulletmark It turned out that I was using outdated driver `xf86-input-synaptics`, switching to `xf86-input-libinput` helped. thanks for your help for debugging the source of problem.
