### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by noscript** [bulletmark/libinput-gestures#208]
I think there should be a timeout feature. That if you haven't finished the gesture within a certain time, it will be ignored.

The reasoning is that sometimes I realize that I started a wrong gesture. With every other gesture recognition system I would simply not complete it in time (not lifting the fingers for example), and it would time out. libinput-gestures however will run the action no matter what, as long as the gesture was recognized.

**Comment by bulletmark** [comment]
My immediate reaction is to agree with you but at the end of the day this utility merely respects whatever libinput passes to it as  a "gesture" so I wonder why libinput itself does not apply a timeout?

Note that libinput does cancel some gestures based on interpreting the users touch movements. E.g. run `libinput-gestures -r` and then do a swipe but finish it by spreading your fingers in an outwise pinch motion. You will see that libinput tacks a "cancel" on the SWIPE_END and libinput-gestures does respect this and cancels any pending command so the user sees no action. I think there are other ways to cancel gestures.

Adding a timeout is easy so I will think about it. Just want to see if I can find out why libinput does not already do this.

**Comment by bulletmark** [comment]
What value timeout would you think appropriate as a default?

**Comment by noscript** [comment]
I tried to finish the gesture with pinch out and received `event2   GESTURE_SWIPE_END +42.65s      4 cancelled` but it's not very reliable, out of multiple attempts I could cancel the gesture only a few times.

I think something like 1 second for the default would be good enough.

**Comment by bulletmark** [comment]
I agree the cancel is awkward but it is implemented in `libinput`, not `libinput-gestures` so nothing I can do about that.

I think 1 sec is too fast. I have set it to 4 secs so nobody gets a surprise but you can change it with the  `timeout` config command. See commit 753b1556fe68976c0fc8e7914c3f1df9dde2143c.

**Comment by bulletmark** [comment]
After using this a bit, I have changed the timeout to 1.5 secs with commit 57df3d295c1a7c15dc4a9baa94e97d67a8f2bcda. @noscript , me know what you think.

**Comment by noscript** [comment]
Works great, thank you for implementing this.

One request still, in verbose mode print out immediately when timeout is triggered. Currently it prints that only after finishing the gesture.

**Comment by bulletmark** [comment]
The utility is written to be efficient as possible. libinput communicates a start flag, then a heap of gesture updates, then an end flag. So the change just records the time at the start, and then does a one of comparison of the time at the end. Your  proposal would require the timeout calc at each of the many updates which is inefficient given we don't actually need it for the functionality. The gesture is not logged in diag/verbose mode until that point anyhow.

Does the 1.5 sec timeout seem sensible?

**Comment by noscript** [comment]
I see. In that case the issue can be closed. The main functionality is there and works perfectly.

I configured the timeout for myself to 0.5 sec, but for most people 1.5 sec will do too.

**Comment by bulletmark** [comment]
Timeout  changed added in version 2.43.
