### ISSUE TITLE
libinput-gestures qt-based GUI

### ISSUE THREAD

**Issue by OneAdder** [bulletmark/libinput-gestures#209]
It's not really an issue. Today I started writing some basic GUI for libinput-gestures:
https://github.com/OneAdder/libinput-gestures-qt
I plan to add keyboard input for xdotool and controls for libinput-gestures-setup.
I just wanted to ask your opinion of whether it's worth it and whether somebody (else) needs such thing.

**Comment by bulletmark** [comment]
Did you look at what is already around? E.g. see https://github.com/GabMus/gestureManager and https://gitlab.com/cunidev/gestures.

Sorry, I am not interested or plan on adding anything like this.

**Comment by OneAdder** [comment]
Thank you for your response. They are both GTK, and mine will be QT, so there is point in writing another one. I think I'll just finish it to some point and pack it for Debian and OpenSUSE
