### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ankkax** [bulletmark/libinput-gestures#21]
I get this when I try to run libinput-gestures -d
Using ubuntu 16.04 Gnome and using ETPS/2 Elantech touchpad

~~~
libinput-list-devices: /usr/lib/x86_64-linux-gnu/libinput.so.10: version `LIBINPUT_1.5' not found (required by libinput-list-devices)
libinput-list-devices: /usr/lib/x86_64-linux-gnu/libinput.so.10: version `LIBINPUT_1.4' not found (required by libinput-list-devices)
libinput-list-devices: /usr/lib/x86_64-linux-gnu/libinput.so.10: version `LIBINPUT_1.3' not found (required by libinput-list-devices)
Traceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 185, in <module>
    device = get_device()
  File "/usr/bin/libinput-gestures", line 44, in get_device
    universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'libinput-list-devices' returned non-zero exit status 1
~~~

**Comment by bulletmark** [comment]
I edited your comment above to add code tags around the output.

The problem seems something to do with your system, not `libinput-gestures`. Please run `libinput-list-devices` directly on the command line. That is a utility provided by the libinput package. If you get errors then you need to fix your installation of libinput.

**Comment by ankkax** [comment]
alright, thanks for the answer. Sry but i have no idea how to fix my libinput :) . Tried with this guide http://askubuntu.com/questions/649103/proper-touchpad-thumb-palm-detection-with-libinput , but all my inputs stopped working.

**Comment by bulletmark** [comment]
See issue #12.

**Comment by ankkax** [comment]
I finally got it working, but only pinch is working. For some reason it doesn't recognize 3 fingers.

**Comment by bulletmark** [comment]
When you say you "got it working", what did you change and what works? Is that `missing capability CAP_GESTURE` error message still reported?

Also, run `libinput-debug-events` at the command line and see what GESTURE events are reported.

**Comment by ankkax** [comment]
I managed to upgrade libinput to 1.4.1 and `missing capability CAP_GESTURE` error is not appearing anymore. `libinput-debug-events` does not react to tapping on touchpad, it records movement and pinch only.

**Comment by bulletmark** [comment]
I will close this issue as all this is related to either how your system is installed/updated, your specific touchpad, and/or libinput.
