### ISSUE TITLE
libinput-gestures shuts down

### ISSUE THREAD

**Issue by andrewc910** [bulletmark/libinput-gestures#210]
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README.

**DONE**

```
[andrew@andrew-pc ~]$ libinput-gestures -l
libinput-gestures: session KDE+x11 on Linux-4.19.34-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.3, libinput 1.13.1
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       4 ctrl+alt+Right
swipe up         3 xdotool key Alt+Tab
swipe right      4 Ctrl+Alt+Left
libinput-gestures: device /dev/input/event11: SynPS/2 Synaptics TouchPad


```

**Describe the issue**
Im on manjaro(arch based) 18 KDE plasma. Pretty fresh install(less than a week)

Okay, i am having 2 problems. 1 has to be with gestures while the other i believe is my lack of knowledge. Lets start with libinput.

Problem 1:
3 finger swipe up with alt+tab for about 5 minutes after i use libinput-gestures-setup restart (or stop and start). After X time, it just doesn't work. Status command will show gestures is running though. 

Problem 2:
So i'm using KDE plasma. I have my virtual desktops horizontally set up(like mac or windows). My key commands are ctrl+alt+arrow(left, right) to move between them. I'm trying to make it so i can 4 finger swipe either left or right to move over. These do not work at all. However, in debug mod, the swipes do register. Code block below shows this.

```
[andrew@andrew-pc ~]$ libinput-gestures -d
libinput-gestures: session KDE+x11 on Linux-4.19.34-1-MANJARO-x86_64-with-arch-Manjaro-Linux, python 3.7.3, libinput 1.13.1
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       4 ctrl+alt+Right
swipe up         3 xdotool key Alt+Tab
swipe right      4 Ctrl+Alt+Left
libinput-gestures: device /dev/input/event11: SynPS/2 Synaptics TouchPad
libinput-gestures: SWIPE up 3 [-94.03999999999999, -707.1700000000001]
   xdotool key Meta+Tab
libinput-gestures: SWIPE right 4 [774.2700000000001, -52.01]
   Ctrl+Alt+Left
libinput-gestures: SWIPE left 4 [-417.76000000000005, -2.97]
   ctrl+alt+Right
^CTraceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 550, in <module>
    for line in cmd.stdout:
  File "/usr/lib/python3.7/codecs.py", line 319, in decode
    def decode(self, input, final=False):
KeyboardInterrupt

```

PS: I don't really know what i'm doing. I'm just half-way decent at reading documentation and github issues. With that said, I can give log files or whatever would be needed, just let me know the commands!

**Comment by bulletmark** [comment]
Note this is a bug tracker, not really a support forum. Make sure you follow each step of the TROUBLESHOOTING section (as you pasted in the first line above so you should not have missed it).

You have configured the commands `ctrl+alt+Right` and `Ctrl+Alt+Left`. Apart from the inconsistent case, I presume you are missing the `xdotool key` to preface both of these?!

Also, I note something very odd from the output you have pasted for the `libinput-gestures -d`. It says you have configured `swipe up  3 xdotool key Alt+Tab` but the actual runtime output for `SWIPE up 3` says `xdotool key Meta+Tab` which is different?! Could it be that you have manually spliced two different outputs (with different configurations) to form that single paste?!

**Comment by bulletmark** [comment]
Also, regarding your problem "after 5 mins it stops working", please run the same `xdotool` command manually in a terminal when in that "failed" state to confirm `xdotool` is still working normally. Also, look at the output of `journalctl -b` from the time it stops working to see if any error messages are generated.

**Comment by andrewc910** [comment]
Hey, sorry to bother you with my initial questions. I ended up changing distros, not messing with the conf file and everything works. Thanks so much for the hardwork on this package! Good day! :)
