### ISSUE TITLE
Determines touchpad but gestures not works

### ISSUE THREAD

**Issue by GrishinSergey** [bulletmark/libinput-gestures#211]
Hello, everyone. I tried to install this tool for setuping gestures for my ubuntu-notebook.
My Ubuntu is 16.04.6 LTS, 64x. Also, debug output "libinput-gestures" below:

```
~$ libinput-gestures -l
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-47-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.6.3

/usr/bin/libinput-gestures: hash 4cc3250c5befc6926c04b3e499114677
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 nautilus
pinch clockwise  2 nautilus
libinput-gestures: device /dev/input/event5: SynPS/2 Synaptics TouchPad
```

So, my problem is: libinput-gestures not recognised gestures. I tryied to open my nautilus with gesture "swipe up 3 nautilus" but nothing happened.

**Comment by bulletmark** [comment]
Did you read the second last paragraph of the CONFIGURATION section? It explains why this is not working for you. To make this clearer, I just added commit 1f3b29a4faea2c24014f4d271103e171c7fb7d3e to mention the PATH issue explicitly.

**Comment by GrishinSergey** [comment]
@bulletmark , thank you for response. I read this paragraph. But I don't understand about what PATH there written? PATH - variable of environment? Also read about "commands" there. What means with this?

**Comment by bulletmark** [comment]
Change your configuration `nautilus` to `/usr/bin/nautilus`. Your shell (e.g. `bash`) normally looks up your PATH value to find where a program lives but `libinput-gestures` does not invoke a shell for the command so you need to specify the full path.

**Comment by GrishinSergey** [comment]
```
sergey@sergey-HP-ProBook-450-G3:~$ libinput-gestures -d
libinput-gestures: session ubuntu+x11 on Linux-4.15.0-47-generic-x86_64-with-Ubuntu-16.04-xenial, python 3.5.2, libinput 1.6.3

/usr/bin/libinput-gestures: hash 4cc3250c5befc6926c04b3e499114677
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 /usr/bin/nautilus
libinput-gestures: device /dev/input/event5: SynPS/2 Synaptics TouchPad
```
Maybe, I stil doing something wrong... I changed command to `/usr/bin/nautilus`, but this gesture still not opens file manager

**Comment by bulletmark** [comment]
What you say is not correct. You will actually see that nautilus appears fine the first time, but if you close it then there is a period of time before it opens again. That is because nautilus hangs around, it seems for about 10 secs. So you need to add a script, e.g. add `~/bin/libinput-gestures-nautilus.sh`:
```
#!/bin/bash
exec /usr/bin/nautilus &
```
Be sure to `chmod +x ~/bin/libinput-gestures-nautilus.sh`. Then change your libinput-gestures configuration command to that script.

This is a bit hacky but it's a bit odd to use a gesture to start nautilus. Each to their own I guess. Note this is all just Linux issues, not to do with libinput-gestures.

**Comment by GrishinSergey** [comment]
No, it not appears first time. If you saying about `swipe up 3 /usr/bin/nautilus`, that is log with gesture and what should be runned. Nautilus not runned anytime

**Comment by bulletmark** [comment]
Are you saying you are running `libinput-gestures -d` and expecting the command to be executed?! You surely found that debug mode described in step 4 of the TROUBLESHOOTING section? Please read the second sentence there!
