### ISSUE TITLE
Gestures still registered when touchpad disabled by WM

### ISSUE THREAD

**Issue by daanjderuiter** [bulletmark/libinput-gestures#213]
I run libinput-gestures under SwayWM, which can automatically disable/enable the touchpad when a USB mouse is plugged in/out. However, I notice that the gestures are still enabled when the touchpad is disabled. I have also observed this behaviour under X11 WM's. Would it be possible for libinput-gestures to be started/stopped automatically when the WM has enabled/disabled the touchpad?

For completeness' sake, here's the output of `libinput-gestures -l`:

```
libinput-gestures: session /usr/share/wayland-sessions/sway+wayland on Linux-5.0.12-arch2-1-ARCH-x86_64-with-arch, python 3.7.3, libinput 1.13.2
/usr/bin/libinput-gestures: hash 34ab6c1e45b5673bf2b143a6321c81c4
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down         swaymsg workspace prev_on_output
swipe up           swaymsg workspace next_on_output
swipe right        /usr/local/bin/button forward
swipe left         /usr/local/bin/button backward
pinch in           swaymsg fullscreen disable
pinch out          swaymsg fullscreen enable
libinput-gestures: device /dev/input/event21: ETPS/2 Elantech Touchpad
```

**Comment by bulletmark** [comment]
Well `libinput-gestures` merely listens to `libinput` events so clearly SwayWM does not actually disable those, it likely just stops listening to `libinput` events itself. Not sure what `libinput-gestures` can do about that. You perhaps need to add a `udev` rule to `libinput-gestures-setup stop[|start]` (as your user) when the device is removed/inserted?

**Comment by daanjderuiter** [comment]
That'd probably get real ugly real quick since I often plug/unplug the mouse while the machine is suspended, so hotplug-events would need to be backed up by some resume-time check. I'd really prefer to instead delegate that sort of thing to the driver/WM. Looking at the Sway docs, the functionality that disables an input device disables send_events. Not sure how to best handle this, but it seems that the problem does not lie in libinput-gestures, so I'll close this issue.
