### ISSUE TITLE
make error 127

### ISSUE THREAD

**Issue by jfellien** [bulletmark/libinput-gestures#219]
When I try to install on a blank Ubuntu 19 by entering sudo make install I get error 127. What can I do?

**Comment by jfellien** [comment]
I fixed it by my self. Had to use dos2unix to remove the windows linebreakes. :smiley:

**Comment by bulletmark** [comment]
There are no "windows linebreaks" in any files. What do you mean?

**Comment by jfellien** [comment]
I found out what's happen (I have a guess). My .gitconfig contained an old windows setting `autocrlf = true` so any repository I cloned will get CRLF instead of LF, so yours. My fault :smile:
