### ISSUE TITLE
Libinput-gestures doesn’t work after resume of suspend and hibernate

### ISSUE THREAD

**Issue by geremi1** [bulletmark/libinput-gestures#223]
The title is self-explainatory. The command is still running in the background, but any of my configured gestures (even the one JUST FOR testing (like touching a file)) didn’t work.

How can I solve this issue ?

**Comment by bulletmark** [comment]
Please follow the instructions in the trouble shooting guide and provide the basic information requested there.

**Comment by geremi1** [comment]
here's the output of libinput-gesture -l : 

libinput-gestures: session unknown+tty on Linux-5.2.9-arch1-1-ARCH-x86_64-with-arch, python 3.7.4, libinput 1.14.0
/usr/bin/libinput-gestures: hash f95095d1e2bdad0b6c844ae190ede89e
Gestures configured in ~/.config/libinput-gestures.conf:
swipe right      4 xdotool key Super_L+Left
swipe left       4 xdotool key Super_L+Right
swipe up         3 xdotool key Alt_L+x
pinch in         4 xdotool key Alt_L+z
libinput-gestures: device /dev/input/event8: CUST0001:00 06CB:CDAA Touchpad

**Comment by bulletmark** [comment]
See https://github.com/bulletmark/libinput-gestures/issues/194#issuecomment-457547823.
