### ISSUE TITLE
problem using libinput-gestures

### ISSUE THREAD

**Issue by jatin510** [bulletmark/libinput-gestures#226]
```
Run libinput-gestures -l on the command line and paste the output here.

libinput-gestures: session ubuntu+x11 on Linux-5.0.0-27-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.8, libinput 1.10.4
/usr/bin/libinput-gestures: hash f95095d1e2bdad0b6c844ae190ede89e
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key super+Down
swipe left       3 xdotool key super+Right
swipe right      3 xdotool key super+Left
Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event16 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Can not see any devices, did you add yourself to the input group and log out/in?
Could not determine touchpad device.

```

**Describe the issue**
While trying to use the libinput-gestures I am facing this problem.
The output on my terminal is : 

Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event16 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Can not see any devices, did you add yourself to the input group and log out/in?
Could not determine touchpad device.

**Comment by bulletmark** [comment]
Any reason you thought it necessary to print out those errors twice?!

The reason for your problem is stated at the end of the error messages. What is not clear about that?

**Comment by bulletmark** [comment]
No response from OP so closing. Seems likely he had not done what the error message was telling him.
