### ISSUE TITLE
Disable touchpad while typing - timeout

### ISSUE THREAD

**Issue by RidgeA** [bulletmark/libinput-gestures#229]
Is it possible to configure a delay to enable the touchpad back after finishing typing?
E. g. with [`syndaemon`](https://linux.die.net/man/1/syndaemon):
```
syndaemon -i 2
```

**Comment by bulletmark** [comment]
Sorry but you are in the wrong place. This is just a simple utility which captures libinput gesture events and maps them to user actions. You should read https://wiki.archlinux.org/index.php/Libinput#Configuration, https://wayland.freedesktop.org/libinput/doc/latest/configuration.html, and https://wayland.freedesktop.org/libinput/doc/latest/palm-detection.html#disable-while-typing. However, I don't think libinput allows you to change those timeouts.
