### ISSUE TITLE
Keyboard layout is restarted after hit a back/forward gesture

### ISSUE THREAD

**Issue by glats** [bulletmark/libinput-gestures#231]
```
jcuzmar@artix-probook ~> libinput-gestures -l
libinput-gestures: session i3+x11 on Linux-5.3.6-artix1-1-ARTIX-x86_64-with-glibc2.2.5, python 3.7.4, libinput 1.14.3
/usr/bin/libinput-gestures: hash 5c8bd05b1deb7a0975b359983e3f1490
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event8): SYNA3081:00 06CB:826F Touchpad
```

**Describe the issue**
Hi! first of all thank you for your work. 
I've configure my keyboard with X11 in this way:
```
Section "InputClass"
       Identifier "system-keyboard"
       Option "XkbLayout"  "es,latam"
       Option "XkbModel"   "pc105"
EndSection
```
As you can see I configured to have different keyboard layout and to change it whenever i want.
The problem comes up when i use the gesture to get back or forward a webpage in the browser the keyboard layout is changed.
For example I'm using the "latam" layout then I do back gesture and the layout is restarted. 
I hope to be clear.
Thank you.

**Comment by bulletmark** [comment]
I don't see how you could think this is a bug in libinput-gestures. Did you follow the trouble shooting guide, in particular step 7?

I've never used `XkbLayout` before (haven't even used Xorg for ages) but looking at the [documentation](https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration) it says the toggle keys are defined in `/usr/share/X11/xkb/rules/base.lst` and looking at that I see the default toggle seems to be Right + Alt which is the same you have defined for swipe left. Use `XkbOptions` to change your toggle.

**Comment by glats** [comment]
I'm sorry my bad. I didnt try xdotool standalone.
I checked and the command change the layout. Thanks anyway.

**Comment by bulletmark** [comment]
Did you try the easy fix I gave you?

**Comment by glats** [comment]
yeah but didnt work. I put this:
```
Section "InputClass"
        Identifier "system-keyboard"
        Option "XkbLayout"  "es,latam"
        Option "XkbModel"   "pc105"
        Option "XkbOptions" "grp:win_space_toggle"
EndSection
```
and ran ```xdotool key alt+Right``` and the restarting persists

**Comment by glats** [comment]
I did a little more research and i found this https://github.com/jordansissel/xdotool/issues/211#issuecomment-389151228
I tried the workaround posted above and it worked.
