### ISSUE TITLE
does support linux mint 19.2 Cinnamon

### ISSUE THREAD

**Issue by deanjo** [bulletmark/libinput-gestures#234]
Hello
  I tried to install libinput-gestures in linux mint 19.2 Cinnamon but it seems to be working.

**Comment by bulletmark** [comment]
Please read the [TROUBLESHOOTING](https://github.com/bulletmark/libinput-gestures#troubleshooting) section then come back here and start again.

**Comment by bulletmark** [comment]
No response from OP so closing.
