### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by 3nriqu390** [bulletmark/libinput-gestures#235]
Im trying to uninstall this library and cant find a way.

**Comment by bulletmark** [comment]
You missed the section about it in the README?

**Comment by 3nriqu390** [comment]
jajaja yeah found it abot 30 seconds after reporting it, im in cuba so
my internet its pretty slow and the readme dint charge up untill then

2019-11-10 18:03 GMT-05:00, Mark Blakeney <notifications@github.com>:

**Comment by bulletmark** [comment]
So did you successfully uninstall? Can you/I close this bug?

**Comment by bulletmark** [comment]
No response from OP so closing.
