### ISSUE TITLE
Events in between swipes ( enhancement )

### ISSUE THREAD

**Issue by tanishqmanuja** [bulletmark/libinput-gestures#237]
I wanted to implement windows 10 like windows switching feature via libinput-gestures,
Details of what i want to happen:
When i swipe & hold with 3 fingers alt+ctrl+tab should be pressed and further movement of fingers should switch windows.
config file should look like this -
```
gesture swipe_begin	 	3 xdotool keydown alt key ctrl+tab
gesture swipe_held right	3 xdotool key right
gesture swipe_held left 	3 xdotool key left  
gesture swipe_end		3 xdotool keyup

```
I experimented and saw indeed we can see update events of gestures by using
```
libinput-gestures -r
```
Any idea how to implement this ?

**Comment by bulletmark** [comment]
Sorry, this utility doesn't do anything close to what you are looking for.

**Comment by tanishqmanuja** [comment]
Successfully Implemented what I wanted :)

[libinput-gestures.zip](https://github.com/bulletmark/libinput-gestures/files/3932643/libinput-gestures.zip)

PS: made suitable changes in the config file, removed all 3 finger gestures.

**Comment by MrXlebNick** [comment]
@tanishqmanuja could you pull request your changes?
