### ISSUE TITLE
option to trigger Tap-to-click gesture

### ISSUE THREAD

**Issue by hrvoj3e** [bulletmark/libinput-gestures#240]
Is there an option to trigger **Tap-to-click**?

https://wayland.freedesktop.org/libinput/doc/latest/tapping.html#tap-to-click-default-setting

```
➜ libinput-gestures -l
libinput-gestures: session KDE+wayland on Linux-5.4.6-2-MANJARO-x86_64-with-glibc2.2.5, python 3.8.1, libinput 1.14.3
/usr/bin/libinput-gestures: hash 5c8bd05b1deb7a0975b359983e3f1490
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       3 ydotool key alt+Right
swipe right      3 ydotool key alt+Left
pinch in           ydotool key ctrl+F9
pinch out          ydotool key ctrl+F9
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event8): MSFT0001:01 06CB:CDB0 Touchpad
```

**Comment by bulletmark** [comment]
This is the wrong place to ask that question. I don't use KDE but I am sure like GNOME it has a "tap to click" option in the touchpad settings.

**Comment by hrvoj3e** [comment]
I realize that now. Sorry.

Found it. In KDE there is a setting (checkbox).
> System Settings > Input Device > Touchpad > Tapping > Tap-to-click
