### ISSUE TITLE
backend for libinput-gestures

### ISSUE THREAD

**Issue by natask** [bulletmark/libinput-gestures#241]
I used to use `libinput-gestures` but `libinput debug-events` was too limited for me, particularly concerning tap gestures and 5-finger gestures. 
so I wrote a driver in python primarily for gestures built upon `evtest (evemu is also possible)`. 
I also made some modifications so that the gestures weren't one-shot (much like `fusuma`).

It has well for me for the last few months.

I felt like sharing the script to others.Therefore, I was looking to make it more customizable by supporting  config files from `libinput-gestures` and `fusuma`.  
I realized then that it would be much better if I packaged the core of `[gestures](https://github.com/natask/gestures)` to avoid re-inventing the wheel and avoid fracturing this key feature.

Is this something that people are interested in? [stuff after this line](https://github.com/natask/gestures/blob/caff4e83c944b0be4b7fbbf08d1f67b2ce241481/gestures#L941) is the main meat of the backend.
In the mean time, I will incorporate 5-finger gestures and tap gestures to `libinput` as PRs.

**Comment by bulletmark** [comment]
I'll may try that out if you improve the readme and say exactly what it does and how it is different to libinput-gestures.  Sorry but I also don't see the point of raising an issue here though so closing.

**Comment by natask** [comment]
I raised an issue here to see if there was interest. 

## Key features
### 5 finger gestures 
 This means that you can place 5 fingers on the touchpad and that is recognized as another class of gestures. BTN_TOOL_QUINTTAP must supported. check by running.
### tap gestures. 
This means that tapping the touchpad with 4 or 5 fingers is recognized as a gesture. 
### Touchscreen gestures 
Extend gestures to touchscreen.
### Fluid gestures.
  Allow the user to do different things without raising their fingers from the touchpad. This takes advantage of the fact that gesture execution is separated into 3 parts, start, update, and end, by doing complementary actions in each. 

  For example, assume the shortcut to switch windows is "CTRL + ALT" + direction, where direction is "LEFT", "RIGHT", "UP", "DOWN". 

 to switch windows fluidly, "CTRL + ALT" are held down programmatically on a start gesture event, then depending on which direction the user is swiping while fingers are still on the touchpad, dynamically generate direction commands. Then when the user raises their fingers, which is an end gesture event, the "CTRL + ALT" are released programmatically.
