### ISSUE TITLE
libinput helper tools do not seem to be installed?

### ISSUE THREAD

**Issue by mm3psych0sis** [bulletmark/libinput-gestures#245]
[madamepsychosis@madamePsyChosis ~]$ libinput-gestures -l
libinput helper tools do not seem to be installed?

I receive this message every time I try to run libinput-gestures. Whenever I try libinput-gestures, libinput-gestures-setup start, or even python libinput-gestures I receive this message. I looked through the script and see that it is related to libvers (which I can't find any documentation on) and the comment above saying "# Libinput changed the way in which it's utilities are called". Would like some input on what could possibly be causing this.

**Comment by bulletmark** [comment]
Is this on a Debian or Ubuntu system, or derivative? Please note the second and third last paragraphs in the INSTALLATION section of the README.

**Comment by mm3psych0sis** [comment]
I am using Arch and installed it from the AUR so helper tools should already be installed. Just to be safe I reinstalled xdotool and wmctrl as well and still have the same issue. I've looked into libinput-tools but if I'm correct that seems to only be for Debian installs.

**Comment by bulletmark** [comment]
Please provide output of `libinput --version`, You installed what from AUR?

**Comment by mm3psych0sis** [comment]
Hey just letting you know I think this was caused because I was messing around with python modules. Reinstalled Arch and libinput is working fine now. Thanks for all the work you do on this package, it truly is vital enough to me that it is worth reinstalling my whole os for.
