### ISSUE TITLE
How to quiet the jumping cursor error messages

### ISSUE THREAD

**Issue by fintelkai** [bulletmark/libinput-gestures#248]
I get a good amount of these error messages in my terminal:

```
libinput error: event9  - SYNA8004:00 06CB:CD8B Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.15.3/touchpad-jumping-cursors.html for details
```

At the risk of annoying the maintainer: I realize that the jumping cursor error message is not due to this utility and is "benign" enough. So I'd prefer not to be bothered by it. Is there something in the way `libinput-gestures` calls `libinput-debug-events` that could be adjusted so as to log the messages rather them showing up in my terminal? I'd appreciate a pointer in the right direction.

**Comment by fintelkai** [comment]
Closing this myself, because I seem to have found the solution for my own setup. In `/etc/systemd/journald.conf` I changed the default setting `ForwardToWall=yes` to `ForwardToWall=no`, which has successfully quieted the jumping cursor error message.

**Comment by bulletmark** [comment]
Note the [libinput documentation about this issue](https://wayland.freedesktop.org/libinput/doc/latest/touchpad-jumping-cursors.html).

**Comment by fintelkai** [comment]
Yeah, I read that of course, but it doesn't say how to quiet the damn warnings once you're aware of them. As far as I can tell, the touchpad and gestures work perfectly well and so the warnings don't do anything for me. Having them show up on my console/terminal all the time was really bugging me.

**Comment by bulletmark** [comment]
Well that is why I have previously called them "benign" as you no doubt have read around here. I am a bit finicky about this kind of stuff also but there is plenty of other annoying noise in our journal which we can't do much about so I just lump it in that basket.

**Comment by fintelkai** [comment]
Yeah, but it didn't just show up in `journalctl`, it got injected into my terminal session incessantly, disrupting anything that was going on in there, including editing a file with vim.

**Comment by bulletmark** [comment]
Well that is another issue then. I have never seen or heard of that level of intrusion occurring. I only see those messages in my journal (using a stock journald configuration which includes `ForwardToWall=true.`). What is your output of `libinput-gestures -l`?

**Comment by fintelkai** [comment]
Output of `libinput-gestures -l` is:

```
libinput-gestures: session unknown+tty on Linux-5.5.8-arch1-1-x86_64-with-glibc2.2.5, python 3.8.2, libinput 1.15.3
/usr/bin/libinput-gestures: hash 6c180fdc9cdd31a8d8fea8733408b55a
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left         _internal ws_up -w
swipe right        _internal ws_down -w
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event9): SYNA8004:00 06CB:CD8B Touchpad
```

**Comment by fintelkai** [comment]
I figured out that starting `libinput-gestures` via the autostart mechanism properly logs the messages rather than bombarding my terminal session. So, the lesson is that starting it via the i3 config (`exec libinput-gestures-setup start`) is not a good idea.
