### ISSUE TITLE
Gestures stop working after a touchpad is reconnected

### ISSUE THREAD

**Issue by avanishsubbiah** [bulletmark/libinput-gestures#250]
```
libinput-gestures: session gnome-xorg+x11 on Linux-4.19.112-surface-lts-x86_64-with-Ubuntu-19.10-eoan, python 3.7.5, libinput 1.14.1
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:14.0-usb-0:1.3:1.0-event-mouse(event17): Microsoft Surface Keyboard Touchpad
```

**Describe the issue**
Libinput gestures all work perfectly fine when first booting up the laptop; however, after disconnecting the touchpad and reconnecting it (I have a surface book so the touchpad does disconnect), the gestures are not working.

**Comment by bulletmark** [comment]
This has been reported many times here. Some touchpads have an issue which causes the underlying `libinput debug-events` process to stop after suspend/resume. Most touchpads have no problem with this. [Here is a solution](https://github.com/bulletmark/libinput-gestures/issues/163#issuecomment-428340925) offered by somebody previously, also on GNOME like you so this should work as is. He is a little unclear but create that script e.g. `libinput-gestures-restart` then create a `libinput-gestures-restart.desktop` for it and add that to your startup applications (e.g. use `gnome-tweaks` tool to add that).

Please comment back here if it works or not.

**Comment by bulletmark** [comment]
I guess I should

**Comment by bulletmark** [comment]
No response from OP so closing ..
