### ISSUE TITLE
libinput-gestures still working when touchpad turn off

### ISSUE THREAD

**Issue by DucKhaiTong** [bulletmark/libinput-gestures#252]
```
libinput-gestures: session KDE+x11 on Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid, python 3.7.4, libinput 1.14.1
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down       4 xdotool key super+shift+d
swipe down       3 xdotool key ctrl+F9
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event4): ELAN1200:00 04F3:301A Touchpad

```

**Describe the issue**
Sorry, I dont even know whether it's an issue or not. But i really want libinput-gesture follow the rule of touchpad, i mean it disable when touchpad turn off and vice versa. thanks

**Comment by bulletmark** [comment]
How are you turning it off?

**Comment by DucKhaiTong** [comment]
> How are you turning it off?

I simply use shortcut Fn + F9 (which is touchpad button in my laptop). I know how to turn libinput-gestures off manually but i want it can be toggle same as default touchpad. By the way, thanks for your help.

**Comment by bulletmark** [comment]
Can you please do me a favor? Please run `dbus-monitor --system` and see if there is a dbus event when your turn that off? If that doesn't show anything then try `dbus-monitor --session` instead. Also capture the event when you turn it back on.

**Comment by DucKhaiTong** [comment]
"Failed to open connection to system bus: Failed to connect to socket /home/khai/anaconda3/var/run/dbus/system_bus_socket: No such file or directory" 
this is message when i run ```dbus-monitor --system```.
```dbus-monitor --session``` show a lot of signals, events or somethings, i guess.

**Comment by DucKhaiTong** [comment]
```dbus-monitor --session``` show a mess . i don't know what should i copy to here.

**Comment by bulletmark** [comment]
> `dbus-monitor --session` show a mess . i don't know what should i copy to here.

I'm not interested in all of it. I presume a message will be emitted immediately after you press that button to turn off the touchpad. I only want that message.

Regarding that anaconda3 error message, I don't know much about that but are you running that within a conda environment? Can you please run it in a clean terminal session?

**Comment by DucKhaiTong** [comment]
I deativated conda and here is the first part of the message : 
```
signal time=1586532247.385195 sender=:1.784 -> destination=(null destination) serial=6433 path=/Layouts; interface=org.kde.KeyboardLayouts; member=layoutListChanged
signal time=1586532247.385215 sender=:1.784 -> destination=(null destination) serial=6434 path=/modules/keyboard; interface=org.kde.KeyboardLayouts; member=layoutListChanged
signal time=1586532247.462576 sender=:1.787 -> destination=(null destination) serial=1447 path=/component/kcm_touchpad; interface=org.kde.kglobalaccel.Component; member=globalShortcutPressed
   string "kcm_touchpad"
   string "Toggle Touchpad"
   int64 49116423
signal time=1586532247.468226 sender=:1.784 -> destination=(null destination) serial=6435 path=/modules/touchpad; interface=org.kde.touchpad; member=enabledChanged
   boolean true
method call time=1586532247.470132 sender=:1.784 -> destination=org.kde.plasmashell serial=6436 path=/org/kde/osdService; interface=org.kde.osdService; member=touchpadEnabledChanged
   boolean true
signal time=1586532247.470377 sender=:1.794 -> destination=(null destination) serial=77454 path=/org/kde/osdService; interface=org.kde.osdService; member=osdText
   string "input-touchpad-on"
   string "Touchpad On"
method return time=1586532247.493666 sender=:1.794 -> destination=:1.784 serial=77455 reply_serial=6436
method call time=1586532247.625677 sender=:1.784 -> destination=org.kde.kglobalaccel serial=6437 path=/kglobalaccel; interface=org.kde.KGlobalAccel; member=setInactive
   array [
      string "KDE Keyboard Layout Switcher"
      string "Switch to Next Keyboard Layout"
      string "KDE Daemon"
      string "Switch to Next Keyboard Layout"
   ]
```

**Comment by bulletmark** [comment]
Is that `--system` output, or `--session`? Is that just before you turned the touchpad off? What about just after you turned it back on?

**Comment by DucKhaiTong** [comment]
Sorry for the late. It was ```--session``` output. ```--system``` shown this at first : 
```
dbus-monitor: unable to enable new-style monitoring: org.freedesktop.DBus.Error.AccessDenied: "Rejected send message, 1 matched rules; type="method_call", sender=":1.213" (uid=1000 pid=4626 comm="dbus-monitor --system " label="unconfined") interface="org.freedesktop.DBus.Monitoring" member="BecomeMonitor" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)". Falling back to eavesdropping.
signal time=1586603740.210960 sender=org.freedesktop.DBus -> destination=:1.213 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.213"
```
then nothing when i toggled touchpad.

**Comment by bulletmark** [comment]
I've add a new utility [dbus-action](https://github.com/bulletmark/dbus-action) mainly for the issue I describe [here](https://github.com/bulletmark/libinput-gestures#problem-resuming-from-suspend) but you should be able use it to stop and start `libinput-gestures` when you turn your touchpad off and on.

**Comment by DucKhaiTong** [comment]
that's cool, i'll try it. thank you.
