### ISSUE TITLE
Can't add myself to the input group

### ISSUE THREAD

**Issue by AayushBangroo** [bulletmark/libinput-gestures#253]
I used the first command to add myself to the input group and it shows adding user to input group and then i restarted.However the autostart command doesnt work since i am not able to add myself to the input group i dont know why.This permission error pops up:
cp: cannot create regular file '/home/aayushbangroo/.config/autostart/libinput-gestures.desktop': Permission denied
installed or updated /home/aayushbangroo/.config/autostart/libinput-gestures.desktop

**Comment by bulletmark** [comment]
In your first draft of the above comment you pasted the instructions to always include the output of `libinput-gestures -l` whenever you raise a bug. You fixed the comment to remove that but you still have not done what it says! Please do that.

Anyhow, it seems you have a fundamental permissions issue in your home area, nothing to do with this application. All directories and files under your home area should be owned by your normal user ("aayushbangroo" for you), not root. Many inexperienced linux users overuse root/sudo ability and end up inadvertently creating dirs and files in their home area which are owned by root.

This problem has nothing to do with being in the `input` group or not and that error also has nothing to do with trying to add yourself to that.

**Comment by bulletmark** [comment]
No response from @AayushBangroo so closing ...
