### ISSUE TITLE
script run by service can't libinput-gestures-setup restart

### ISSUE THREAD

**Issue by BieggerM** [bulletmark/libinput-gestures#254]
```
$ libinput-gestures -l
libinput-gestures: session pantheon+x11 on Linux-5.3.0-46-generic-x86_64-with-elementary-5.1.3-hera, python 3.6.9, libinput 1.10.4
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key Super+w
swipe down       3 xdotool key Super+Down
swipe left       3 xdotool key Super+Right
swipe right      3 xdotool key Super+Left
libinput-gestures: device /dev/input/by-path/pci-0000:00:14.0-usb-0:7:1.0-event-mouse(event6): Microsoft Surface Type Cover Touchpad
```
I got a detachable keyboard and need to run `libinput-gestures-setup restart` upon re-attaching. So I wrote a service to execute a script that does exactly that. 
However while this seems to work fine, this is what journalctl -xe outputs:
```
Apr 21 15:22:13 mb-Surface-Pro-4 systemd[1]: Found device Surface_Type_Cover.
-- Subject: Unit dev-input-by\x2dpath-pci\x2d0000:00:14.0\x2dusb\x2d0:7:1.0\x2devent\x2dmouse.device has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit dev-input-by\x2dpath-pci\x2d0000:00:14.0\x2dusb\x2d0:7:1.0\x2devent\x2dmouse.device has finished starting up.
-- 
-- The start-up result is RESULT.
Apr 21 15:22:13 mb-Surface-Pro-4 upowerd[886]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/0003:045E:07E8.0011
Apr 21 15:22:13 mb-Surface-Pro-4 systemd[1]: Started Service for restarting gestures.
-- Subject: Unit gestures-restart.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit gestures-restart.service has finished starting up.
-- 
-- The start-up result is RESULT.
Apr 21 15:22:13 mb-Surface-Pro-4 upowerd[886]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0
Apr 21 15:22:13 mb-Surface-Pro-4 upowerd[886]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7
Apr 21 15:22:13 mb-Surface-Pro-4 gestures-restart.sh[5532]: libinput-debug-events stopped.
Apr 21 15:22:13 mb-Surface-Pro-4 gestures-restart.sh[5532]: libinput-gestures stopped.
```
As you can see, my service (gestures-restart) will run fine and even trigger the STOP-events of the restart. Still, I am unable to find a reason why it isn't starting libinput-gestures up again.

**Comment by BieggerM** [comment]
So afaict, the restart job just triggers `user_action "stop"` and  `user_action "start"`. As the stop part seems to work fine it must be an issue with the start action. 
```
if [[ $cmd == start ]]; then
	if [[ ! -f $APPDIR/$NAME.desktop ]]; then
	    echo "$NAME is not installed."
	    exit 1
	fi
	if launch "$NAME"; then
	    echo "$NAME started."
	fi
```
I ran the output of the script into a log file and there too was no output of the start action. It almost seems like the start trigger gets ignored all together. 

On another note: thanks for maintaining this project. software works really well (whenever i dont have this bug :>)

**Comment by bulletmark** [comment]
Please just run it on the command line and paste the output here.

    libinput-gestures-setup stop
    libinput-gestures-setup start

**Comment by BieggerM** [comment]
```
$ libinput-gestures-setup stop
libinput-debug-events stopped.
libinput-gestures stopped.

```
```
$ libinput-gestures-setup start
libinput-gestures started.
```

**Comment by bulletmark** [comment]
So it works fine. What you are really asking me with this bug is to help you debug your own script(!)

You may not realize but I very recently added a [utility](https://github.com/bulletmark/dbus-action/) to stop/start libinput-gestures. I added a [note to the README](https://github.com/bulletmark/libinput-gestures#problem-resuming-from-suspend). Almost certainly you could use that. All you have to do is identify the DBUS messages output when you detach and attach your keyboard. The utility [gives you instructions](https://github.com/bulletmark/dbus-action/#configuration) how to do that.

**Comment by BieggerM** [comment]
Thank you! There's not much to debug. My script really only consists of the restart one-liner. 
I suspect it has to do with the service being run by systemd then. I thought the obligatory `User=` would suffice. 
But it would make sense that the start action cannot be run properly if it's not being run in an actual user session.

Does this make sense? I'm fairly new to Linux and just want to verify that I'm not interpreting this wrong.

About your utility. I missed that note. Will take a look into it tomorrow.

Thanks for the assistance!

**Comment by bulletmark** [comment]
Yes, it makes sense because it is exactly what I also found only last week when I wrote that other [dbus-action](https://github.com/bulletmark/dbus-action/) utility.

If you try that utility out and have any problems, issues, etc then please raise a bug on it's [issue-tracker](https://github.com/bulletmark/dbus-action/issues), not here. It is brand new so likely you will find something not clear.

I will close this bug.
