### ISSUE TITLE
3 Finger Swipes not working

### ISSUE THREAD

**Issue by SUNGOLDSV** [bulletmark/libinput-gestures#255]
```
$ libinput-gestures -l
libinput-gestures: session KDE+x11 on Linux-5.4.36-1-lts-x86_64-with-glibc2.2.5, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash 6c180fdc9cdd31a8d8fea8733408b55a
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down 3 xdotool key ctrl+F10
swipe up      3 _internal ws_down
swipe left     3 xdotool key alt+Left
swipe right   3 xdotool key alt+Right
swipe_threshold 40
libinput-gestures: device /dev/input/by-path/platform-i8042-serio-1-event-mouse(event10): SynPS/2 Synaptics TouchPad

$ libinput-gestures -d
# no gesture events detected

$ libinput-gestures -r
# no events are detected during 3 finger swipes, 2 finger scroll and taps are detected

$ groups
power users video storage lp input wheel
```

I've tried both under Wayland and X11, same results and I did a full system upgrade a day ago.
It's not a hardware issue because 3 finger swipes work for me both under Windows and MacOS. I don't think 4 finger swipes work for me on any os.

**Comment by bulletmark** [comment]
I've edited your comment above to fix up the formatting, spelling, etc. Please double-check that what I edited is correct.

Please remove your own configuration and just use the default configuration until you at least see `libinput-gestures` working. Follow the trouble-shooting section and not particularly step 5. If you don't see GESTURE events then sorry but nothing I can do. Search Google for info about your laptop/touchpad and linux.

**Comment by bulletmark** [comment]
No response from @SUNGOLDSV so closing ..
