### ISSUE TITLE
libinput debug-gui not working

### ISSUE THREAD

**Issue by georged4s** [bulletmark/libinput-gestures#256]
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README.

```
Run libinput-gestures -l on the command line and paste the output here.
```
`$ libinput-gestures -l`
libinput-gestures: session ubuntu+x11 on Linux-5.4.0-29-generic-x86_64-with-glibc2.29, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         4 _internal ws_up
swipe down       4 _internal ws_down
swipe up         3 xdotool key super+a
swipe down       3 xdotool key super+s
swipe left       3 xdotool key alt+Right
swipe right      3 xdotool key alt+Left
pinch out        2 xdotool key super+Up
pinch in         2 xdotool key super+Down
libinput-gestures: device /dev/input/by-path/platform-i8042-serio-1-event-mouse(event7): SynPS/2 Synaptics TouchPad

**Describe the issue**
The `libinput debug-gui` command is not recognized even after reinstalling libinput-tools.
![image](https://user-images.githubusercontent.com/57380498/81060945-cd9ea480-8f16-11ea-8e0d-c1d07fb5103e.png)

**Comment by bulletmark** [comment]
I have no idea why that libinput tool is not installed on your Ubuntu system but what has that got to do with libinput-gestures? Please describe your actual problem here. If you are seeing a libinput-gestures problem then please follow the trouble-shooting section of the README.

Regarding your libinput issue, do at least what that message says. I.e. see if the help says `debug-gui` should be available.

**Comment by georged4s** [comment]
I have installed libinput-tools following the README and checked the help page. It says `debug-gui` is one of the command. Please see screenshot below. I can also run `debug-events` so not sure what is wrong here. Is the help page up-to-date?
![image](https://user-images.githubusercontent.com/57380498/81067419-faa48480-8f21-11ea-97b8-10cfec58d250.png)

**Comment by bulletmark** [comment]
This is a little project called libinput-gestures. It is not libinput! Do you have an actual problem with libinput-gestures? Otherwise, there are other places where you may find help with that issue.

**Comment by georged4s** [comment]
Ahhhh sorry my bad. Posted it in the wrong place....
