### ISSUE TITLE
libinput-gestures not working

### ISSUE THREAD

**Issue by Abdelwahab0** [bulletmark/libinput-gestures#257]
I've been trying to move around with the touchpad but still nothing!

`libinput-gestures -l`
```
libinput-gestures: session gnome+x11 on Linux-5.6.8-1-MANJARO-x86_64-with-glibc2.2.5, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse(event7): Elan Touchpad

`libinput-gestures -d
````
libinput-gestures: session gnome+x11 on Linux-5.6.8-1-MANJARO-x86_64-with-glibc2.2.5, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse(event7): Elan Touchpad

`libinput-gestures-setup status
`
```
libinput-gestures is installed.
libinput-gestures is set to autostart.
libinput-gestures is not running.
libinput-gestures is using custom configuration.

```

**Comment by bulletmark** [comment]
The output above says you have no gestures configured in your `~/.config/libinput-gestures.conf` file. Remove that file and try again with the default configuration.

**Comment by Abdelwahab0** [comment]
it worked thanks a lot!

**Comment by bulletmark** [comment]
So you never actually wanted any custom configuration? Can this bug be closed?

**Comment by Abdelwahab0** [comment]
that's super great for now thanks. please mark it closed.
