### ISSUE TITLE
Gestures not detected after suspend (ask for help)

### ISSUE THREAD

**Issue by michcio1234** [bulletmark/libinput-gestures#258]
```
libinput-gestures: session cinnamon+x11 on Linux-5.3.0-51-generic-x86_64-with-debian-buster-sid, python 3.7.7, libinput 1.10.4
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       4 _internal ws_up
swipe right      4 _internal ws_down
swipe left       3 xdotool key alt+Right
swipe right      3 xdotool key alt+Left
swipe up         3 xdotool key ctrl+alt+Down
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/platform-i8042-serio-1-event-mouse(event5): SynPS/2 Synaptics TouchPad
```

In my case `libinput-gestures` works fine. The problem is probably with `libinput` itself, but I can't figure it out, so I am asking here for help.

My problem: after I wake the computer up from sleep, my touchpad no longer recognises gestures. After a reboot, before sleeping, everything works - 3 and 4-finger gestures are recognised as `GESTURE_SWIPE_UPDATE` events. After a wake-up, swiping 3 or 4 fingers produces only `POINTER_AXIS` events. 

I would appreciate any clue on how I can fix it. Thanks.

**Comment by bulletmark** [comment]
There have been others who have reported a problem like this. It seems some touchpad devices do not resume properly after suspend. I recently created a general purpose tool which can possibly be of help in this situation and I added a [note here in the README](https://github.com/bulletmark/libinput-gestures#automatic-stoprestart-on-d-bus-events-such-as-suspend) about it. You can try that.

**Comment by michcio1234** [comment]
Yes, I did it (sorry to not mention it before), but it didn't help. :/ As far as I understand, the solution that you proposed restarts libinput-gestures, not libinput itself, right? (I am talking about [this](https://github.com/bulletmark/dbus-action/blob/master/dbus-action.conf) configuration file.) I think that my problem lies deeper than that.

Oh, and by the way - when I resumed my computer from sleep now, gestures with 3 fingers **are** recognised, but 4-finger gestures are recognized as 3-finger ones. :/

**Comment by bulletmark** [comment]
Yes, that solution merely restarts libinput-gestures after waking up from suspend.

I don't understand. You say you "tried stopping and resuming libinput-gestures manually **before** suspending". You originally said the problem occurs after you wakeup your computer. So if you restart libinput-gestures **after** waking your computer up, does the problem go away, i.e. does libinput-gestures then work fine?

**Comment by michcio1234** [comment]
Sorry, I wasn't clear.
I tried: 
1) `libinput-gestures-setup stop`, 
2) suspend, 
3) wake up, 
4) `libinput-gestures-setup restart`

That didn't help. Is there anything else I can stop before suspending my computer and restart after wake up?

**Comment by bulletmark** [comment]
Clearly this bug has nothing to do with libinput-gestures so you really should not be raising an issue here. You are best to google search for similar issues reported for your model laptop/touchpad. Your libinput version is quite old, I'd look to update that (and your linux kernel) if possible.

**Comment by michcio1234** [comment]
Okay, thanks for help. I have the freshest kernel, but maybe I'll be able to update libinput.
