### ISSUE TITLE
Gnome overview not working

### ISSUE THREAD

**Issue by AlexD97** [bulletmark/libinput-gestures#26]
i am not able to configure libinput-gestures in a way that it can open/close the gnome overview. "xdotool key super+s" is not working.

**Comment by AlexD97** [comment]
okay, I just saw, that xdotool is not supported by wayland. probably that's the problem.

**Comment by bulletmark** [comment]
Note that latest version outputs an error message and exits if you have `xdotool` specified in your configuration file and you are running on Wayland. That version is in the current AUR package.
