### ISSUE TITLE
Can't delete

### ISSUE THREAD

**Issue by ismaelcuen** [bulletmark/libinput-gestures#264]
I've done each of the steps to uninstall the application, but for some reason it stays on the applicacion menu. When I open the app it says the following: "Can't load libinput-gestures: Make sure it is correctly installed. The configuration file has been saved anyway" and then it starts as if it hasn't been deleted. I've tried with the commands of purge and remove but it says that it can't find the package "gestures", so I don't know if I'm writing the name wrong. Help please.

**Comment by bulletmark** [comment]
You haven't done what the **bolded** statement says in the opening paragraph of the trouble-shooting section, and as the last step there says, and as the template says when you open this issue.

**Comment by ismaelcuen** [comment]
I don't know if this is what you mean, but I'm using Ubuntu 20.04 and this is the command line I used and the output:
<pre>$ libinput-gestures -l
libinput-gestures: orden no encontrada
I think I just need to know the name of the package, that way I can use --purge to delete it.

**Comment by bulletmark** [comment]
How did you install this package? And exactly what steps did you follow to uninstall it?

**Comment by bulletmark** [comment]
No response from @ismaelcuen so closing ..
