### ISSUE TITLE
Possibility to mute the swipe-sound and hide the "Workspace x" overlay?

### ISSUE THREAD

**Issue by valentinlietz** [bulletmark/libinput-gestures#265]
Hey, 
I wanted to know if there is a possibility to mute the swipe sound and stop the workspace overlay on switching workspaces. I think this would make the experience even better.

Cheers

**Comment by bulletmark** [comment]
What swipe sound and what overlay? Libinput-gestures doesn't do any thing like that. Please follow instructions in opening paragraph of troubleshooting section.
