### ISSUE TITLE
Custom config file not working

### ISSUE THREAD

**Issue by thelordharry** [bulletmark/libinput-gestures#267]
Hi,

I don't like 'natural scrolling' and prefer to do a three-finger drag left to go back a page, and a three-finger drag right to go forward a page. I've created a custom config file in:

~/.config/libinput-gestures.conf

with these two lines:

# Browser go forward (works only for Xorg, and Xwayland clients)
gesture swipe left	xdotool key alt+Left

# Browser go back (works only for Xorg, and Xwayland clients)
gesture swipe right	xdotool key alt+Right

I am 100% confident the file has saved properly to:

~/.config/libinput-gestures.conf

and I've rebooted the laptop to reload everything.

However, it always defaults to the default:

libinput-gestures-setup status
libinput-gestures is installed.
libinput-gestures is set to autostart.
libinput-gestures is running.
libinput-gestures is using default configuration.

(again, this is after a machine reboot, and several times).

For some strange reason, it doesn't seem to be picking up my custom config file?

Any ideas please? It's working perfectly in 'default' mode, but I'd love to change it to normal scrolling rather than natural.

FWIW, I'm using Linux Mint 20 and the machine is a HP Elitebook x360 1030 G3.

Thank you 😀

**Comment by bulletmark** [comment]
Please follow the TROUBLESHOOTING section. Note the **bolded** sentence in the opening paragraph.

**Comment by thelordharry** [comment]
Thank you:

libinput-gestures -l
libinput-gestures: session cinnamon+x11 on Linux-5.4.0-39-generic-x86_64-with-glibc2.29, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash 0f92076ca945416b73f4362e9e3e6979
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event16): ALP001C:00 044E:120A Touchpad

**Comment by thelordharry** [comment]
Custom config saved:

.config/libinput-gestures.conf

# Configuration file for libinput-gestures.
# Mark Blakeney, Sep 2015
#
# The default configuration file exists at /etc/libinput-gestures.conf
# but a user can create a personal custom configuration file at
# ~/.config/libinput-gestures.conf.
#
# Lines starting with '#' and blank lines are ignored. Currently
# "gesture" and "device" configuration keywords are supported as
# described below. The keyword can optionally be appended with a ":" (to
# maintain compatibility with original format configuration files).
#
# Each gesture line has 3 [or 4] arguments separated by whitespace:
#
# action motion [finger_count] command
#
# where action and motion is either:
#     swipe up
#     swipe down
#     swipe left
#     swipe right
#     swipe left_up
#     swipe left_down
#     swipe right_up
#     swipe right_down
#     pinch in
#     pinch out
#     pinch clockwise
#     pinch anticlockwise
#
# command is the remainder of the line and is any valid shell command +
# arguments.
#
# finger_count is a single numeric digit and is optional (and is
# typically 3 or 4). If specified then the command is executed when
# exactly that number of fingers is used in the gesture. If not
# specified then the command is executed when that gesture is executed
# with any number of fingers. Gesture lines specified with finger_count
# have priority over the same gesture specified without any
# finger_count.
#
# Typically command will be xdotool, or wmctrl. See "man xdotool" for
# the many things you can action with that tool. Note that unfortunately
# xdotool does not work with native Wayland clients.

###############################################################################
# SWIPE GESTURES:
###############################################################################

# Note the default is an "internal" command that uses wmctrl to switch
# workspaces and, unlike xdotool, works on both Xorg and Wayland (via
# XWayland). It also can be configured for vertical and horizontal
# switching over tabular workspaces, as per the example below. You can
# also add "-w" to the internal command to allow wrapping workspaces.

# Move to next workspace (works for GNOME/KDE/etc on Wayland and Xorg)
# gesture swipe up	_internal ws_up

# NOTE ABOUT FINGER COUNT:
# The above command will configure this command for all fingers (i.e. 3
# for 4) but to configure it for 3 fingers only, change it to:
# gesture swipe up	3 _internal ws_up
# Then you can configure something else for 4 fingers or leave 4 fingers
# unconfigured. You can configure an explicit finger count like this for
# all example commands in this configuration file.
#
# gesture swipe up	xdotool key super+Page_Down

# Move to prev workspace (works for GNOME/KDE/etc on Wayland and Xorg)
# gesture swipe down	_internal ws_down
# gesture swipe down	xdotool key super+Page_Up

# Browser go forward (works only for Xorg, and Xwayland clients)
gesture swipe left	xdotool key alt+Left

# Browser go back (works only for Xorg, and Xwayland clients)
gesture swipe right	xdotool key alt+Right

# NOTE: If you don't use "natural" scrolling direction for your touchpad
# then you may want to swap the above default left/right and up/down
# configurations.

# Optional extended swipe gestures, e.g. for browser tab navigation:
#
# Jump to next open browser tab
# gesture swipe right_up xdotool key control+Tab
#
# Jump to previous open browser tab
# gesture swipe left_up xdotool key control+shift+Tab
#
# Close current browser tab
# gesture swipe left_down xdotool key control+w
#
# Reopen and jump to last closed browser tab
# gesture swipe right_down xdotool key control+shift+t

# Example of 8 static workspaces, e.g. using KDE virtual-desktops,
# arranged in 2 rows of 4 columns across using swipe up/down/left/right
# to navigate in fixed planes. You can also add the "-w/--wrap" option
# to allow wrapping in any direction. You must configure your virtual
# desktops with the same column dimension.
# gesture swipe up	_internal --cols 4 ws_up
# gesture swipe down	_internal --cols 4 ws_down
# gesture swipe left	_internal --cols 4 ws_left
# gesture swipe right	_internal --cols 4 ws_right
#
# Example of 16 static workspaces, e.g. using KDE virtual-desktops,
# arranged in 4 rows of 4 columns across using swipe up/down/left/right
# to navigate in fixed planes, and also using swipe
# left_up/left_down/right_up/right_down to navigate diagonally. You can
# also add the "-w/--wrap" option to allow wrapping in any direction
# and/or diagonally. You must configure your virtual desktops with the
# same column dimension.
# gesture swipe up		_internal --cols 4 ws_up
# gesture swipe down		_internal --cols 4 ws_down
# gesture swipe left		_internal --cols 4 ws_left
# gesture swipe right		_internal --cols 4 ws_right
# gesture swipe left_up		_internal --cols 4 ws_left_up
# gesture swipe left_down	_internal --cols 4 ws_left_down
# gesture swipe right_up	_internal --cols 4 ws_right_up
# gesture swipe right_down	_internal --cols 4 ws_right_down

# Example virtual desktop switching for Ubuntu Unity/Compiz. The
# _internal command does not work for Compiz but you can explicitly
# configure the swipe commands to work for a Compiz virtual 2
# dimensional desktop as follows:
# gesture swipe up	xdotool key ctrl+alt+Up
# gesture swipe down	xdotool key ctrl+alt+Down
# gesture swipe left	xdotool key ctrl+alt+Left
# gesture swipe right	xdotool key ctrl+alt+Right

# Example to change audio volume:
# Note this only works on an Xorg desktop (not Wayland).
gesture swipe up   xdotool key XF86AudioRaiseVolume
gesture swipe down xdotool key XF86AudioLowerVolume

###############################################################################
# PINCH GESTURES:
###############################################################################

# GNOME SHELL open/close overview (works for GNOME on Xorg only)
gesture pinch in	xdotool key super+s
gesture pinch out	xdotool key super+s

# KDE Plasma open/close overview
# gesture pinch in	xdotool key ctrl+F9
# gesture pinch out	xdotool key ctrl+F9

# GNOME SHELL open/close overview (works for GNOME on Wayland and Xorg)
# Note since GNOME 3.24 on Wayland this is implemented natively so no
# real point configuring for Wayland.
# gesture pinch in dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'
# gesture pinch out dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'Main.overview.toggle();'

# Optional extended pinch gestures:
# gesture pinch clockwise <whatever command>
# gesture pinch anticlockwise <whatever command>

###############################################################################
# This application normally determines your touchpad device
# automatically. Some users may have multiple touchpads but by default
# we use only the first one found. However, you can choose to specify
# the explicit device name to use. Run "libinput list-devices" to work
# out the name of your device (from the "Device:" field). Then add a
# device line specifying that name, e.g:
#
# device DLL0665:01 06CB:76AD Touchpad
#
# If the device name starts with a '/' then it is instead considered as
# the explicit device path although since device paths can change
# through reboots this is best to be a symlink. E.g. instead of specifying
# /dev/input/event12, you should use the corresponding full path link
# under /dev/input/by-path/ or /dev/input/by-id/.
#
# You can choose to use ALL touchpad devices by setting the device name
# to "all". E.g. Do this if you have multiple touchpads which you want
# to use in parallel. This reduces performance slightly so only set this
# if you have to.
#
# device all

###############################################################################
# You can set a minimum travel distance threshold before swipe gestures
# are actioned using the swipe_threshold configuration command.
# Specify this value in dots. The default is 0.
# E.g. set it to 100 dots with "swipe_threshold 100".
# swipe_threshold 0

###############################################################################
# You can set a timeout on gestures from start to end. The default is
# the value commented below. It can be any value in float secs >= 0.
# 0 = no timeout. E.g. set it to 2 secs with "timeout 2".
# timeout 1.5

**Comment by bulletmark** [comment]
Note above it is using the default config in `/etc/libinput-gestures.conf` and note it is also telling you that in the `libinput-gestures-setup status` output you quote above. You have not put your config file in `~/.config/libinput-gestures.conf`. Please paste the output of `ls -l ~/.config`. Note the `~` is shell shortcut for your `$HOME`.

**Comment by bulletmark** [comment]
Note I deleted that huge config file you pasted in large bold text. It was just noise and flooded these comments. I also fixed the formatting of your `libinput-gestures -l` output.

**Comment by thelordharry** [comment]
The more you know, eh?

Sorry about the noise. I was trying to be 'helpful' by providing as much info as possible. I copied and pasted the custom file, not realising all the hashes made everything huge.

Thanks to your guidance with the $HOME tip, I worked out I had pasted the custom file in the wrong location. I put it in root, not home. I cut and pasted it to home, rebooted my laptop and it's now working as expected. I've got a lot to learn with Linux.

Thank you for your help.

**Comment by bulletmark** [comment]
Note to get the reverse scrolling that you prefer with the default configuration, you just need to swap the 2 gesture up/down lines, and the 2 swipe left/right lines. If you paste your revised `libinput-gestures -l` output, it should be the same as above with those lines swapped.

**Comment by thelordharry** [comment]
It sure does, thanks:

libinput-gestures -l
libinput-gestures: session cinnamon+x11 on Linux-5.4.0-39-generic-x86_64-with-glibc2.29, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash 0f92076ca945416b73f4362e9e3e6979
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left         xdotool key alt+Left
swipe right        xdotool key alt+Right
swipe up           xdotool key XF86AudioRaiseVolume
swipe down         xdotool key XF86AudioLowerVolume
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event16): ALP001C:00 044E:120A Touchpad

I don't use workspaces, so I've used the 3-finger up and down (is that a euphemism?) for volume.

Thanks again.
