### ISSUE TITLE
Ubuntu Budgie 20.04 nothing works - gestures UI does work

### ISSUE THREAD

**Issue by zilexa** [bulletmark/libinput-gestures#268]
Ubuntu Budgie 20.04
```
$ sudo libinput-gestures -l
[sudo] password for asterix: 
libinput-gestures: session unknown+unknown on Linux-5.8.0-050800-generic-x86_64-with-glibc2.29, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash 0f92076ca945416b73f4362e9e3e6979
Gestures configured in /etc/libinput-gestures.conf:
swipe up           /usr/lib/budgie-previews/previews_triggers hotcorners_all
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/platform-AMDI0010:03-event-mouse(event10): SYNA32A0:00 06CB:CE14 Touchpad
```

**Describe the issue**
None of the default commands seem to work, even after I added the user to the group and logged out. 
I am trying to get alt+tab functionality with 3/4 finger swipe up. I tried with the command in quotes but it does not work. 
Note I also installed: https://gitlab.com/cunidev/gestures
Which is a little UI for libinput-gestures. When I use that UI, add the same (3 finger) gesture with the exact same command, it does work. But I would like my setup to be independent from that little UI tool.

**Comment by bulletmark** [comment]
You say "default commands" but they are not the default commands. You have clobbered the default config with something else. Please reinstall and leave the default `/etc/libinput-gestures.conf` as is then try again and see if the default swipe up/down can change workspaces. Go through all the steps in the trouble-shooting section.

To create a custom config, copy that file to your own `~/.config/libinput-gestures.conf` and edit as you like.

**Comment by zilexa** [comment]
I didn't create a custom config because the default didn't work yet. But I started over and now it works. I was a bit too quick opening an issue.
