### ISSUE TITLE
Scrolling in browser (Chromium, Firefox) affected

### ISSUE THREAD

**Issue by dodalovic** [bulletmark/libinput-gestures#269]
Hi, I really like the product, first of all. 

One thing I spotted is that when `libinput-gestures` is active, then scrolling in browsers I have installed is affected. Pretty much, it's not smooth. 
I have a touch screen and using the latest Pop OS. 

Please, let me know if I can better describe the issue. 

Thanks!

**Comment by bulletmark** [comment]
Yes, please read the first paragraph of the trouble-shooting section and provide the essential info requested there.

**Comment by dodalovic** [comment]
```
libinput-gestures: session pop+x11 on Linux-5.4.0-7634-generic-x86_64-with-glibc2.29, python 3.8.2, libinput 1.15.5
libinput-gestures: hash 0f92076ca945416b73f4362e9e3e6979
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event10): DELL098F:00 04F3:311C Touchpad
```

**Comment by dodalovic** [comment]
I haven't done any config, I was just doing minimal install

**Comment by bulletmark** [comment]
Nobody else have ever commented that this small utility imposes any noticeable effect on their system. Try scrolling in your browser with this utility disabled/enabled (`libinput-gestures-setup stop|start`) with `htop` running in a terminal and see if you can see it affecting the CPU. I tried on my old laptop and I can't see any difference. Make sure you are have the same browser tabs open etc, and keep everything else constant.

**Comment by dodalovic** [comment]
I believe your analysis is correct at the very end, and very likely this smooth scrolling issue might be related to something else (trackpad or my 4k screen, or whatever else). 
Sorry for bothering :(
