### ISSUE TITLE
ydotool

### ISSUE THREAD

**Issue by gaspar-d** [bulletmark/libinput-gestures#271]
I really don't have a problem, just ask what do you think of ydotool? I tested it in wayland and seens to work with libinput-gestures.

https://github.com/ReimuNotMoe/ydotool

**Comment by bulletmark** [comment]
I don't know much about it. README says it must be run as root so are you running your desktop as root?

**Comment by gaspar-d** [comment]
Nope, using Majaro right now and in there's a ydotool package in AUR, did a normal yay install using my user.

**Comment by bulletmark** [comment]
"Nope" - do you mean you are not running your DE as root? And if you aren't then how are you using ydotool when the README says it needs root permission?

**Comment by gaspar-d** [comment]
"This program requires access to /dev/uinput. This usually requires root permissions." 
As it states in the README, "usually", I'm by no means an expert programmer (I just begin to study this year) to give any evidence about the 'why',  but it's working right now, just changed the command 'xdotool key comand' for 'ydotool key command'.
Didn't worked for all commands I had under xorg, but now gestures are pretty much usable under wayland.

**Comment by gaspar-d** [comment]
I'm not a native english speaker, so I' think I didn't express myself well.
I'm not using my DE as root.

**Comment by bulletmark** [comment]
As requested for all new bugs, please paste the output of `libinput-gestures -l` here. That will show me the actual commands you are using.

**Comment by gaspar-d** [comment]
Here it's.

```
libinput-gestures: session gnome+wayland on Linux-5.6.19-2-MANJARO-x86_64-with-glibc2.2.5, python 3.8.3, libinput 1.15.6
/usr/bin/libinput-gestures: hash b1fb733b08ae7c49c1660382dd44a5ed
Gestures configured in ~/.config/libinput-gestures.conf:
swipe right      3 ydotool key super+Tab
swipe left        3 ydotool key super+shift+Tab
swipe up         3 ydotool key ctrl+Tab
swipe down    3 ydotool key ctrl+shift+Tab
pinch in          4 ydotool key super+z
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event13): ELAN1200:00 04F3:303E Touchpad
```

**Comment by bulletmark** [comment]
ydotool doesn't work on my system as it can't open the uinput device. The installation and instructions on the github page are poor and little activity is shown there. The author also says he has little time to maintain the project. So I don't think it is a valid tool.

**Comment by goetzc** [comment]
@bulletmark just add your user to the `input` group.

```sh
usermod -aG input $USER
```

**Comment by bulletmark** [comment]
@goetzc I am the author of `libinput-gestures` and thus have used it for years (with Wayland and `xdotool`). Note the first step in the installation instructions is to add yourself to the `input` group so clearly I have done that! Also, you must be interpreting that fusima README completely differently to me as it pretty much proposes to use `xdotool`, then adds a very short list of three alternatives at the end, one of which is `ydotool` and even then it says `needs more maintainers`. I just tried `ydotool` again and it doesn't work for me.

**Comment by goetzc** [comment]
@bulletmark, thanks for your answer. 

As I understand it, because of the differences between input handling on X11 and Wayland, `ydotool` works a bit different than `xdotool`. It must [create a virtual input device](https://github.com/ReimuNotMoe/ydotool#why-a-background-service-is-needed) everytime it's executed, and this takes time and probably it's here where it fails in your machine. There is an option to start a background daemon, `ydotoold`, which holds a persistent virtual device. This might work in your case, I'm running that too.

As `ydotool` works using `uinput`/`udev`, it will also work on any modern X11 DE.

My `libinput-gestures.conf`:

```ini
gesture swipe left  ydotool key ctrl+alt+l
gesture swipe right ydotool key ctrl+alt+h

gesture swipe up    ydotool key alt+\`
gesture swipe down  ydotool key alt+shift+\`

gesture pinch in    ydotool key super+=
gesture pinch out   ydotool key super+-
```

Thanks for your work on the project.
