### ISSUE TITLE
Guestures Not working even tho touchpad is reckognized

### ISSUE THREAD

**Issue by almulalic** [bulletmark/libinput-gestures#273]
Run libinput-gestures -l on the command line and paste the output here.
```
libinput-gestures: session gnome+wayland on Linux-5.5.0-kali2-amd64-x86_64-with-glibc2.29, python 3.8.2, libinput 1.15.5
/usr/bin/libinput-gestures: hash 0f92076ca945416b73f4362e9e3e6979
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
device ELAN0634:00 04F3:0400 Mouse
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse(event5): ELAN0634:00 04F3:0400 Mouse
```

**Describe the issue**
So after a two month long battle with this touchpad one super friendly guy from ubuntu forums finally resolved my issue of not working touchpad. I have a lenovo thinkbook 15 IIL and as it seems it uses some kind of  touchpad that's new for linux community. At first it was not reckognized at all but after some kernel fixes and some code commenting I managed to make it work. Unfortunatley I just got mouse movment with clicks, no gestures at all. I installed this tool and tried it but it showed touchpad not found, then as one thread in this repo suggested I manually inputed device name which is " ELAN0634:00 04F3:0400 Mouse" and after a restart libinput reckognized it and started logging mouse move and click events, but again no gestures at all.  I'm currently dual booting with windows so I can 100% confirm that this touchpad is more that capable of delivering gestures. I would like to know if this issue is even possible to resolve because I'm currently debating between wireless mouse and this so it's kind of a important question for me. If you need any additional output please say Ill add it as soon as I see. Thanks for contributing to the linux community.

Distro: Kali
Kernel: 5.5.0-kali-amd64

**Comment by bulletmark** [comment]
Please follow the troubleshooting section. Note particularly, steps 5 and 6.

**Comment by bulletmark** [comment]
No response from @almulalic so closing ...
