### ISSUE TITLE
Caps/Control remapping issue

### ISSUE THREAD

**Issue by evalexpr** [bulletmark/libinput-gestures#274]
libinput-gestures -l:

```
libinput-gestures: session none+i3+x11 on Linux-5.7.19-x86_64-with-glibc2.2.5, python 3.7.6, libinput 1.15.0, hash ?
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       3 xdotool key Control_L+bracketleft
swipe right      3 xdotool key Control_L+bracketright
libinput-gestures: device /dev/input/event15: ETPS/2 Elantech Touchpad
```

I have `ctrl:swapcaps` in my xkb options, and am trying to set a mapping to run `xdotool key Ctrl+[` as you can see above.

I'm running into an issue where, if I have this mapping defined as above - and swipe with 3 fingers, becauseof the xkb option I mentioned before - it works - but caps lock is turned on/off every time I swipe (once turns it on, again afterwards turns it off).

I've tried using the mapping `Caps_Lock+bracketleft` instead, but the same issue seems to occur.

Is this expected? or a known issue? Is there something I can do to mitigate it?

**Comment by bulletmark** [comment]
The obvious question is whether this happens when you run those xdotool commands manually? I.e. run the commands on the command line with libinput-gestures not involved.

**Comment by evalexpr** [comment]
I should've checked that, apologies. It does seem that it's an issue even without libinput-gestures - so I'll have to figure that out. Thanks
