### ISSUE TITLE
Can different DE/WM use a unique config file?

### ISSUE THREAD

**Issue by vaskark** [bulletmark/libinput-gestures#276]
Output of libinput-gestures -l:
```
libinput-gestures: session bspwm+x11 on Linux-5.8.14-custom-x86_64-with-glibc2.32, python 3.8.6, libinput 1.16.2
/usr/bin/libinput-gestures: hash 9f979356e75d2fde95745b2036f97f24
Gestures configured in ~/.config/libinput-gestures.conf:
swipe down       4 _internal ws_up
swipe up         4 _internal ws_down
swipe up         3 xdotool key super+s
swipe down       3 xdotool key super+s
swipe right      3 xdotool key XF86AudioRaiseVolume
swipe left       3 xdotool key XF86AudioLowerVolume
swipe_threshold 100
device ELAN1300:00 04F3:3059 Touchpad
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event7): ELAN1300:00 04F3:3059 Touchpad
```
Issue:

I was wondering if it's possible to set up unique config files for different environments, ie. Gnome and bspwm, as some gestures don't make sense in one or the other.

Example:
In bspwm I have in my start file `libinput-gestures -c ~/.config/bspwm/gestures.conf` and everything is fine. But if I switch into GNOME (w/o rebooting) it is still using this same config file, and not the one at `~/.config/libinput-gestures.conf`, which is what I want GNOME to use. The opposite happens if I'm in GNOME first.

I probably could have explained this better. Obviously each environment needs to stop `libinput-gestures` then restart with it's own config file. I've tried a few different things with partial success. Hopefully someone has a solution (which will turn out to be super obvious :)

Thanks. I'm using latest git on Ubuntu 20.04.1.

**Comment by bulletmark** [comment]
I suggest the following:

1. Create the following files:
```
~/.config/libinput-gestures-gnome.conf
~/.config/libinput-gestures-bspwm.conf
~/.config/autostart/my-libinput-gestures.desktop (with Exec=/home/myname/bin/my-libinput-gestures-start)
~/bin/my-libinput-gestures-start (your shell script)
```

Your shell script should look at the `XDG_SESSION_DESKTOP` and/or `DESKTOP_SESSION` vars and based on which desktop is running then symlink the appropriate conf file to `~/.config/libinput-gestures.conf` and then it should run `libinput-gestures-setup restart`.

**Comment by bulletmark** [comment]
No response from @vaskark so closing ...
