### ISSUE TITLE
Reading gestures from terminal Ubuntu 18 on Jetson Xavier

### ISSUE THREAD

**Issue by canozcivelek** [bulletmark/libinput-gestures#278]
Hi, I 'm looking for a way to read my touch input from terminal, note that I'm not using a trackpad, I'm using a touch screen. My eventual goal is to simulate pinch gesture inside an OpenCV applicaton where I can perform pinch to zoom. The way I'm thinking of doing it is if I can find out what command is being run, I'd run that same command inside my application. I'm using the default config file. Pinch works on Chrome, 3-4 finger gestures work as well. libinput gestures -d command doesn't output any actions :/

Here is some other info that may be helpful:
**Device:** Jetson Xavier on Ubuntu 18
**Touch screen:** Waveshare 13.3" LCD panel
**libinput-gestures -l output:**
libinput-gestures: session unity+x11 on Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic, python 3.6.9, libinput 1.10.4
/usr/bin/libinput-gestures: hash 9f979356e75d2fde95745b2036f97f24
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/platform-3610000.xhci-usb-0:2.2:1.1-event-mouse(event5): ILITEK Multi-Touch-V3000

I'm new to this stuff so really appreciate any help. Thanks!

**Comment by bulletmark** [comment]
Note the [opening paragraph of the libinput documentation](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#gestures). Libinput does not support gestures on touchscreens so this utility is not relevant to what you want sorry.
