### ISSUE TITLE
Wrong detection of Swipe event

### ISSUE THREAD

**Issue by af2005** [bulletmark/libinput-gestures#28]
Hi,
I've been looking for multitouch gestures on linux for a long time. Finally a working solution! Thanks for that. 
But for my touchpad the detection of pinch and swipe often gets messed up. Surely because of my messy swipe movement. I'd love to be able to disable pinch completely as I never use it. Meaning that not only there is no command behind it but the software only detects left swipe and right swipe which surely could be done without false detection.

**Comment by bulletmark** [comment]
Copy `/etc/libinput-gestures.conf` to `~/.config/libinput-gestures.conf` and then delete/comment out the pinch entries, or make them the same as the swipe entries, etc.

Iibinput reports the gestures explicitly as swipe or pinch, before it even gets to this little utility so there is nothing I can do about discerning them differently.

**Comment by af2005** [comment]
ok. thanks. 
Somehow the gestures do not work in nautilus (gnome files) for me. Pressing Alt+Left / Alt+Right works perfectly.  I'm on Gnome + wayland. Maybe this is related to the missing popup while changing workspaces?

**Comment by bulletmark** [comment]
Unfortunately `xdotool` does not work at all on Wayland and never will because Wayland is designed in a more secure way that prohibits such apps. This means that `libinput-gestures` is useless on Wayland. See issues #26 and #27.
