### ISSUE TITLE
Make xdotool and wmctrl optional dependencies in the AUR package

### ISSUE THREAD

**Issue by zeertzjq** [bulletmark/libinput-gestures#282]
In PKGBUILD of the AUR package, `xdotool` and `wmctrl` are listed as required dependencies, but with a libinput-gestures.conf that doesn't use these two commands, libinput-gestures can work without these two packages installed, so maybe `xdotool` and `wmctrl` should be optional dependencies instead.

**Comment by bulletmark** [comment]
Fair suggestion I guess. `wmctrl` is necessary for all users who rely on the `_internal` command. To make this clear, I have added a startup check which outputs a warning if `_internal` is configured, but `wmctrl` is not installed. I have made a new AUR package 2.53 with this change and with those dependencies removed.
