### ISSUE TITLE
Continuous scrolling wtih 3 or more fingers

### ISSUE THREAD

**Issue by 3ThumbsUp** [bulletmark/libinput-gestures#283]
Maybe this is possible somehow already, but I haven't found a way to do it. I'm not sure about proper terminology but I'll explain as best as I can what I mean.

Basically what I would like to emulate is the following behavior.

3 finger swipe left or right = Alt+tab or alt+shift+tab (switch applications)
As long as 3 fingers are on the touchpad, it emulates alt being kept down.
When the fingers are released, alt is released.

This would allow one to scroll through open applications and choose one by releasing rather than just switch one application at a time. There are many actions that could benefit from a behavior like this (switch applications, switch window in open application, switch workspaces, switch tabs etc).

I think the above behavior would be a big improvement to an already great program.

**Comment by bulletmark** [comment]
No sorry, this is a very simple utility which merely invokes what ever you configure as an action at the end of what [libinput defines as a gesture](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html). What you want would not be easy to add to the current design.
