### ISSUE TITLE
Enable 2 finger gestures when edge scrolling is used

### ISSUE THREAD

**Issue by HarshGundecha** [bulletmark/libinput-gestures#285]
Hello, 
I am using Ubuntu 20, where there's this option in mouse "Enable edge scrolling" enabling which makes 2 fingers gestures free to be used for other purpose.
So i would request to add a behavior where 2 finger gestures are enabled conditionally by checking whether or not the 2 finger gestures are used.
Thank you

**Comment by bulletmark** [comment]
Firstly, note the bolded sentence in the opening paragraph of the README.

Secondly, 2 finger gestures ARE enabled, at least for pinch gestures (2 to 4 fingers). 3 and 4 finger gestures are enabled for swipe gestures. Are you asking for 2 finger swipe gestures? Libinput does not provide that. Read https://wayland.freedesktop.org/libinput/doc/latest/gestures.html.

**Comment by bulletmark** [comment]
No response from @HarshGundecha so closing ...
