### ISSUE TITLE
Can't uninstall...

### ISSUE THREAD

**Issue by jaysinha3595** [bulletmark/libinput-gestures#287]
I ran these three lines but still Gesture shows up in Show Application Window.
`libinput-gestures-setup stop`
`libinput-gestures-setup autostop`
`sudo libinput-gestures-setup uninstall`

**Comment by bulletmark** [comment]
Please note the bolded sentence in the opening paragraph of the trouble-shooting section in the README.

**Comment by bulletmark** [comment]
No response from @jaysinha3595 so closing ...
