### ISSUE TITLE
Autostart not working on Gentoo

### ISSUE THREAD

**Issue by joshuamoorexyz** [bulletmark/libinput-gestures#288]
```
libinput-gestures: session i3+x11 on Linux-5.9.14-x86_64-AMD_Ryzen_5_4500U_with_Radeon_Graphics-with-gentoo-2.7, python 3.7.9, libinput 1.16.4
/usr/bin/libinput-gestures: hash 0344acdbe1ec2e111b60830e2839cce5
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/platform-AMDI0010:03-event-mouse(event6): ELAN1206:00 04F3:30F1 Touchpad
```
libinput-gestures-setup autostart is not actually autostarting when the device is booted.
Ive tried to add this to a cron job but cant seem to get it to work correctly.Any ideas as to why the autostart feature would not work?

**Comment by bulletmark** [comment]
Please run the following commands and paste the commands and output here:
```
libinput-gestures-setup status
libinput-gestures-setup stop
libinput-gesture-setup autostop
libinput-gesture-setup autostart
libinput-gestures-setup start
libinput-gestures-setup status
```

**Comment by joshuamoorexyz** [comment]
~  libinput-gestures-setup status
libinput-gestures is installed.
libinput-gestures is set to autostart.
libinput-gestures is not running.
libinput-gestures is using default configuration.
 ~  libinput-gestures-setup stop
 ~  libinput-gestures-setup autostop
removed '/home/moorejoshua96/.config/autostart/libinput-gestures.desktop'
 ~  libinput-gestures-setup autostart
installed or updated /home/moorejoshua96/.config/autostart/libinput-gestures.desktop
 ~  libinput-gestures-setup start
libinput-gestures started.
 ~  libinput-gestures-setup status
libinput-gestures is installed.
libinput-gestures is set to autostart.
libinput-gestures is running.
libinput-gestures is using default configuration.
 ~ 

**Comment by bulletmark** [comment]
I don't use i3 but it appears that it does not honor the standard XDG file standards. See https://askubuntu.com/questions/654801/how-to-run-gnome-startup-applications-in-i3 and https://faq.i3wm.org/question/2155/how-can-i-use-autostart-desktop-files-in-i3.1.html. Surprisingly, no other i3 user has ever mentioned this issue previously so I guess it is a common issue installing new applications on i3 and they all just add the startup manually.

**Comment by joshuamoorexyz** [comment]
I see.I will add it to my config file.This will most certainly help others in the future.Thank you.
