### ISSUE TITLE
[Errno 2] No such file or directory: 'libinput-list-devices'

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [bulletmark/libinput-gestures#29]
When I run:
" libinput-gestures -d "
I get:
" [Errno 2] No such file or directory: 'libinput-list-devices' "

I am running ubuntu 16.10.
I did install xdotool and follow the instruction listed for compiling.

**Comment by bulletmark** [comment]
I don't use Ubuntu but I just had a quick check and it seems that utility may be packaged independently in the `libinput-tools` package? Please install that and let me know so that I will update the README here.

**Comment by JamesTiberiusKirk** [comment]
First of all, thanks for responding so quickly, you're amazing! 
I've installed the package and now it works beautifully!

Thanks for the good work!

**Comment by bulletmark** [comment]
Updated the README with commit af6ad43.

**Comment by grigio** [comment]
i get
```
❯ [Errno 2] No such file or directory: 'libinput-list-devices'
Traceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 337, in <module>
    if not args.device or args.device.lower() != "all" else None
  File "/usr/bin/libinput-gestures", line 154, in get_device
    if dev_text:
UnboundLocalError: local variable 'dev_text' referenced before assignment
```

**Comment by bulletmark** [comment]
@grigio please follow the installation instructions in the README. It states that on Ubuntu you must install the `libinput-tools` package.

This is the same problem the OP here reported, and the answer was already provided above.

**Comment by grigio** [comment]
Thanks it fixed, I had problems with deps so I forgot to reinstall it
