### ISSUE TITLE
Cause invalid systemctl option 'P' error when libinput-gestures-setup service

### ISSUE THREAD

**Issue by eypsume** [bulletmark/libinput-gestures#292]
Cause invalid systemctl option 'P' error when libinput-gestures-setup service
Anyway I replace uppercase -P to lowcase -p at line 288~289 in the libinput-gestures-setup
and  works perfect!

**Comment by bulletmark** [comment]
When raising an issue, please always provide the output of `libinput-gestures -l`. That will allow me to see what system you are running.

Both [`-P` and `-p` options](https://man7.org/linux/man-pages/man1/systemctl.1.html) are valid but different. It must be the case that older versions of `systemctl` did not have the `-P` option so I will make a new release now using only `-p` with a little more logic. Note that simply replacing `-P` with '-p' will **not** work.

**Comment by bulletmark** [comment]
Fixed by commit 115dd640b381a919369e804a31d29ed52538604f and release 2.60.
