### ISSUE TITLE
Multi-finger tap and drag in libinput 1.17

### ISSUE THREAD

**Issue by OliverLew** [bulletmark/libinput-gestures#294]
Curious if libinput-gestures can use the new "tap-and-drag with two and three fingers" feature in libinput 1.17:
https://lists.freedesktop.org/archives/wayland-devel/2021-February/041733.html

**Comment by bulletmark** [comment]
Libinput has long had [tap-and-drag](https://wayland.freedesktop.org/libinput/doc/latest/tapping.html#tap-and-drag). Previously you could only use it for a single tap. Libinput 1.17 adds the ability to use it with two and three finger taps as well. None of this is reported by libinput as [gestures](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html) so this change is not relevant here sorry.

**Comment by OliverLew** [comment]
Thanks for explaining
