### ISSUE TITLE
Issues starting libinput

### ISSUE THREAD

**Issue by linusrg1** [bulletmark/libinput-gestures#299]
My setup:
Arch kde
Synaptics touchpad

I dont know what is happening to be honest. It appears to be starting. I tried starting it from libinput-gestures-qt and from the terminal but there is never any output so I can't troubleshoot the issue. I dont know what is going on.

**Comment by bulletmark** [comment]
Please follow the TROUBLE SHOOTING section. Note the bold sentence in the opening paragraph.

**Comment by linusrg1** [comment]
libinput-gestures: session KDE+x11 on Linux-5.11.15-zen1-2-zen-x86_64-with-glibc2.33, python 3.9.3, libinput 1.17.1
/usr/bin/libinput-gestures: hash 494597e082dbf3864a47761a3b7ae27c
Gestures configured in ~/.config/libinput-gestures.conf:
swipe right      3 xdotool key alt+Left
libinput-gestures: device /dev/input/by-path/platform-i8042-serio-1-event-mouse(event14): SynPS/2 Synaptics TouchPad

here is the output of libinput-gestures -l. Mb.

I was using the aur version but since it wasnt starting I tried compiling the github version instead. It started once but that was it. 
It never started again. I did add myself to the input group and I even checked the /etc/group file to check that I was actually added to it.

**Comment by bulletmark** [comment]
Please provide the output of `libinput-gestures-setup status`.

**Comment by linusrg1** [comment]
```libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is not currently running.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration.
```
It says it isnt running but thats 'cause it wont start.

**Comment by bulletmark** [comment]
SInce you are using Arch, you are better off starting this as a systemd user service which as the README says is the preferred option. Type:
````
libinput-gestures-setup service
libinput-gestures-setup autostart
libinput-gestures-setup start
````

**Comment by linusrg1** [comment]
ok i did do that but I misunderstood some of the output so I thought I disabled it instead of enabling it with those comands

**Comment by bulletmark** [comment]
So is it working now?

**Comment by linusrg1** [comment]
sadly no it still says it is not running, should I try a reboot?

**Comment by bulletmark** [comment]
Please paste the output of `libinput-gestures-setup status` again here.

**Comment by linusrg1** [comment]
```libinput-gestures is installed.
libinput-gestures is set up as a user service.
libinput-gestures is not currently running.
libinput-gestures is set to autostart as a user service.
libinput-gestures is using custom configuration.
```

**Comment by bulletmark** [comment]
What is output of these:
````
systemctl status --user libinput-gestures
journalctl -b --user -u libinput-gestures
````

**Comment by linusrg1** [comment]
```× libinput-gestures.service - Actions gestures on your touchpad using libinput
     Loaded: loaded (/usr/lib/systemd/user/libinput-gestures.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-04-21 18:33:26 EDT; 5min ago
       Docs: https://github.com/bulletmark/libinput-gestures
    Process: 7275 ExecStart=/usr/bin/libinput-gestures (code=exited, status=1/FAILURE)
   Main PID: 7275 (code=exited, status=1/FAILURE)
        CPU: 234ms

Apr 21 18:33:25 linus-laptop systemd[573]: Started Actions gestures on your touchpad using libinput.
Apr 21 18:33:26 linus-laptop libinput-gestures[7275]: libinput-gestures is already running for linus, terminating ..
Apr 21 18:33:26 linus-laptop systemd[573]: libinput-gestures.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 18:33:26 linus-laptop systemd[573]: libinput-gestures.service: Failed with result 'exit-code'.
```
```Apr 21 18:31:46 linus-laptop systemd[573]: Started Actions gestures on your touchpad using libinput.
Apr 21 18:31:47 linus-laptop libinput-gestures[7235]: libinput-gestures is already running for linus, terminating ..
Apr 21 18:31:47 linus-laptop systemd[573]: libinput-gestures.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 18:31:47 linus-laptop systemd[573]: libinput-gestures.service: Failed with result 'exit-code'.
Apr 21 18:33:25 linus-laptop systemd[573]: Started Actions gestures on your touchpad using libinput.
Apr 21 18:33:26 linus-laptop libinput-gestures[7275]: libinput-gestures is already running for linus, terminating ..
Apr 21 18:33:26 linus-laptop systemd[573]: libinput-gestures.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 18:33:26 linus-laptop systemd[573]: libinput-gestures.service: Failed with result 'exit-code'.
```

**Comment by bulletmark** [comment]
Says it is already running. Must have got something in a knot earlier. Reboot, then should be ok.

**Comment by linusrg1** [comment]
ok

**Comment by bulletmark** [comment]
So did that fix it?

**Comment by linusrg1** [comment]
Sadly no unless it doesnt autostart it still says it isnt running. Maybe it doesnt like my trackpad it is 11 years old.

**Comment by bulletmark** [comment]
Please type the output of the following now that you have rebooted:
````
systemctl status --user libinput-gestures
journalctl -b --user -u libinput-gestures
````

**Comment by linusrg1** [comment]
```○ libinput-gestures.service - Actions gestures on your touchpad using libinput
     Loaded: loaded (/usr/lib/systemd/user/libinput-gestures.service; enabled; >
     Active: inactive (dead)
       Docs: https://github.com/bulletmark/libinput-gestures
````
```-- Journal begins at Fri 2021-04-16 06:32:42 EDT, ends at Wed 2021-04-21 19:52:>
-- No entries --
```
```libinput-gestures is installed.
libinput-gestures is set up as a user service.
libinput-gestures is not currently running.
libinput-gestures is set to autostart as a user service.
libinput-gestures is using custom configuration.
```

Here

**Comment by bulletmark** [comment]
Sure you typed `journalctl -b --user -u libinput-gestures` exactly?

**Comment by linusrg1** [comment]
yep copied and pasted ur exact command.

**Comment by linusrg1** [comment]
Maybe it is a zen kernel issue? Should I try the stock kernel?

**Comment by bulletmark** [comment]
When you paste output always include the initiating command so there is no confusion about that.

Hard to believe it is a kernel issue when we can't even see the journal output. Something basic we are missing here.

**Comment by linusrg1** [comment]
Ok. I removed the initiating command because it was cutting the first line off.

**Comment by linusrg1** [comment]
Also despite using arch I know less about linux than u might think. Im not clueless I know quite a bit but not as much about the linux backend.

**Comment by linusrg1** [comment]
So I apologize if I am having issues thinking of potential answers

**Comment by bulletmark** [comment]
Type `journalctl --since today --user -u libinput-gestures`

**Comment by linusrg1** [comment]
```Apr 21 18:31:46 linus-laptop systemd[573]: Started Actions gestures on your touchpad using libinput.
Apr 21 18:31:47 linus-laptop libinput-gestures[7235]: libinput-gestures is already running for linus, terminating ..
Apr 21 18:31:47 linus-laptop systemd[573]: libinput-gestures.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 18:31:47 linus-laptop systemd[573]: libinput-gestures.service: Failed with result 'exit-code'.
Apr 21 18:33:25 linus-laptop systemd[573]: Started Actions gestures on your touchpad using libinput.
Apr 21 18:33:26 linus-laptop libinput-gestures[7275]: libinput-gestures is already running for linus, terminating ..
Apr 21 18:33:26 linus-laptop systemd[573]: libinput-gestures.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 18:33:26 linus-laptop systemd[573]: libinput-gestures.service: Failed with result 'exit-code'.
```

**Comment by linusrg1** [comment]
It looks like to me it tries to run it thinks it is already running then kills it.

**Comment by bulletmark** [comment]
Please run these commands again and then paste all the output as one (including all the commands).
````
libinput-gestures-setup stop
libinput-gestures-setup autostop
libinput-gestures-setup service
libinput-gestures-setup autostart
libinput-gestures-setup start
````

**Comment by linusrg1** [comment]
```Created symlink /home/linus/.config/systemd/user/graphical-session.target.wants/libinput-gestures.service → /usr/lib/systemd/user/libinput-gestures.service.
libinput-gestures is installed.
libinput-gestures is set up as a user service.
libinput-gestures is currently running as a user service.
libinput-gestures is set to autostart as a user service.
libinput-gestures is using custom configuration.
```

**Comment by bulletmark** [comment]
Where's all the commands?

**Comment by linusrg1** [comment]
oh u wanted those too? sry. 
```[linus@linus-laptop ~]$ libinput-gestures-setup stop
libinput-gestures stopped as a user service.
[linus@linus-laptop ~]$ libinput-gestures-setup autostop
[linus@linus-laptop ~]$ libinput-gestures-setup service
[linus@linus-laptop ~]$ libinput-gestures-setup autostart
Created symlink /home/linus/.config/systemd/user/graphical-session.target.wants/libinput-gestures.service → /usr/lib/systemd/user/libinput-gestures.service.
libinput-gestures enabled as a user service.
[linus@linus-laptop ~]$ libinput-gestures-setup start
libinput-gestures started as a user service.
[linus@linus-laptop ~]$ libinput-gestures-setup status
libinput-gestures is installed.
libinput-gestures is set up as a user service.
libinput-gestures is currently running as a user service.
libinput-gestures is set to autostart as a user service.
libinput-gestures is using custom configuration.
```

**Comment by bulletmark** [comment]
The above says it is running. Is there still a problem?

**Comment by linusrg1** [comment]
gestures aint working but ill delete my config that gestures-qt made and use the default one.

**Comment by bulletmark** [comment]
Please type `journalctl -b --user -u libinput-gestures ` exactly as you see here (i.e. copy/paste it). Then paste that command and the output that follows it here. Please include that first line (note you missed the first line in your output just above).

**Comment by linusrg1** [comment]
still nope? I even restarted it. Maybe 11yr old trackpads dont have more that 2 finger support?

**Comment by bulletmark** [comment]
Nope? I was expecting the output I asked for?

**Comment by bulletmark** [comment]
If you trackpad is not supported we work that out from the log. But we aren't even getting off the ground here. Something very basic is wrong.

**Comment by linusrg1** [comment]
> Nope? I was expecting the output I asked for?
did I forget to give u something?

**Comment by bulletmark** [comment]
Please read back here a litte, to [this comment](https://github.com/bulletmark/libinput-gestures/issues/299#issuecomment-824448115).

**Comment by linusrg1** [comment]
ok

**Comment by linusrg1** [comment]
I have a feeling it is a driver issue. Gnome didnt really like my touchpad kde doesnt mind using it but it can be buggy at times.

**Comment by bulletmark** [comment]
So where is the output I last asked for?

**Comment by linusrg1** [comment]
Sorry Im getting tired didnt read everything properly. 
```libinput-gestures is already running for linus, terminating ..
```

**Comment by bulletmark** [comment]
You still did not paste the command! And that is not all the output.

Anyhow, what you are pasting here is not consistent. That above says it is not running as a service but just above that you paste that `libinput-gestures is currently running as a user service`. Please type:
````
libinput-gestures stop
libinput-gestures autostop
````
Then reboot. Then type:
````
libinput-gestures service
libinput-gestures autostart
libinput-gestures start
libinput gestures-setup status
````

Then paste here **the entire 4 last commands above** with their output. Please take care to type and paste exactly what I am asking for.

**Comment by linusrg1** [comment]
```libinput-gestures-setup service
"no output"
libinput-gestures-setup autostart
Created symlink /home/linus/.config/systemd/user/graphical-session.target.wants/libinput-gestures.service → /usr/lib/systemd/user/libinput-gestures.service.
libinput-gestures enabled as a user service.
libinput-gestures-setup start
libinput-gestures started as a user service.
libinput-gestures-setup status
libinput-gestures is installed.
libinput-gestures is set up as a user service.
libinput-gestures is currently running as a user service.
libinput-gestures is set to autostart as a user service.
libinput-gestures is using default configuration.
journalctl -b --user -u libinput-gestures
-- Journal begins at Fri 2021-04-16 06:32:42 EDT, ends at Thu 2021-04-22 07:17:09 EDT. --
Apr 22 07:15:48 linus-laptop systemd[573]: Started Actions gestures on your touchpad using libinput.
systemctl status --user libinput-gestures
● libinput-gestures.service - Actions gestures on your touchpad using libinput
     Loaded: loaded (/usr/lib/systemd/user/libinput-gestures.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-04-22 07:15:48 EDT; 9min ago
       Docs: https://github.com/bulletmark/libinput-gestures
   Main PID: 1955 (python3)
      Tasks: 3 (limit: 9507)
     Memory: 13.7M
        CPU: 788ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/libinput-gestures.service
             ├─1955 python3 /usr/bin/libinput-gestures
             └─1960 libinput-debug-events --device /dev/input/by-path/platform-i8042-serio-1-event-mouse

Apr 22 07:15:48 linus-laptop systemd[573]: Started Actions gestures on your touchpad using libinput.
```

**Comment by linusrg1** [comment]
Sorry for the inconvenience

**Comment by bulletmark** [comment]
What is "no output"? Where are your prompts? Why not simply paste the full output of the terminal? I get the feeling you are pasting selected parts of your session so I don't have confidence I am seeing everything. I want the full session!

**Comment by linusrg1** [comment]
That is the output of all the commands I only left out my username. And my laptop name. If you need it to see what type of shell I am in it is standard. I am not logged into the terminal as a root user.

**Comment by linusrg1** [comment]
But if you really need all that I can run it again

**Comment by bulletmark** [comment]
My point is that you are editing what you paste here so it means you can accidently leave stuff out and make mistakes. Who cares what your prompt looks like?

Regardless, that output seems to show everything working normally. You have titled this but as "Issues starting libinput". I guess you really mean "libinput-gestures" and I guess that is not a problem anymore? If your issue now is that "Gestures are not working" you need to follow all the steps of the trouble-shoorting section.

**Comment by linusrg1** [comment]
Ok yes thank you so much for helping me get ti up and running. Ill figure out why gestures arent working when I have the time. Btw do gui frontends for libinput-gestures ever mess up the way the config is made causing gestures not to work?

**Comment by bulletmark** [comment]
This is a simple utility with a simple text config file. It does not matter how you create or edit that text file whether with a text editor like I or most do, or with some other tool. If the file is invalidly formatted then `libinput-gestures` will report the error on startup.

I will close this bug as the issue it asked about does not exist anymore (and the title is wrong). If you "have the time" and later work out that your gestures are still not working, then please open another bug but only after carefully performing every step in the trouble-shooting section and then provide the information it asks for.
