### ISSUE TITLE
Pinch gestures rely on finger position.

### ISSUE THREAD

**Issue by mvaraga** [bulletmark/libinput-gestures#3]
Thank you, you have done a great job. I was looking for something like this for plasma 5.

Pinch gestures rely on finger position.
Pinch in/out is correct only for pinch from bottom left corner to top right corner, when I rotated fingers (top-bottom, left-righ or top left corner and botom right corner) it is not detecting correct pinch gesture.

**Comment by bulletmark** [comment]
Can you explain the problem a little more? It works for me no matter which orientation I do the pinch, in or out.

**Comment by mvaraga** [comment]
always detected as pinch out
![touchpad](https://cloud.githubusercontent.com/assets/2885768/11742233/7311a0fa-9ffe-11e5-95ca-33be6aca7e2e.jpg)

**Comment by bulletmark** [comment]
Thanks for the picture. Yep silly bug which is fixed in commit f05c58e255b4a7e73b7c9ba6b3f7199c2cbe822f.

**Comment by bulletmark** [comment]
I improved the pinch threshold a little with commit 348530e115a23d90bfa116ded35a69e538dc0e27.
