### ISSUE TITLE
libinput-gestures crashes constantly

### ISSUE THREAD

**Issue by michaldybczak** [bulletmark/libinput-gestures#30]
I am using Manjaro KDE.
swipe left/right works well
swipe up/down had to be manually set for ctrl+F1 and ctrl+F12 (I have two virtual desktops, there is no next/previous desktop in plasma so native shortcuts don't work)
pinch/stretch doesn't work no matter what, although I was trying to map it to plasma's super+= and super+- (magnifying desktop)

Swiping left/right seems to be least problematic, however other actions crash the service constantly. Sometimes I can make many successful gestures before it crashes, sometimes it crashes after first or second attempt. Basically I suspect that if gesture is not clearly recognized or cannot be used, libinput-gestures crashes and that happens a lot so I have to start service all the time.

Also, custom shortcuts seems to not work, only some general system/desktop shortcuts and even not all of them.

Any idea what's the issue and how can it be prevented? I know that it's meant for gnome but should work with plasma as well after some configuration.

Will be testing this on other (older laptop) to see if it's hardware issue with libinput or just general problem with kde.

**Comment by bulletmark** [comment]
This app is just a simple wrapper around the `libinput-debug-events` utility and if that dies then almost certainly it will report an error. Please type this following and then do heaps of gestures to see the error message. You will just see the raw `libinput-debug-events` messages and no gestures will be actioned.
~~~~
libinput-gestures-setup stop
libinput-gestures -r

**Comment by michaldybczak** [comment]
Hmm... At the beginning I get:

`-event9         DEVICE_ADDED     SynPS/2 Synaptics TouchPad        seat0 default group1 cap:pg       size 102.19/53.79mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on`


Then bunch of info about the position and gestures. From what I observed, most of the time it works but once in a while I got:

```
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.5.0/touchpad_jumping_cursor.html for details
```

and that's probably enough to stop libinput-gestures.

Weird thing is, I got this error frequently at the beginning but later it was actually absent and I couldn't induce it. Yet still after start I have no issues with swipe left/right, but attempting swipe up/down does nothing. Check on status shows as if it was running (but is hanging), trying to do up/down swipes and at some point status shows not-running. While checking -r is ok, no further errors.

**Comment by bulletmark** [comment]
That "kernel bug" error message is harmless. I was seeing that for a while also but it seems to have been fixed in recent updates (either in the kernel or in libinput). Are you using the stock configuration file? If not, please show your configuration here.

**Comment by michaldybczak** [comment]
Original conf works only for browser site swiping, so I created:
~/.config/libinput-gestures.conf
Hashed beginning is copied over from original conf file, then I have:

```
# GNOME SHELL move to next workspace
gesture: swipe up	xdotool key ctrl+F1

# GNOME SHELL move to prev workspace
gesture: swipe down	xdotool key ctrl+F2

# GNOME/Browser go back
gesture: swipe right	xdotool key alt+Left

# GNOME/Browser go forward
gesture: swipe left	xdotool key alt+Right

# GNOME SHELL open/close overview
gesture: pinch in	xdotool key super+=
gesture: pinch out	xdotool key super+-
```

**Comment by bulletmark** [comment]
If you configure a invalid command that fails when run then the utility will print an error message and die. See all error messages since your last reboot with:

    journalctl -b | grep libinput-gestures

E.g. I configured that `super+-` shortcut and it dies reporting that `xdotools` says it is a invalid key sequence.

BTW, GNOME by default runs on Wayland now. Are you running your KDE session ox Xorg, or Wayland?

**Comment by michaldybczak** [comment]
OK, I reverted last lines to 
```
gesture: pinch in   xdotool key super+s
gesture: pinch out  xdotool key super+s
```
Also added 3 fingers to swipe up/down. Now it seems to work without crashes or at least it works longer now. From what I saw after -r is that most up/down swipes are recognized as pinches, w whole bunch of them. Maybe that was overloading the service?

Another thing is: swipe up/down is very unreliable, it seems to be recognized once for a few attempts.

**Comment by michaldybczak** [comment]
No, I'm not running wayland on kde. It's not ready yet for general usage as far I heard. I don't even have enough packages installed to even see the choice of wayland session in sddm, but some wayland components are integrated into plasma already so from what I know, I don't need much to install to run it.

Seems like changing to super+s ended crashes. Now, what shortcut could I utilize to make it work? Hmm...

Thanks.

**Comment by bulletmark** [comment]
The service won't get overloaded because it is band-limited by the rate of messages from libinput and does very little processing per update message. When you ran that `-r` option you would have seen the raw messages that `libinput-debug-events` outputs and thus you may appreciate that the low-level determination of what a SWIPE or PINCH is etc is done directly by `libinput`. This utility here just actions commands based on the gestures that libinput has decided upon.

**Comment by michaldybczak** [comment]
Since desktop magnifying shortcut (super+= and super+-) is not working with gestures I wonder if it can be forced to record firefox and some other apps ctrl+ and ctrl-? I tried that but it didn't work, but maybe I was doing it wrong way (ctrl++)?

**Comment by bulletmark** [comment]
Whatever shortcut you are trying to use just run the xdotool command by hand at the command line to confirm that command works.

**Comment by michaldybczak** [comment]
Ah, thanks. Seems like xdotool limitations play a role here. I tried:
`xdotool key super+=`
and got:
`(symbol) No such key name '='. Ignoring it.`

Now I have a way to test shortcuts before putting them into conf :)

Anyway, I was looking long for multitouch gestures in linux and now I have it, thanks :). It's not perfect since pinch is not working, there is no rotation or possibility to add some other gestures but still, it's still a nice addon :D. Who knows how long we will have to wait for native multigestures support? Thanks for creating that package.

**Comment by michaldybczak** [comment]
One more thing.

I managed to have the zoom out effect with: super+minus
But super+equal doesn't work because when testing I get:
```
xdotool key super+equal
::1                 ff02::2             ip6-localhost
alienware-linux-PC  ip6-allnodes        ip6-loopback
ff02::1             ip6-allrouters      localhost
```
Any idea how to specify command so super+equal would work?

**Comment by bulletmark** [comment]
Sorry, have no idea.

For something else I am working on, and since you are using KDE, would you mind please installing the `wmctrl` package then printing the output of the following command here:

    wmctrl -d

**Comment by michaldybczak** [comment]
Sure, here:
```

0  * DG: 1920x1080  VP: 0,0  WA: 52,0 1868x1080  Pulpit 1
1  - DG: 1920x1080  VP: 0,0  WA: 52,0 1868x1080  Pulpit 2
```
where "pulpit" means "desktop"

**Comment by bulletmark** [comment]
OK, good stuff. I have made a change to add a new `_internal` command to replace `xdotool` for switching desktops. It uses `wmctrl` to list then select the next workspace and works on Wayland and Xorg for GNOME and KDE as you show. It will be the new default in the config.

**Comment by bulletmark** [comment]
It is commit 903f21ad0d9782fc167bd98a9161b1bc11fbf6f8. You can use that default `_internal` command instead of your F1/F2 selections.

**Comment by michaldybczak** [comment]
Great. I added 4 desktops in 2 rows and got:

```
0  * DG: 1920x1080  VP: 0,0  WA: 52,0 1868x1080  Pulpit 1
1  - DG: 1920x1080  VP: 0,0  WA: 52,0 1868x1080  Pulpit 2
2  - DG: 1920x1080  VP: 0,0  WA: 52,0 1868x1080  Pulpit 3
3  - DG: 1920x1080  VP: 0,0  WA: 52,0 1868x1080  Pulpit 4
```

so it seems like rows doesn't matter in that case, although they matter to shortcuts, because there are shortcuts to move into desktop right/left and up/down.

**Comment by michaldybczak** [comment]
How would I use it internal? How command would look like in such case?

**Comment by bulletmark** [comment]
Look at the default configuration file.

**Comment by michaldybczak** [comment]
Ah, yeah. I checked it, adjusted my local conf and it works with 4 desktops in 2 rows well. However the issue is: libinput recognizes the swipe one for 10 times and for 5 times it takes it for a pinch so the effect is not so desirable. But that's libinput work so from your side it all works as intended. Thanks :)

**Comment by bulletmark** [comment]
I just installed KDE on my laptop and my swipes work 100%. I may add some options to the `_internal` command so that people can swipe up/down/left/right if they use row+column workspace arrangements.

**Comment by sarbikbetal** [comment]
> Ah, thanks. Seems like xdotool limitations play a role here. I tried:
> `xdotool key super+=`
> and got:
> `(symbol) No such key name '='. Ignoring it.`
> 
> Now I have a way to test shortcuts before putting them into conf :)
> 
> Anyway, I was looking long for multitouch gestures in linux and now I have it, thanks :). It's not perfect since pinch is not working, there is no rotation or possibility to add some other gestures but still, it's still a nice addon :D. Who knows how long we will have to wait for native multigestures support? Thanks for creating that package.

Try this :
gesture pinch in	xdotool key control+minus
gesture pinch out	xdotool key control+plus
