### ISSUE TITLE
This app doesn't want to uninstall and I read the readme and followed all steps.

### ISSUE THREAD

**Issue by Dejee98** [bulletmark/libinput-gestures#301]
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README.

```
Run libinput-gestures -l on the command line and paste the output here.
```

**Describe the issue**
A clear and concise description of what the issue is.

**Comment by Dejee98** [comment]
I have tried including the libinput-gestures -l but it says command not found but when I press the app icon the app runs.

**Comment by bulletmark** [comment]
How did you uninstall this app? Did you follow the instructions in the README?

Please type `ls -l /usr/bin/libinput-gestures*` and show the output here.

**Comment by Dejee98** [comment]
The output is, "No such file or directory". I read all the instructions in the readme and followed them.

**Comment by Dejee98** [comment]
ls -l /usr/bin/libinput-gestures
ls: cannot access '/usr/bin/libinput-gestures': No such file or directory

**Comment by bulletmark** [comment]
Please answer all the questions I asked.

**Comment by Dejee98** [comment]
I installed it from the core repo. To uninstall it I used the exact commands from the readme, 'libinput-gestures-setup stop
libinput-gestures-setup autostop
sudo libinput-gestures-setup uninstall
'. No it is not giving me an error, I try to uninstall using your steps and I still have the icon and when I open the app it shows me the interface and all.

**Comment by bulletmark** [comment]
What is the "core" repo? You should state what Linux distro you are using. Why the heck would you install this app via your distro's package tool and then uninstall it another way? If you install it using your system package tool then uninstall it via that same tool.

What is the exact package command you used to install this? Or if you used a point and click GUI package tool, which one?

Also, I ask a question quickly back to you then you take 2 days to give a half answer. At this rate it will take a month of back and forth. Please try and respond more promptly.
