### ISSUE TITLE
Multi-device support

### ISSUE THREAD

**Issue by FherStk** [bulletmark/libinput-gestures#302]
I was using gestures with no issue over an Ubuntu 20.04 LTS and a Lenovo laptop with an integrated touchpad but, when I plugged in (just for fun) an external touchpad, gestures was still working but just for the integrated one. I opened gestures config and the behaviour was swapped: suddenly the external touchpad started working with my defined gestures but the integrated one stopped.

It could be nice to setup the same config along all devices, or be able to define different configs per device. I asked on the gestures repo (https://gitlab.com/cunidev/gestures/-/issues/34#note_542997502) but they redirected me here.

Thanks a lot in advance!

**Comment by bulletmark** [comment]
As asked for all new issues, please paste here the output of `libinput-gestures -l`.

Also, what do you mean by "I opened gestures config"?

**Comment by bulletmark** [comment]
No response from @FherStk so closing ..

**Comment by FherStk** [comment]
Sorry, I wrote the first issue in hurry and I forgot completely about answering your last message. I'm a bit overloaded of work right now, but I will try to rewrite a new post with more detail including all you need as soon as I can.

Sorry and thanks for your time and effort.
