### ISSUE TITLE
Under Wayland, 4 fingers up are seen as 3 fingers up. Unders Xorg it worked.

### ISSUE THREAD

**Issue by All3xJ** [bulletmark/libinput-gestures#303]
Here's are my infos: (the .sh files are bash script that allows me to do repeat gestures. for example if I do 3 fingers up and then do 3 fingers down, it just evoke "Escape" key to exit, and it doesn't do the the action that I set for 3 fingers down)
```
$ libinput-gestures -l
libinput-gestures: session KDE+wayland on Linux-5.10.38-1-lts-x86_64-with-glibc2.33, python 3.9.5, libinput 1.17.2
Hash: 63c9c2e7aa76f826431104886222c993
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       3 qdbus org.kde.KWin /KWin org.kde.KWin.nextDesktop
swipe right      3 qdbus org.kde.KWin /KWin org.kde.KWin.previousDesktop
swipe up         3 /home/allexj/Desktop/showWinFix.sh
swipe down       3 /home/allexj/Desktop/showDeskFix.sh
swipe up         4 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut ShowDesktopGrid
swipe down       4 ydotool key ESC
pinch in         4 /home/allexj/Desktop/showDashbFix.sh
pinch out        4 /home/allexj/Desktop/showDashbFix.sh
libinput-gestures: device /dev/input/by-path/platform-AMDI0010:01-event-mouse(event9): 06CBCDC2:00 06CB:CDE9 Touchpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a desktop application.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration.
```

**Describe the issue**
If I try to use 4 fingers up gesture, I can't.
If I comment all the lines of my libinput-gestures.conf file and I only leave the 3 fingers up gesture and the restart libinput-gestures, I am able to use it by using 4 fingers up.
All this is when using Wayland. In xorg it was running flawless.

**Comment by bulletmark** [comment]
Please follow the trouble-shooting section. In particular, do steps 5 and 6 with for various 3 and 4 finger swipe gestures. Step 5 will show you how many fingers `libinput-gestures` is interpreting for each gesture and step 6 will show you the raw messages from `libinput` with the finger count.

**Comment by All3xJ** [comment]
> Please follow the trouble-shooting section. In particular, do steps 5 and 6 with for various 3 and 4 finger swipe gestures. Step 5 will show you how many fingers `libinput-gestures` is interpreting for each gesture and step 6 will show you the raw messages from `libinput` with the finger count.

thanks for answer. it looks like libinput-gestures is correctly interpreting 4 fingers up and 3 fingers up.

I noticed that if I remove ALL the gestures from ~/.config/libinput-gestures.conf and I restart libinput-gestures and I do the 4 swipe up gesture, it performs the action..... How is it possible if I removed all the gestures?
I don't have /etc/libinput-gestures.conf file so I don't know how can it be possible.....

**Comment by bulletmark** [comment]
It's pretty easy to completely turn `libinput-gestures` off, i.e. type `libinput-gestures-setup stop` and then prove it is not involved. I don't use or know much about KDE, perhaps it is actioning those?

**Comment by All3xJ** [comment]
> It's pretty easy to completely turn `libinput-gestures` off, i.e. type `libinput-gestures-setup stop` and then prove it is not involved. I don't use or know much about KDE, perhaps it is actioning those?

If I stop libinput-gestures and I do 4 fingers up, I have the action activated... a real mistery... I don't think that kde uses gestures by default.

**Comment by bulletmark** [comment]
So it seems there is no problem with `libinput-gestures`. Do you agree to close this bug?

**Comment by All3xJ** [comment]
> So it seems there is no problem with `libinput-gestures`. Do you agree to close this bug?

yeah, thanks for the help and the amazing work with libinput-gestures :)
