### ISSUE TITLE
libinput-gestures failed to start as a desktop application.

### ISSUE THREAD

**Issue by Anonymous7code** [bulletmark/libinput-gestures#306]
The issue is it executes autostart but on doing start it throws the error
```libinput-gestures failed to start as a desktop application.```

**Comment by bulletmark** [comment]
Please follow the instruction in the trouble shooting opening paragraph.

**Comment by bulletmark** [comment]
@Anonymous7code please provide the information requested.

**Comment by muh-hassani** [comment]
@Anonymous7code,  I had similar issue. I returned back to the readme. I had missed a step. I had forgotten to reboot after `sudo gpasswd -a $USER input`. I hope this also fix your issue.

**Comment by Anonymous7code** [comment]
My system crashed thrice after trouble shooting so I reinstalled linux and now it's working fine.

**Comment by bulletmark** [comment]
So please close this bug if you have no issue now.
