### ISSUE TITLE
Holding key while swiping

### ISSUE THREAD

**Issue by ReaderGuy42** [bulletmark/libinput-gestures#307]
```
libinput-gestures: session cinnamon+x11 on Linux-5.4.0-73-generic-x86_64-with-glibc2.29, python 3.8.5, libinput 1.15.5
Hash: 7b225afc6809da81d306436673af8a29
Gestures configured in ~/.config/libinput-gestures.conf:
swipe right      4 _internal ws_down -w
swipe left       4 _internal ws_up -w
swipe down       4 xdotool key Ctrl+alt+Down
swipe up         4 xdotool key Ctrl+alt+Up
swipe left       3 xdotool key Ctrl+super+Left
swipe right      3 xdotool key Ctrl+super+Right
swipe up         3 xdotool key Shift+Ctrl+Up
swipe down       3 xdotool key Shift+Ctrl+Alt+Up
swipe right        xdotool key alt+Left
pinch in         2 xdotool key Ctrl+minus
pinch out        2 xdotool key Ctrl+plus
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.0-platform-i2c_designware.0-event-mouse(event7): ELAN0501:00 04F3:3060 Touchpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a desktop application.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration file.

```

**Describe the issue**
I have four-finger swipe right/left set to switch to the next workspace, i.e. a key press of Ctrl+Alt+Right/Left.

Now according to the system hotkey list, if I add the shift button, I should be able to move the active window to the next workspace. When I do this with the actual keys, that's fine. If I hold shift and swipe it just goes to the next workspace.

Am I missing something? I feel like adding the shift button should do the same thing, since the swipe should really be just acting like that key combo, right?

I have all of about three days of experience of Linux in general and Mint as well, so any help is appreciated :) Thanks!

**Comment by bulletmark** [comment]
Adding the shift key manually to "augment" your configured `xdotool` keys is not something I have thought of previously but I just tried it and it works fine for me.

The first thing you should do is to fix your configuration! E.g you have `swipe right` configured 3 times. Swipes can be either 3 fingers, or 4 fingers, or either 3 or 4 fingers if you do not specify a finger count. So if you specify both 3 and 4 finger gestures for `swipe right` then the other one is ignored but it seems to me that you don't actually want the `_internal` actions configured?

After fixing that, do step 5 of the trouble-shooting section just to confirm to yourself which gestures +  actions are being selected. Try them all. Once you understand that, then run `libinput-gestures` as normal and try with the shift key. Make sure you configure the `xdotool` keys *exactly* as what you find works when you run them manually.

**Comment by ReaderGuy42** [comment]
Jeez! You're right! Thank you :) The third swipe was something I'd accidentally left, though I hadn't had any issues with that, I've `commented` that now. The other thing was the issue. I copied the _internal_ thing from the wiki I think, and it worked, but now I've replaced it with the `xdotool` keys and now the shift thing works too. 
Thanks for your help!!

**Comment by trinib** [comment]
how to hold down when switching between apps .. alt + tab ????

**Comment by ReaderGuy42** [comment]
> how to hold down when switching between apps .. alt + tab ????

I'm not sure I understand your question?

**Comment by trinib** [comment]
> > how to hold down when switching between apps .. alt + tab ????
> 
> I'm not sure I understand your question?

sorry never mind ..Figured it out
