### ISSUE TITLE
support several devices at the same time

### ISSUE THREAD

**Issue by squalou** [bulletmark/libinput-gestures#311]
```
libinput-gestures: session xfce+x11 on Linux-5.10.41-1-lts-x86_64-with-glibc2.33, python 3.9.6, libinput 1.18.0
Hash: 7b225afc6809da81d306436673af8a29
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         4 _internal ws_up
swipe down       4 _internal ws_down
swipe right      4 xdotool key alt+Right
swipe left       4 xdotool key alt+Left
swipe up         3 xfdashboard -t
libinput-gestures: device /dev/input/event20: apple trackpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is not currently running.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration file.
```

**Describe the issue**

it may seem weird, BUT here's my situation.
I use a laptop (which comes with its own trackpad, managed by libinput /dev/input/event10).
I also have a bluetooth "apple magic trackpad", which works better for me (fighting with hand and wrist pain). 

But sometimes, batteries will fail, or I'll be on the move without the magic trackpad, so I have to rely on the native laptop one

It would be really nice to be able to use gestures on both trackpads at the same time.

**Comment by bulletmark** [comment]
There is a comment in the `libinput-gestures.conf` about how to do this. Try it and let me know here how you go.

**Comment by squalou** [comment]
`device all`
works just fine, thank you !

My bad : I did also install "gestures" minimal GUI, which at first run completely wipes comments in configuration file. I didn't think about checking the original file.
