### ISSUE TITLE
xdotool stopped to work under Wayland

### ISSUE THREAD

**Issue by mario-tux** [bulletmark/libinput-gestures#312]
```
libinput-gestures: session gnome+wayland on Linux-5.13.13-arch1-1-x86_64-with-glibc2.33, python 3.9.6, libinput 1.18.1
Hash: 7b225afc6809da81d306436673af8a29
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       4 xdotool key control+shift+Tab
swipe right      4 xdotool key control+Tab
swipe up         4 xdotool key alt+Left
swipe down       4 xdotool key alt+Right
pinch in         4 xdotool key control+w
pinch out        4 xdotool key control+shift+t
device all
libinput-gestures: monitoring all devices
libinput-gestures is installed.
libinput-gestures is set up as a user service.
libinput-gestures is not currently running.
libinput-gestures is set to autostart as a user service.
libinput-gestures is using custom configuration file.
```

**Describe the issue**
I use libinput-gestures in Gnome with Wayland to switch tab and history on Google Chrome (XWayland) by means of xdotool. Since the update to xdotool 3.20210804.2, libinput-gestures stopped to have effect the xdotool doesn't work any more under Wayland:
```
The X server at :0 appears to be XWayland. Unfortunately, XWayland does not correctly support the features used by libxdo and xdotool.
Failed creating new xdo instance.
```

If there is no workaround the README should be updated. Any alternative way to make actions like above in Chrome?

**Comment by bulletmark** [comment]
FYI, xdotool stopped working on Arch a month ago. I raised an issue about it [here](https://github.com/jordansissel/xdotool/issues/346). You can either install the previous version, or get the current sources and delete the offending line.

**Comment by bulletmark** [comment]
Do `yay -S xdotool-xwayland` to work around this.

**Comment by bulletmark** [comment]
Note xdotool release [v3.20210903.1](https://github.com/jordansissel/xdotool/releases/tag/v3.20210903.1) on 2021-Sep-04 fixed this issue 3 weeks ago. xdotool [3.20210903.1-1](https://github.com/archlinux/svntogit-community/commit/65f0ac7eef22a8c1ab1f95e879a5d86ecf89fe9a#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a) on Arch was released the same day and the package xdotool-xwayland was deleted from the AUR.
