### ISSUE TITLE
Can I swipe with 1 finger only:

### ISSUE THREAD

**Issue by iacchus** [bulletmark/libinput-gestures#314]
I would like to reserve my touchpad for gestures only. Is it possibleto swipe with only 1 finger, 1 touch (actually I can do it two touches, like clicking-and-dragging,) but I am trying to use only touching the touchpad once.

**Comment by bulletmark** [comment]
No, read what a libinput gesture is: https://wayland.freedesktop.org/libinput/doc/latest/gestures.html

**Comment by iacchus** [comment]
This is why I don't use libinput on my Arch..
