### ISSUE TITLE
FR: allow multiple layers of libinput-gestures

### ISSUE THREAD

**Issue by mefromthepast** [bulletmark/libinput-gestures#316]
I suggest that multiple layers of libinput-gestures can be used and should be accessible via configurable modifier keys (e.g. CTRL, ALT, META, Shift, F13, ESC, ...). When the modifier key corresponding to the layer is pressed, commands from this layer are executed and not those from the `base layer`.

This would allow for example to have a browser mode where libinput-gestures offers different functionality, without having to encode a more or less complex script in the command which determines whether the window focused may be a browser or not and change its functionality this way.

**Comment by bulletmark** [comment]
I have always said I want to keep this utility simple and this change violates that plan. Feel free to fork this repo and implement it although I think a better approach would be to write a generic utility which libinput-gestures would activate on any gesture and that utility (with it's own configuration file) implements the mapping you are suggesting. That's a neat little project for anybody that is interested.
