### ISSUE TITLE
Keep getting this warning in journald libinput-gestures.desktop[2334]: Unknown gesture received: HOLD.

### ISSUE THREAD

**Issue by Hikandy** [bulletmark/libinput-gestures#318]
The gesturess are working fine, using gnome 41 wayland on archlinux, this keeps getting logged 

    libinput-gestures.desktop[2334]: Unknown gesture received: HOLD.

Run libinput-gestures -l on the command line and paste the output here.

    libinput-gestures: session gnome+wayland on Linux-5.14.7-arch1-1-x86_64-with-glibc2.33, python 3.9.7, libinput 1.19.0
    Hash: 7b225afc6809da81d306436673af8a29
    Gestures configured in ~/.config/libinput-gestures.conf:
    swipe left       4 ydotool key ctrl+KEY_PAGEDOWN
    swipe right      4 ydotool key ctrl+KEY_PAGEUP
    libinput-gestures: device /dev/input/by-path/platform-AMDI0010:03-event-mouse(event10): ASUE140A:00 04F3:3134 Touchpad
    libinput-gestures is installed.
    libinput-gestures is set up as a desktop application.
    libinput-gestures is currently running as a desktop application.
    libinput-gestures is set to autostart as a desktop application.
    libinput-gestures is using custom configuration file.

libinput-gestures.desktop[2334]: Unknown gesture received: HOLD, thiis keeps getting logged in my journald and not sure what is causing it?

**Comment by bulletmark** [comment]
Please follow the steps in the TROUBLESHOOTING section. Note particularly step 8. So run your ydotool commands manually in  a terminal and I suspect your will see the same messages.

**Comment by bulletmark** [comment]
No response from OP so closing.

**Comment by xarthna** [comment]
Looks like `libinput` released [hold gestures ](https://www.phoronix.com/scan.php?page=news_item&px=libinput-1.19) as part of the 1.19 release on Sept 14. I have seen this issue in the journal as well. I believe what is happening is that [this hold event](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#hold-gestures) added in the latest release is firing but it is not being handled being handled by `libinput-gestures`.

**Comment by bulletmark** [comment]
@xarthna yes you are right! Had not seen that. I just added [HOLD gestures](https://github.com/bulletmark/libinput-gestures#hold-gestures) and made a new [release 2.69](https://github.com/bulletmark/libinput-gestures/releases/tag/2.69).
