### ISSUE TITLE
Specify list of devices to monitor

### ISSUE THREAD

**Issue by Fandekasp** [bulletmark/libinput-gestures#32]
Thanks for this product, very useful.

When running verbose, I can read:
```
$ libinput-gestures -v
libinput-gestures: monitoring device /dev/input/event15 for 10 gestures
```

Would it be possible to specify a list of devices to monitor ? My touchscreen is /dev/input/event11, and I'd love to be able to use these gestures on both touchpad and touchscreen (even better, being able to attach gestures to devices).

**Comment by bulletmark** [comment]
It is certainly not possible with the current code but is not a bad suggestion and is something that could probably be implemented. My main problem is that I don't have a touchscreen although I may be able to develop it on a branch and have you test it for me?

Can you please paste the output of `libinput-list-devices` here for your laptop:

**Comment by Fandekasp** [comment]
I'd be very pleased to test it for you, thank you for considering it!

Here you go:
[devices.txt](https://github.com/bulletmark/libinput-gestures/files/599243/devices.txt)

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Thu, 2016-11-17 at 18:59 -0800, Adrien Lemaire wrote:
> Would it be possible to specify a list of devices to monitor ? My touchscreen
> is /dev/input/event11, and I'd love to be able to use these gestures on both
> touchpad and touchscreen (even better, being able to attach gestures to
> devices).

I'm not sure if I understand it correct, but isn't some of the desktop
environment supporting it natively ?

I'm here on a touch screen device, and run GNOME perfect. Oh. Wait. AFAIK, it is
only GNOME that does touch screen.

Hmmm... if so, yes, it'd be cool to have.

- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEQCVDstmIVAB/Yn02pjpYo/LhdWkFAlgvUfcACgkQpjpYo/Lh
dWm1tg/5ARqg4CHt/OCEeR1GMiOjAi2NkuPIPqI078t8J5b0BDSswd3vyElJro13
pLmPZUBdJPyNUPC5Tb5NOfe8hMPHGuI+ynsHKKmxayee4AM3IHkbbxm4mWdwfHvF
F515zBRL5+k1bf/TFL5nKDaw8iW/iSK1VThsUxKnE6GDoIx27Xji1NWqhYjomFcQ
FjzQaI8HG1qDe216t/STz/RpvpcCftQyFB6LXjJTiLB0RGM1XiUCZYJTvfA/6Upi
Q1H2Dm8ta+fsjwbHMgybpsSWBshtqQXTcKgv0z9a1r03AJNKX+OK+8LSJxkjHUsO
K6h2KtF3LrjGvtWeqTyYvGJI+i+BdNrcENfHF98YkJuqjgecoEPeurkLKGbTQX1C
2VeZ9Myzezxwmao47M8RZ4fkj8VTPgGfxGVoAiL3TBxaN6n1rTRFzxJuLrcvJ+z/
KZsGMVtWjGNGnT9WvHjDH4lW7MaAlPMOQT5mPAOkZzNib5dNZm/oGs8OxTLF6Ivx
wdCGsSmqBC0CqPjgfZQ5lVHvc44CoeuwUeA+A37mei+G7SEOXMEVRP4IAXeyiIWH
tTAFKlHah+6reReuLo3XwesXyC+HHUP5DUY6BSD1niAt5iCjETmT9PMQ+QZ/ktBL
+zteq5zq5oDumjY3ZkNFnucl/C1f+Ga4+H/c0Biy9+sN+hO0c58=
=QOdz
-----END PGP SIGNATURE-----

**Comment by bulletmark** [comment]
@Fandekasp can you also please attach the output of `libinput-debug-events --device /dev/input/event16` here? Run that command and do a heap of 3, 4, 5 finger swipe up, down, left, right and multi-finger pinch in, out gestures while capturing the output. Note that the device name can change between reboots so you may need to do another `libinput-list-devices` to work out the current name for your touch-screen.

**Comment by bulletmark** [comment]
@Fandekasp I just pushed changes to the dev branch which I'd like you to try. Just configure some `gesture_screen` lines in your conf file to try out.

**Comment by Fandekasp** [comment]
[events.txt](https://github.com/bulletmark/libinput-gestures/files/601335/events.txt)

heap of 3, 4, 5 finger swipe left, up, right, down, pinch in and pinch out.

**Comment by Fandekasp** [comment]
Running dev.

```
$ libinput-gestures -v 
libinput-gestures: monitoring touchscreen device /dev/input/event16 for 4 gestures
libinput-gestures: monitoring touchpad device /dev/input/event15 for 10 gestures
```

with libinput-gestures.conf
```
...
gesture: swipe left 3 i3-msg "move container to workspace prev"
gesture: swipe right 3 i3-msg "move container to workspace next"
gesture: swipe left 4 i3-msg "workspace prev"
gesture: swipe right 4 i3-msg "workspace next"
gesture_screen: swipe left 3 i3-msg "move container to workspace prev"
gesture_screen: swipe right 3 i3-msg "move container to workspace next"
gesture_screen: swipe left 4 i3-msg "workspace prev"
gesture_screen: swipe right 4 i3-msg "workspace next"
```

But touchscreen actions aren't working unfortunately.  I suppose it's related to the heap log above not properly recording the swipe direction (touch_motion instead of touch_right ... ) ?

**Comment by bulletmark** [comment]
Yipes, the raw messages are completely different to a touchpad! There are not even any GESTURE events. Obviously my code is assuming the exact same messages so it certainly is not going to work. To be honest, it would be just too hard to develop the code without a touchscreen so I will just leave this on the back-burner until I have access to one.

**Comment by bulletmark** [comment]
Closing since this libinput gestures are not relevant to a touchscreen. Also, since commit c683ec1c980741103e88b87ab0f8e7d682108145 we have the ability to name the touchpad device to use or use "all".
