### ISSUE TITLE
How to enable alt+tab using three finger swipe right like in Windows 10?

### ISSUE THREAD

**Issue by lakshits11** [bulletmark/libinput-gestures#320]
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README.

```
Run libinput-gestures -l on the command line and paste the output here.
```

**Describe the issue**
How to bring up the applications menu (when we press alt+tab it brings us the window menu and we can toggle through different applications by pressing tab appropriate number of times (while holding down alt key)) .

I used gestures app. And I did
`xinput key alt+Tab` and selected options Swipe right, three fingers.

But it only press alt+Tab once. So how can I get the appropriate behaviour as in Windows ?

Please help.

**Comment by bulletmark** [comment]
Sorry this is not an appropriate place to ask for such advice. You have an audience of 1 here (me, and I don't use Windows) but thousands if you post on a forum/discord/irc/etc.
