### ISSUE TITLE
Rethinking Gestures Suggestion

### ISSUE THREAD

**Issue by jujuscream** [bulletmark/libinput-gestures#321]
Right now my config file has this in it:
```
gesture swipe up	3 pactl set-sink-volume @DEFAULT_SINK@ +1%
gesture swipe down	3 pactl set-sink-volume @DEFAULT_SINK@ -1% 
```

Just bumps the volume up or down 1% with the touchpad, right?

The problem is that when I do it, it only bumps the volume up once and then I have to lift my fingers off the touchpad and lay them down again to bump the volume up another 1%! Too tedious.

What if I want it to keep bumping the volume up 1%, until I stop doing the gesture. To explain this more, if I want to turn the volume up or down (say from 13 to 35 for example, random numbers) without my fingers leaving the touchpad, I can. And I can turn the volume up do that in one quick swipe up with my Three Fingers Gesture.

Furthermore, what if the rate at which the volume went up or down was adaptive to the **speed** of your gesture? What if when I swiped up with three fingers **slowly** the volume only went up 1%, but when I **quickly** swiped with three fingers the volume went up 5%?

Anyways, they're simple ideas. Maybe I just don't have it setup correctly and you've already thought of these things. I just thought I'd post this real quick and get on to my work. Talk to ya soon.

Roberts

**Comment by solarfl4re** [comment]
If you clone @MidnightNerd's code here (https://github.com/bulletmark/libinput-gestures/pull/296), what you are describing works - as you swipe, the volume continues to go up or down.
