### ISSUE TITLE
libinput-gestures failed to start as a desktop application or a system service

### ISSUE THREAD

**Issue by networkdeliverables** [bulletmark/libinput-gestures#323]
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README.

```
libinput-gestures: session ubuntu+x11 on Linux-5.13.0-1017-oem-x86_64-with-glibc2.29, python 3.8.10, libinput 1.15.5
Hash: 7fdb535fddc8a8f2306c17ccf295e6b9
Gestures configured in /etc/libinput-gestures.conf:
swipe up           _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event11): DELL0A36:00 06CB:CE65 Touchpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a user service.
libinput-gestures is not set to autostart.
libinput-gestures is using default configuration file.
```
Some additional details
```
$ uname -srvp
Linux 5.13.0-1017-oem #21-Ubuntu SMP Tue Oct 12 09:32:36 UTC 2021 x86_64
$ cat /etc/group | grep input
input:x:107:networkdeliverables
$ dpkg --list | grep 'xdotool\|wmctrl\|libinput-tools' | awk '{print $2,$3}'
libinput-tools 1.15.5-1ubuntu0.2
wmctrl 1.07-7build1
xdotool 1:3.20160805.1-4
```
**Describe the issue**
Unable to use the tool as the application never runs. I've gone through set up and troubleshooting with a complete uninstall twice (including subsequent reboots) but having no luck. Fails to run as a desktop or a system service. What am I missing here?
```
$ libinput-gestures-setup stop autostop service start
libinput-gestures failed to start as a user service.
$ libinput-gestures-setup stop autostop desktop start
libinput-gestures failed to start as a desktop application.
```
Great project, really excited to use it, but am just having no luck

**Comment by bulletmark** [comment]
Please paste output of `ls -l /tmp/libinput-gestures-*`.

**Comment by bulletmark** [comment]
So you are saying it is now working fine?

**Comment by networkdeliverables** [comment]
No, I still can't run the service. Every issue of 'start' returns a simply failure of "libinput-gestures failed to start as a user service."

**Comment by bulletmark** [comment]
@margual56 you are describing a different issue to what is discussed here. You are saying that libinput-gestures is failing to start as a desktop application. Please raise a new issue and copy your info there.

**Comment by bulletmark** [comment]
Note that the OP here eventually decided that he didn't have a problem so we got nowhere with this issue. It has been closed and there is no useful info here. @margual56 so I still think you should raise a new issue if you really think you have a problem.

**Comment by ddrtwo** [comment]
I had the same issue. I installed libinput-tools (not installed by default on opensuse)
And it worked fine ;-)
