### ISSUE TITLE
libinput-gestures suddenly doesn't start, gives some sort of deprecation warning

### ISSUE THREAD

**Issue by CIAMagnet** [bulletmark/libinput-gestures#325]
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README. 

Run libinput-gestures -l on the command line and paste the output here.

```
/usr/bin/libinput-gestures:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion as Version
libinput-gestures: session gnome+x11 on Linux-5.14.17-301.fc35.x86_64-x86_64-with-glibc2.34, python 3.10.0, libinput 1.19.2
Hash: 7fdb535fddc8a8f2306c17ccf295e6b9
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key super
swipe down       3 xdotool key super+m
swipe right      3 _internal ws_down
swipe left       3 _internal ws_up
libinput-gestures: device /dev/input/by-path/pci-0000:00:1d.0-usb-0:1.2:1.1-event-mouse(event2): Apple Inc. Magic Trackpad 2
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is not currently running.
libinput-gestures is not set to autostart.
libinput-gestures is using custom configuration file.

```
**Describe the issue**
A clear and concise description of what the issue is.
I have a custom config file that I've been using successfully for quite a while now, so I'm sure this isn't an invalid configuration issue. Neither `libinput-gestures-setup start` nor `libinput-gestures` successfully start, and if I try the `libinput-gestures` command multiple times it will tell me that the process is already running, however looking at top tells me that it's not. The only thing I've done recently that might cause any changes was that I upgraded to Fedora 35. When I first noticed that it stopped working, I pulled the latest version from git and installed it. I also tried uninstalling and reinstalling, but the problem persists. Any help would be appreciated.
EDIT: For the sake of thoroughness, I also tried running it in both desktop and service mode. Neither work.

Even though I doubt this is a config issue, I'm including my config file:
```
# Generated by Gestures 0.2.3  -->  https://gitlab.com/cunidev/gestures
# Manual editing might result in data loss!


# Invalid lines


# Unsupported lines

# Swipe threshold (0-100)
swipe_threshold 0

# Gestures
gesture swipe up 3 xdotool key super
gesture swipe down 3 xdotool key super+m
gesture swipe right 3 _internal ws_down
gesture swipe left 3 _internal ws_up

**Comment by bulletmark** [comment]
Please type the following and paste the commands + output here:
```
libinput-gestures-setup stop
libinput-gestures -d
````

**Comment by CIAMagnet** [comment]
Did a system update, and restarted. That somehow fixed it. I have no idea why. I'll comment here again if it does it again.

**Comment by bulletmark** [comment]
The depreciation warning is irrelevant here, but I have removed that anyhow with new [release 2.70](https://github.com/bulletmark/libinput-gestures/releases/tag/2.70).

**Comment by bulletmark** [comment]
BTW, that cunidev/gestures UI supports less than half of the gestures provided by libinput-gestures so I don't understand why anybody would use it? The config file is just simple text.
