### ISSUE TITLE
Fedora 35 KDE libinput-gestures failed to start as a desktop application.

### ISSUE THREAD

**Issue by illeatmyhat** [bulletmark/libinput-gestures#327]
In a more-or-less fresh install, simply following the instructions will lead to 
```
libinput-gestures failed to start as a desktop application.
```

It turns out that this is because the `packaging` python package is not installed.
To solve,
```bash
sudo dnf install python3-pip
pip install packaging
```

and then `libinput-gestures-setup start` should work correctly

**Comment by bulletmark** [comment]
Actually, the 2nd line in the installation section did say you have to install the `packaging` library.

However, I have realised that I can rework the code to avoid the need that library so I have [removed it](https://github.com/bulletmark/libinput-gestures/commit/f99ed6a3c96edb687ba2ee4fb58d29778ca0db89) and released version 2.72.
