### ISSUE TITLE
Suggestion: More composite swipe gestures

### ISSUE THREAD

**Issue by nclarius** [bulletmark/libinput-gestures#328]
I would appreciate if there was a wider selection of multiple-step swipe gestures, e.g. 'first vertical then horizontal' motions distinct from the 'first horizontal then vertical' ones (e.g. up_left separately from left_up), or gestures composed of three steps such as left_down_right.

**Comment by bulletmark** [comment]
Have you tried the extended gestures? They don't work how I suspect you think they work. There is no "first vertical then horizontal" motion. The current implementation just looks at the start and final position to decide which of the 8 swipe directions occurred (all 45 degrees apart). So "left_up" is the same as "up_left". i.e. a swipe in the north-west direction.

I also suspect that having more than these 8 distinct swipe motions would be too awkward for users. In fact, most users just configure the 4 "classic" up/down and left/right swipe gestures and I have never had any feedback about the 4 extended (45 degree) gestures so I guess people just don't use them. [Although I actually use all 8 gestures myself and think they work well and are extremely useful].

**Comment by nclarius** [comment]
Yes, making the order of horizontal and vertical movements distinct is what I'm suggesting.  

I'll leave it here as the first pro vote then.

**Comment by bulletmark** [comment]
You are not clear on what you are asking. There are currently 8 swipe gestures which are all based on a straight line swipe: Up/Down, Left/Right, NorthEast/SouthWest, and NorthWest/SouthEast. So please clarify that you are asking for another 4 swipes extra to these which are an arc of the last 4? If so, then you should be consistent and also ask for the 4 which are an arc of the first 4? So there are currently 8 swipes but you want 16?

**Comment by nclarius** [comment]
Sorry, I don't understand what you mean by "an arc".

Currently there are

up
down
left
right
up left = left up
up right = right up
down left = left down
down right = right down

What I had in mind was making the equal pairs non-equal, so that there are 4 more.  

And while already at it I guess it would also make good sense to add

up down
down up
left right
right left

if that's what you mean.

**Comment by bulletmark** [comment]
Your fingers can not move in a perfect right angle so when they travel from A to B then the software has to decide whether your fingers get there via an approximate straight line, or an approximate curve/arc on one side of that line, or a curve/arc on the other side of that line. Actually, there are 16 extra possibilities (because there are 2 arcs per the existing 8 line gestures). Please draw the options out on a piece of paper to understand what I am getting at.

I think 8 gestures are plenty. Adding another 16 is too complicated for users.

**Comment by nclarius** [comment]
Ok, I get what you mean by the number of arcs now.

I really don't see the "too complicated" part; no one will have to use all 16, and from my user perspective, left_up and up_left as two distinct motions would if anything be *easier* to grasp than the fact that left_up = up_left.

But I do understand if there are limitations given by the precision of recognition.

**Comment by bulletmark** [comment]
I still don't understand what you are suggesting? Swipe `left_up` is currently a straight line. Are you suggesting to change that name to mean an arc? What name would be used for the original straight line gesture? Or are you saying to keep `left_up` the existing straight line and introduce a new `up_left` but it would be an arc? If so, which arc, the top one or the bottom one?

The only way we could add 16 new gestures is to add 16 new names.

**Comment by nclarius** [comment]
I am suggesting to replace the diagonal straight line gestures by pairs of arcs, i.e. keep the name `left_up`, change its meaning to a bottom arc, add the name `up_left`, make its meaning a top arc, and analogous for the other three diagonal gestures. That would be minus 4 (straight) plus 8 (arc) center-to-corner gestures. And perhaps the additional 4 center-to-north/east/south/west-and-back-to-center ones.

**Comment by bulletmark** [comment]
I can't change the name of an existing gesture which users have already been using for years. So I would have to create 16 new ones.

I think 8 gestures is enough. 16 new gestures would be too confusing.
