### ISSUE TITLE
Swipe back/forward not working

### ISSUE THREAD

**Issue by dereke** [bulletmark/libinput-gestures#33]
I am using fedora 23 (gnome) and have installed the latest code from git.
I can swipe between workspaces which is great but I'm not able to swipe back/forward in chrome/firefox.
It seems like this should work (using the default conf). Is there anything I can do to figure why it is not working?

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Fri, 2016-11-18 at 03:21 -0800, Derek Ekins wrote:
> I am using fedora 23 (gnome) and have installed the latest code from git.
> I can swipe between workspaces which is great but I'm not able to swipe
> back/forward in chrome/firefox.
> It seems like this should work (using the default conf). Is there anything I
> can do to figure why it is not working?

It works perfectly fine for me. What command have you mapped to the swipe
gesture ? Does it work when you execute the command manually ?


- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEQCVDstmIVAB/Yn02pjpYo/LhdWkFAlgvBdkACgkQpjpYo/Lh
dWmMtxAAoqc38jU5zvtdQ10ZZ/KAKsZ56gnwCbYctA91BXwdd7z8zbWuB7hKp721
zCcnfCocSOJJsvfbax85WHQ6gGOHSWh/DeTSCpz4fnaf8Jq/PrGrzfROtlrmuZbF
S9Td9okIhtswdRHKCnxl4odis5d3VpiLx9A2BFw6brqkuXhHdwEU30aUYrPVQ1ZY
f+BxTtliyjzTVC93kSwGVzND6xmcUlE1GpLB0F4bgZXjynh/NQCdS10ZiiyCh7yk
1S5NiQLHMGA3gR9qCbiBkxgF301A7HQHc+MlJGwHn+mUMIue30miuRJTBtMzkyC8
TwHIWtBtHLy4Xf0F5nvdEReXeu2WndxLbseHnSfFtzv63PWRD9nufRqtrQsYAUrh
pvWXa1kNRyvlY/iF1bu9WREPYQxfC+zZaWAg5JPAItsAze752E5hTZCHyHk6A35b
OCy1GWR/ugVIA/dAEveu+sRmzlW00gSnnB2V1BoDVqy1RE8qgukfKyhFMSYmbaRZ
2lnXMMyv3WsNkqaGCZEiwHYHAxmCqvFQhGeJvt8tnlHExyxnaWheObsPuib0543D
F/KhWSNYGmcwS5He57rGQHV2PKCBsh/nohuaNjc2eg3PsWJkoVoP2MtH5xvlx8kl
F9QiC23wfl6ALjoHdbl++wHx7/Rw+pZOsxprHP25BXrQE5G/wb0=
=dwjW
-----END PGP SIGNATURE-----

**Comment by dereke** [comment]
Ah right looks like I hadn't installed xdotool, installing that sorted it out.

Thanks!
