### ISSUE TITLE
Arch Linux - Installation problem from aur repository

### ISSUE THREAD

**Issue by dj-d** [bulletmark/libinput-gestures#331]
Hardware specification:
- Dell XPS 15 9570
- Arch Linux
- Kernel 5.15.16-1-lts 

When I try to install libgestures from aur repository I have this error
![Lib_gestures_error](https://user-images.githubusercontent.com/50825148/151036868-1eae317b-cbb5-400b-8153-fc2c0c35f893.png)

**Comment by bulletmark** [comment]
You say you are trying to install `libgestures`. Do you mean this [package in the AUR](https://aur.archlinux.org/packages/libgestures/)? If so then that has nothing to do with `libinput-gestures` so create a comment on that AUR page or at the source repo.

**Comment by a7n007** [comment]
Unsubscruve
