### ISSUE TITLE
comand super+w only works repeating the gesture twice.

### ISSUE THREAD

**Issue by githubtefo** [bulletmark/libinput-gestures#332]
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README.

```
❯ libinput-gestures -l 
libinput-gestures: session KDE+x11 on Linux-5.16.13-arch1-1-x86_64-with-glibc2.35, python 3.10.2, libinput 1.20.0
Hash: 40fbc7bf6f74dfec892301edf07949e5
Gestures configured in ~/.config/libinput-gestures.conf:
swipe right        _internal ws_up
swipe left         _internal ws_down
swipe down         xdotool key super+w
pinch in           xdotool key super+s
pinch out          xdotool key super+s
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event7): ELAN2301:00 04F3:306B Touchpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a desktop application.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration file.

```

**Describe the issue**
I configured the swipe down to show the preview on KDE (the shortcut is super+w); I have to repeat the gesture twice in order to enter to Preview mode, because in the first attempt the gesture shows the 'w' (it is like is forgetting the super hehe).
Any thoughts?? Thanks!

**Comment by bulletmark** [comment]
What do you mean "the gesture shows the 'w' "? Shows where? As the instructions say, make sure you run your `xdotool` commands manually in the terminal and confirm they work as you expect.

**Comment by githubtefo** [comment]
Hi @bulletmark, thanks for your reply.
What I means is the gestures is typing the 'w' letter in the first attempt, while in the second repetition it works as expected.
The output of `xdotool key super+w` in the terminal is not working as expected neither, it is typing 'sw'.

**Comment by bulletmark** [comment]
You say "the gestures is typing the 'w' letter in the first attempt", again I ask you to be very specific to explain what you mean. Note that libinput-gestures runs in the background. So do you mean you see a "sw" reported in the libinput-gestures log? Where EXACTLY are you seeing this "sw"?

If you type `xdotool key super+w` in a terminal and you get no result other than "sw" reported back then it should be clear to you this issue is nothing to do with libinput-gestures? If that is true you need to work out what is happening to do with your system or your technique.

**Comment by githubtefo** [comment]
> You say "the gestures is typing the 'w' letter in the first attempt", again I ask you to be very specific to explain what you mean. Note that libinput-gestures runs in the background. So do you mean you see a "sw" reported in the libinput-gestures log? Where EXACTLY are you seeing this "sw"?

The first attempt I perform the gesture, I am seeing the 'w' (not 'ws' in the case of the gesture) type on wathever text body space I have active (for example, if I perform the gesture here, it will type: w).
> 
> If you type `xdotool key super+w` in a terminal and you get no result other than "sw" reported back then it should be clear to you this issue is nothing to do with libinput-gestures? If that is true you need to work out what is happening to do with your system or your technique.

I would be 100% agreed if the gesture wouldn't work at all. But the fact that when I repeat the gesture, it is actually working as expected, make me think that there are something erratic on its behavior and that is the reason I wanted to ask.

I will close the issue because it seems clear to you at least that is unrelated with libinput-gestures. I apologize for open it in the first place.
