### ISSUE TITLE
Uninstall bug

### ISSUE THREAD

**Issue by Omar611** [bulletmark/libinput-gestures#335]
I have uninstalled the app using the steps in the readme but it only removed the backend but the frontend is still there and it shows among my apps.
![Screenshot from 2022-05-14 22-48-24](https://user-images.githubusercontent.com/45848435/168447699-5dbdea85-3857-40e9-9516-320e4c205101.png)

**Comment by bulletmark** [comment]
This dekstop application is called "Libinput Gestures" not "Gestures" and the application icon looks like [this](https://github.com/bulletmark/libinput-gestures/blob/master/libinput-gestures.svg) so that is something else you have installed.
