### ISSUE TITLE
Loop through workspaces

### ISSUE THREAD

**Issue by nelwa** [bulletmark/libinput-gestures#338]
Hi,

Is it possible to loop through workspaces, ie: when you reach the last workspace, but 3-finger swipe up, it should go to the first workspace again.

Keyboard shortcuts, ctrl+alt+left or right arrow works like this, but libinput-gestures stops at the last/first workspace, and the only way to reach the other end is to reverse your swipe direction, and go through each workspace.

Thanks for a great utility!

**Comment by bulletmark** [comment]
Please, as per the instructions, always paste the output of `libinput-gestures -l` when you raise any issue.

In short, that is already possible. Read the instructions in the `libinput-gestures.conf` sample file. I.e, add `-w` to the `_internal` command.

**Comment by nelwa** [comment]
Thanks for the reply, but I can't seem to get it to work.

Where exactly in libinpunt-gestures.conf should I add the -w

gesture swipe up	_internal -w ws_up
or 
gesture swipe up	_internal ws_up -w
or where?

**Comment by nelwa** [comment]
Never mind, I was working in the wrong libinput-gestures.conf file.  The changes should be applied in the /etc/ version & this is the correct format: gesture swipe up _internal -w ws_up

**Comment by bulletmark** [comment]
The changes should **not** be in the `/etc/libinput-gestures.conf` file. Please read the instructions. You copy the default file to your personal `~/.config/libinput-gestures.conf` file and edit that. E.g. the file in `/etc/` may get clobbered when you update libinput-gestures. We would have both seen this if you had pasted the output of `libinput-gestures -l` (as the README asks, the issue raising instructions ask, and as I asked for above).

**Comment by nelwa** [comment]
Ok, thank you, I've copied the file to ~/.config/

All is working now.  Thank you for a great utility!
