### ISSUE TITLE
Could not determine touchpad device.

### ISSUE THREAD

**Issue by Mohamed3on** [bulletmark/libinput-gestures#34]
I have added the user to input group, logged out and in, and still get the message when I try to start the service. XPS 13 2016, ubuntu 16.10

List of devices:
```
`Device:           Power Button
Kernel:           /dev/input/event3
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event5
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event1
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Sleep Button
Kernel:           /dev/input/event2
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Integrated_Webcam_HD
Kernel:           /dev/input/event10
Group:            5
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           DLL075B:01 06CB:76AF Touchpad
Kernel:           /dev/input/event11
Group:            6
Seat:             seat0, default
Size:             101.33x56.67mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

Device:           Intel Virtual Button driver
Kernel:           /dev/input/event8
Group:            7
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Intel HID events
Kernel:           /dev/input/event7
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event4
Group:            9
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Dell WMI hotkeys
Kernel:           /dev/input/event9
Group:            10
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a
`
```

**Comment by bulletmark** [comment]
Please install the very latest version and run again. I fixed some missing error messages.

**Comment by Mohamed3on** [comment]
Ok, did that, now I get this:
```
 Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event11 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Failed to open /dev/input/event12 (Permission denied)
Failed to open /dev/input/event13 (Permission denied)
Failed to open /dev/input/event14 (Permission denied)
Failed to open /dev/input/event15 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Could not determine touchpad device.

```

**Comment by bulletmark** [comment]
Type the output of the `id` command here.

**Comment by Mohamed3on** [comment]
```
 id
uid=1000(mohamed) gid=1000(mohamed) groups=1000(mohamed),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare)

```

**Comment by bulletmark** [comment]
Don't see you assigned to the `input` group?

**Comment by Mohamed3on** [comment]
I don't know, how do I change that?
this is what I run, and what I get:
`sudo gpasswd -a $USER input  # Log out and back in to assign this group
Adding user mohamed to group input
`

**Comment by bulletmark** [comment]
What do you get? What is the output of `sudo gpasswd -a $USER input` when you run it?

**Comment by Mohamed3on** [comment]
` Adding user mohamed to group input `
Sorry it wasn't clear.

**Comment by bulletmark** [comment]
Please paste output of `ls -l /dev/input`

**Comment by Mohamed3on** [comment]
`total 0
drwxr-xr-x 2 root root      60 Nov 18 19:11 by-id
drwxr-xr-x 2 root root     140 Nov 18 19:11 by-path
crw-rw---- 1 root input 13, 64 Nov 18 19:11 event0
crw-rw---- 1 root input 13, 65 Nov 18 19:11 event1
crw-rw---- 1 root input 13, 74 Nov 18 19:11 event10
crw-rw---- 1 root input 13, 75 Nov 18 19:11 event11
crw-rw---- 1 root input 13, 76 Nov 18 19:11 event12
crw-rw---- 1 root input 13, 77 Nov 18 19:11 event13
crw-rw---- 1 root input 13, 78 Nov 18 19:11 event14
crw-rw---- 1 root input 13, 79 Nov 18 19:11 event15
crw-rw---- 1 root input 13, 66 Nov 18 19:11 event2
crw-rw---- 1 root input 13, 67 Nov 18 19:11 event3
crw-rw---- 1 root input 13, 68 Nov 18 19:11 event4
crw-rw---- 1 root input 13, 69 Nov 18 19:11 event5
crw-rw---- 1 root input 13, 71 Nov 18 19:11 event7
crw-rw---- 1 root input 13, 72 Nov 18 19:11 event8
crw-rw---- 1 root input 13, 73 Nov 18 19:11 event9
crw-rw---- 1 root input 13, 63 Nov 18 19:11 mice
crw-rw---- 1 root input 13, 33 Nov 18 19:11 mouse1`

**Comment by bulletmark** [comment]
Well `input` is the correct group. You must not have logged out/in? Please reboot and then try again.

**Comment by Mohamed3on** [comment]
OK, So a reboot did fix it. Now the service is working, but gestures don't work. In the terminal, I'm getting: 
`
 [Errno 2] No such file or directory: 'xdotool'

`

**Comment by bulletmark** [comment]
Please follow the README instructions. It says to install `xdotool` and `wmctrl` but you haven't done that,

**Comment by bulletmark** [comment]
BTW, you only had to add yourself to the `input` group and then log out and back in as the instructions say. Note the reboot was not required, I was just forcing you to log back in.

**Comment by bulletmark** [comment]
@geryit so either Ubuntu has a fundamental bug in the way Linux has always worked, or you didn't fully log out of your desktop session. Which one do you think is more likely?

**Comment by geryit** [comment]
It must be the bug then @bulletmark

**Comment by exp0nge** [comment]
Don't want to narc this, but a restart was also required for me... maybe that should be recommended now instead of logout (ubuntu 19.10)

**Comment by mariusfrinken** [comment]
Hey, as I was trying to install gestures on a fresh ubuntu 20.04.1 on a macbookpro9,2 I also **had** to reboot the OS. 
I did so because I found this issue here, so thanks!
I would like a short recommendation in the installation text, that says ubuntu users have to fully reboot.

**Comment by bulletmark** [comment]
Sorry, but unless somebody can provide explicit technical substantiation for this requirement, I am not going to add hocus-pocus words merely to satisfy people's superstition. You have to log out of your session, not just your terminal. There is no reason Ubuntu would be any different to any other Linux system. Look at the confusion of the OP here as one example. He raised this bug but he clearly had not added himself to the input group or followed the installation instructions correctly.

**Comment by mariusfrinken** [comment]
I see your point, so to demonstrate that I am not just superstitious:

https://youtu.be/N1Oup30U-AE

(fresh Mac OS 10.15.6, VirtualBox 6.1 and a fresh ubuntu 20.04.01 image from linuxvmimages.com)

Note: I know that more testing with `newgrp ` or `su` might be worthwhile, but I honestly do not have the time atm.
From reading the original issue here, I do believe the OP did the exact same thing as I did (and redid in the video).

**Comment by bulletmark** [comment]
@mariusfrinken, well I can't really argue with that demonstration! Thanks for your effort.

I did some research and it appears that [Ubuntu 18.04 changed things](https://askubuntu.com/a/1046365/50822) so that a user's session "lingers around" after logging out for some time, e.g. 20 secs. So if you log back in quickly you actually get the same session. Seems a ridiculous change to me but that is how it is so I will change the words. To keep it simple, I will just suggest to reboot.

**Comment by exp0nge** [comment]
Thanks @bulletmark

**Comment by mariusfrinken** [comment]
Thanks @bulletmark, especially for the quick answers.
