### ISSUE TITLE
Does not detect gesture swipe or gesture pinch

### ISSUE THREAD

**Issue by radzih** [bulletmark/libinput-gestures#343]
I runed ibinput-gestures -r and tried to swipe with 3 fingers also tried to pinch and this is output
(finger)
event5   POINTER_SCROLL_FINGER   +20.661s	vert 2.34/0.0* horiz 4.39/0.0* (finger)
event5   POINTER_SCROLL_FINGER   +20.682s	vert 0.00/0.0* horiz 0.00/0.0* (finger)
event5   POINTER_MOTION          +21.773s	  2.01/ -0.71 ( +5.00/ -1.78)
event5   POINTER_MOTION          +21.813s	  0.00/ -0.64 ( +0.00/ -1.78)
event5   POINTER_MOTION          +21.824s	  1.62/ -0.36 ( +4.00/ -0.89)
event5   POINTER_MOTION          +21.834s	  6.59/ -0.78 (+15.00/ -1.78)
event5   POINTER_MOTION          +21.844s	  7.02/  0.78 (+16.00/ +1.78)
event5   POINTER_MOTION          +21.854s	  6.15/  1.95 (+14.00/ +4.44)
event5   POINTER_MOTION          +21.864s	  7.02/ -1.17 (+16.00/ -2.67)
-event20  KEYBOARD_KEY            +22.881s	*** (-1) pressed
event20  KEYBOARD_KEY            +22.929s	*** (-1) pressed

when i swiping with 3 fingers there is no output, only when scroll or move cursor with one finger

my setup 
Static hostname: n/a                                  
Transient hostname: fedora
         Icon name: computer-laptop
           Chassis: laptop 💻
        Machine ID: 08efcb4e16a0449b8ee4b41820c95152
           Boot ID: 98959b107301443097ffedd713f44d78
  Operating System: Fedora Linux 37 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:37
            Kernel: Linux 6.0.11-300.fc37.x86_64
      Architecture: x86-64
   Hardware Vendor: Dell Inc.
    Hardware Model: Latitude E5540
  Firmware Version: A12
use wayland

my touchpad from libinput list-devices

Device:           AlpsPS/2 ALPS GlidePoint
Kernel:           /dev/input/event5
Group:            11
Seat:             seat0, default
Size:             83x52mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: enabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    none
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive
Rotation:         n/a

**Comment by bulletmark** [comment]
Please go back and follow every step in the [TROUBLESHOOTING](https://github.com/bulletmark/libinput-gestures#troubleshooting) section and then come back and fix this issue (you have ignored what the new issue template asked you to do).
