### ISSUE TITLE
libinput-gestures give me the error `Could not determine touchpad device.`

### ISSUE THREAD

**Issue by open-antux** [bulletmark/libinput-gestures#344]
```
λ ~/ libinput-gestures -l 
libinput-gestures: session unknown+tty on Linux-6.1.1-gentoo-x86_64-Intel-R-_Core-TM-_i5-8600K_CPU_@_3.60GHz-with-glibc2.36, python 3.10.9, libinput 1.22.0
Hash: 913c888f4e6a7ca5fe56f4931ec004b2
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       4 _internal ws_left
swipe right      4 _internal ws_right
Could not determine touchpad device.
```

**Describe the issue**
libinput-gestures doesn't recognize my touchpad (USB Mouse Pad USB Mouse Pad Mouse):
```
λ ~/ libinput debug-events             
-event2   DEVICE_ADDED            Power Button                      seat0 default group1  cap:k
-event1   DEVICE_ADDED            Power Button                      seat0 default group2  cap:k
-event0   DEVICE_ADDED            Sleep Button                      seat0 default group3  cap:k
-event20  DEVICE_ADDED            C-Media Electronics Inc.       USB PnP Sound Device seat0 default group4  cap:k
-event12  DEVICE_ADDED                       Logitech              Logitech Speaker seat0 default group5  cap:k
-event13  DEVICE_ADDED            USB Keyboard                      seat0 default group6  cap:k
-event14  DEVICE_ADDED            USB Keyboard Consumer Control     seat0 default group6  cap:kp scroll-nat
-event15  DEVICE_ADDED            USB Keyboard System Control       seat0 default group6  cap:k
-event16  DEVICE_ADDED            USB Keyboard                      seat0 default group6  cap:k
-event17  DEVICE_ADDED            USB Mouse Pad USB Mouse Pad Mouse seat0 default group7  cap:p left scroll-nat scroll-button
-event18  DEVICE_ADDED            USB Mouse Pad USB Mouse Pad System Control seat0 default group7  cap:k
-event19  DEVICE_ADDED            USB Mouse Pad USB Mouse Pad       seat0 default group7  cap:k
-event13  KEYBOARD_KEY            +0.000s       *** (-1) pressed
 event13  KEYBOARD_KEY            +0.072s       *** (-1) pressed
^C
```

**Comment by bulletmark** [comment]
So to be clear, are you saying your touchpad doesn't work at all? Can you do ordinary finger movements of the cursor?

**Comment by bulletmark** [comment]
I updated step 6 in the [trouble-shooting section](https://github.com/bulletmark/libinput-gestures#troubleshooting) to be hopefully more clear so please do that step.

**Comment by open-antux** [comment]
Hi, thanks for the reply.

I've done some tests and it seems that the touchpad doesn't support multi-finger gestures (tested on Gentoo with libinput and Windows). So sad...

I've another question by the way, I've tried to switch workspace by swiping to the left/right using only two finger (supported gesture):
```
λ ~/ libinput-gestures -v --device "USB Mouse Pad USB Mouse Pad Mouse"
libinput-gestures: session unknown+tty on Linux-6.1.1-gentoo-x86_64-Intel-R-_Core-TM-_i5-8600K_CPU_@_3.60GHz-with-glibc2.36, python 3.10.9, libinput 1.22.0
Hash: 913c888f4e6a7ca5fe56f4931ec004b2
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left         /home/antonio/.xmonad/bin/switch_workspace.sh switch_empty next
swipe right        /home/antonio/.xmonad/bin/switch_workspace.sh switch_empty prev
device USB Mouse Pad USB Mouse Pad Mouse
libinput-gestures: device /dev/input/by-path/pci-0000:00:14.0-usb-0:8:1.0-event-mouse(event17): USB Mouse Pad USB Mouse Pad Mouse
```
But for some reason it seems that doesn't work.

Thanks for the support.

**Comment by bulletmark** [comment]
What do you mean "swiping with two finger (supported gesture)"? Gestures are 3 (or more) fingers as [described in the documentation](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#swipe-gestures).

**Comment by open-antux** [comment]
I'm sorry for the misunderstanding, I mean the feature described [here](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html#gestures-on-two-finger-touchpads).

What I want is to do this gesture (left or right) in order to change workspace, did I've done something wrong in the configuration shown above?

Thanks for the support.

**Comment by bulletmark** [comment]
You're off on a tangent there. Just do [step 6 of the trouble-shooting](https://github.com/bulletmark/libinput-gestures#troubleshooting) procedure as I said. If you don't see `GESTURE_*` events reported then libinput does not support your touchpad and this issue can be closed.

**Comment by open-antux** [comment]
I see, thanks for the support :smile:
