### ISSUE TITLE
Swipes not working

### ISSUE THREAD

**Issue by Mohamed3on** [bulletmark/libinput-gestures#35]
So I got this setup, and tested all gestures, and got good responses:
```
mohamed@mohamed-xps:~$ libinput-gestures -d
libinput-gestures: monitoring device /dev/input/event11 for 6 gestures
libinput-gestures: SWIPE down 3 [-42.64, 346.4]
   _internal ws_down
libinput-gestures: SWIPE up 3 [66.68999999999998, -577.7099999999999]
   _internal ws_up
libinput-gestures: SWIPE right 3 [1286.9000000000003, 239.22000000000003]
   xdotool key alt+Left
libinput-gestures: SWIPE left 3 [-1428.5299999999997, 164.84999999999997]
   xdotool key alt+Right
libinput-gestures: PINCH out 2 -15.959999999999997
   xdotool key super+s
libinput-gestures: PINCH in 2 5.120000000000001

```
But after starting the service, I try the gestures in chrome, and nothing happens. swiping left/right does not go back or forward. pinches also do nothing, neither do up/down swipes.
However, swiping right/left writes 'D' or 'C' in the terminal.

**Comment by Mohamed3on** [comment]
Edit: restarting the service did the trick.

**Comment by bulletmark** [comment]
I.e. after you edit the configuration you must run `libinput-gestures-setup restart`, as the instructions say.

**Comment by Mohamed3on** [comment]
Yes, correct. My mistake.
