### ISSUE TITLE
Cannot use modified version of libinput-configs anymore

### ISSUE THREAD

**Issue by linuxtopia** [bulletmark/libinput-gestures#350]
Read TROUBLESHOOTING section but there is no option for my case

` libinput-gestures -l`

```
libinput-gestures: session KDE+x11 on Linux-5.14.21-150400.24.63-default-x86_64-with-glibc2.3.4, python 3.6.15, libinput 1.19.4
Hash: 1cfe6ad528f2202a483fea24b3cd7f47
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key ctrl+F9
swipe down       3 xdotool key ctrl+F11
swipe left       4 xdotool key ctrl+1
swipe right      4 xdotool key ctrl+1
swipe up         4 xdotool key control+shift+Down
swipe down       4 xdotool key control+shift+Up
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
swipe right_up     xdotool key control+Tab
swipe right_down   xdotool key ctrl+F5
swipe left_down    xdotool key control+w
swipe left_up      xdotool key control+shift+t
pinch in           xdotool key ctrl+F8
pinch out          xdotool key ctrl+F12
pinch clockwise    xdotool key XF86AudioRaiseVolume
pinch anticlockwise   xdotool key XF86AudioLowerVolume
hold on         4 xdotool key control+t
libinput-gestures: device /dev/input/by-path/platform-AMDI0010:03-event-mouse(event15): ELAN050A:01 04F3:3158 Touchpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a desktop application.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration file.
```

**Describing the issue**

I was using it normally and able to edit config file in /.config and then restart the service what was working. But recently changed my browser gestures on libinput-gestures via config and it still uses old edition of config file.

Why this causes no any idead, several times stopped service, restarted, rebooted even reinstalled but nothing helped.

Hope you handle and help me on this great editable tool.
Thanks.

**Comment by bulletmark** [comment]
In your above description you say "edit config file in /.config". Is that a typo? You should be editing the file which is shown above in the output, i.e. `~/.config/libinput-gestures.conf`, i.e. `$HOME/.config/libinput-gestures.conf`. Are the gestures listed above the ones you are expecting?

**Comment by linuxtopia** [comment]
no not typo I just wanted to write it briefly. i meant what was under ~/.config.

`~/.config/libinput-gestures.conf` is the path to the config file.

**Comment by bulletmark** [comment]
"No not a typo"? Please note that `/.config` and `~/.config` are completely different directories. If you are editing any file at `/.config` then that is the wrong directory.

The above output of your `libinput-gestures -l` shows that libinput-gestures is using your custom file in `~/.config/libinput-gestures.conf` and the gestures you have configured there are printed out also. Is that the file you are editing? Are you saying that file is not being used? Are the gestures list above the ones you have configured/changed? What exactly is the issue you are reporting?

**Comment by linuxtopia** [comment]
![image](https://github.com/bulletmark/libinput-gestures/assets/19939134/c8cf09bd-fc53-4a29-83f3-9eabb2975b8d)

I have changed libinput-gestures browser gestures but they had worked previous vise versa setting.

# Refresh browser tab
gesture swipe right_down xdotool key control+R

# Close current browser tab
gesture swipe left_down xdotool key control+w

After reboot systemctl stop/disable/enable/restart looking solved the issue. we may close this :)

*btw, hold 3 finger works with libinput-gestures?

**Comment by bulletmark** [comment]
Your output says you are running libinput-gestures as a desktop app so any `systemctl` is irrelevant. In fact you should get an error if you try to run `systemctl` on anything to do with libinput-gestures so that can't have solved anything. If you read the [instructions in the README](https://github.com/bulletmark/libinput-gestures#starting-and-stopping) you will see that you restart this utility (to pick up config changes etc) by typing the command:

    libinput-gestures-setup restart

And can you please clarify what you are asking in that final sentence? Of course the software works but please try the `hold on` command and see if it is what you are wanting.
