### ISSUE TITLE
[Readme] Add Table of Index

### ISSUE THREAD

**Issue by KAGEYAM4** [bulletmark/libinput-gestures#351]
I was facing this issue - `libinput-gestures failed to start as a desktop application`.

Looked on internet first as i thought there was no troubleshoot in Readme ( newbie mistake ). Then later searched in the `issues`. Found to run `libinput-gestures -l` for log. Then in the log - `IsADirectoryError: [Errno 21] Is a directory: '/home/phoenix/.config/libinput-gestures.conf'` helped, as i looked in the .config directory and delted the folder so it can read from /etc default config location. Don't how how that directory ( /home/phoenix/.config/libinput-gestures.conf ) got created.

**Comment by bulletmark** [comment]
If you read that trouble-shooting section in the README then how did you miss that bolded sentence in the first paragraph and in step 9?

**Comment by bulletmark** [comment]
No response from OP to provide the requested information so closing.

**Comment by KAGEYAM4** [comment]
> No response from OP to provide the requested information so closing.

I apologize for not replying in time. Don't know how i missed the notification even though you replied on same day.


I think my issue Title and Description was vague and confusing. The issue was resolved. What i actually raised this issue was for - `To include a TableOfIndex at start of Readme` so that we can get overview of all the `topics` inside Readme.

As the issue was resolved , the output of `libinput-gestures -l` will just add distraction so i didn't posted it.
