### ISSUE TITLE
[Bug] Hold on gestures don't work in 1.23.0 version

### ISSUE THREAD

**Issue by IceAsteroid** [bulletmark/libinput-gestures#356]
The output of "libinput-gestures -l" on a terminal:
```
/usr/bin/libinput-gestures:643: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if Version(libvers) >= Version('1.8'):
libinput-gestures: session unknown+wayland on Linux-6.3.13_1-x86_64-with-glibc2.36, python 3.11.5, libinput 1.23.0
/usr/bin/libinput-gestures: hash de25c8c01861acf0314d14565f96b2b1
Error at line 26 in file ~/.config/libinput-gestures/main.conf:
>> gesture hold on 4 echo sdf <<
Gesture "hold" is not supported.
Must be "swipe" or "pinch".
```

**Describe the issue**
The github readme page of this repo says it's already available since version 1.19 of libinput.

But the libinput version is already 1.23.0 running on my system, and it still doesn't support the hold on gestures.

The OS is voidlinux.

Any ideas?

**Comment by bulletmark** [comment]
The version of `libinput-gestures` you are running is ancient, more than 2 years old, before that hold gesture was added (and before distutils started reporting that depreciation message). Please upgrade to the latest version.

**Comment by bulletmark** [comment]
No response from OP so closing.
