### ISSUE TITLE
Bug when using three finger swipe to switch between open applications.

### ISSUE THREAD

**Issue by Rossmaxx** [bulletmark/libinput-gestures#357]
**libinput-gestures -l output**
```
roshan@roshan-Inspiron-15-3511:~$ libinput-gestures -l
libinput-gestures: session cinnamon+x11 on Linux-5.15.0-86-generic-x86_64-with-glibc2.35, python 3.10.12, libinput 1.20.0
Hash: bc14b1ce9ae349e2a64d765873e74fc6
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         3 xdotool key 0xffe3+0xFFEA+0xFF54
swipe down       3 xdotool key super+d
swipe left       3 xdotool keyup 0xffea
swipe right      3 xdotool keydown 0xffea + key 0xff09
swipe up         4 xdotool key 0xffea+m
swipe down       4 xdotool key 0xffe9+0xffc1
swipe left       4 xdotool key super+0xff51
swipe right      4 xdotool key super+0xff53
pinch out        2 xdotool key 0xffe3+0x002b
pinch in         2 xdotool key 0xffe3+0x002d
libinput-gestures: device /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse(event9): DELL0AB0:00 04F3:3147 Touchpad
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a desktop application.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration file.
roshan@roshan-Inspiron-15-3511:~$ 

```

**Describe the issue**
I used libinput gestures to get three finger swipe to switch between open applications gesture on my linux install. But after I do the three finger swipe, some sort of a bug occurs on my pc. This video below demonstrates the issue better. 

https://github.com/bulletmark/libinput-gestures/assets/74815851/94801d2e-4fab-4b3d-921c-a25c47490f1f

(Excuse the poor quality. Had to reduce it to fit it in github embed.)

I followed along some tutorial to enable the gesture, don't remember which one. 

Also, the issue disappears when i log out and log back in.

**Comment by bulletmark** [comment]
Please note the **bold** sentence in the opening paragraph of the [TROUBLESHOOTING](https://github.com/bulletmark/libinput-gestures#troubleshooting) section.

**Comment by Rossmaxx** [comment]
> Please note the bold sentence in the opening paragraph of the [TROUBLESHOOTING](https://github.com/bulletmark/libinput-gestures#troubleshooting) section.

updated with the command output.

**Comment by bulletmark** [comment]
Note item 8 in the TROUBLESHOOTING section. You have 4 different 3 finger swipes configured so I am not sure which you have an issue with nor do I know specifically what those 4 `xdotool` calls are doing. Please execute those exact same commands in a terminal window and confirm they do watch you want.

**Comment by Rossmaxx** [comment]
> Please execute those exact same commands in a terminal window and confirm they do exactly what you want.

I'm new to linux so don't know much about what exact commands to run.

What I want to do on 3 finger left swipe is the same as alt+tab key. Don't remember which tutorial I followed to set up.

**Comment by bulletmark** [comment]
In your video you are swiping right so what does `xdotool keydown 0xffea + key 0xff09` do?

There is no magic here. `libinput-gestures` merely invokes whatever commands you configure in your `~/.config/libinput-gestures.conf` file. You have to make sure the commands you configure work by testing them on the command line. If they don't work there as you want then sorry but `libinput-gestures` can't somehow make them work.

**Comment by bulletmark** [comment]
No response from @Rossmaxx so closing ..

**Comment by Rossmaxx** [comment]
Sorry for the late response. Since I'm on dual boot for now, haven't booted into the linux partition in a long time.

> libinput-gestures merely invokes whatever commands you configure in your ~/.config/libinput-gestures.conf file. You have to make sure the commands you configure work by testing them on the command line. If they don't work there as you want then sorry but libinput-gestures can't somehow make them work.

I tried that but those commands seem to not work on the command line either. Like I said earlier, I don't know what exactly is going on as i followed a tutorial to set up. Still haven't found the exact video or blog i followed.

**Comment by Rossmaxx** [comment]
did some digging and the bug seems to be with xdotool. https://askubuntu.com/questions/122161/alt-tab-with-xdotool-and-xkeybind
