### ISSUE TITLE
Not really an issue, more a cry for help!

### ISSUE THREAD

**Issue by crazybadger** [bulletmark/libinput-gestures#36]
Sorry, was't really sure where to ask this and I can't seem to find a solution anywhere, but feel free to delete!

I'm running this on elementary OS 0.4 loki to try and replicate some macOS gesures and I think I've got most of them working well.  The problem I'm having is with 3-finger left-right swipes to switch forward-backward in a browser (I'm using Chrome) window.  Whichever way I configure the command in the .conf file they always work in reverse (i.e. swipe right goes back and left forward).  I've switched the command several times but it always works the same way!  This is what I have:

gesture: swipe left     xdotool key alt+Right
gesture: swipe right    xdotool key alt+Left

Any ideas?

Thanks

**Comment by bulletmark** [comment]
What you have configured above is the default configuration as shipped and that works for me fine in chromium browser. You can just swap the `swipe left` to `swipe right` etc, to swap them around if you prefer "unnatural scrolling" direction. Are you sure you are restarting the app after changing the config: `libinput-gestures-setup restart`?

**Comment by crazybadger** [comment]
Thanks for the quick reply!

Yes, I've swapped them around, restarted and  rebooted several times but it just doesn't change the way they behave!  It's much better than nothing, but I'd prefer it the other way.

**Comment by bulletmark** [comment]
Where are you putting your custom config file? You should be adding your custom config in `~/.config/libinput-gestures.conf` but it sounds to me like it is still using the system config.

**Comment by crazybadger** [comment]
Agh!  Good catch.  I had moved the .conf file but into a folder ~./config/libinput-gestures/libinput-gestures.conf!  Copied down a level and now it's working!  Thanks again for your help and great little app!
