### ISSUE TITLE
libinput-gestures + ydotool + wmctrl work well in Wayland KDE Plasma 6.2.3

### ISSUE THREAD

**Issue by skjongithub** [bulletmark/libinput-gestures#369]
Recently libinput-gestures failed after KDE Plasma update.
I replaced xdotool with ydotool, installed wmctrl, and reinstalled libinput-gestures, and now they work like charm.
I hope this info helps

**Comment by bulletmark** [comment]
No, it does not help. You have raised a bug with no description of the problem, no mention of your platform/environment, or any versions, and missing the `llibinput-gestures -l` output explicitly requested by the instructions and bug template here. If you changed to `ydotool` then you also changed your configuration but include no mention of that.

In the last few days, libinput updated to v1.27 and it required a change to libinput-gestures to version 2.78 so given your lack of information here let's assume that update fixed your issue.
