### ISSUE TITLE
Allow different actions based on the active window

### ISSUE THREAD

**Issue by fish-face** [bulletmark/libinput-gestures#37]
This is a feature request based on the functionality of touchegg, where you can specify the application that a gesture action applies to. This is very useful if you want to map gestures to special application actions.

This would be easy enough to implement - there are various ways of getting the name of the active window (probably best to match based on the WM_CLASS rather than just the title since windows like Terminals tend not to include anything useful in their title) and the trickiest thing would perhaps be picking a syntax for the configuration file. Touchegg uses some kind of horrendous XML, but something like:

    [window Firefox]
        gesture: swipe up 3 xdotool ctrl+E
    [window Firefox, Chrome, Nautilus]
        gesture: swipe left 3 xdotool alt+Left
        gesture: swipe right 3 xdotool alt+Right

would work. I am being inspired by ini files - but basically anything would work.

**Comment by bulletmark** [comment]
I'm trying to keep this app useful on Wayland but certainly there is no way for an app to get a list of current windows on Wayland so this is not possible there.

**Comment by fish-face** [comment]
There is also no way of sending keys on Wayland without xdotool - you can get the class of the currently active window using xdotool and wmctrl. In bash you can do:

    wmctrl -px -l | grep "`xdotool getwindowfocus getwindowname`" | awk '{print $4;}'

So this would not involve any new dependency, would be useful on X and would not break the tool on Wayland, where such directives can just be ignored.

**Comment by Phantom-Punch** [comment]
> wmctrl -px -l | grep "`xdotool getwindowfocus getwindowname`" | awk '{print $4;}'

On wayland this only shows the xwayland windows. Native clients don't show up.

**Comment by fish-face** [comment]
Yes but this is also true for xdotool's usage (as per the README) to send keys to windows. It only works for XWayland clients under Wayland, also. Under Wayland you'd only be able to set per-application gestures for XWayland clients - it would still be useful and wouldn't break anything.

**Comment by Phantom-Punch** [comment]
Agreed then.

**Comment by bulletmark** [comment]
@fish-face you say there is no way to send keys on Wayland without `xdotool` but that is not correct. The default libinput-gestures.conf actions for swipe up and down to switch desktops (using an `_internal` command), does not use `xdotool`, works on all desktops (GNOME and KDE at least), and works on both Wayland and Xorg.

**Comment by fish-face** [comment]
But that is not sending keys, just sending the switch desktop action. You can't send some arbitrary key combination that way, but you can with xdotool for X clients. This is what you have written in the README. I am just saying that using xdotool in this way to get focus info (which wouldn't work well in Wayland) is no worse for compatibility/dependency than the recommended use of xdotool to send, e.g. Ctrl+PgUp.

**Comment by bulletmark** [comment]
Closing as I do not plan to add this enhancement.
