### ISSUE TITLE
Failed to open /dev/input/event1 (Permission denied)

### ISSUE THREAD

**Issue by sandangel** [bulletmark/libinput-gestures#43]
I have add user to input group and logout/login but libinput-gestures-set can not started.
I'm using ubuntu 17.04, gnome 3.22 session and I have installed libinput, x86-input-libinput.
How can I fix this. My touch pad still can not use gesture except 4 finger swipe up/down to change
workspace

**Comment by bulletmark** [comment]
Are you running the very latest version of libinput-gestures?

Have you installed xdotool and wmctrl as per the instructions?

Have you checked the journal, and/or run with the -v switch to check what errors are reported?

Are you using the default configuration? If you are using a custom configuration file then please list it here.

**Comment by sandangel** [comment]
1. I'm running the very latest version of libinput-gestures.
2. I have installed xdotool and wmctrl as per the instructions.
3. I have checked the journal as below
$ sudo gpasswd -a $USER input
Adding user XXXX to group input
// logout/login
$ sudo apt-get install xdotool wmctrl
$ xdotool -v
xdotool version 3.20160512.1
$ wmctrl --version
1.07
$ git clone http://github.com/bulletmark/libinput-gestures
$ cd libinput-gestures
$ sudo make install
'libinput-gestures-setup' -> '/usr/bin/libinput-gestures-setup'
'libinput-gestures' -> '/usr/bin/libinput-gestures'
'libinput-gestures.desktop' -> '/usr/share/applications/libinput-gestures.desktop'
'libinput-gestures.png' -> '/usr/share/icons/hicolor/128x128/apps/libinput-gestures.png'
'libinput-gestures.conf' -> '/etc/libinput-gestures.conf'
install: creating directory '/usr/share/doc/libinput-gestures'
'README.md' -> '/usr/share/doc/libinput-gestures/README.md'
gtk-update-icon-cache: Cache file created successfully.
$ libinput-gestures-setup start
Failed to open /dev/input/event1 (Permission denied)
Failed to open /dev/input/event3 (Permission denied)
Failed to open /dev/input/event0 (Permission denied)
Failed to open /dev/input/event10 (Permission denied)
Failed to open /dev/input/event2 (Permission denied)
Failed to open /dev/input/event4 (Permission denied)
Failed to open /dev/input/event7 (Permission denied)
Failed to open /dev/input/event8 (Permission denied)
Failed to open /dev/input/event9 (Permission denied)
Failed to open /dev/input/event5 (Permission denied)
Failed to open /dev/input/event6 (Permission denied)
Could not determine touchpad device.
^C
$ libinput-gestures-setup status
libinput-gestures is installed.
libinput-gestures is set to autostart.
libinput-gestures is not running.

**Comment by bulletmark** [comment]
Those permission errors tell you that you have not added yourself to the input group and logged out/in. See the instructions.

**Comment by sandangel** [comment]
I got it, Logout and Login did not add user to group input. I have restarted then I can start libinput-gesture. Thanks

**Comment by bulletmark** [comment]
You're using a linux system like the rest of us so logging out and back in does assign the group. You probably just closed the terminal and opened a new one.

**Comment by s7urmi** [comment]
i had the exact same issue just now.
Added my user to group, closed gnome-terminal, logged off, logged in, did not work, tried it again after reading this here, same result. 
Rebooted, worked just fine /shrug

**Comment by bulletmark** [comment]
The "closed gnome-terminal" statement is irrelevant. You have to log completely out of your gnome session, back to the gdm login prompt, then log back in.

**Comment by s7urmi** [comment]
I did exactly that(right top corner>username>log out>enter password at the login screen>...) but still got the permission issue after logging back into the gnome-session. Only after i tried the reboot it worked. 
So if anyone has that issue, just reboot.

**Comment by bulletmark** [comment]
@dcomtois if you log out of your session *completely*, as the README says, you should not have this problem. So please clarify what you mean when you say "simply logging out then in still led to this error". What did you actually do?

**Comment by dcomtois** [comment]
@bulletmark Well, as I said, I logged out (yes, I know what it means), and logged back in, just following the instructions to the letter. So you can keep thinking none of us know what we're doing, or acknowledge that for some configurations, logging out might not be enough and restarting fixes it. You do whatever you want, I just thought adding a note might save some time to others, that's all.

**Comment by bulletmark** [comment]
I am asking what you mean by "logged out". Are you running a DE, or something else? Paste the output of `libinput-gestures -l` here. You have to log out completely from your desktop.

**Comment by dcomtois** [comment]
Yes I use a cinnamon desktop env. I log out using
`cinnamon-session-quit --logout --force`

Here's the output, after I added two actions (they work as intended):
```
$ libinput-gestures -l
libinput-gestures: session cinnamon+x11 on Linux-4.15.0-43-generic-x86_64-with-LinuxMint-19.1-tessa, python 3.6.7, libinput 1.10.4
/usr/bin/libinput-gestures: hash 473074771d28c793b85639c34fd7abce
Gestures configured in ~/.config/libinput-gestures.conf:
pinch out        2 xdotool key ctrl+plus
pinch in         2 xdotool key ctrl+minus
libinput-gestures: device /dev/input/event11: DLL06E4:01 06CB:7A13 Touchpad
```

**Comment by bulletmark** [comment]
Well clearly whatever that command line does, it does not log you out properly.

**Comment by dcomtois** [comment]
Ok so what would be the proper way then?

**Comment by bulletmark** [comment]
Well I have never used cinnamon but I just looked on YouTube and see that you click on an icon at the bottom and select "Log Out ..." - i.e. pretty much like every other desktop!?

**Comment by dcomtois** [comment]
Well that's what I do too... They accomplish the same thing AFAIK... I'm not sure which one of the two I used, might have been the button.

**Comment by nqgl** [comment]
I tried both logging out via the GUI and command line, neither was successful, though looking in the "users and groups" application, my account did show membership in the input group. So I don't think these other people were wrong.
Reboot worked though, and this program works wonderfully! Thank you.

**Comment by rmnagrwal** [comment]
> I got it, Logout and Login did not add user to group input. I have restarted then I can start libinput-gesture. Thanks

what you did here?
