### ISSUE TITLE
"Tap" and "double tap" as a gesture

### ISSUE THREAD

**Issue by capstan1** [bulletmark/libinput-gestures#44]
Is it possible to get tap and double-tap with up to 5 fingers? Would be a great way of extending the variety of gestures with gestures easy to perform. (Having my problems doing a 4-fingers pinch in for example, 4-fingers double-tap would be great)

Thank you for this great tool, which is "just working"!

**Comment by bulletmark** [comment]
This utility only acts on what libinput reports as gesture events. Currently that is 3 or more finger swipes in any direction, and 2 or more finger pinches in or out. Tapping is not a gesture event unfortunately.

So `libinput-gestures` really only exists to provide swipes and pinch actions, and then only until the DE's implement this stuff themselves which is what we all really want.

**Comment by capstan1** [comment]
okay, thank you very much for your quick response!
