### ISSUE TITLE
libinput-gestures does not detect any events :(

### ISSUE THREAD

**Issue by jplatte** [bulletmark/libinput-gestures#47]
How do I debug this? I think it might be listening for events on the wrong device, at least that's the case if the IDs listed by xinput correspond with the number after the `/dev/input/event`.

**Comment by bulletmark** [comment]
Well, as the instructions say, you could run it explicitly with the `-d` or `-v` switches. That will print out the device it has auto-selected as your touchpad and other stuff. Please paste the output of `libinput-list-devices` here. Also, try using the default configuration if you are not. I.e.

~~~~
mv ~/.config/libinput-gestures.conf ~/.config/libinput-gestures.conf.save
libinput-gestures-setup restart
~~~~

Also you should state the obvious. What distro are you using? Is your system up to date? What DE? What version of libinput-gestures? Xorg or Wayland? etc ...
````

**Comment by jplatte** [comment]
> Well, as the instructions say, you could run it explicitly with the `-d` or `-v` switches.

I did that, that's how I know it's not detecting anything, instead of my config being faulty or sth. like that. Here is my device list, so my initial idea that it detects the wrong thing seems off the table now..

```
Device:           Power Button
Kernel:           /dev/input/event4
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event9
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event1
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Sleep Button
Kernel:           /dev/input/event2
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           BisonCam, NB Pro
Kernel:           /dev/input/event10
Group:            5
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event0
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event11
Group:            7
Seat:             seat0, default
Size:             63.94x32.08mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    none
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a
```

I have stopped the background daemon and started `libinput-gestures -dv` with the default config, then swiped with three fingers up and down, plus pinched in and out, and have still not gotten any output.

Distro: arch linux
Up-to-date: yes
DE: i3 (with compton)
libinput-gestures version: 2.13
Xorg or Wayland: Xorg (obviously, as I'm using i3)

**Comment by jplatte** [comment]
One thing that is curious about the output of libinput-list-devices is that it says tap-to-click and natural scrolling are disabled. I actually have both enabled, they work, and `xinput` shows it too:

```
libinput Tapping Enabled (282):	1
libinput Natural Scrolling Enabled (292):	1
```

Maybe libinput-list-devices shows these properties instead?

```
libinput Tapping Enabled Default (283):	0
libinput Natural Scrolling Enabled Default (293):	0
```

**Comment by bulletmark** [comment]
So when you run `libinput-gestures -v' or 'libinput-gestures -d`, what device does it say it is using? It should say `/dev/input/event11` from your list above (note that this device number can change between reboots).

**Comment by jplatte** [comment]
Yes, that is what it says:

```
libinput-gestures: using /etc/libinput-gestures.conf, session unknown
libinput-gestures: monitoring device /dev/input/event11 for 2 gestures
```

**Comment by bulletmark** [comment]
Please also paste the output of `wmctrl -d` here.

**Comment by jplatte** [comment]
Successfully lists my workspaces:

```
0  - DG: N/A  VP: 0,0  WA: N/A  1: Web
1  - DG: N/A  VP: 0,0  WA: N/A  2: IM
2  - DG: N/A  VP: 0,0  WA: N/A  3: Mail
3  * DG: N/A  VP: 0,0  WA: N/A  4
4  - DG: N/A  VP: 0,0  WA: N/A  5
```

**Comment by bulletmark** [comment]
It says 2 gestures only. So you are not using the default config. Please paste your config here.

**Comment by jplatte** [comment]
Yeah I have some stuff commented out, I didn't know how the global config looked by default. The two rules I still have active are:

```
gesture: swipe up	_internal ws_up
gesture: swipe down	_internal ws_down
```

**Comment by bulletmark** [comment]
The default config is in `/etc/`. Just move your config from `~/config` and it will use the default.

**Comment by jplatte** [comment]
No I changed the config in /etc right after install (commented out everything).

**Comment by bulletmark** [comment]
Why do it that way? Install the package again from the AUR and just create your custom config in the right place.

**Comment by jplatte** [comment]
Yeah I didn't initially know that I could have my own user config file. But I don't see how the default config would change anything here. The commands it would run wouldn't do anything in i3.

**Comment by jplatte** [comment]
I have now saved the config in this repo as my user config, now it says 6 gestures. Still no other output on the command line or anything else noticable though.

**Comment by bulletmark** [comment]
Please reinstall from AUR? Doesn't take long and we know where we are then.

**Comment by bulletmark** [comment]
Then do the following:
~~~~
libinput-gestures-setup stop
libinput-gestures -v
~~~~~
Do some swipes up and down then paste the output here.

**Comment by jplatte** [comment]
Alright, I have removed /etc/libinput-gestures.conf and reinstalled the AUR package. This is the full output:

```
jplatte@jp-tuxedo ~ % libinput-gestures-setup stop
jplatte@jp-tuxedo ~ % libinput-gestures -v
libinput-gestures: using /etc/libinput-gestures.conf, session unknown
libinput-gestures: monitoring device /dev/input/event11 for 6 gestures

```

**Comment by bulletmark** [comment]
That output is after you have done some 3 finger swipes up and down?

**Comment by jplatte** [comment]
Yes.

**Comment by bulletmark** [comment]
Type:
~~~~
libinput-gestures -r
~~~~
And then do some swipes please.

**Comment by jplatte** [comment]
Huh. It doesn't log anything when I do 3 finger swipes. It does log 1/2 finger movements though. So my hardware just gives up when I use more than 2 fingers?

**Comment by bulletmark** [comment]
Yep, that is what it seems.

**Comment by jplatte** [comment]
Wow, that sucks. But then there's nothing to be done I guess.

**Comment by bulletmark** [comment]
May not be your hardware. May be an issue in the kernel and/or libinput, particularly if it is a new model laptop.

**Comment by bulletmark** [comment]
Similar to issue #39.

**Comment by jplatte** [comment]
Hm, maybe. But the laptop is not that new and also not from a big brand. Also, in the libinput bug created by the creator of that other issue one of the libinput devs says that the gestures are disabled intentionally on some touchpads because the hardware data is not very good. So overall it seems very unlinkely that this will ever work, and to be honest, I don't care enough to try any further.
