### ISSUE TITLE
pinch seems very easily confused with swipe

### ISSUE THREAD

**Issue by oblitum** [bulletmark/libinput-gestures#5]
I've been using this with great effect since its beginning on my MacBook Pro 2011 but recently, I think, it's being very easy to confuse swipe with pinch, which is kind of annoying since I often get a "open overview" in place of "moving to workspace", this is my slightly modified configuration:

```
# GNOME SHELL move to next workspace
gesture: swipe up	xdotool key super+J

# GNOME SHELL move to prev workspace
gesture: swipe down	xdotool key super+K

# GNOME/Browser go back
gesture: swipe right	xdotool key alt+Left

# GNOME/Browser go forward
gesture: swipe left	xdotool key alt+Right

# GNOME SHELL open overview
gesture: pinch in	xdotool key super+s
gesture: pinch out	xdotool key super+s
```

Could there be a fix or configuration to tweak this sensibility?

**Comment by oblitum** [comment]
I'm running an up to date archlinux with gnome 3.

**Comment by bulletmark** [comment]
Can you please confirm you are running the latest libinput-gestures version? I improved the logic considerably with commits after issue #3.

**Comment by oblitum** [comment]
Currently I'm at afd2b976c977156a8684bfdf85be7225c1e36abd. I will update to latest later but I guess the latest commits don't touch this.

**Comment by bulletmark** [comment]
Your configuration file look the same as the default but it looks like you have custom keyboard mappings to use super+J/K instead of the GNOME defaults super+Page_Up/Page_Down to switch workspaces. Is that correct?

**Comment by oblitum** [comment]
Yes indeed.

**Comment by bulletmark** [comment]
By the time the gesture gets to this app it has already been identified by libinput as either a SWIPE or a PINCH so if you are unhappy with the discrimination between them unfortunately there is nothing I can do as it is all within libinput. There are a few libinput parameters you may be able to tweak, see man libinput.

**Comment by oblitum** [comment]
OK then..

**Comment by postadelmaga** [comment]
Did you get any luck with this @oblitum ?

**Comment by oblitum** [comment]
@postadelmaga I think I've learned to live with it. It doesn't affect my workflow anymore for me to notice.

**Comment by postadelmaga** [comment]
mmm, I think we may fill a bug here https://bugs.freedesktop.org/enter_bug.cgi?product=wayland&component=libinput
