### ISSUE TITLE
KDE version support

### ISSUE THREAD

**Issue by SpiderX** [bulletmark/libinput-gestures#52]
Which KDE version do you support?

In KDE 5 binary for kioclient has name kioclient5.
So if you support only KDE 5, then 

> if hash kioclient &>/dev/null; then

and

> kioclient exec "$APPDIR/$app.desktop" >/dev/null 

should be changed to kioclient5.

Otherwise, support for KDE 4 and KDE 5 should be introduced.

**Comment by bulletmark** [comment]
I don't use KDE, have no KDE system to test against, and have never had any feedback about KDE. So are you saying I should test for executable `kioclient5` and it it doesn't exist then use `kioclient`?

**Comment by SpiderX** [comment]
Yes, exactly.
