### ISSUE TITLE
Can't seem to specify the finger count

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [bulletmark/libinput-gestures#53]
Hi,
Im probably just being stupid, but I cant seem to specify the finger count for each gesture.
For example I want to make the desktop switch with only 4 fingers. The way I was trying it was  trying it was like this:
`gesture swipe up _internal ws_up    finger_count 4` 
and like this
`gesture swipe up finger_count 4    _internal ws_up`

However, 3 finger for swiping through desktops still work.

P.S. 
I would have contacted you through email, since it's probably just me misusing your application, but I wasn't able to find it on your page.

Thanks!

**Comment by bulletmark** [comment]
To specify a finger count change:

    gesture swipe up _internal ws_up

to:

    geture swipe up 4 _internal ws_up

I.e. Just insert the number before the command. There is no `finger_count` keyword.

**Comment by bulletmark** [comment]
BTW, stock GNOME includes 4 finger swipe up/down to change workspace (at least in 3.22). So if are running GNOME then you probably best to just comment the swipe up/down gestures out and let GNOME do it.
