### ISSUE TITLE
Could not determine touchpad device.

### ISSUE THREAD

**Issue by davduf** [bulletmark/libinput-gestures#54]
I  follow the install instructions here https://github.com/bulletmark/libinput-gestures/blob/master/README.md

But when I do libinput-gestures-setup start

I get this:

> Failed to open /dev/input/event3 (Permission denied)
> Failed to open /dev/input/event5 (Permission denied)
> Failed to open /dev/input/event1 (Permission denied)
> Failed to open /dev/input/event0 (Permission denied)
> Failed to open /dev/input/event2 (Permission denied)
> Failed to open /dev/input/event14 (Permission denied)
> Failed to open /dev/input/event16 (Permission denied)
> Failed to open /dev/input/event15 (Permission denied)
> Failed to open /dev/input/event8 (Permission denied)
> Failed to open /dev/input/event9 (Permission denied)
> Failed to open /dev/input/event10 (Permission denied)
> Failed to open /dev/input/event11 (Permission denied)
> Failed to open /dev/input/event12 (Permission denied)
> Failed to open /dev/input/event7 (Permission denied)
> Failed to open /dev/input/event4 (Permission denied)
> Failed to open /dev/input/event6 (Permission denied)
> Failed to open /dev/input/event13 (Permission denied)
> Could not determine touchpad device.

I am running Ubtunu 16.04 under Gnome 3

My very best,
David

**Comment by bulletmark** [comment]
You didn't do the very first line in the instructions!

Add yourself to the _input_ group jusing the stated`gpasswd` command and then log completely out of your session and back in.

**Comment by bulletmark** [comment]
Added commit 2f03f2e98cb2e03fad16455ab8bc5624973b7d62 with more explicit instructions about this in the README and added an error message warning about this if no devices can be seen.
