### ISSUE TITLE
Help wanted: For keyboard does not has number pad 

### ISSUE THREAD

**Issue by sandangel** [bulletmark/libinput-gestures#55]
My keyboard does not has a number pad so when I try to assign super and 'plus' or super and 'minus', It seem to point to my plus and minus button on numb pad. I assigned like this: 
pinch out 2 xdotool key super+plus
pinch out 2 xdotool key super+minus
The problem is I'm using elementary os loki, and a keyboard with japanese layout and it only  has plus sign at  "+/;" button and minus sign at "=/-" button. When I press super+"+/;" and super+"=/-" zoom in and zoom out function worked but when I use touchpad It just print out plus sign or "~" sign at same pinch in action and cursor just blinking with pinch out action. Does anyone knows solution?

**Comment by bulletmark** [comment]
Sorry but this is not a question about `libinput-gestures`, it is a generic question about `xdotool`. Sorry, I don't know the answer but you could ask on the [xdotool users group](https://groups.google.com/forum/#!forum/xdotool-users).

**Comment by armc** [comment]
I setup pinch to zoom in / out using my keyboard in browser:

gesture: pinch in	xdotool key control+equal
gesture: pinch out	xdotool key control+minus

Firefox appears to not require a "control+shift+plus" to get the result.  Also, when looking for your keyboard key names... I used this list.  Note that sometimes there are differences between keypad and keyboard entry for key names.

https://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h

Good luck.

I hope I am not violating anything in the forum by posting when it is marked as closed and obviously redirected to another another posting area.
