### ISSUE TITLE
Edge gestures

### ISSUE THREAD

**Issue by v1v3kgithub** [bulletmark/libinput-gestures#57]
Is it possible to support edge gestures, e,g; Left or Right edge swipe in?

(I would like to mark this as an enhancement rather than an issue - not sure how I can do that here - my first time raising an issue)

**Comment by bulletmark** [comment]
When I look at the output of `libinput-debug-events` as I do a 3-finger swipe in from the touchpad edge I find that it does not always report it as a gesture. So the answer is no. This utility only processes what libinput reports as gestures.
