### ISSUE TITLE
2 finger Alt-Left (navigate back in browser) doesnt seem to work.

### ISSUE THREAD

**Issue by v1v3kgithub** [bulletmark/libinput-gestures#58]
I am not sure what I am doing wrong but I am not able to move Back/Forward on my browser (Firefox/Chrome) using the following setting

gesture swipe left 2 xdotool key alt+Right

Ubuntu 16.10 
HP Spectre x360 (Kaby Lake)

**Comment by bulletmark** [comment]
A 2 finger swipe on a touchpad is a scroll, not a gesture. This program only actions what libinput calls gestures. Delete the 2 from your config line. Or just delete your custom file to use the default file and you will see 3 finger right/left swipes work fine for back/fwd in Firefox and Chrome.

**Comment by v1v3kgithub** [comment]
Thanks for the the quick reply, I didnt realize they were categorized as 'scroll'
I dont think the 3 finger left/right 'swipe' would work since I have configured them as move to desktop (left/right) 

gesture swipe left 3 xdotool key ctrl+alt+Right

**Comment by bulletmark** [comment]
But surely you use 2 fingers to both up/down and left/right all the time?!

Of course you can't configure the same gesture for 2 different actions.

What distribution and what DE are you using? Distro's are switching to Wayland where `xdotool` can not be used to switch desktops so you should best be using the built command which works on Wayland and Xorg:

    gesture swipe left 3 _internal ws_down

Read about libinput gestures here https://wayland.freedesktop.org/libinput/doc/latest/gestures.html.

**Comment by v1v3kgithub** [comment]
Thank you for the quick reply.
I had a question regarding the suggest setting - why should I specify ws_down when I actually want to move left/right.
`gesture swipe left 3 _internal ws_down`

I am using Ubuntu 16.10 how do I determine if its running wayland.

**Comment by bulletmark** [comment]
You have a right command configured also don't you? Swap the `ws_up` and `ws_down` around then as I only wrote that off the top of my head.

If `xdotool` was working to switch desktops then you must be using Xorg.

**Comment by bulletmark** [comment]
I just realized you are perhaps confused about what `ws_down` means. It means to switch "down" a desktop. What "down" means depends on whether your desktops are arranged vertically or horizontally (or in a table) etc but don't get caught up in the semantics, just try it and swap it around to do what you want.

**Comment by v1v3kgithub** [comment]
I am sorry I didnt the documentation in the supplied config file, for the clarification.
Will give it a try.
