### ISSUE TITLE
Not work on KDE

### ISSUE THREAD

**Issue by sandangel** [bulletmark/libinput-gestures#60]
I'm using Manjaro KDE 16.10.3. After I have installed by using AUR package, there was an error when I try libinput-gestures-setup start.

$libinput-gestures-setup restart
libinput-debug-events stopped.
libinput-gestures stopped.

(gtk-launch:7542): GLib-GIO-WARNING **: /etc/xdg/kde-mimeapps.list contains a [Added Associations] group, but it is not permitted here.  Only the non-desktop-specific mimeapps.list file may add or remove associations.
libinput-gestures started.
 ❯ libinput-gestures is already running for $USER, terminating ..

And when I try libinput-gestures-setup status show that:

libinput-gestures is installed.
libinput-gestures is set to autostart.
libinput-gestures is running.

I assigned super+Left for move to next desktop on KDE shortcut config and gesture swipe left 4 for libinput-gestures.conf, but nothing worked. Of course I when I install using AUR, wmctrl and xdotool package has been installed too. When I try press on my keyboard super+Left or type in terminal "xdotool key super+Left", it works. 

Any help would be appreciated.

**Comment by bulletmark** [comment]
Looks like I introduced an error in one of my recent changes. Thanks for pointing that out. I have pushed commit 9e599b815e494c504ab36be41b43dbf8df58a1a6 to fix it and am releasing version 2.16 with this commit to the AUR very soon.

**Comment by bulletmark** [comment]
That commit should fix both the Glib error and the "already running" message. Please update from the AUR and remove your custom configuration to prove that everything works, e.g. switch desktop using a triple swipe up/down.

**Comment by sandangel** [comment]
sorry for late reply. I confirm that it work out of the box. Thanks
