### ISSUE TITLE
xubuntu 16.04 libinput "elantech" touchpad but

### ISSUE THREAD

**Issue by tristan3214** [bulletmark/libinput-gestures#62]
See #16 and #12 for the same libinput bug scenario.  I tried forcefully installing libinput-tool 1.3.1 with the dependencies libinput10 and libinput-bin.  After I reinstalled libinput-gestures, I ran `libinput-gestures -v` and was greeted with a different looking bug when trying to use some custom xdotool commands.

`libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.3.1/touchpad_jumping_cursor for details`

I should mention, it seems like it takes quite an effort when swiping left or right to produce this message.  

Is this within your scope?

**Comment by bulletmark** [comment]
I see that exact error occasionally in my journal as well but it doesn't seem to cause any problem. It gets reported by the libinput  `libinput-debug-events` utility so it has nothing to do with this app.

Are you actually seeing any problem with `libinput-gestures`?

**Comment by tristan3214** [comment]
That is what it felt like. I will continue to investigate. 

That is the only output I see; nothing about certain keys that are supposed to be pressed.  Maybe I need to tinker with the config further. 

Thanks for that speedy response.

**Comment by bulletmark** [comment]
So are you saying that your gestures are not working?

Please update to the latest version, delete any custom configuration, and restart:

    rm -f ~/.config/libinput-gestures.conf
    libinput-gestures-setup restart

Then confirm that a 3 finger swipe up and down changes your desktop.

**Comment by tristan3214** [comment]
Sorry it took awhile.  I did what you said, and no nothing is happening when I any of the default gestures. Swipe up, down, left, right and pinch in or out.

The reason I used a custom config was because it seemed that the default gestures would be more for Gnome rather than XFCE 4.2, based off your documentation.

I tried using xdotool in terminal and find that the keys that I mapped for switching desktops works.  For example, switching to the right desktop is mapped to Super+Right.  Typing `xdotool key Super+Right` gives me the desired effect.

**Comment by bulletmark** [comment]
I have never used XFCE but I would expect that the default commands to switch desktops (which use an `_internal` command rather than `xdotool`) should work. If your `xdotool` command works on the command line then it should definitely work via `libinput-gestures`. Please remove your custom configuration, type the following, and do various swipe and pinch gestures. Then paste the output here.
~~~~
libinput-gestures-setup stop
libinput-gestures -d
~~~~~

Then restore your custom config file and repeat the above, also pasting the output here.

**Comment by tristan3214** [comment]
It looks like there isn't anything happening when I try any of the gestures and I have made sure I am added to the input list.

Default output:
````
libinput-gestures: using /etc/libinput-gestures.conf, session x11
libinput-gestures: device /dev/input/event10: ETPS/2 Elantech Touchpad
libinput-gestures: configured with 6 gestures
````

The custom commands are just xdotool running ctrl+alt+Right/Left to keep things simple and see if I can switch work spaces.
Custom output:
````
libinput-gestures: using /home/tristan/.config/libinput-gestures.conf, session x11
libinput-gestures: device /dev/input/event6: ETPS/2 Elantech Touchpad
libinput-gestures: configured with 2 gestures
````

**Comment by bulletmark** [comment]
So it seems this is nothing to with any custom configuration etc, your touchpad is not reporting gestures at all. Please run the following, do some 3 and 4 finger swipes and pinches, and paste the output here.
~~~~
libinput-gestures-setup stop
libinput-gestures -r
~~~~

**Comment by tristan3214** [comment]
Here is some output with `libinput-gestures -r` and using the default config file.

None of the 3 swipe gestures are showing any output.  If there is output it just came from my pointer moving inadvertently while I try a 3 finger gesture.  I would try more 4 finger and pinch gestures but my track pad is a bit small and all I end up doing is moving the pointer.

Thanks for the help.  Is my track pad just less advanced as others or is your library supposed to give it the functionality of gestures?
````
event9 	DEVICE_ADDED     ETPS/2 Elantech Touchpad          seat0 default group1 cap:p	size 76.00/40.00mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on
event9 	POINTER_AXIS      +3.21s	vert 9.91* horiz -47.37*
event9 	POINTER_AXIS      +3.35s	vert 0.00* horiz 0.00*
event9 	POINTER_MOTION    +3.69s	 -7.85/  0.79
event9 	POINTER_MOTION    +3.71s	-12.37/  1.16
event9 	POINTER_MOTION    +3.72s	-15.37/  1.30
event9 	POINTER_MOTION    +3.73s	-11.41/  2.85
event9 	POINTER_MOTION    +3.75s	 -8.14/  4.81
event9 	POINTER_MOTION    +3.76s	 -7.10/  6.82
event9 	POINTER_MOTION    +3.77s	 -5.80/  7.59
event9 	POINTER_MOTION    +3.79s	 -4.15/  6.36
event9 	POINTER_MOTION    +3.80s	 -2.74/  4.11
event9 	POINTER_MOTION    +3.81s	 -1.75/  2.56
event9 	POINTER_MOTION    +3.83s	 -1.05/  2.63
event9 	POINTER_MOTION    +3.84s	 -0.64/  3.09
event9 	POINTER_MOTION    +3.85s	 -0.64/  2.54
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.3.1/touchpad_jumping_cursor for details
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.3.1/touchpad_jumping_cursor for details
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.3.1/touchpad_jumping_cursor for details
event9 	POINTER_AXIS      +5.01s	vert 10.54* horiz -65.28*
event9 	POINTER_AXIS      +5.03s	vert 8.64* horiz -78.99*
event9 	POINTER_AXIS      +5.06s	vert 9.91* horiz -83.82*
event9 	POINTER_AXIS      +5.10s	vert 0.00* horiz 0.00*
````

**Comment by bulletmark** [comment]
My utility just runs the stock `libinput-gestures-debug-events` and interprets the raw gesture messages to action commands. It doesn't do much! So if libinput does not recognise gestures from your touchpad, which is the case because the raw output proves it here, there is nothing I can do. There may be a kernel and/or libinput bug open for your model touchpad.

Same as issues #12. #16, #39, #47. Read the comments there.
