### ISSUE TITLE
xdotool conflicts meta key

### ISSUE THREAD

**Issue by dpmungo** [bulletmark/libinput-gestures#63]
Dear Mark,
firstly I want to thank you for providing this useful package! I have a little annoying issue on Manjaro (Arch based system) with KDE 5.8.5. I start `libinput-gestures` and until I use gestures that call `_internal` on my touchpad, all works properly on my system. However, if I use a gesture which calls `xdotool`, the first gesture doesn't take any effect and, from this moment, I'm unable to open application launcher pressing windows key. The following gestures instead take effect. After `libinput-gestures-setup stop`, windows key doesn't work even.
I don't know if it's a code-related problem.
Thank you for your time.

**Comment by bulletmark** [comment]
Sorry, so it is not clear whether you are saying if `_internal` commands, as per the default config, are working? With the default config, do swipe ups and downs switch your workspace? That should work on KDE under both Wayland and Xorg. Also, please state whether you are using Wayland or Xorg? Running `libinput-gestures -d` should print this out.

What are the exact `xdotool` commands which seem to stop the application launcher? Please try the default configuration and the swipe left and right (which in the default config use `xdotool`), should at least make Firefox and/or Chrome page back and forward.

**Comment by dpmungo** [comment]
`_internal` commands are working and they raise no problems. I'm able to switch workspace with four finger swipe up, down, left and right. I think I'm using Xorg, `libinput-gestures -d` prints out `session x11`.

The `xdotool` commands that stop opening launcher pressing meta key are the two in default configuration
`gesture swipe left   xdotool key alt+Right`
`gesture swipe right  xdotool key alt+Left`
The first time I swipe left/right nothing happens, the following are correctly mapped to alt+Left/Right on Chrome. 
I try to modify config file in this way 
[libinput-gestures.conf.txt](https://github.com/bulletmark/libinput-gestures/files/737551/libinput-gestures.conf.txt)
but after making a gesture mapped to `xdotool` meta key stops working

**Comment by bulletmark** [comment]
Firstly, make sure you have the very latest `libinput-gestures` version installed. Run the following and exercise all the swipe combinations you have configured to confirm that the app is running properly, that you have a valid configuration file, and that your touchpad is reporting gestures correctly. This will just print the actions to your terminal window but not actually invoke them.
~~~~
libinput-gestures-stop
libinput-gestures -d
~~~~~

After that, copy and paste the exact same `xdotool` commands you have configured to execute them directly from your terminal window. If you are saying they are not working via `libinput-gestures`, then I suggest they will not work when you run them manually either.

**Comment by dpmungo** [comment]
Ok, I think it's a `xdotool` issue, it's not related with your code. After executing a `xdotool` command from terminal (eg `xdotool key alt+Left`), I'm unable to open application launcher pressing the meta key. I will search the internet for a solution. Thank you!
