### ISSUE TITLE
Ubuntu 16.10

### ISSUE THREAD

**Issue by davduf** [bulletmark/libinput-gestures#64]
Hi all,
Hi Mark,

Thank you so much for this!

I just updated my Ubuntu to Gnome 16.10 and it seems impossible to install it again...
Do you know why ?

All my best

David

**Comment by bulletmark** [comment]
No sorry, not a clue with seeing any error messages!

**Comment by davduf** [comment]
At the very end 
`davduf@davdux:~/libinput-gestures$ sudo make install
sudo: make : commande introuvable
`
This is in French, it says unfoundable command

**Comment by bulletmark** [comment]
Please do this and try again:

    sudo apt-get install build-essential

**Comment by davduf** [comment]
Yes !! Thank you so much !

If you have time, what is it for ?
`sudo apt-get install build-essential`

**Comment by bulletmark** [comment]
You didn't have the `make` command installed on your machine. It is included in that package.

**Comment by davduf** [comment]
Thx !
