### ISSUE TITLE
Elementary OS Loki

### ISSUE THREAD

**Issue by bksubhuti** [bulletmark/libinput-gestures#65]
Thanks for making this.  Touchegg seems a little dead.  
Can you provide a eOS config file for Loki.  Out of the box, I get workspace switching.  That is it.  
I would like to get as many apple OS gestures as possible.  Thanks..

**Comment by bulletmark** [comment]
Sorry, I have no experience with Elementary OS. It is almost certainly running X11 so your question is about what keyboard shortcuts to configure with `xdotool`. Just copy `/etc/libinput-gestures.conf` to your own custom`~/.config/libinput-gestures.conf` and then play with xdotool to see what shortcuts to add/replace in your custom file. Read `man xdotool`.

Note that with the default configuration I would expect that swipe left and right should page forward and backwards in your web browser (e.g. chrome or firefox) and in your file browser? All I personally use is swipe up/down to switch workspaces and left/right to page/forward back in browser, all of which you should also have.
