### ISSUE TITLE
stops working after suspend

### ISSUE THREAD

**Issue by scurrvy2020** [bulletmark/libinput-gestures#68]
Hello, thanks for making this great script. 
I've been using it with xdotool on unity. Unfortunately it stops working after resume from suspend. 

I've tried adding this to /lib/systemd/system-sleep/ but it still does not resume after suspend. 
`#!/bin/sh

case $1 in
  post)
    libinput-gestures-setup restart
    ;;
esac`

Any other advice to keep it working after resume from suspend?

**Comment by bulletmark** [comment]
Please suspend and resume your laptop then execute the steps in the TROUBLESHOOTING section of the README. This will almost certainly be a problem specific to your laptop and/or model of touchpad.

**Comment by scurrvy2020** [comment]
Thanks for the reply. 
It works fine after I restart the service. I just thought there my be a way to automate the restart of the service. placing it in the /lib/systemd/system-sleep/ doesn't work.

**Comment by bulletmark** [comment]
There is nothing about `libinput-gestures` that would require a restart. What you are saying is the the underlying `libinput-debug-events` utility from libinput must require a restart, i.e. it something peculiar about your laptop and/or libinput etc but certainly nothing to do with this utility. Run `libinput-gestures -r` on the command line as you suspend then resume your laptop and see if the raw libinput messages stop.

**Comment by scurrvy2020** [comment]
gotcha, the libinput-gestures -r doesn't persist through a suspend. 

I'll find a workaround, thanks for your help.

**Comment by bulletmark** [comment]
So after a resume does your touchpad work normally, apart from gestures?

Bit odd that the touchpad would work but just stop reporting gestures. What model laptop? What touchpad device name does `libinput-gestures -d` report at start? Have you updated your BIOS to the latest version?

**Comment by scurrvy2020** [comment]
Thanks for your help. I've gone back to synclient and touchegg for gestures, which persists through suspend.

**Comment by bulletmark** [comment]
@mkhalila please paste the output of `libinput-gestures -l`. If your issue is the same as the OP here you will note that it seems that `libinput-debug-events` stops after a suspend in which case clearly it is not the fault of `libinput-gestures`.
