### ISSUE TITLE
Application specific bindings

### ISSUE THREAD

**Issue by rajeshksv** [bulletmark/libinput-gestures#69]
Can we have application specific bindings instead of just global bindings ? One of the main use cases for me is to do three finger swipe left/right to navigate between open tabs.  For firefox tab navigation is done using ctrl+Tab and ctrl+Shift+Tab. So my bindings look like 

gesture: swipe left 3 xdotool key ctrl+Tab 
gesture: swipe right 3 xdotool key ctrl+shift+Tab

But it might not work in other apps as they may have different key bindings. If application specific binding is there, then I can have three finger swype left/right for tab navigation in all applications. This is just one use case and I have many more :)

Thanks!

**Comment by bulletmark** [comment]
This has been asked previously as issue #37. As I said there, this is not possible on Wayland (at least not possible for non-Xwayland clients) which is what some distros (e.g mine which is GNOME on Arch Linux) use by default now and is what all Linux users will soon be running. Wayland has a much stricter security policy on not allowing apps to intercept keys intended for other apps so it will never be possible. So I don't want to pursue a dead-end feature for X clients only and which also adds much more complexity.

As I say in the opening section of the README, this is/was only ever intended to be a simple work-around utility until the DE's all get their act together and expose this multi-touch functionality properly.
