### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by nos1609** [bulletmark/libinput-gestures#7]
Running on arch as a simple user fails

> [nos1609@mac-mini-arch libinput-gestures]$ ./libinput-gestures -v
> Failed to open /dev/input/event2 (Permission denied)
> Failed to open /dev/input/event3 (Permission denied)
> Failed to open /dev/input/event0 (Permission denied)
> Failed to open /dev/input/event1 (Permission denied)
> Failed to open /dev/input/event4 (Permission denied)
> Failed to open /dev/input/event5 (Permission denied)
> Failed to open /dev/input/event10 (Permission denied)
> Failed to open /dev/input/event6 (Permission denied)
> Failed to open /dev/input/event11 (Permission denied)
> Failed to open /dev/input/event12 (Permission denied)
> Failed to open /dev/input/event13 (Permission denied)
> Failed to open /dev/input/event14 (Permission denied)
> Failed to open /dev/input/event15 (Permission denied)
> Failed to open /dev/input/event7 (Permission denied)
> Failed to open /dev/input/event16 (Permission denied)
> Failed to open /dev/input/event9 (Permission denied)
> Failed to open /dev/input/event8 (Permission denied)
> Could not determine touchpad device.

sudo output claims that no config files found

> [nos1609@mac-mini-arch libinput-gestures]$ sudo ./libinput-gestures -v
> [sudo] пароль для nos1609: 
> Traceback (most recent call last):
>   File "./libinput-gestures", line 187, in <module>
>     count = get_conf(args.conffile)
>   File "./libinput-gestures", line 145, in get_conf
>     with open(conffile) as fp:
> FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/libinput-gestures.conf'

So far, a complete reboot is needed for wayland

**Comment by bulletmark** [comment]
What OS/environment are you trying to run this under?

You must not run this as root. 

This utility just wraps itself around the standard _libinput-debug-events_ program so if you can't run that as your normal user then this utility won't work. You need to add yourself to the _input_ group so that _libinput-debug-events_  can read `/dev/input/event*`.

**Comment by nos1609** [comment]
archlinux with gnome 3.18.2

**Comment by bulletmark** [comment]
@nos1609 Did you add yourself to the _input_ group? Did it fix the problem?

Use `gpasswd -a $USER input` and log out/in.

That gnome version on Arch is from 2015. Any reason you are not updating your system? What kind of machine is this?

**Comment by bulletmark** [comment]
I presume that was the problem so I made the README a little more explicit about this with commit f415dfac905071bd3838df6567e4928df2d7d66b.

**Comment by haroldSanchezb** [comment]
I have the same problem also I ran `sudo gpasswd -a $USER input` but nothing changed, I have Ubuntu 16.04 ( also I installed libinput-tools xdotool )

**Comment by bulletmark** [comment]
Note the instructions say to run that command and then log out and back in. Did you do that?

**Comment by haroldSanchezb** [comment]
Hi, I did that but I getting this message 

> Could not determine touchpad device.

**Comment by bulletmark** [comment]
Please list the output of `libinput-list-devices` here.

**Comment by haroldSanchezb** [comment]
Device:           Power Button
Kernel:           /dev/input/event3
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Video Bus
Kernel:           /dev/input/event5
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Power Button
Kernel:           /dev/input/event1
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Sleep Button
Kernel:           /dev/input/event2
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Integrated_Webcam_HD
Kernel:           /dev/input/event8
Group:            5
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event4
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           ImPS/2 Generic Wheel Mouse
Kernel:           /dev/input/event6
Group:            7
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat*adaptive

Device:           Dell WMI hotkeys
Kernel:           /dev/input/event9
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           DELL Wireless hotkeys
Kernel:           /dev/input/event7
Group:            9
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

**Comment by bulletmark** [comment]
There is no touchpad listed there. What model of laptop is this? There is a mouse reported so perhaps unplug that and run the command again.

**Comment by haroldSanchezb** [comment]
Dell Latitude E7470, it's a laptop

**Comment by bulletmark** [comment]
What about my mouse question?

**Comment by haroldSanchezb** [comment]
I don't use a mouse or external peripheral , I use the built in touchpad, also, in web browser respond with two fingers scroll, :(

**Comment by bulletmark** [comment]
So your touchpad is reported as a mouse it seems. Run the following command and do some 3 and 4 finger swipes and pinches to see if gestures are reported.

    libinput-debug-events --device /dev/input/event6

Note that device path may change between reboots. Get the current path using the `libinput-list-devices` command.

**Comment by haroldSanchezb** [comment]
Hi, I did that but only recognize two fingers

**Comment by bulletmark** [comment]
Ok, that is a fairly new laptop. If you look around your will see others reporting on various Linux forums and bugtrackers that their similar model Dell laptops are reporting their touchpad as a mouse. E.g. see https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-synaptics/+bug/1590590 and http://en.community.dell.com/techcenter/os-applications/f/4613/t/19982526. Unfortunately you have to wait for a Linux kernel update.

For the first 3 months after I got my Dell XPS 13 I compiled up my own kernel with various little patches for issues like this sad to say. Eventually, everything was working well by default.

**Comment by haroldSanchezb** [comment]
Ohh hehehe ok, I will wait, I don't have experience compiling kernel or libs hehehe :( thank you so much!!

**Comment by passabilities** [comment]
Hey so for me, I figured out which input device is the correct one: (NOTE: I am using the Razer Blade Pro 2017)

```
Device:           CRQ1001:00 0488:D020
Kernel:           /dev/input/event15
Group:            9
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a
```

Which is weird because as you can see, I would not have expected this device to be the trackpad. I tested this device using the `libinput-debug-events --device /dev/input/event15` command with the following output:

```
libinput-debug-events --device /dev/input/event15
event15	DEVICE_ADDED     CRQ1001:00 0488:D020              seat0 default group1 cap:p left scroll-nat scroll-button
event15	POINTER_AXIS      +1.60s	vert 15.00* horiz 0.00
event15	POINTER_AXIS      +1.61s	vert 15.00* horiz 0.00
event15	POINTER_AXIS      +1.62s	vert 15.00* horiz 0.00
event15	POINTER_AXIS      +1.67s	vert 15.00* horiz 0.00
event15	POINTER_AXIS      +1.73s	vert 15.00* horiz 0.00
event15	POINTER_MOTION    +3.56s	 -0.65/ -1.63
event15	POINTER_MOTION    +3.56s	-20.71/-41.42
event15	POINTER_MOTION    +3.60s	  0.00/ -1.86
event15	POINTER_MOTION    +3.65s	 -1.05/  0.00
event15	POINTER_MOTION    +3.67s	  0.00/ -1.00
event15	POINTER_MOTION    +3.68s	 -1.00/ -1.00
event15	POINTER_MOTION    +3.69s	 -1.00/ -1.00
event15	POINTER_MOTION    +3.70s	 -1.00/ -1.00
event15	POINTER_MOTION    +3.71s	 -1.00/ -1.00
```

But no recognizing any other gestures.

**Comment by SanjayVyas** [comment]
I had the same problem on Ubuntu 17.04.
I have used this earlier on 16.04 and it had worked, but not this time

Despite adding the user to group, logging out and logging back in and even rebooting, it continued to give the same error.

libinput-ilist-devices would continue to give permission denied but would work with sudo.
I noticed that /dev/input/event* were root/input but 644.
I changed permissions of event* to 664 and it started working.

I am not sure if I did the right thing by changing it, but then this is my personal system with no one else using it.

Can someone confirm what should be the owner:group and permission of /dev/input/event* files?

Thanks

**Comment by SanjayVyas** [comment]
I found my culprit.. an app called "WhatPulse", which tracks the number of keystrokes and mouse clicks. 
It had put a udev rule changing the permission on /dev/event* to 640 on every reboot.

**Comment by retsel89** [comment]
Hello i have the same problem that haroldSanchezb, i have Xiaomi NoteBook Pro
and here is mi list of devices

Device:           Power Button
Kernel:           /dev/input/event2
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event4
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event0
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Lid Switch
Kernel:           /dev/input/event1
Group:            4
Seat:             seat0, default
Capabilities:     switch
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event5
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Logitech M510
Kernel:           /dev/input/event7
Group:            5
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

Device:           XiaoMi USB 2.0 Webcam: XiaoMi U
Kernel:           /dev/input/event9
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           ETD2303:00 04F3:3083 Touchpad
Kernel:           /dev/input/event10
Group:            7
Seat:             seat0, default
Size:             125x78mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

Device:           Intel HID events
Kernel:           /dev/input/event8
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH Headphone
Kernel:           /dev/input/event11
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=3
Kernel:           /dev/input/event12
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=7
Kernel:           /dev/input/event13
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=8
Kernel:           /dev/input/event14
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=9
Kernel:           /dev/input/event15
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           HDA Intel PCH HDMI/DP,pcm=10
Kernel:           /dev/input/event16
Group:            9
Seat:             seat0, default
Capabilities:     
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event3
Group:            10
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           ETPS/2 Elantech Touchpad
Kernel:           /dev/input/event6
Group:            11
Seat:             seat0, default
Size:             125x81mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    *button-areas clickfinger 
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

please any idea

**Comment by bulletmark** [comment]
@retsel89 this closed bug is 3 years old. Please read and follow the TROUBLESHOOTING section in the README thoroughly and then raise a new bug if you think appropriate (providing all the data asked for there).
