### ISSUE TITLE
unconsistent detection

### ISSUE THREAD

**Issue by NikolasSetiawan** [bulletmark/libinput-gestures#70]
Hi there, It seems that I have a quite inconsistent 3 finger swipes detection with my libinput gestures. This seems to happen after I make a fix to my trackpad palm rejection by adding the line:
blacklist i2c_designware-platform  
to the file 
/etc/modprobe.d/blacklist.conf

It occasionally outputs error code:
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.4.3/touchpad_jumping_cursor.html for details
when it's not detecting the gestures. 
Any Idea on what happens here?

**Comment by bulletmark** [comment]
Please read the TROUBLESHOOTING section in the README. In particular, please paste the output of at least the startup lines of `libinput-gestures -d`.

**Comment by bulletmark** [comment]
Also, please remove that blacklist line/file, reboot, and paste the full output here of `libinput-list-devices`.

**Comment by NikolasSetiawan** [comment]
On debug mode, when it's working, 3 finger gestures output the folowing:
libinput-gestures: SWIPE up 3 [-16.799999999999997, -254.53000000000003]
   xdotool key --delay milliseconds super+w
libinput-gestures: SWIPE right 3 [313.52, -1.37]
   xdotool key alt+Right
libinput-gestures: SWIPE left 3 [-682.74, 119.02]
   xdotool key alt+Left
libinput-gestures: SWIPE down 3 [-86.41999999999999, 816.47]
   xdotool key alt+Tab

It sometimes misinterpret swipes as pinch, but I guess that's fine. The output: 
libinput-gestures: PINCH out 3 -0.050000000000000044
   dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:Main.overview.toggle();

When not working, it output the following:
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.4.3/touchpad_jumping_cursor.html for details

I'll reboot and post the results with the blacklist removed

**Comment by NikolasSetiawan** [comment]
Without the blacklist, it works flawlessly:
libinput-gestures: device /dev/input/event14: DLL06E4:01 06CB:7A13 Touchpad
libinput-gestures: session ubuntu+x11 on Linux-4.10.1-041001-generic-x86_64-with-Ubuntu-16.10-yakkety and python 3.5.2+
libinput-gestures: using /home/nikolas/.config/libinput-gestures.conf with 10 gestures
libinput-gestures: SWIPE up 3 [-64.77, -371.8299999999999]
   xdotool key --delay milliseconds super+w
libinput-gestures: SWIPE down 3 [-23.229999999999997, 752.4000000000002]
   xdotool key alt+Tab
libinput-gestures: SWIPE left 3 [-688.9700000000001, 29.25]
   xdotool key alt+Left
libinput-gestures: SWIPE right 3 [563.21, 7.6499999999999995]
   xdotool key alt+Right
libinput-gestures: SWIPE right 4 [586.87, 7.3900000000000015]
   xdotool key ctrl+alt+Right
libinput-gestures: SWIPE left 4 [-421.16, 24.410000000000004]
   xdotool key ctrl+alt+Left
libinput-gestures: SWIPE down 4 [0.8200000000000001, 597.75]
   xdotool key F11
libinput-gestures: SWIPE up 4 [-0.21999999999999997, -421.36999999999995]
   xdotool key shift+ctrl+alt+Right

**Comment by bulletmark** [comment]
I want to see the startup lines of `libinput-gestures -d` (first 3 lines).

**Comment by bulletmark** [comment]
The message from libinput about "Touch jump detected" I think is harmless and irrelevant to any issue you are having. I see that message occasionally in my journal and don't see any problem. It has been reported by many people using libinput on various forums etc (with or without `libinput-gestures`).

**Comment by NikolasSetiawan** [comment]
Thank you for your reply bulletmark. So do you know why the blacklist causing problem? Without that, my touchpad palm detection is not working.

**Comment by bulletmark** [comment]
This small app just reads what `libinput-debug-events` tells it, i.e. a gesture is either a SWIPE or a PINCH. The discrimination of those is entirely within libinput so if you think some swipes are being interpreted as pinches, it is a libinput problem, not a problem within this app.

No idea about the blacklist issue sorry. Again though, if adding that affects libinput there is not much this app can do about it.

**Comment by NikolasSetiawan** [comment]
Alright then, thanks again, great work on the app by the way. I'll probably try finding alternative for the palm detection fix.
