### ISSUE TITLE
Repeatable events

### ISSUE THREAD

**Issue by zhulik** [bulletmark/libinput-gestures#71]
Hi! You've made a great work, thank you!

I just want to suggest possibility for repeatable events. For example, for scrolling thought the all workspaces with only one gesture. The events can be sent while gesture is not finished, and frequency can depends on gesture speed, distance or it's duration.

How do you think, is it possible to implement and will it be comfortable for user or not?

**Comment by bulletmark** [comment]
Sorry, this could be implemented but I think it would be too awkward to use. Gesture speed would not work but I guess we could action something different if the gesture distance was bigger. However, I want to keep this utility simple. 

You can already go some way to doing this yourself. Just create your own script which, e.g., takes various arguments and configure that as the action for gestures. That script can record a timestamp and do different things as gestures increase in rate for example.
