### ISSUE TITLE
A Solution to controlling Wayland Applications

### ISSUE THREAD

**Issue by appetrosyan** [bulletmark/libinput-gestures#72]
Hey. I've found a way to use the gestures in Wayaland (and not only) apps. I'm thinking of writing a control program that would, 

1. use wmctrl to get info about the app in focus. E.g. is it an X.org or Wayland app, etc... 
2. If it's an X.org app, just use Xdotool, Legacy apps, not much we can do... 
3. If it' a Wayland app, and immune to Xdotool, determine what it is, and send a customised dBus message, appropriate for the command. E.g. If it's Nautilus, send `org.grk.Actions.Activate"up" [] {}` to it and when doing a swipe up. 

With your permission I'd like to package the parser with libinput-gestures, as it simplifies end-user experience.

**Comment by bulletmark** [comment]
"Per app/window" configuration has been asked for before but I am not keen on it for a number of reasons, the most immediate that I want to keep this application simple as I say in the README. Obviously you are free to fork this repo and do whatever you like though.
