### ISSUE TITLE
Event for missing capability CAP_GESTURE on device

### ISSUE THREAD

**Issue by tennom** [bulletmark/libinput-gestures#75]
I get the errors on the screen shots when I perform the gestures configured on libinput-gestures.
![dbug1](https://cloud.githubusercontent.com/assets/8739460/24575372/ac706034-16d6-11e7-8748-38926a313bf6.png)
![gesture-l](https://cloud.githubusercontent.com/assets/8739460/24575380/d09e8dfa-16d6-11e7-9088-a5a384385e76.png)
![gesture-r](https://cloud.githubusercontent.com/assets/8739460/24575381/d0a20e76-16d6-11e7-8df4-c06757d8073a.png)

1. I have two finger scrolling working before installation of libinput-gestures.
2. I have followed the instruction and configured correctly. 
3. i'm using unity, not gnome.

**Comment by bulletmark** [comment]
Those messages are coming from libinput sorry. They are nothing to do with libinput-gestures so there is nothing that I can do about them. Apart from those error messages, you don't say whether gestures actually work or not? I notice that libinput 1.2.3 is a fairly old version.
