### ISSUE TITLE
pinch/scroll send multiple events?

### ISSUE THREAD

**Issue by chconnor** [bulletmark/libinput-gestures#78]
Hi -- apologies if this isn't an appropriate place to ask this:

I've been trying to use a tablet to use pinch to zoom in and out in GIMP. That (and other gestures) in libinput-gestures seem to be "one-off", meaning I do a pinch and it sends a single xdotool event to the application at the end of the pinch, rather than continuously sending events as the pinch goes in or out.

Is there any way to configure libinput-gestures.conf to send multiple events? I'm on Kubuntu and I'm just hoping I don't have to wait until 18.04 to make this work. :-) I'm currently not using any gesture layer and just relying on scroll up/down/left/right for zooming and such, since its continuous, but it leaves me without pinch (plus the scroll takes way too much movement to activate for some reason, and I can't find anything appropriate in xsetwacom or xinput to change that) so it'd be great to figure something else out.

touchegg seems to recognize the constant stream of events, but also only sends one out at the end (and seems to have other bugs that make is unusable for me.)

Thanks for any ideas!

**Comment by bulletmark** [comment]
No sorry. As I say in the README, `libinput-gestures` is only intended as a simple stop-gap measure to give us essential things like scrolling between workspaces until Linux DE's and app's get this stuff implemented natively. I use GNOME on Wayland and there are some apps, like the stock GNOME image viewer, which already action touchpad pinch to zoom in and out by default. Such apps read the libinput gestures directly. We just have to wait for GIMP to add that.

**Comment by chconnor** [comment]
Understood -- thank you for the response and your work on the project.
