### ISSUE TITLE
Implementing a windows10 like alt+tab 

### ISSUE THREAD

**Issue by nirmik379kale** [bulletmark/libinput-gestures#79]
Hello,
I wish to implement a W10 style alt+tab using gestures...

lets say i configure 4 finger left swipe for the next window in alt tab.
what I would like to happen is the alt+tab window is opened and then stays. swiping further without picking up the fingers should shift the focus to the right side or left side window ( atleast the same direction as original gesture. in this case next window ).
I understand there might be limitations to it but is it possible? I saw the code and saw wmctrl being used as the _internal command.  may be wmctrl -a can be used somehow? idk, just a guess from a newbie...
Also triend entering a sweies of command in the confid like - 

xdotool keydown alt key Tab; sleep 2; xdotool keyup alt keyup Tab

and it doesnt work, although it does individually on bash prompt ( the closest implementation i could find to what i want to achieve ) 

IDK if issues is the right section to write this...but anyways.

Thanks in advance!

**Comment by bulletmark** [comment]
I don't really understand what you are asking for but I tried those xdotool commands and they do nothing for me (on Xorg). Xdotool can never be used like that for Wayland anyhow which we are all soon moving to. I use where Wayland is already the default for GNOME. As I say in the README, I want to keep this utility simple. It just actions a configured command (or _internal) at the end of a libinput gesture.

**Comment by nirmik379kale** [comment]
Hi...

I am running on x11 on gnome 3.20 and not wayland... I cross verified it using  'loginctl show-session 5 -p Type'

althoug, to give you a clear idea of what I wanted to achieve, i recorded a screencast on windows 10... i think you'll get what i wana achieve seeing that...
here is the link - 

https://youtu.be/jF3dJVV39e8

whats happening in the videos is purly gesture based... ( 4 fingers left / right swipe in windows )

and what the xdotool commands I mentioned do is start the alt + tab popup that shows a list of windows and sleeps for 2 sec allowing me to select the window i want and then it releases the alt key to get rid of the alt + tab popup and change to the specified window...
Also, i understand the fact that you wana keep this program simple...there is only so much customization everyone can want... thus I am asking you for any suggestion that will allow me to edit the code for personal use if needed  ( and publish it in your work if you wish )... or any suggestions if any config commands combo can achieve that!
Cheers!

**Comment by bulletmark** [comment]
Just fork the code here and do whatever you like. We can see that 24 others have already forked it. You can request me to pull whatever changes you do in your own repo.

**Comment by nirmik379kale** [comment]
Sure!
I'll try to do it... I am new to making real code changes to gnome or a DE... thats why... do you think its possible to achieve it though?

**Comment by bulletmark** [comment]
This code is not related to GNOME/DE at all. It's just regular python code which parses a config file to get commands then sits in a loop parsing libinput messages for gestures to act on. It's pretty simple!

**Comment by nirmik379kale** [comment]
Ah.. alright! Ill take a look and see if I can achieve that! Thankyou! :D
