### ISSUE TITLE
modifiers recognised only once then need keyboard reset

### ISSUE THREAD

**Issue by xlinbsd** [bulletmark/libinput-gestures#81]
Hello,

(some of) my xdotool commands take account of <super> modifier only once then only output the other keys.
I need to type manually something in the front application to reset the correct behavior a new time.

Example, with my config
```
# scale (compiz)
gesture swipe up 3 xdotool key super+w
# expo (compiz)
gesture swipe up 4 xdotool key super+s
# show desktop (compiz)
gesture swipe down xdotool key ctrl+alt+d
# browser previous/next
gesture swipe left xdotool key alt+Right
gesture swipe right xdotool key alt+Left
```
When I "swipe up" with 3 fingers, I call compiz scale function (like MacOS Exposé).
The second time I swipe up 3, a simple "w" is typed, until I type manually something with the keyboard.

That can lead to big mistakes since the keyboard shortcuts sent are transformed. Other gestures than swiping up do not cease to work at any moment.

Weird, since the `libinput-gestures -d` output is flawless, and if I manually type the xdotool commands that work successfully every time. I excluded a xdotool bug from that point. Any escape sequence problem ?

I'm on MATE Desktop. My env output is
```
libinput-gestures: monitoring all devices
libinput-gestures: session mate+x11 on Linux-4.11.0-041100rc8-generic-x86_64-with-Ubuntu-17.04-zesty, python 3.5.3, libinput 1.6.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 5 gestures
```

Regards

**Comment by xlinbsd** [comment]
[update]
The super key is not the problem. I replaced my calls from "super" to "alt". The problem is the same. When I swipe Up once, all swipe Up are broken. The other gestures work

**Comment by bulletmark** [comment]
When you say "a simple w is typed", what do you mean? Where is it "typed"? When you say you do it a second time, do you mean while the expo mode is still on? 

This is a very simple utility. It just executes the command you configured when it sees the gesture. What do you mean by "transformed"? There's no magic involved here.

**Comment by xlinbsd** [comment]
I understand the basic functionality of your utility, you follow a device to extract gestures, then pass a command.

In my situation, the command is trucated  after the first usage. From 'super+w', it become 'w', the front window receive a character input. In a text field or the terminal, it is obvious, since I can fill the screen with 'wwwwwwwwww' if I continue to swipe.
The expo mode is at this moment on or dismissed already. Normally the second command call should dismiss the expo mode.

I think there can be a problem in the transmission of the command to xdotool, since super disappear.

Perhaps are you using an escape sequence to pass xdotool command, since when I quote the commands in the config file  `gesture swipe up 3 xdotool key Super+w` to `gesture swipe up 3 xdotool key 'Super+w'`
the output in `libinput-gestures -d` remove the quotes
```
libinput-gestures: SWIPE up 3 [10.83, -289.7]
   xdotool key super+w
```

**Comment by bulletmark** [comment]
The quotes are removed by python shlex the same as the shell would parse them away before they are given to xdotool so that looks fine.

I think this is a Compiz issue. Write a test shell script to send xdotool key super+w in quick series with a delay in between.

**Comment by xlinbsd** [comment]
You are right.

```
xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w && sleep 0.5 && xdotool key super+w
```

Works twice, then ouput wwwwwwww
The sleep time to not infer, I tried 0.1 to 1.5 without change in behavior.

I will complain before compiz !

**Comment by xlinbsd** [comment]
thank you

**Comment by xlinbsd** [comment]
I'll try dbus-send commands instead of xdotool

**Comment by bulletmark** [comment]
Originally I had the pinch commands to  action GNOME shell overview (expose) mapped to super+s but changed that some time ago to dbus-send commands because they work in both Xorg and Wayland. Xdotool commands for the desktop only work in Xorg.

**Comment by xlinbsd** [comment]
Hello,

I found out a correct call for dbus, but I do not find out how to escape it correctly

I need that
```
gesture swipe up 3 dbus-send --print-reply --type=method_call --dest=org.freedesktop.compiz /org/freedesktop/compiz/scale/screen0/initiate_key org.freedesktop.compiz.activate string:'root' int32:`xwininfo -root | grep id: | awk '{ print $4 }'`
```
to convert dynamically in (for my desktop)
```
gesture swipe up 3 dbus-send --print-reply --type=method_call --dest=org.freedesktop.compiz /org/freedesktop/compiz/scale/screen0/initiate_key org.freedesktop.compiz.activate string:'root' int32:0xev
```
Do you know how to escape correctly the xwinfo command ?

**Comment by bulletmark** [comment]
If you want to configure a pipeline of commands then put it in a personal shell script and call that.

**Comment by xlinbsd** [comment]
OK, less all-in-one solution but that works. Thanks.
