### ISSUE TITLE
Libinput-gesture dosen't work.

### ISSUE THREAD

**Issue by thymbahutymba** [bulletmark/libinput-gestures#82]
According to issue [67](https://github.com/bulletmark/libinput-gestures/issues/67) libinput-gestures dosen't work with my touchpad. How i wrote today in the other issue, my touchpad support 3-fringer
```
andrea@HP-ProBook-4540s ~> xinput list-props "SynPS/2 Synaptics TouchPad" | grep Capabilities
	Synaptics Capabilities (331):	1, 0, 1, 1, 1, 1, 1
```
How i can fix it?

**Comment by bulletmark** [comment]
Please follow the TROUBLESHOOTING section in the README. Note the first sentence there!

Do step 4. If you don't see GESTURE events there is nothing we can do about it.
