### ISSUE TITLE
Suggestion: Workspace looping

### ISSUE THREAD

**Issue by andrewjong** [bulletmark/libinput-gestures#83]
With keyboard shortcuts I can infinitely loop around the end of the workspace list back to the beginning. Libinput doesn't do this (that I know of). Can this feature of infinite workspace cycling be added?

**Comment by bulletmark** [comment]
It's already there. Try the `-w` option on the `_internal` command.

**Comment by andrewjong** [comment]
Ah, it works. Thanks!
