### ISSUE TITLE
How do I capture scroll/swipe length?

### ISSUE THREAD

**Issue by nikhilw** [bulletmark/libinput-gestures#84]
What I am trying to achieve is 3 finger gesture to scroll through open applications, which in terms of keys would be equivalent to `alt+tab+tab+tab...`. I can do a single alt+tab, something like:
```
gesture swipe left	3	xdotool key alt+Tab
gesture swipe right	3	xdotool key alt+shift+Tab 
```
But how do I do multiple alt tabs proportional the the length of swipe gesture?
Is there any other way I can achieve the alt+tab behaviour?

**Comment by bulletmark** [comment]
I understand what you are asking for which is similar to something that has been asked before. However, `libinput-gestures` can not do that and it's design precludes implementing anything close to that functionality.  Also, xdotool/etc can not be used in Wayland which is what most distros are now using by default for GNOME at least. If you stick to Xorg then perhaps try https://github.com/iberianpig/fusuma?

**Comment by nikhilw** [comment]
Thanks @bulletmark for your reply. I tried fusuma, but even that does not seem capable of what I am trying to achieve. It can let you control the length of the swipe, but that affects all shortcuts. Also, it cannot let you map swipe to scroll. Even if it allowed local-to-gesture lengths, what I could possibly try is length=0.5:ctrl+tab and length=1:ctrl+tab+tab and increment it, but that would not let me select any app from UI.
Thinking of it, ideal would be mapping (3/4)-touch-and-hold to alt+tab and then horizontal swipe to scroll, effectively allowing selecting the application you want to switch to.
But none of these options seem doable with any of the current tools.
