### ISSUE TITLE
Add more configurations for different DE's

### ISSUE THREAD

**Issue by capstan1** [bulletmark/libinput-gestures#86]
It would be way easier and very convenient for new users if the gestures would be working out of the box in different desktop environments.

The install-script could simply ask for the desktop environment which is used and install the libinput-gestures.conf with matching shortcuts.

I could provide the file for Pantheon, if neeeded.

**Comment by bulletmark** [comment]
I'd prefer to just add them as examples in the `libinput-gestures.conf` file as I have already done for Compiz on Ubuntu as one example. The reason is that everybody wants a different configuration anyhow so should just go through the configuration file and select those gestures they want.

**Comment by capstan1** [comment]
okay, fair point!

**Comment by bulletmark** [comment]
Please post here whatever examples you would like to contribute though.
