### ISSUE TITLE
Feature requests:  4 finger tapping and border swipes

### ISSUE THREAD

**Issue by adrfantini** [bulletmark/libinput-gestures#9]
I have two feature requests, the first of which I'm not sure can be implemented:

1. 4/5 finger tapping. This is not supported by libinput directly, so I doubt that it can be easily implemented.
2. Border swipes, just like in Jolla's Sailfish OS. Swipes that start right at the border of the touchpad are treated differently compared to swipes in the main area of the touchpad. This allows for even more swiping options (I already filled all of mine! :) ), e.g. changing tab with a three finger internal lateral swipe, but changing windows with a three finger border lateral swipe.

**Comment by bulletmark** [comment]
This simple utility merely runs and reads the output of libinput-debug-events which for touchpads only outputs 3 and 4 finger swipe and pinch gestures so item 1 is not possible.
Nor does libinput-debug-events process item 2 very well. I could add a configuration to map actions based on "size" of the swipe/pinch but I think it would be awkward to use and configure.

As I say in the README, this utility is only intended to used temporarily until all this stuff is handled natively within DEs, e.g. probably after we all start using Wayland.

**Comment by gcoda** [comment]
@adrfantini If you still need it, here is a hack, i wrote a [shell script](https://gist.github.com/gcoda/2a893e80077487e630fb726a29d9d4ba)

**Comment by daljit97** [comment]
@gcoda how can I use the 4 finger tap with your script?

**Comment by gcoda** [comment]
@daljit97 sorry, it was a stupid idea, it hogs CPU like crazy, i do not really know bash, i thought i will improve on it later, but i completely forgot about and readjusted my habits.

But you can try if you want. run `evtest` look at your touchpad device name, make sure it sends `BTN_TOOL_QUADTAP` and then run `evtest /dev/input/event16 | ./gist.sh 'notify-send tap4' | sh` - it will execute `notify-send tap4` on every 4 finger tap. and hog your cpu on every touch you make

**Comment by daljit97** [comment]
Oh ok, thanks for that. I came across xserver-xorg-input-mtrack that is supposedly able to implement this and 3 finger drag (selecting text by 3 fingers), but could not manage to make it work properly on my XPS 15 9550.
