### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by vbashiri** [bulletmark/libinput-gestures#92]
_i follow the guide step by step but still doesn't work for me._

`libinput-gestures -e`
libinput-gestures: device /dev/input/event8: AlpsPS/2 ALPS GlidePoint
libinput-gestures: session KDE+x11 on Linux-4.10.0-19-generic-x86_64-with-Ubuntu-17.04-zesty, python 3.5.3, libinput 1.6.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 6 gestures

`libinput-gestures -l`
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       <not configured>
swipe right      <not configured>
swipe up         <not configured>
swipe down       <not configured>
swipe left_up    <not configured>
swipe right_up   <not configured>
swipe left_down  <not configured>
swipe right_down <not configured>
pinch in         <not configured>
pinch out        <not configured>
pinch clockwise  <not configured>
pinch anticlockwise <not configured>

_but in config file except these I comment all lines:_
       gesture swipe up          3	    xdotool key ctrl+F12
       gesture swipe down     3	    xdotool key ctrl+F8
       gesture swipe left         3	    xdotool key ctrl+alt+Left
       gesture swipe right       3	    xdotool key ctrl+alt+Right

`libinput-gestures -d`     _and one try for every direction_
libinput-gestures: device /dev/input/event8: AlpsPS/2 ALPS GlidePoint
libinput-gestures: session KDE+x11 on Linux-4.10.0-19-generic-x86_64-with-Ubuntu-17.04-zesty, python 3.5.3, libinput 1.6.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 4 gestures
libinput error: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.6.3/touchpad_jumping_cursor.html for details

_if I remove finger number,_ `libinput-gestures -l` _will show them but still no swipe detection in debug mode._

`libinput-gestures -r`    _and one try for every direction_

libinput-gestures: device /dev/input/event8: AlpsPS/2 ALPS GlidePoint
libinput-gestures: session KDE+x11 on Linux-4.10.0-19-generic-x86_64-with-Ubuntu-17.04-zesty, python 3.5.3, libinput 1.6.3
libinput-gestures: using ~/.config/libinput-gestures.conf with 4 gestures
-event8   DEVICE_ADDED     AlpsPS/2 ALPS GlidePoint          seat0 default group1  cap:pg  size 102x29mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on
event8   POINTER_AXIS      +1.64s	vert 0.00 horiz -2.91* (finger)
event8   POINTER_AXIS      +1.65s	vert 0.00 horiz -15.30* (finger)
event8   POINTER_AXIS      +1.66s	vert 0.00 horiz -17.84* (finger)
event8   POINTER_AXIS      +1.67s	vert 0.00 horiz -7.65* (finger)
event8   POINTER_AXIS      +1.68s	vert 0.00 horiz -19.30* (finger)
event8   POINTER_AXIS      +1.70s	vert 0.00 horiz -19.67* (finger)
event8   POINTER_AXIS      +1.71s	vert 0.00 horiz -7.47* (finger)
event8   POINTER_AXIS      +1.72s	vert 0.00 horiz -19.48* (finger)
event8   POINTER_AXIS      +1.73s	vert 0.00 horiz -19.67* (finger)
event8   POINTER_AXIS      +1.74s	vert 0.00 horiz -19.30* (finger)
event8   POINTER_AXIS      +1.76s	vert 0.00 horiz -9.65* (finger)
event8   POINTER_AXIS      +1.77s	vert 0.00 horiz -20.94* (finger)
event8   POINTER_AXIS      +1.78s	vert 0.00 horiz -21.30* (finger)
event8   POINTER_AXIS      +1.79s	vert 0.00 horiz -20.94* (finger)
event8   POINTER_AXIS      +1.80s	vert 0.21* horiz -10.93* (finger)
event8   POINTER_AXIS      +1.82s	vert 0.92* horiz -18.21* (finger)
event8   POINTER_AXIS      +1.83s	vert 1.74* horiz -20.39* (finger)
event8   POINTER_AXIS      +1.85s	vert 0.00* horiz 0.00* (finger)
event8   POINTER_AXIS      +2.34s	vert 0.00 horiz 12.75* (finger)
event8   POINTER_AXIS      +2.36s	vert 0.00 horiz 9.29* (finger)
event8   POINTER_AXIS      +2.37s	vert 0.00 horiz 20.39* (finger)
event8   POINTER_AXIS      +2.38s	vert 0.00 horiz 20.94* (finger)
event8   POINTER_AXIS      +2.39s	vert 0.00 horiz 9.83* (finger)
event8   POINTER_AXIS      +2.40s	vert 0.00 horiz 23.12* (finger)
event8   POINTER_AXIS      +2.42s	vert 0.00 horiz 25.67* (finger)
event8   POINTER_AXIS      +2.43s	vert 0.00 horiz 24.40* (finger)
event8   POINTER_AXIS      +2.44s	vert 0.00 horiz 27.31* (finger)
event8   POINTER_AXIS      +2.45s	vert 0.00 horiz 24.95* (finger)
event8   POINTER_AXIS      +2.46s	vert -2.97* horiz 24.58* (finger)
event8   POINTER_AXIS      +2.48s	vert 0.00 horiz 26.58* (finger)
event8   POINTER_AXIS      +2.49s	vert -3.28* horiz 36.78* (finger)
event8   POINTER_AXIS      +2.50s	vert 0.00 horiz 26.04* (finger)
event8   POINTER_AXIS      +2.51s	vert 0.00 horiz 24.40* (finger)
event8   POINTER_AXIS      +2.54s	vert 0.00* horiz 0.00* (finger)
event8   POINTER_AXIS      +3.09s	vert -5.13* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.10s	vert -7.90* horiz -19.12* (finger)
event8   POINTER_AXIS      +3.11s	vert -6.77* horiz -39.33* (finger)
event8   POINTER_AXIS      +3.12s	vert -2.77* horiz -10.20* (finger)
event8   POINTER_AXIS      +3.13s	vert -7.28* horiz -2.19* (finger)
event8   POINTER_AXIS      +3.15s	vert -10.98* horiz -0.73* (finger)
event8   POINTER_AXIS      +3.16s	vert -7.28* horiz -0.18* (finger)
event8   POINTER_AXIS      +3.17s	vert -5.95* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.18s	vert -6.98* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.20s	vert -7.28* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.21s	vert -7.69* horiz 8.01* (finger)
event8   POINTER_AXIS      +3.23s	vert 0.00* horiz 0.00* (finger)
event8   POINTER_AXIS      +3.65s	vert 7.08* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.66s	vert 6.87* horiz 0.55* (finger)
event8   POINTER_AXIS      +3.67s	vert 6.87* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.69s	vert 7.08* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.70s	vert 7.59* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.71s	vert 10.98* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.73s	vert 6.98* horiz 0.00 (finger)
event8   POINTER_AXIS      +3.74s	vert 7.59* horiz 8.01* (finger)
event8   POINTER_AXIS      +3.75s	vert 11.39* horiz -4.37* (finger)
event8   POINTER_AXIS      +3.76s	vert 9.44* horiz 10.01* (finger)
event8   POINTER_AXIS      +3.77s	vert 5.64* horiz -6.19* (finger)
event8   POINTER_AXIS      +3.79s	vert 7.80* horiz -3.10* (finger)
event8   POINTER_AXIS      +3.80s	vert 12.62* horiz -0.91* (finger)
event8   POINTER_AXIS      +3.81s	vert 8.72* horiz 4.37* (finger)
event8   POINTER_AXIS      +3.85s	vert 0.00* horiz 0.00* (finger)

`

**Comment by bulletmark** [comment]
Firstly, "doesn't work" is a terrible choice of title.

Secondly, your first command reports 6 gestures configured. Then your second command reports all the gestures configured, each with a blank command (but if you try and run with that configuration it will immediately report a configuration error for each of those blank commands so you clearly never actually tried to use that configuration). Then your third command reports 4 gestures?! Which configuration are you actually complaining about?

Thirdly, your `libinut-gestures -r` output probably shows your problem. It is described in step 5 of the TROUBLESHOOTING section of the README.
