### ISSUE TITLE
pinch on three finger swipe?

### ISSUE THREAD

**Issue by jtzero** [bulletmark/libinput-gestures#93]
Turns out I'm not always stable when I swipe, and the gnome overview accidentally comes up, which was odd to me at first, because I didn't notice I had pinched.  It doesn't happen often but it does happen, which leads me to wonder if pinching is supposed to be enabled when I have three fingers down?

**Comment by bulletmark** [comment]
The determination of what is a SWIPE or a PINCH is done by libinput, not this app. Please follow the instructions in the TROUBLESHOOTING section of the README if you have issues.

**Comment by jtzero** [comment]
sorry didnt catch that
