### ISSUE TITLE
Setup pinch to zoom

### ISSUE THREAD

**Issue by JarrColl** [bulletmark/libinput-gestures#96]
Pinch doesn't seem to be working by default in i3wm manjaro. So i was wondering what I should enter into the config to setup pinch to zoom.

**Comment by bulletmark** [comment]
"Doesn't seem to be working"?

Please read the TROUBLESHOOTING section of main README.

**Comment by JarrColl** [comment]
libinput-gestures -e:
libinput-gestures: device /dev/input/event6: ETPS/2 Elantech Touchpad
libinput-gestures: session i3+x11 on Linux-4.9.35-1-MANJARO-x86_64-with-glibc2.3.4, python 3.6.1, libinput 1.7.3

libinput-gestures: using ~/.config/libinput-gestures.conf with 6 gestures

libinput-gestures -l:

Gestures configured in ~/.config/libinput-gestures.conf:
swipe up           workspace next #_internal ws_up
swipe down         workspace prev #_internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:Main.overview.toggle();
pinch out          dbus-send --session --type=method_call --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:Main.overview.toggle();

by "Doesn't seem to be working" I mean when I pinch in firefox for example it does not zoom. I am not sure if it is libinput-gestures or my wm that is at fault but either way I would like to know how to setup pinch to zoom in the config

gesture pinch *

what should the * be equal to.

**Comment by bulletmark** [comment]
You are using i3 yet you have pinch to send a toggle overview command to GNOME. Pinch to zoom is implemented at the application level (because only the application knows what context it is relevant to) so you are best to comment out the two pinch commands you have to let each application handle pinch, AFAIK, Firefox and Chrome don't implement pinch to zoom.

What are those "workspace commands" for swipe up/down? I doubt they will work with the comment still appended.

**Comment by JarrColl** [comment]
I have commented out the pinch, yet it doesn't work. I assume I need to go somewhere to find a zoom command for i3? The gnome zoom thing was in the default config.

Also firefox and chrome can definately do pinch for zoom. As i have used it before.

Yeah the workspace commands were wrong I have fixed them now.

**Comment by JarrColl** [comment]
i think i might just bind the pinch commands to ctrl+- and ctrl++

**Comment by libasoles** [comment]
Tried that in KDE and it doesn't work
```

pinch in         2 xdotool key ctrl+-
pinch out        2 xdotool key ctrl++

```

-_-

**Comment by bulletmark** [comment]
@libasoles please follow the TROUBLESHOOTING section. Note how prominently I have said there that is you report an issue **you must** paste the output of `libinput-gestures -l` here.

**Comment by leomp12** [comment]
@libasoles as you don't put your logs here I'm not sure if it is your problem, but the correct keys for xdotool are `ctrl+plus` and `ctrl+minus`.

```
# zoom
gesture pinch   in    2  xdotool key ctrl+minus
gesture pinch   out   2  xdotool key ctrl+plus
```
