### ISSUE TITLE
Is there a way to scroll the tabs in chrome?

### ISSUE THREAD

**Issue by CoREse** [bulletmark/libinput-gestures#98]
Just like in chrome os, three fingers swipe will do something like hover your mouse on tabs then scroll, aka, scroll the tabs. That's different from ctrl-tab just switch one tab a time, it scrolls due to your swipe. Is there anyway to achieve that with libinput-gestures or with other softwares? Thanks!

**Comment by bulletmark** [comment]
No, this utility merely actions a single command at the end of a gesture.

I use the 45 degree up swipes to go left and right in my tabs, and 45 degree down swipes to close and re-open tabs. See the commented out examples in `libinput-gestures.conf`.
